### ISSUE TITLE
[macOS] StageVideo in fullscreen mode show only 1/4 of the viewport

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1001]
## Problem Description
`StageVideo` in fullscreen mode show only 1/4 of viewport with macOS. May be problem "under the hood" with scale factor of Retina screens.
This bug affect every AIR application that uses `StageVideo` with fullscreen mode.

Tested with multiple AIR versions even with latest AIR 33.1.1.554 with multiple macOS devices with different OS versions with different videos with Retina screens.
Same problem in all cases.
Didn't try with non-Retina screens.
Changing `renderMode` in application xml didn't solve issue.
Increasing `viewPort` didn't solve problem.
There is no such problem when you try to play video in window (not fullscreen) mode.

Tracker link: https://tracker.adobe.com/#/view/AIR-3655955
Related issues:
https://tracker.adobe.com/#/view/AIR-3946226
https://github.com/airsdk/Adobe-Runtime-Support/issues/88

## Steps to Reproduce
Launch code below with macOS device. It will start to playback video in fullscreen.

Application example with sources and example of video attached.
[stagevideo_macos_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/6863080/stagevideo_macos_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.net.NetConnection;
	import flash.net.NetStream;
	import flash.media.StageVideo;
	import flash.geom.Rectangle;
	import flash.events.NetStatusEvent;
	import flash.display.StageDisplayState;
	
	public class StageVideoMacOSBug extends Sprite {
		private var nc:NetConnection;
		private var ns:NetStream;
		
		public function StageVideoMacOSBug() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			stage.displayState = StageDisplayState.FULL_SCREEN;//Fullsreen cause incorrect behavior
			
			nc = new NetConnection();
			nc.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);
			nc.connect(null);
		}
		
		private function netStatusHandler(event:NetStatusEvent):void {
			trace(event.info.code);
			switch (event.info.code){
				case "NetConnection.Connect.Success":
					ns = new NetStream(nc);
					ns.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);
					ns.client = {onMetaData:getMeta, onPlayStatus:onPlayStatus};
					var sv:StageVideo = stage.stageVideos[0];
					sv.viewPort = new Rectangle(0, 0, 1280, 800);
					sv.attachNetStream(ns);
					
					ns.play("video.mp4");
					break;
				case "NetStream.Play.StreamNotFound":
					trace("Stream not found");
					break;
				case "NetStream.Buffer.Full":
					break;
			}
		}
		
		private function getMeta(mdata:Object):void { }
		
		//Seek video to begin after complete
		private function onPlayStatus(infoObject:Object):void {
			ns.seek(0);
		}
	}
}
```

**Actual Result:**
`StageVideo` shows only 1/4 of viewport.
<img width="1791" alt="look" src="https://user-images.githubusercontent.com/10899066/126660426-d47dd0ac-1c11-4b19-9b57-5b712e6d7b57.png">

**Expected Result:**
`StageVideo` shows full (correct) viewport.
<img width="1276" alt="should look" src="https://user-images.githubusercontent.com/10899066/126661002-5f4d9056-48a9-4dc3-b15a-266f81d81035.png">

## Known Workarounds
none
Use `Video` (have performance issues) or `VideoTexture` (also seems still have some stability issues).

**Comment by Oldes** [comment]
I have the same problem.. it should be noted, that the issue is only in the _fullscreen_ mode. In classic _window_ mode it is working correctly.

**Comment by Oldes** [comment]
Ok... after playing with it a little bit.. 
I may say, that after removing `<requestedDisplayResolution>high</requestedDisplayResolution>` from the manifest file, I can see the video on fullscreen (when made an app). It looks, that `adl` ignores this manifest setting and always starts with the _high_ resolution and so the issue is always present in this debug mode!

The source of this bug must be in the `stageVideo.viewPort`.

**Comment by itlancer** [comment]
Fixed with latest AIR versions. Checked with latest AIR 33.1.1.821.
Thank you!
