### ISSUE TITLE
[Android] Black application screen when device screen enabling (or unlock "lock screen") with "direct" renderMode for some Samsung devices

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1003]
## Problem Description
Black application screen when device screen enabling (or unlock "lock screen") with "direct" `renderMode` for some Samsung devices with Android.

Tested with latest AIR 33.1.1.533 and 33.1.1.554 versions.
Tested with "direct" `renderMode`. Seems there is no such issue with "auto" `renderMode`.
Tested with and without "lock screen" (enter pin-code etc).
Reproduced with Samsung Galaxy S9 (SM-G960F) Android 9 and Samsung Galaxy Tab S5e (SM-T720) Android 10.
The same problem in all cases.
There is no such issues found with other Android devices.

Device (phone/tablet) rotation (orientation change) seems to "fix" this issue.

Related issues (not the same):
https://github.com/airsdk/Adobe-Runtime-Support/issues/6
https://github.com/airsdk/Adobe-Runtime-Support/issues/698
https://github.com/airsdk/Adobe-Runtime-Support/issues/1002

## Steps to Reproduce
1) Launch code below with Samsung Galaxy S9 or Samsung Galaxy Tab S5e device. It will just show red stage color.
2) Lock screen (turn screen off via power button).
3) Turn screen on (via power button) and unlock device (if you have pin-code etc).

Application example with sources and application xml attached.
[black_screen_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/6863657/black_screen_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	
	public class BlackScreenBug extends Sprite {
		
		public function BlackScreenBug() {
			addEventListener(Event.ADDED_TO_STAGE, addedToStage);
		}
		
		private function addedToStage(e:Event):void {
			stage.color = 0xff0000;
			trace("addedToStage");
		}
	}
}
```

**Actual Result:**
Application shows black screen. Look at video:

https://user-images.githubusercontent.com/10899066/126670604-4affd342-88eb-4118-a3db-6c625de1cb94.mov

With 1-3 seconds you can see another bug: https://github.com/airsdk/Adobe-Runtime-Support/issues/1002
After 7 second you can see this bug.

**Expected Result:**
Application correctly render itself (shows red stage color in this example).

## Known Workarounds
none
For some other Android (mostly Samsung) devices some time ago worked (such other old AIR issues seems fixed right now):
- Change `Stage::quality` https://stackoverflow.com/questions/19515570/air-for-android-black-screen-after-device-alarm
- Use "blackScreenHelper"
https://docs.airnativeextensions.com/docs/application/general-helpers/#usage
https://forum.starling-framework.org/d/4540-starling-turns-into-black-screen
- Make few `Stage::setOrientation` calls with different orientation

**Comment by itlancer** [comment]
With latest AIR 33.1.1.620 it works much better.
With Samsung Galaxy Tab S5e (SM-T720) Android 11 and Samsung Galaxy A5 (SM-A520F) Android 11 with different scenarious now it works fine.
We found only one problem scenario with Samsung Galaxy S9 (SM-G960F) Android 9 and AIR 33.1.1.620 when:
1) "Always On Display" Samsung function https://www.samsung.com/ph/support/mobile-devices/what-is-always-on-display-aod-and-how-to-use-it/ **disabled**
2) "Lock screen" **disabled** ("Screen lock type" in Android settings set to **"None"**)

With such prerequisites steps to reproduce it with Samsung Galaxy S9 (SM-G960F) Android 9:
1) Launch original sample. It will just show red stage color.
2) Lock screen (turn screen off via power button).
3) Turn screen on (via power button).

**Actual Result:**
Application shows black screen.

**Expected Result:**
Application shows red stage color.

**Comment by itlancer** [comment]
Last issue with Samsung Galaxy S9 (SM-G960F) Android 9 still exists with latest AIR 50.2.4.1.

**Comment by ajwfrost** [comment]
Thanks -> so it looks like this is caused by the event ordering between the 'surfaceCreated' and the 'onResume' callbacks. Think we have a workaround for this now, it actually looks like Adobe had done a very targeted fix for some devices/OS versions .. so we'll need to do a bit of regression testing here but I can't see any obvious drawback from the change.

thanks

**Comment by ajwfrost** [comment]
... and in case you wanted to test this with your devices ... this should go into /lib/android/lib
[runtimeClasses.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13478818/runtimeClasses.zip)
thanks

**Comment by itlancer** [comment]
@ajwfrost
Thank you very much! Now it works as expected in all cases.
