### ISSUE TITLE
Adobe Air Nellymoser Codec crashes iPhone since iOS 14.6

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#1019]
### Discussed in https://github.com/airsdk/Adobe-Runtime-Support/discussions/1017

<div type='discussions-op-text'>

<sup>Originally posted by **apofis1969** July 27, 2021</sup>
We are creating a Live WebStream to a web player using Wowza and Ant Media
The problem is, that the iPhone with iOS 14.6 can not stream anymore using Nellymoser. The App crashes completely.
Wowza does not accept SPEEX as sound codec, the H264 feature of Adobe Air is also not working, Wowza does not realise the H264 stream.
We have to use PCMU to realise a stream to receive a live stream via a transcoder to Ant Media using an iPhone. The iPad (iPad Pro 12.9, 2nd Generation) with iOS 14.7 sends the stream using Nellymoser without any problems. No idea how the newer generation devices accept the PCMU. Until now not tested with Android.

It is really a pity, that the H264VideoStreamSettings are not working properly for Live Streaming and that there is no AAC Codec or any other sound codec such as Vorbis or Opus which can be used to enjoy the whole power of Wowza without using a FFMPEG based transcoder. Why there is no solution for this until now? At least it could be offered for paying users like us. 

Air: 33.1.1.554
iPhone 11 with iOS 14.6
Known Workarounds
Substitute Nellymoser with PCMU</div>

**Comment by marchbold** [comment]
Duplicate #1010
