### ISSUE TITLE
ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET

### ISSUE THREAD

**Issue by spielepalast** [airsdk/Adobe-Runtime-Support#1037]
## Problem Description

Describe your problem in detail. Include the following information:

* AIR SDK: 33.1.1.476
* Describe the affected environment: Android
* We can reproduce this every time we build an apk 

## Steps to Reproduce

* we changed our manifest from this: `<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="29"/>` to this: `<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="30"/>`
* with this new version we cannot upload our apps to google play
* we get the following error: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme

* the question is how to select this signature scheme

**Comment by FliplineStudios** [comment]
I believe you need to use a newer AIR version (33.1.1.533+) to support the newer signature scheme, I found this mentioned in the [Release Notes](https://airsdk.harman.com/release_notes) for .533:

> AIR-3379: Signing APK files with apksigner for code signature v2

**Comment by spielepalast** [comment]
Thank you @FliplineStudios for the hint. @ajwfrost can you show me how to adapt my build command to use the v2 signing scheme?

**Comment by ajwfrost** [comment]
If you're using that later AIR SDK, you shouldn't need to change anything, it should just happen by default if you're generating an APK output. (AAB outputs are just jar-signed...)

You can then check with the apksigner.bat file from the Android build-tools:
```
apksigner.bat verify --verbose MyApp.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```

**Comment by spielepalast** [comment]
@ajwfrost : thank you very much for your help. I believe you can close this.

**Comment by ajwfrost** [comment]
Thanks @spielepalast  - any issues with it, please just let us know (or reopen this!)
