### ISSUE TITLE
Iphone simulator crash (Flex mobile - AIR 33.1.1.575)

### ISSUE THREAD

**Issue by 42retfa** [airsdk/Adobe-Runtime-Support#1049]
Hi,

I'm trying to run a Flex mobile application on the iPhone simulator : the simulator is launched after the .ipa build but it crashes right after the splash screen.

Same behaviour is observed with a "blank" application based on a single .mxml file. 

Here is the crash report :[iphone_simulator_crash_report.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/6940307/iphone_simulator_crash_report.txt)

Thanks in advance.

Vincent.

**Comment by 42retfa** [comment]
Hi,

Any idea about the reason for the iPhone simulator to crash ?

The test application I'm compiling is :
 
`<?xml version="1.0" encoding="utf-8"?>
<s:ViewNavigatorApplication
        xmlns:fx="http://ns.adobe.com/mxml/2009"
        xmlns:s="library://ns.adobe.com/flex/spark">
</s:ViewNavigatorApplication>
`
Xcode : Version 12.5.1 (12E507)
Simulator : Version 12.5.1 (961.1)

Thanks.

Vincent.

**Comment by 42retfa** [comment]
Hi again,

I just want to make sure that someone from Harman has read this issue.

Maybe this crash is caused by something wrong specific to my computer/configuration ? Does anyone experiment the same issue ?

Thanks.

Vincent.

**Comment by ajwfrost** [comment]
Hi - yes sorry for the delay! Seems odd, but we can try to replicate the environment to see if we get the same.
Just to confirm, the macOS machine you're running on is on 11.4 and is an Intel chipset rather than M1/Apple silicon? and the simulator SDK is 14.5 I assume, using Xcode 12.5.1 - all seems fairly standard! The error suggests a very wrong memory location being used... what Flex SDK are you using, in case there's something specific to that ...?

thanks

**Comment by 42retfa** [comment]
Hi Andrew,

No worries for the delay, this issue is not blocking at all.

- I just updated macOS to 11.5.2 
- Processor is 4.2 GHz Intel Core i7 quad
- Xcode Version 12.5.1 (12E507)
- Simulator Version 12.5.1 (961.1) / SimulatorKit 609 / CoreSimulator 757.5
- Using latest flex SDK (4.16.1) overlayed with AIR SDK 33.1.1.575

Thank you.

Vincent.

**Comment by 42retfa** [comment]
hi Andrew,

Just tried Apple Simulator version 13.0 (970) with AIRSDK  33.1.1.633 and it doesn't crash anymore.

Thank you.

Vincent.
