### ISSUE TITLE
Context3D not available! Possible reasons: wrong rendenMode or missing device support

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#1052]
When our game is startup on some android phones, the following errors will appear. We use starling and rendermode  is set direct.This may happen to some devices of the same model, and some will not.Several users have encountered this problem.How can we avoid this problem? I hope I can get some help.
![QQ图片20210807174158](https://user-images.githubusercontent.com/1818875/128596573-5e777089-b9f0-4fa0-ae7f-adb5509d20fd.jpg)

**Comment by ajwfrost** [comment]
Can you please let us know what phone models you're seeing this on?
thanks

**Comment by pengyangjin** [comment]
> Can you please let us know what phone models you're seeing this on?
> thanks
![a](https://user-images.githubusercontent.com/1818875/128963583-1d656cc4-550b-4b59-86ca-225ff0fd8efe.jpg)

**Comment by DrNeroCF** [comment]
What happens if you force a constrained render mode?

If it is the device rendering at a super high resolution, I've been thinking that AIR should be able to restrict the rendering resolution, older, cheaper 4k Android phones running AIR in interpreter mode is a bit of a disaster.

**Comment by ventr1x** [comment]
We are currently receiving some reports of this.
We do not use AA or anything special.
One device being reported is Galaxy A71.
Again a fun issue to explain to customers that have 260k active users...

**Comment by ajwfrost** [comment]
It's tricky to know for sure the exact reason, but if you're getting the "Context3D not available" message from Starling (or the error 3702) then it means the creation of the direct-mode context internally has failed. One possibility of this as mentioned in #364 is that anti-aliasing is 'not allowed' in direct mode. So if all of the EGL configs that AIR finds have got anti-aliasing set, then we fail to find an appropriate configuration and will fall back to software composition and therefore can't do Stage3D.

I have to confess, I don't know why it's not permitted to create a direct mode context when anti-aliasing is on. It is fine to do this with GPU contexts i.e. with gpu rendering as well as compositing; just not with direct mode. So we can look at removing this restriction to see what side-effects there might be; if we add it as a fail-over condition then it should minimise the impact i.e. if we can find a configuration that doesn't use anti-aliasing, then we'll choose it, but if there are no such suitable configs then we'll start looking for the best match that does use anti-aliasing...

@ventr1x are you able to provide your app to us so we can try this on an A71 - if you can build it with apk-debug (or aab-debug) it means we can add some extra debugging into it to see what it's doing... as I just tried a regular starling app on an A71 and it worked fine (without the force-AA setting turned on)

thanks
