### ISSUE TITLE
Application Not Running Full Screen on Android Xiaomi Mix 3

### ISSUE THREAD

**Issue by RossD20Studios** [airsdk/Adobe-Runtime-Support#1058]
## Problem Description

One of our prerelease testers reported that their Android Device, the Xiaomi Mix 3, does not run our application in fullscreen mode as expected. The application was built using AIR_33.1.1.554. Our application is designed to run fullscreen for any orientation and aspect ratio, so I'm not sure if this is an issue with AIR or something specific about how this particular device operates given it has a particularly widescreen aspect ratio.

Their device specs and screenshots have been attached.

## Screenshots

![androidScreen1](https://user-images.githubusercontent.com/1627128/128744021-9cd48806-fd3a-47f2-ba3c-a5f35d272e5c.jpg)
![androidScreen2](https://user-images.githubusercontent.com/1627128/128744027-a26cc18e-eb4d-4b0d-ac0c-70c2d2516254.jpg)
![androidScreen3](https://user-images.githubusercontent.com/1627128/128744028-e59350c4-25c2-4268-92d6-9739a3d7931f.jpg)

**Comment by marchbold** [comment]
Have you added the `android.max_aspect` meta data tag to your application. This often affects high aspect ratio screens:

```xml
<meta-data android:name="android.max_aspect" android:value="2.5" />
```

This must be added inside your application node in your manifest additions for Android.

**Comment by RossD20Studios** [comment]
I have not, but I will give this a try and report back once I've released the next build and can confirm with users the full screen is functional. Let me make sure, first, that I am adding this line to correct place:

<android>
        <manifestAdditions><![CDATA[<manifest><uses-permission android:name="android.permission.INTERNET"/></manifest>]]></manifestAdditions>
    </android>

**Comment by marchbold** [comment]
Ah not quite, you need an `application` node in your manifest: 

```xml
<android>
    <manifestAdditions><![CDATA[
        <manifest android:installLocation="auto">

            
            <uses-permission android:name="android.permission.INTERNET"/>
            
            <application>
                <meta-data android:name="android.max_aspect" android:value="2.5" />

            </application>
        
        </manifest>
    ]]></manifestAdditions>
</android>
```

More info: https://docs.airnativeextensions.com/docs/application/display/display/#aspect-ratios

**Comment by RossD20Studios** [comment]
Perfect, thank you for clarifying! I'll give this a shot and report back once I get user confirmation. For the max_aspect value, are there any phones that support aspects wider than 2.5 yet? I'm curious what would happen if I put in a higher value than 2.5.

**Comment by marchbold** [comment]
I'm not 100% sure, but 2.5 has worked on any device I've tested, you should be able to set it higher if you wish.

**Comment by RossD20Studios** [comment]
Thanks again for your help @marchbold - I applied your solution and now have user confirmation that this resolved the issue. Closing this ticket.
