### ISSUE TITLE
Android manifest `queries` support 

### ISSUE THREAD

**Issue by marchbold** [airsdk/Adobe-Runtime-Support#1100]
I'm attempting to add some support for Android 30 and the newer security measures for querying packages. In order to do so we need to add some new tags to the manifest, eg:

```xml
<queries>
    <package android:name="net.sourceforge.opencamera" />
</queries>
```

Currently this results in an error when building 

```
error 402: Current Android sdk version doesn't support queries as xml tag
```

- AIR SDK v33.1.1.575
- target `apk` or `aab` result in the same error
- added the Android sdk via adt.cfg

Reference: https://developer.android.com/guide/topics/manifest/queries-element

**Comment by ajwfrost** [comment]
Hi @marchbold  - slightly cheeky for this to say "Android sdk version doesn't support..." since that message just comes from ADT itself. There's just a list of the manifest tags that are allowed, so if we add 'queries' to this list, the tag is then just passed through to the generated AndroidManifest.xml file....

thanks

**Comment by marchbold** [comment]
Yeah I guessed it was an AIR message as i outputs that same message when using the latest build tools and the android sdk to package an aab. :) 

Cheers! 

Also, is that the same reason for the amazon tag removal, I know that it is slightly more complex with the namespace but while you're looking at it? https://github.com/airsdk/Adobe-Runtime-Support/issues/1064

**Comment by ajwfrost** [comment]
There's a lot of validation going on here - I guess, trying to ensure that any problems are caught early rather than letting an application be created that then may not install/run properly.

That other one is a bit more complex as it would mean adding a custom namespace into the generated XML, but it should be possible to support..

thanks

**Comment by marchbold** [comment]
Yeah, I thought it might be more complex. 

This queries one though will become pressing soon with Android 30 being required now and this will be required for certain functionality in our extensions.

**Comment by marchbold** [comment]
That seems to have worked, cheers!

**Comment by CoolFishGames** [comment]
> 嗨@marchbold - 你能检查下面更新版本的 ADT，它现在应该支持“查询”：
> [https](https://transfer.harman.com/message/Hn0uKXIqQQHARz1dRhERvH) : [//transfer.harman.com/message/Hn0uKXIqQQHARz1dRhERvH](https://transfer.harman.com/message/Hn0uKXIqQQHARz1dRhERvH)
> 谢谢

Hello, the URL connection cannot be opened. Please have a look.

**Comment by CoolFishGames** [comment]
https://transfer.harman.com/message/Hn0uKXIqQQHARz1dRhERvH
Hello, the URL connection cannot be opened. Please have a look

**Comment by ajwfrost** [comment]
Hi @CoolFishGames  - please use the below link
https://transfer.harman.com/message/tDd168zzA6P4iVqBbn1iyh
thanks

**Comment by marchbold** [comment]
@ajwfrost Out of interest when will this be rolled into a release? We just have a few extensions for Android 30 that need this addition :)

**Comment by ajwfrost** [comment]
@marchbold  we're looking to get a beta release out next week that would then be updated/formalised as soon as we have the final Xcode 13 and iPhoneOS 15 SDK releases...

**Comment by marchbold** [comment]
@ajwfrost  Cheers!

**Comment by wonderdragons** [comment]
![image](https://user-images.githubusercontent.com/59364828/133995645-c76203ae-c557-4ae4-9065-09f2a4cba27e.png)

31.1.1.575 also has the error

**Comment by ajwfrost** [comment]
@wonderdragons yes, that update to allow the `queries` tag was added in 33.1.1.620:

![image](https://user-images.githubusercontent.com/6400804/133998659-e98006bd-e4a0-48fb-b117-f73e0a02cdcd.png)

**Comment by marchbold** [comment]
This is working in our tests with 620.
