### ISSUE TITLE
Invalid input dialog when packaging ipa by Animate 20.5.1

### ISSUE THREAD

**Issue by Devkjk** [airsdk/Adobe-Runtime-Support#1118]
MacOS 10.14.6
Animate 20.5.1
AIRSDK 33.1.1.406,444,575
ANE Distriqt Core,InAppBilling,Adverts

I create Certfiles today,when publish,Invalid input dialog appears,and nothing created.
I want advices.
When use 33.1.1.217,"The signing certificate is not from the expected issuer" occues instead.(I check prev Issue,and I see it solved at newly SDKs)

**Comment by Devkjk** [comment]
Hmm,What am I doing wrong?
I got adt.log.
`
Stack trace:
ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch armv7 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk" -L/usr/lib -F"/System/Library/Frameworks" -L"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib" -o "../aot14042648291356291034.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -non_global_symbols_no_strip_list "/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib/local_nostrip.arm-air.txt" "/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib/libRuntimeHMAOT.arm-air.a" -lc++ -lSystem.B -lcrt1.o -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -ios_version_min 9.0 -w -weak_framework UserNotifications "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/a1c736ba-e230-4667-bb4a-6894d3c08cc4" -framework "CoreNativeExtension" -exported_symbol _CoreExtInitializer -exported_symbol _CoreExtFinalizer -ios_version_min 9.0 -w -framework StoreKit -exported_symbol _InAppBillingExtInitializer -exported_symbol _InAppBillingExtFinalizer -ios_version_min 9.0 -w -framework AdSupport -framework AVFoundation -framework AudioToolbox -framework CoreGraphics -framework CoreTelephony -framework CoreMotion -framework CoreVideo -framework MessageUI -framework MediaPlayer -framework SafariServices -framework StoreKit -framework SystemConfiguration -framework GLKit -weak_framework iAd -ObjC -lsqlite3 "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/edd8e990-02bc-4f51-af50-0dfb2d101142" -framework "GoogleAppMeasurement" "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/edd8e990-02bc-4f51-af50-0dfb2d101142" -framework "GoogleMobileAds" "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/edd8e990-02bc-4f51-af50-0dfb2d101142" -framework "GoogleUtilities" "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/edd8e990-02bc-4f51-af50-0dfb2d101142" -framework "nanopb" "-F/var/folders/qv/9gwpq0gs4xv2_99611xxpyg80000gn/T/edd8e990-02bc-4f51-af50-0dfb2d101142" -framework "PromisesObjC" -exported_symbol _AdvertsExtInitializer -exported_symbol _AdvertsExtFinalizer -force_load "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/../../../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a" -filelist "/Users/xxx/Documents/my_work/kjkss2_2021_iOS/AOTBuildOutput16446225681079412984.tmp/OBJFilesList.txt" -ios_version_min 10.0
..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java)
..com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream.access$100(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream$CompileTask.run(IPAOutputStream.java)
..java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
..java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
..java.base/java.lang.Thread.run(Thread.java:835)
Stack trace:
..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.IPAOutputStream$CompileTask.throwAppropriateException(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream.finalizeSig(IPAOutputStream.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Invalid input: Compilation failed while executing : ld64
`

**Comment by ajwfrost** [comment]
Well it's a fairly long command for the linker but I don't think it's going to be too long. My only slight curiosity is whether the recent AIR SDK versions that are built with later versions of Xcode and iPhoneOS SDK versions are going to cope with being used on a machine with an older Xcode and iPhoneOS13.2.

But just in case .. does it work if you have a really basic/empty SWF application?

We can see whether there's going to be any more debug information we could glean from the output of `ld`. To me it looks like this is just giving you the command line and then `Compilation failed` rather than providing any output from the actual linker itself...

thanks

**Comment by Devkjk** [comment]
Hi, I can get ipa from basic/empty SWF without any problems.
`ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch arm64 -L"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/stub" -sdk_version 14.5 -F"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/stub" -L"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib" -o "../aot3392454209225103110.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib/libRuntimeHMAOT.arm-air.a" -lc++ -lSystem.B -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -w -filelist "/Users/xxx/Documents/my_work/kjkss2_2020/AOTBuildOutput1539877498708424782.tmp/OBJFilesList.txt" -ios_version_min 9.0
`
`
ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch armv7 -L"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/stub" -sdk_version 14.5 -F"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/stub" -L"/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib" -o "../aot17267131698441816836.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/xxx/Documents/my_work/AIR_SDK/AIRSDK33.1.1.574/lib/aot/lib/libRuntimeHMAOT.arm-air.a" -lc++ -lSystem.B -lcrt1.o -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -w -filelist "/Users/xxx/Documents/my_work/kjkss2_2020/AOTBuildOutput3136044675903288404.tmp/OBJFilesList.txt" -ios_version_min 9.0`

**Comment by ajwfrost** [comment]
Those are very different command-lines ... 
It looks like the first one (that fails) is being run with a `-platformsdk` argument. Can you check that you do have that iphone 13.2 SDK on your computer i.e. in a terminal window:
```
ls -la /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
ls -la /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
```
Currently it looks like any error from the linker itself is being output to stdout. Is it possible for you to re-run this build from the command-line? this should have been output within the adt.log file when ADT was launched ...

thanks

**Comment by Devkjk** [comment]
Hi,I run the build from the command-line.The output is here.
`
ld: framework not found AppTrackingTransparency
ld: framework not found AppTrackingTransparency
Compilation failed while executing : ld64`
I will try updating XCode.

**Comment by Devkjk** [comment]
Adt log
`Stack trace:
..java.lang.Thread.getStackTrace(Thread.java:1552)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.IPAOutputStream$CompileTask.throwAppropriateException(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream.finalizeSig(IPAOutputStream.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Invalid input: Compilation failed while executing : ld64`

**Comment by ajwfrost** [comment]
Thanks -> it should be possible to add this framework as a dependency into the ANE, via the linker options? the same way as it's adding 'GoogleAppMeasurement' etc?

**Comment by Devkjk** [comment]
Hi.
Finally I have updated MacOS to BigSur and ANEs.
Animate succeeded publishing now.
