### ISSUE TITLE
Build AAB file, failed with AirSDK 33.1.1.575

### ISSUE THREAD

**Issue by MESepehr** [airsdk/Adobe-Runtime-Support#1130]
I want to build an aab file for the first time 
but it crashes and I see this log file in my user windows directory:

> *** ADT Logging at 2021/09/06 13:32:58 ***
> Called by: F:\Tools\AirSDK\Air33\lib\adt.jar
> ADT 33.1.1.575 called with: -package -target aab -storetype pkcs12 -storepass xxxxxx -keystore cert/MasterWin.p12 Masterwin.aab android.xml MasterWin.swf Data swc AppIconsForPublish -extdir .\native
>NOTE: Multiple Android build-tools folders exist, choosing the latest version (30.0.3) for packaging
> AAB Packager entry point
> Version in APK = 33.1.1.575, version of ADT = 33.1.1.575
> Version in APK = 33.1.1.575, version of ADT = 33.1.1.575
> Version in APK = 33.1.1.575, version of ADT = 33.1.1.575
> Version in APK = 33.1.1.575, version of ADT = 33.1.1.575
> Gradle build command:  C:\Program Files\Java\jdk1.8.0_51\bin\java.exe -Xmx2048m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx2048m -Duser.dir="C:\Users\MASHAY~1\AppData\Local\Temp\0f909edb-1441-4a67-977d-4bb3adb48ec8" -cp "F:\Tools\AirSDK\Air33\lib\android\bin\gradle-wrapper.jar";"F:\Tools\AirSDK\Air33\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease
> ..java.lang.Thread.getStackTrace(Unknown Source)
> ..com.adobe.air.DebugFile.printStack(DebugFile.java)
> ..com.adobe.air.ADTException.<init>(ADTException.java)
> ..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
> ..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
> ..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
> ..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
> ..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
> ..com.adobe.air.ADT.run(ADT.java)
> ..com.adobe.air.ADT.main(ADT.java)
> Stack trace:
> Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'air-FDP-MasterWin'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find com.android.tools.build:gradle:4.1.1.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.1.1/gradle-4.1.1.pom
>        - https://jcenter.bintray.com/com/android/tools/build/gradle/4.1.1/gradle-4.1.1.pom
>      Required by:
>          project :
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 5s

Also I set **AndroidPlatformSDK** and uncomment **KeepAndroidStudioOutput=true** in adt.cfg but nothing happened
how can I solve this issue?

**Comment by ajwfrost** [comment]
If that's a gradle failure, then it may be that something's not set up properly on the machine, so perhaps we have a dependency missing. Have you used Android Studio on that machine before, to create/deploy any Android apps?

What I'd suggest is, if you've got "KeepAndroidStudioOutput" set to true, then you should have a folder called "AndroidStudioProject" in your output location. If you can open that folder within Android Studio, see whether it then builds with the "Make Project" option; if it does, then please re-try the AIR build..

thanks
