### ISSUE TITLE
SHA256 checksum mismatch

### ISSUE THREAD

**Issue by Andy314159265** [airsdk/Adobe-Runtime-Support#1134]
Hi,

I'm trying to download the 33.1.1.533 runtime from https://airsdk.harman.com/runtime

The SHA256 signature on the download appears valid however the website lists SHA256 checksums which don't match the downloads
"SHA-256 checksums of the above downloads are:
5b32a9fbb39d8a68827c7bedc3eaebc8830531bd0c5cb41f30b506a927a7a206 *AdobeAIR.exe"

AdobeAIR.exe 33.1.1.533 results in 709268f3b91daea6a168141e73b37bee6cbd6988269804f5e2050ee4f5d00832

I don't believe this is an issue my side. Please can you confirm?

cheers

Andy

**Comment by ajwfrost** [comment]
Hi
Looks like the latest change in our website code hasn't made it onto the live server yet, sorry... what I can see here is:
```
-               5b32a9fbb39d8a68827c7bedc3eaebc8830531bd0c5cb41f30b506a927a7a206 *AdobeAIR.exe<br>
-               d7d4f8832c94d066d1af9c92d765b7465608ac7ad23dcf1f202c986b7183b715 *AdobeAIR.dmg
+               709268f3b91daea6a168141e73b37bee6cbd6988269804f5e2050ee4f5d00832 *AdobeAIR.exe<br>
+               f1c3d65cfa712fcf197cc3b806a5b38ff26ee1dac185ee7504f8a8bd3b5af5bb *AdobeAIR.dmg
```

So yes, the 5b32... value is the old one, and the 7092... value is the new one, that matches the values of the actual binaries. 

I'll try to get this updated on the live site soon!

thanks

**Comment by Andy314159265** [comment]
cheers for confirming
