### ISSUE TITLE
Crash from play console

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#1150]
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> air.example <<<

backtrace:
  #00  pc 0000000000c4e1a0  /data/app/air.example-uaIdOrrQ-dQkXMQXx-LD1A==/lib/arm64/libCore.so


```

I saw this occurring quite often and wanted to know if there's any way to resolve this
Here's another:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> air.example <<<

backtrace:
  #00  pc 0000000000c4e1c8  /data/app/~~Qlf6_Ri1nvbCGfNf-0QxTg==/air.example-5e84YxUNldNPu-jN_NbGmQ==/lib/arm64/libCore.so
```
Air version 406

**Comment by ajwfrost** [comment]
These crashes are in an openssl SHA1 function, we used to get these periodically but I've not seen any reports of this since we updated the openssl library - please update to 33.1.1.476 or later to avoid this problem.

thanks
