### ISSUE TITLE
ADL unexpected argument -screensize with IntelliJ and latest AIR 33.1.1.620

### ISSUE THREAD

**Issue by d-angelovski** [airsdk/Adobe-Runtime-Support#1164]
## Problem Description

Changed the Air version to latest one, and suddenly the debug stopped working with the following error, even though that argument is supplied.

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/23104582/133661766-f8d4e28b-aeb9-4e01-8f9c-2ff642b08150.png">

Is this some change on the ADL arguments placement, that they need to be in order, or it should be fixed on IntelliJ side?

* Which AIR SDK did you use? 
AIR 33.1.1.620

## Steps to Reproduce

Latest IntelliJ, with latest AirSDK, this is the configuration used (same was used on previous air versions and it worked):

<img width="655" alt="image" src="https://user-images.githubusercontent.com/23104582/133662377-edbabc2f-64bd-49b4-a64e-a32b4fb37d5b.png">

**Comment by d-angelovski** [comment]
Seems that the ADT is older version here on this release, the version for example of the previos 575 is correct.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/23104582/133663598-6e4e6d1d-9c69-4760-929d-5725237b7076.png">

**Comment by ajwfrost** [comment]
Hmm... it looks like something's gone wrong with the packaging up of the runtime there. We'll have to take a look and get back to you...

thanks

**Comment by ajwfrost** [comment]
@d-angelovski the package was indeed not put together properly, a code-signing/zipping problem due to the new machine being used for building... Apologies for that, please delete and re-download the SDK from the website
https://airsdk.harman.com/download/33.1.1.620

thanks

**Comment by d-angelovski** [comment]
Now it's ok, it works again, and version is also correct.
