### ISSUE TITLE
33.1.1.620 -- Mac Builds?

### ISSUE THREAD

**Issue by urthling** [airsdk/Adobe-Runtime-Support#1168]
Not seeing Mac Builds for 620, assuming those are coming shortly..

Looking through the release notes, it appears the expectation is that we're running Big Sur - I'm on 10.14.6 in order to support 32 bit, so 620 also removes support for 32bit, so I should now finally upgrade to Big Sur.

Before doing through this, is anyone successfully running Flash Builder on Big Sur per chance?  Any issues people have run into?

**Comment by ajwfrost** [comment]
@urthling yes just trying to sort out a signing/packaging glitch... should be available in the next couple of hours.
 
For iOS support of 32-bit devices, you wouldn't be able to use the 33.1.1.620 release I'm afraid. To get the iOS15 support we've had to move to a new build machine which is running Big Sur i.e. can't create 32-bit binaries (as to create them, we need to use a 32-bit tool).

Is it a major problem to drop the 32-bit support? I'm not sure whether it's possible to create some sort of intermediary state where we can try to pull some stuff together from the latest Xcode/SDK versions back into Mojave which we'd been doing with the previous releases, we can perhaps have a look..

thanks

**Comment by urthling** [comment]
Gotcha, Thank you Andrew.

No, not at all -- I'm happy enough to let our current version be the last for 32bit support.  Actually,  I'm more concerned with any potential upgrade related issues from 10.14.6 to Bug Sur.

**Comment by d-angelovski** [comment]
> Before doing through this, is anyone successfully running Flash Builder on Big Sur per chance? Any issues people have run into?

I have not tried to do it, previously I worked on FBuilder, but could not keep it long, and haven't seen anyone that did make it work on Big sur yet, so I upgraded to Big sur, and got IntelliJ licence.

**Comment by urthling** [comment]
Ah, good to know, thank you so much for heads up @d-angelovski

**Comment by ajwfrost** [comment]
Mac builds were added again, hence closing this one...
thanks
