### ISSUE TITLE
Simulator Xcode 12.2 not possible to test iOS App, AIR 575

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#1214]
## Problem Description

Describe your problem in detail. Include the following information:

Error Message:
Packaging failed!
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file 'extensionglue.o' for architecture x86_64

How to resolve this?
Apple sent an email today that we have to update the apps for the new iPad mini with Xcode 13, iOS 15
How to test the app on the Xcode 12.2 simulator iOS 14.2?

Thanks for any advice.

**Comment by ajwfrost** [comment]
Hi

If you've got a later version of Xcode then you can still debug on a simulator with iOS 14.2, you just need to install that version (via Xcode -> Preferences -> Components).

What is your command line here? - building for iOS simulator is working with our test cases but the above link error does look familiar!

thanks

**Comment by apofis1969** [comment]
I am building with FDT linking to the iOS Simulator SDK.
I have no chance to get my app running on the Xcode 12.2 simulators with Catalina.

**Comment by apofis1969** [comment]
@ajwfrost can you please tell me how I can get the app running on the Simulators with Catalina?
Now I have this bug:
Packaging error message: 
Compilation failed while executing : ld64
Packaging output: 
ld: in /Volumes/Sicherung/fdt/air33/sdk33.1.1.633/sdk33-1-1-633/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a(CTGameInput.o), building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file '/Volumes/Sicherung/fdt/air33/sdk33.1.1.633/sdk33-1-1-633/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a' for architecture x86_64
This is the link to the Simulator: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk
I need to be able to use at least Xcode 12.2

**Comment by apofis1969** [comment]
@ajwfrost will there be a solution or at least one reply, please. I am a paying member. Please assist me in this case. Thank you!

**Comment by ajwfrost** [comment]
Hi @apofis1969  - sorry, I had been trying to find one of the team who still had Catalina, to try to get a reproduction of this. We can't reproduce it though so I'm wondering if you have any ANEs in there?

Are you able to set up the SDK to output a log file i.e. edit:
`/Volumes/Sicherung/fdt/air33/sdk33.1.1.633/sdk33-1-1-633/lib/adt.cfg`
to enable `DebugOut=true`, and then send us the contents of `~/adt.log`?

We're wondering what the full linker command is here, since something appears to be making it think it's building for iOS as well as for iOSSimulator..

**Comment by apofis1969** [comment]
Hi @ajwfrost thanks for the reply. I have a lot of distiqt ANEs.
I will do this. Thank you
