### ISSUE TITLE
Unable to connect using HttpService when using self signed cert after upgrade to iOS15

### ISSUE THREAD

**Issue by cowlinb6** [airsdk/Adobe-Runtime-Support#1215]
## Problem Description

We are using mx.rpc.http.HTTPService to make requests to a service that is using a self signed certificate. This is working fine for uses running iOS 14 and below. As soon as they upgrade to iOS 15 this then stops working.

Tested using AIR SDK 33.1.1.533 and 33.1.1.620 and they both fail.

The self signed cert meets the requirements detailed here: `https://support.apple.com/en-gb/HT210176`

I've attached the full console [log](https://github.com/airsdk/Adobe-Runtime-Support/files/7254168/log.txt) but this looks to be the failure:

Sep 29 18:45:04 Bens-iPhone Main(CFNetwork)[956] <Error>: Task <CF1DCC1F-03AC-4022-926B-340C14D22812>.<0> HTTP load failed, 0/0 bytes (error code: -1202 [3:-9807])

Are there any known issues relating to using self signed certs when going from iOS14 - 15 as I can't see any references to this?

**Comment by ajwfrost** [comment]
Hi
I'm not aware of any differences between iOS14 and iOS15 here.. but wondering whether you have your server address set up as an exception to the standard https requirements, in case this makes a difference? e.g. in the Info.plist you'd need something like the below (from [stackoverflow](https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http/32560433#32560433))
```
<key>NSAppTransportSecurity</key>
<dict>
      <key>NSAllowsArbitraryLoads</key> 
      <false/>
       <key>NSExceptionDomains</key>
       <dict>
            <key>example.com</key> <!--Include your domain at this line -->
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSTemporaryExceptionMinimumTLSVersion</key>
                <string>TLSv1.1</string>
            </dict>
       </dict>
</dict>
```
You should be able to inject this if you add it to the iphone | InfoAdditions section of your application descriptor file...

thanks

**Comment by cowlinb6** [comment]
@ajwfrost I didn't have this configured before. I've just tested adding it and it doesn't make any difference. 

Is there anything else that could be affecting this?

Thanks

**Comment by cowlinb6** [comment]
@ajwfrost no problem, just sent the details via email.
