### ISSUE TITLE
htmlText, img tag not working

### ISSUE THREAD

**Issue by myflashlab** [airsdk/Adobe-Runtime-Support#1242]
It's weird but it seems like the `<img src='img.png/>` is not working on any of the `33.**` SDKs. The same project shows the inline image with SDK 32 but not anything higher.

**Comment by itlancer** [comment]
@myflashlab 
At the reference https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#htmlText mentioned:

> For AIR content in the application security sandbox, AIR ignores img tags in HTML content in ActionScript TextField objects. This is to prevent possible phishing attacks,

Many years ago I tried it and it works only for Flash Player output, not for AIR.

@ajwfrost, what "security issues" could be there? And could `img` tag be allowed in future AIR versions (it could be really helpful for many AIR applications)?

**Comment by myflashlab** [comment]
@itlancer Ah, that explains it. thanks for pointing out to that sentence. Anyhow, I was able to load images inline using `TextFlow` instead of the classic `TextField` class anyway.

Considering that this is not a bug, I'll close this ticket but I agree that it would be really nice if there's a possibility to support this feature with the TextField class.

**Comment by myflashlab** [comment]
@ajwfrost It would be nice if it works at least from the local assets.

**Comment by johnou** [comment]
@ajwfrost could we introduce a domain whitelist similar to Security.allowDomain for allowing img tags? we load article HTML from our CDN which is trusted eg. https://sandbox.habbo.com/gamedata/habbopages/21oct01 and prior to AIR linked to images (also hosted on our CDN).

**Comment by johnou** [comment]
@ajwfrost ping

**Comment by ajwfrost** [comment]
Hi

Thanks for the ping :-) So yes, looking back at this one, it sounds like a domain approval list would be a good idea, as then the developer is in control of what domains would be allowed and it would still block anything a user had entered if that didn't match the approval list..

So we could introduce a list of protocol + domain combinations that are allowed, e.g. `https://www.adobe.com` or `*://www.adobe.com` or `file:///*`, `app:/*` etc.

And then hopefully it would (just?) work to include an img tag into a text field..?! will have to check on that part too.....

thanks

**Comment by johnou** [comment]
That would be perfect, thanks!

**Comment by johnou** [comment]
fwiw Security.allowDomain currently throws an exception when used in AIR [1], I guess a new config would need to be introduced?

[1]

```
SecurityError: Error #3207: Application-sandbox content cannot access this feature.
	at flash.system::Security$/allowDomain()
```

**Comment by skramovskiy** [comment]
is there a solution as a result? how can I use an image in a text field in AIR

**Comment by ajwfrost** [comment]
Hi - sorry, no solution as yet, we need to add a new API in for this. The `Security.allowDomain()` method is about allowing another domain to access stuff in the application context, which isn't allowed in AIR; this would be to allow the application context to load content in another domain. The current restriction was put in place to avoid the possibility of malicious injection of content but we are looking at shifting that authority/responsibility onto application developers by allowing them a way to bypass this.

It may be best (from a security perspective) to have this on a per-text-field setting, so we could add something like
`TextField.allowedDomains : Vector.<String>` which would allow you to set the domains under which we would allow images to be loaded.

We did check, and if we ignore the security restriction in code, then the images do load.. although the layout doesn't look quite right to me, maybe that's just the images and text field height settings that I'm trying..

Will get this API update into the AIR 51 codebase..

**Comment by johnou** [comment]
Suggested setting sounds great, thanks Andrew!

**Comment by waveofthought-code** [comment]
domain security aside, is there anything currently stopping us from using library linkage symbols in a textfield with the <img> tag, or is that also "broken"?

**Comment by ajwfrost** [comment]
There is a comment in the code explicitly forbidding this too. The creation of a symbol could lead to other code execution - I guess that's all internal anyway (assuming the symbol was from your swf not a loaded one) but this is equally restricted in AIR at the moment.

So I guess we need a way to have an "allowed domain" to be the current SWF as well.... e.g. "app:/Main.swf" (being, `loaderInfo.url`).

**Comment by johnou** [comment]
@ajwfrost any updates on adding `TextField.allowedDomains : Vector.<String>`?

**Comment by itlancer** [comment]
For me it works fine using latest AIR 51 and https://airsdk.dev/reference/actionscript/3.0/flash/text/TextField.html#allowedDomains
Thanks!
