### ISSUE TITLE
Array Casting Issue (/Curiosity)

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#1260]
Not sure if this is an actual bug but I found a curiosity when it comes to casting with an Array:

1.  The following code is **not** working:
`var tmp : Object = {testArray: []};`
`Array(tmp.testArray).push("Test");`
-> tmp.testArray.length = 0

2. The following code **is** working:
`var tmp : Object = {testArray: []};`
`(tmp.testArray as Array).push("Test");`
-> tmp.testArray.length = 1

Why is 1. not working?

**Comment by ajwfrost** [comment]
It's not a bug, just a misunderstanding .. when I compile that first example I get:
```
Warning: To cast a value 'x' to type Array, use the expression 'x as Array' instead of 'Array(x)'.
			Array(tmp.testArray).push("Test");
```

If you decompile this:
```
       20   getlex        	Array //nameIndex = 17
       23   getlocal1     	//tmp
       26   getproperty   	testArray //nameIndex = 18
       28   call          	(1)
       30   pushstring    	"Test"  //stringIndex = 36
       32   callpropvoid  	http://adobe.com/AS3/2006/builtin::push (1) //nameIndex = 19
```
So it's actually doing a "call" to "Array" passing in one argument which is the tmp.testArray value. And "Array" as a function call is:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/package.html#Array()
i.e. creates a new array from the parameters that are passed in. So, you end up with a new array that contains the tmp.testArray object in the first slot and the string "Test" in the second slot. But it's not referenced and so just gets cleaned up.

To check this, try:
```
			var arr : Array = Array(tmp.testArray);
			arr.push("Test");
			trace( arr.length ); // 2
```

**Comment by 2jfw** [comment]
@ajwfrost Oh.. now I see - Thanks for the explanation and clarification! (Warnings are disabled atm so I did not see that)
