### ISSUE TITLE
On Android when upgrading to api version 30 some of the devices can't install the App!

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#1278]
Hi,

We run on AIR version 33.1.1.406
We've upgraded our Android api target version from 29 to 30, and some of the players and devices can't install the game now!

In the logcat this is the error they're getting when trying to install the app:
`10-18 10:36:50.622 28328 28328 E Finsky  : [2] tqx.onReceive(15): Error -501 while installing air.com.wizits.buddies: -124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary
`

What could be the issue and is it related to our AIR version?
We're having trouble upgrading our air version to the latest one (33.1.1.633)
cause it increased our ANR rate by 30%,
But is this really the cause of this problem?

Thanks,
Shay

**Comment by ajwfrost** [comment]
Hi

Version 33.1.1.533 has this comment:

> AIR-4311: Ensuring the resources.arsc file is not compressed

so a slight update to that version should work: https://airsdk.harman.com/download/33.1.1.533

We're looking at those ANRs, we know of one issue that can cause deadlock in .633 with the audio thread but I wouldn't have thought this would be the culprit for all of the different ANRs we're seeing. But, there was a change that went in to this build:

> github-1189: Protecting the write of data into an Android audio track

and it may be that this (to prevent a crash) has caused a side-effect of some deadlock/livelock or similar..

Version 33.1.1.620 should be suitable though, the .633 was primarily created for iOS.

thanks

**Comment by shaymolho** [comment]
Hi @ajwfrost ,

We moved to version 633 with the fix you provided and the issue was solved.

Closing the case.

Thanks!
