### ISSUE TITLE
How to set the game to immersive mode when use adobe air sdk?

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#1279]
Now full screen mobile phones are becoming more and more common.Making games with adobe air will trigger a full screen gesture when clicking on the edge area.How can I put the game in immersive mode?

**Comment by marchbold** [comment]
If you are talking about the iOS edge gestures, there is also the SystemGestures ANE that allows you to defer them (i.e. the home bar gets hidden and the user has to swipe up to display it and then again to go home). 

https://github.com/distriqt/ANE-SystemGestures

(I'll transfer this to a discussion)
