### ISSUE TITLE
Cannot install adhoc app on iOS15

### ISSUE THREAD

**Issue by Barney4242** [airsdk/Adobe-Runtime-Support#1283]
## Problem Description

Describe your problem in detail. Include the following information:

macOS Big Sur 11.6
AIR 33.1.1.633 for iOS
Adobe Animate 21.0.7

I have built the app with the latest Harman SDK but I am not able install it on iPadPro with iOS 15. 
I am able to install the same .ipa file on an old iPad AIR with iOS 12.

I receive the following error (translated from Russian Language):
"Unable to Install - This app cannot be installed because the integrity could not be verified"

![internal_intergrity](https://user-images.githubusercontent.com/17008731/138132255-72bff0a3-d203-4a24-83bb-f356b67ea33b.jpg)

Our team have SDK licence. Adt.lic is located in lib folder.
Could you please help =) I am ready to give an additional information or send you ipa for examination.

Thank you very much!

**Comment by ajwfrost** [comment]
Hi
I am wondering whether you include any framework libraries in the IPA as this was the only issue I think we had outstanding in that release of the SDK ... are you able to upload the IPA file to the below link and we can check it? And if you're able to re-sign it (e.g. via the Distriqt script) it may help until we get a fix...
https://transfer.harman.com/requests/JGEQgS57DQ1v83ZeHhaSKd

thanks
  Andrew

**Comment by ajwfrost** [comment]
Hi

We can't see anything wrong with this one .. the code signatures all look fine, our only thought at this point is whether the provisioning profile covers that particular iPad? Could you perhaps provide the last 5-6 characters of its UUID so we can confirm it's registered in there?

The device requirements seem to be okay (arm64, opengles2) - the only potential query would be over a field called `CFBundleSupportedPlatforms` - can't find documentation on this but there doesn't appear to be an 'ipad' option, but we may be better off without it... 

Do you have other iPads where you can see whether it works or not on different iOS versions, between the older iOS12 one?

thanks
