### ISSUE TITLE
Video Live Streaming not working with SDK 575, 633 Android

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#1301]
## Problem Description
Since the last updates on Android 10 and 11 the Live Video Streaming is not running smooth anymore on Android devices. It is stuttering and frozen and the stream stops after a few seconds.
I was wondering why the app. went down on Google Play Store until I found today the problem.
The last working SDK is 554, the best working is 476.
Maybe you can have a look what changed.
It is really very difficult already to develop with Adobe Air.
Enhanced microphone on iOS Phones does not work as well as on Samsung Phone. And now the streaming is also a problem.
Older SDKs create problems with the latest ANEs...
I am not happy and loose clients, day by day. 
## Known Workarounds
Moving back to 33.1.1.554 or 533 or 476
But how to target SDK 30 this way??? This is an urgent problem.

**Comment by apofis1969** [comment]
Hi @ajwfrost @marchbold the app with 554 and target 29 is online after a lot of discussions with Google. The curiosity in this case is, that they tested with armv7 devices and Android 10. If I can help to test with an SDK just tell me. If you need a build with 633 please also tell me.

**Comment by ajwfrost** [comment]
@apofis1969 if we can get a build of this with the .633 version it would be good, especially if you can build it with "apk-debug" mode.

When you talk about live streaming, do you mean you're streaming from a media server down to the Android device? Is it just video, or also audio? and is it H.264/AAC or other codecs that are used?

In case you need an upload link for your APK: https://transfer.harman.com/requests/AhBaSPViX9ZRD1eyZt7cE0

thanks

**Comment by apofis1969** [comment]
Hi, @ajwfrost  I will do the .633 build. Tomorrow or tonight you will get it. I am streaming with the normal codecs of Adobe Air between 2 devices. Spark and Speex. The normal live streaming of Adobe Air. I also could create a live web stream without encoder using Spark and Speex to a webplayer. Unfortunately can not make an update for Android, because of the target.

**Comment by apofis1969** [comment]
Hi @ajwfrost, sent you the file.

**Comment by apofis1969** [comment]
Hi @ajwfrost thanks for sending the overly files. It works now. Will use this to do the update. Thanks a lot!
