### ISSUE TITLE
aapt tool failed:First type is not attr!

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#1306]
packageApk:
     [java] NOTE: Multiple Android build-tools folders exist, choosing the latest version (30.0.3) for packaging
     [java] aapt tool failed:First type is not attr!
     [java] aapt.exe F 10-27 10:47:02 10068 21948 First type is not attr!
     [java]

This packaging error is encountered when using ane,but the ane demo is work well in Android Studio.
This problem may be caused by aapt.exe detection of res.
Can adobe air SDK choose aapt2 packaging?
I have set the parameter - Platform SDK when packaging,but It doesn't seem to work.

**Comment by ajwfrost** [comment]
If you're packaging for an APK and you're seeing this error, then it may be that it's best to remove the setting for platform SDK (from command line and/or the config file). It looks like there may be an updated version of AAPT in these 30.0.3+ build tools that needs a different command line from the earlier version.

AAPT2 is used when an app bundle is created but not when an APK is created. So the alternative could be to create a bundle.. or use the bundle option to generate the AndroidStudioProject folder and then build the APK from there? or alternatively if absolutely necessary, you could copy the aapt.exe from the AIR SDK over the version in the Android SDK build-tools\30.0.3 folder..

thanks
