### ISSUE TITLE
Application Tag Android: name be replaced when use aab mode to package.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#1307]
<android>

	<manifestAdditions>

		<![CDATA[

		<manifest android:installLocation="auto">

		<application android:allowBackup="true"   android:name="com.feidou.sdk.util.MyApplication">...</application>

    		</manifest>
		]]>

	</manifestAdditions>

</android>

When I use Adobe AIR SDK to package aab file,the android:name="com.feidou.sdk.util.MyApplication" be replaced to android:name="androidx.multidex.MultiDexApplication".
As a result, the code in com.feidou.sdk.util.MyApplication is not executed.
This is a very fatal problem because some SDK need to be executed in the com.feidou.sdk.util.MyApplication.

**Comment by pengyangjin** [comment]
> 
> 
> Which part of the HMS? Do you have a reference I could have a look at? Just find it odd that I haven't had to do this before.

package com.feidou.sdk.util;

import android.app.Application;
import android.content.Context;

import com.huawei.agconnect.config.AGConnectServicesConfig;
import com.huawei.agconnect.config.LazyInputStream;
import com.huawei.hms.api.HuaweiMobileServicesUtil;

import java.io.IOException;
import java.io.InputStream;


public class MyApplication extends Application {
    @Override
    public void onCreate() {       
            super.onCreate();
            HuaweiMobileServicesUtil.setApplication(this);
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
    }


    @Override
    protected void attachBaseContext(Context context) {
        super.attachBaseContext(context);
        AGConnectServicesConfig config = AGConnectServicesConfig.fromContext(context);
        config.overlayWith(new LazyInputStream(context) {
            public InputStream get(Context context) {
                try {
                    return context.getAssets().open("agconnect-services.json");
                } catch (IOException e) {
                    return null;
                }
            }
        });
    }
}

**Comment by ajwfrost** [comment]
Hi @pengyangjin  - can I check whether this ever worked in the past? From what I can see, it's never been possible to override the application name:

https://help.adobe.com/en_US/air/build/WSfffb011ac560372f2fea1812938a6e463-8000.html#WSfffb011ac560372f33105f2a1293d3d21e0-7ffd
> You cannot set the following attributes of the application element:
>- android:theme
>- android:name
>- android:label
>- ...

**Comment by pengyangjin** [comment]
> 
> 
> Hi @pengyangjin - can I check whether this ever worked in the past? From what I can see, it's never been possible to override the application name:
> 
> https://help.adobe.com/en_US/air/build/WSfffb011ac560372f2fea1812938a6e463-8000.html#WSfffb011ac560372f33105f2a1293d3d21e0-7ffd
> 
> > You cannot set the following attributes of the application element:
> > 
> > * android:theme
> > * android:name
> > * android:label
> > * ...



> 
> 
> Hi @pengyangjin - can I check whether this ever worked in the past? From what I can see, it's never been possible to override the application name:
> 
> https://help.adobe.com/en_US/air/build/WSfffb011ac560372f2fea1812938a6e463-8000.html#WSfffb011ac560372f33105f2a1293d3d21e0-7ffd
> 
> > You cannot set the following attributes of the application element:
> > 
> > * android:theme
> > * android:name
> > * android:label
> > * ...



If adobe air sdk can not be set up some att like android:name, the game engine will be even more difficult  in China.
Because many SDKs need to customize this attribute  like android:name  in China,this is not what game engine users can say no.I sincerely hope you can consider the usage habits of specific areas.

**Comment by ajwfrost** [comment]
Okay we can look at this, the only reason I know of for us keeping the app name is so that we can support the multidex capability, but as long as you're able to ensure that your app derives from the appropriate class then I think we can allow this customisation.

In the short term though, if you set your configuration file up so that it's got `KeepAndroidStudioOutput=true` uncommented, then when you've packaged an AAB file you should have an `AndroidStudioProject` folder. If you open this up in Android Studio, you can add whatever customisations you need to the manifest file etc.

thanks

**Comment by marchbold** [comment]
@pengyangjin Just FYI, AGConnectServicesConfig doesn't have to be done in a custom Application implementation. It can be done at any point before you use HMS. The example just uses this as this is the first place an application has access to the context.  

So you don't **need** a custom Application implementation here.
