### ISSUE TITLE
API Level 30

### ISSUE THREAD

**Issue by vusiem** [airsdk/Adobe-Runtime-Support#1328]
Hi after using
harman sdk 33.1.1.633

and setting
<manifest 
				android:installLocation="auto" 
				android:screenOrientation="portrait">
				uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />

and uploading the app to google play console i still get the error

**Your app currently targets API level 29 and must target at least API level 30 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 30**

**Comment by ajwfrost** [comment]
Strange if you have that targetSdkVersion field (or even if you omit it when you're using .633 release) - we should be setting that value with the Android manifest file. Do you have Android Studio installed? as if so, can you inspect the generated APK file and look at the manifest file to see what this says? (or are you generating an AAB file?)

Not sure whether it can be overwritten by anything but it may be worth just checking with a new/blank project to see whether the same thing happens to the generated APK/AAB file..

thanks

**Comment by vusiem** [comment]
Hi sorry my bad. I had forgot to set the PATH to adt on environment variables to the .633 build. all good now. closing it.
