### ISSUE TITLE
Video can't be played

### ISSUE THREAD

**Issue by aW4KeNiNG** [airsdk/Adobe-Runtime-Support#1337]
This issue is related to https://github.com/airsdk/Adobe-Runtime-Support/issues/80 using the latest AIR SDK (33.1.1.633)
The problem happens on Windows. I haven't tested on Mac yet.
Here is the video: https://www.dropbox.com/s/y3jgxjazuo4ewvw/test.mp4?dl=0
and the information from ffmpeg:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.51.100
  Duration: 00:00:02.03, start: 0.000000, bitrate: 184960 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 3060x1530 [SAR 1:1 DAR 2:1], 187129 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
```

NetStream fires NetStream.Play.Failed event.

**Comment by itlancer** [comment]
@aW4KeNiNG, for me your video works fine with AIR SDK 33.1.1.633 and Windows 10 x64 device using `Video` class.
Could you provide video playback AS3 code?

**Comment by aW4KeNiNG** [comment]
@itlancer I have checked the example in the #80 and it seems to work. I'm not sure why it isn't working on my application. It is a flex application but it should work too, right?

I'm going to close the issue. In the meantime I will check in deep why it isn't working.

**Comment by aW4KeNiNG** [comment]
@itlancer 
The issue happens when a VideoTexture is used to attach the netstream. It reports:

```
NetStream Code - Video texture width - Video texture height
NetStream.Play.Start 3060 1530
NetStream.Buffer.Full 3060 1530
NetStream.Play.Failed 0 0
NetStream.Play.Stop 0 0
```

**Comment by aW4KeNiNG** [comment]
I have attached an example using VideoTexture.

https://www.dropbox.com/s/ueybd7xqe2osya5/AIR33VideoTestAS3.zip?dl=0

@ajwfrost , any ideas?

**Comment by aW4KeNiNG** [comment]
@ajwfrost ? Any ideas?

What is the Harman email support? I have contacted them in the past without any response, and in theory I have "Priority email support for issues".

**Comment by ajwfrost** [comment]
Hi @aW4KeNiNG  - apologies, I'd missed this thread earlier .. 

I've just checked on the support inbox and can't see your messages so we may have an issue with some email filtering, I've had a couple of people say the same recently so I'd asked IT to look into it...

In the meantime -> I'll get someone to check out the above test app, and report back here.

thanks

**Comment by ajwfrost** [comment]
@aW4KeNiNG  - feedback on your mp4 file there: it's using a newer format of the H.264 spec than the AIR code knows about, so it looks like we identified some bits set that we expected to be zero and hence were failing the format check.

The good news -> the bits that are now set to '1' are just about constraint information, so we can modify the SPS handling internally and it then works.

So I'll get this fix put into our next release...

thanks

**Comment by aW4KeNiNG** [comment]
@ajwfrost perfect, thanks for letting me know ;)

**Comment by aW4KeNiNG** [comment]
It works in the latest version. Thanks !

**Comment by aW4KeNiNG** [comment]
I'm having the same issue using the next video in the latest AIR version (33.1.1.889): https://www.dropbox.com/s/mim3q5c0fcljw3f/videoerror.mp4?dl=0

**Comment by ajwfrost** [comment]
That video is "High 10" profile which isn't supported.. I've just tried taking out the checks that we perform on it and getting it to pass straight through to the Windows decoder but that also fails.. 

We can put this on hold in case it's possible to support this one via the new API that we're putting together, we can try it out at some point.
