### ISSUE TITLE
LaunchScreen is Black on iPhone 13 running iOS 15

### ISSUE THREAD

**Issue by Bilbosax** [airsdk/Adobe-Runtime-Support#1354]
Flex Project
Phone - iPhone 13 Pro running on iOS 15.0.2
AIR SDK - 33.1.1.633

I am using Michael's script from Distriqt to create my Assets.car and LaunchScreen.storyboardc assets.  You can view his script here:

https://github.com/distriqt/AIR-ImageScripts

I have two projects set up identically, one for an iPad and one for a phone.  I put that the same exact Assets.car and Launchscreen.sotryboardc files in both projects and made the necessary InfoAdditions changes in my app descriptor files.  The Launchscreen runs perfectly on the iPad, but on the iPhone, I just get a blackscreen at startup.

Because I am using an iPad that runs iOS 9, it needs to run AIR 33.1.1.476.  The iPhone 13 running iOS 15.0.2 requires your latest SDK of 33.1.1.633.  The SDK is the ONLY single difference I can see between the two projects.  Michael has double-checked his script and thinks it should be working fine, so I trust that it contains the properly named and sized files for the launchscreeen.  So I am wondering if it possibly has something to do with 33.1.1.633.  The same problem happens on an iPhone 12 running a later version of iOS 14.  I have uploaded my Assets.car and LaunchScreen.storyboardc in the zip file attached below.  Please let me know if you can think of any reason my launchscreen would not be working using 33.1.1.633 on an iPhone 13 running iOS 15.0.2.

Thanks!

[MyAssets.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7523476/MyAssets.zip)

**Comment by marchbold** [comment]
Forgot to ask something obvious in the starling forum, have you got your license in both AIR SDK versions? If you don't have a license the custom launch screen won't work.

**Comment by Bilbosax** [comment]
Yes, I put the adt.lic file in the lib folder of my SDK in both SDK's

**Comment by Bilbosax** [comment]
@marchbold So I installed the sdk outside of Flash Builder so that there would be no permissions issue with the adt.lic file.  So, I know it is not the license file.

I used your script on a launch image that was 4000 x 4000, so I know it was not the resolution of the launch image.

I have included the same Assets.car and LaunchScreen.storyboardc in both projects.  It works on an iPad using 33.1.1.476, but not on an iPhone using 33.1.1.633.

You say that you are using 33.1.1.633 with no problems.  But are you absolutely sure???  I mean, is it possible that your launch screens are cached too and are only working in 33.1.1.633 because they are cached?

Could you or Andrew download my launchscreen and Assets.car and use them in a project to see if they work on your devices with 33.1.1.633?  Should be an easy test since you already have projects made I'm sure.

Thanks.

**Comment by marchbold** [comment]
That may be too large an image. 

I do see a black screen with your assets. 

Have you tried the suggested resolution of 2732x2732? Could you send me your launch image and icon so i can have a play?

**Comment by marchbold** [comment]
(Also yes definitely working with 633, I've can change the launch screen completely by creating something different and reinstalling/restarting the device)

**Comment by marchbold** [comment]
Okay I've done some more testing, and I think it's something with the png you are using. I've added it to a simple Xcode project and it shows up black in the simulator. I am trying to find some details on what format the image should be exactly but having troubles finding anything specific.

**Comment by marchbold** [comment]
Okay, found the issue, in the [UI Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/launch-screen/)

> In iOS 14 and later, the launch screen is limited to 25 MB.

This is uncompressed i.e bitmap size. So the image is too large :) 

I reduced your image to 2400x2400 (~23mb?) and it worked fine. The images I were testing with weren't complete sRGB so didn't have as many channels per pixel and aren't as large.

**Comment by Bilbosax** [comment]
Michael, you are truly a brilliant man and an asset to this community.  I saw that launchscreen reference on apple's site limiting the size to 25MB, but since your instructions recommended 2732 x 2732 combined with the fact that the png was only 100k, I thought I was more than good. Not to mention, all the resized images produced by imagemagick were under 30k, and none of them looked black, so I just ruled it out as a possibility.  I don't know how to look inside the Assets.car file, but I assumed that no matter how large I created the Launch Image, that imagemagick was resizing it appropriately to keep it within the sizing limits.  Perhaps you could add that to your script.  It never even OCCURRED to me that the uncompressed bitmap might actually be over 25MB.  A very deceiving little problem.  I really truly appreciate you taking the time to help me out.  Have a great weekend!

Cheers.

**Comment by marchbold** [comment]
Brilliant! Glad to help! 

Yeah that recommended size was what most people were using in the ios community so I thought it wouldn't be an issue. Just had missed that change in the ui requirements. 

I've already updated the script to limit the launch image to 2400 pixels so if you grab the latest it should resize it automatically for you in the future. 

Cheers
