### ISSUE TITLE
iOS iPad Mini 6 resolution error

### ISSUE THREAD

**Issue by pavelzmolik** [airsdk/Adobe-Runtime-Support#1358]
Hello, i tried make an IPA app to iOS and installed it into new iPad Mini 6 and i got some resolution error...
## Problem Description

The new AIR SDK cant recognize real resolution of new iPad Mini 6, which is 2266x1488
[https://www.theiphonewiki.com/wiki/IPad_mini_(6th_generation)](https://www.theiphonewiki.com/wiki/IPad_mini_(6th_generation))

it shows me 1333x744, so exactly 50% of the native resolution.. 

The App is working.. but the graphics are distorted because of double scale..

## Steps to Reproduce

Look at my screenshots from my device and another testing devices i use.. e.g. iPad Mini 2, iPhone 12 Pro Max
[iPad Mini 6](https://www.pavelzmolik.cz/dl/ipad_mini6.jpg)
[iPad Mini 2](https://www.pavelzmolik.cz/dl/ipad_mini2.jpg)
[iPhone Pro Max](https://www.pavelzmolik.cz/dl/iphone_12_promax.jpg)

You can see another devices get correct native resolutions, so the graphics is nice sharp.. Every other device i tried(which I have at home) show correct resolution except the new iPad Mini 6

I tried _stage.fullScreenWidth_ even _Capabilities.screenResolutionX_ but the result is the same..
I can provide my source code of the testing app but I think the bug is inside the SDK..

Please can you fix this bug?
thanks and best regards
Pavel Zmolik

**Comment by ajwfrost** [comment]
Hi @pavelzmolik  - can I just check why you closed this issue? Not sure whether this is something we need to look into .. normally the resolutions are set via launch images though so it may be an update needed there..
thanks

**Comment by pavelzmolik** [comment]
Hello @ajwfrost
I closed this issue because I research the point of that bug..
In the descriptor i have this settings:
`<requestedDisplayResolution excludeDevices="iPad1 iPad2 iPad3,1 iPad3,2 iPad3,3 iPad3,4 iPad3,5 iPad3,6">high</requestedDisplayResolution>`

And the ID of the new ipad mini 6 is **iPad14,1** or **iPad14,2** 
But the compiler is probably coming with something like 
`string.indexOf(iPad1)`
 so if the ID of iPad begin with 1 it exclude all new iPads(,Ipad Mini 6,iPad Mini5, iPad Pro 5th gen, iPad Pro 3rd gen, iPad Air 3rd and 4th gen, and so on)
Yes its some kind of bug, but I think many years ago developers didn't expect so many generations of devices :) If you can fix it it can be more comfortable, but it isn't necessary.. I these days I think you cannot deploy new apps to the devices withou retina display.. If the new iPad mini didnt come with the new aspect ratio I've never get the point.. Because I have to calculate apps for the older devices to optimize lack of CPU power..
I had to make some research of the workaround before I wrote this solution..
cheers and thanks you noticed this thread..
