### ISSUE TITLE
macOS Catalina: adl killed by OS

### ISSUE THREAD

**Issue by ciacob** [airsdk/Adobe-Runtime-Support#1359]
## Problem Description

Used ItelliJ Idea to build a most simple AIR/FLEX application on Earth, compiled it, and tried to tun it with ADL, but it gets killed by the OS.

* Which AIR SDK did you use? 
   **AIR 33.1.1 for MacOs, Flex version**; overlaid over perfectly working **AIR 28.0.0/Apache Flex 4.16.1** combo. <br><br>
* Describe the affected environment:
   **macOs Catalina** (Intel machine, needles to say).<br><br>
* Can you reproduce it yourself, or did you get reports from other users? 
   I can reproduce it with minimal setup. <br>See attached [delme.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7539305/delme.zip), which contains **Main.swf** and **Main-descriptor.xml**. See also [project.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7539315/project.zip), which contains the IntelliJ IDEA project that compiled the SWF (compilation went flawless).<br><br>I CAN REPRODUCE THE ISSUE FROM THE COMMAND LINE. It is **not** IDE related.

## Steps to reproduce
So I have my SDK in `/Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/`, and the project sits at `/Users/ciacob/IdeaProjects/delme/`, with files being compiled to `/Users/ciacob/IdeaProjects/delme/out/production/delme/`. Therefore, I type into Terminal:

```bash
/Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/bin/adl -profile extendedDesktop /Users/ciacob/IdeaProjects/delme/out/production/delme/Main-app.descriptor /Users/ciacob/IdeaProjects/delme/out/production/delme
```
and I get:

```
zsh: killed     /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/bin/adl -profile extendedDesktop  
```
I know Catalina is somewhat old, but it still should be on your list of supported systems.

Thanks.

**Comment by ajwfrost** [comment]
Hi @ciacob  - can I just check which exact build you're using? If you run ADL without any arguments it should tell you...
thanks

**Comment by ciacob** [comment]
Well, it gets get killed even when run with **no arguments,** so, no, I am afraid I cannot give you this information :-(

**Comment by ciacob** [comment]
I do not know "who" kills it or why, and don't know how to find out either.

**Comment by ajwfrost** [comment]
Okay alternatively then: `./adt -version`?
thanks

**Comment by ciacob** [comment]
33.1.1.674
So I guess is the **674** build.

**Comment by ajwfrost** [comment]
Okay - just thinking about this, are you able to go into the root folder of the SDK within a terminal window and try to clear any quarantine flags that may be left on the SDK?
```
cd /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/
xattr -r -d com.apple.quarantine .
```

thanks

**Comment by ciacob** [comment]
Aren't extended attributes suggested by a leading "@" when doing a `ls -la *`? Because I see no `@` sign.

**Comment by ciacob** [comment]
Nevertheless, I did that quarantine removal and I'm still not able to run adl
I wonder, what if I copy it from an older SDK?

**Comment by ajwfrost** [comment]
Yes - but I would expect those to appear on anything you'd downloaded from the web, maybe it was just Big Sur and up that did that. Thanks for trying it...

Next thought would be something up with the code signature of the application, are you able to run:
```
codesign -v -vvv runtimes/air/mac/Adobe\ AIR.framework
```
and perhaps
```
 codesign -d --entitlements - bin/adl
```
to check that the files are okay?

thanks

**Comment by ciacob** [comment]
Well, I got the output:

```
runtimes/air/mac/Adobe AIR.framework: a sealed resource is missing or invalid
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/MacOS/FlashPlayer-10.6
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/Resources/AIRCaptivePluginMessage.bmp
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/Info.plist
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/version.plist
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Adobe AIR.vch
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Adobe AIR_64 Helper
```

for the first command, and

```
Executable=/Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/bin/adl
??qqG<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.cs.allow-dyld-environment-variables</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
	<key>com.apple.security.cs.disable-library-validation</key>
	<true/>
	<key>com.apple.security.device.camera</key>
	<true/>
	<key>com.apple.security.device.microphone</key>
	<true/>
</dict>
</plist>
```
for the second. I'm not familiar with `codesign`, so I do not know if this is relevant in any way. `Adl` keeps getting killed after running the two commands.

**Comment by ciacob** [comment]
I believe I leave you to it, I must go. Packing proceeds correctly, though, and the packed `*.app` file runs just fine.

**Comment by ajwfrost** [comment]
Okay thanks! So I believe the first output shows what the issue is; the second one looks fine, it shows the appropriate entitlements that we'd expect.

But the first one is showing that the signature is wrong, because of some unexpected files:
```
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/MacOS/FlashPlayer-10.6
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/Resources/AIRCaptivePluginMessage.bmp
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/Info.plist
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin/Contents/version.plist
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Adobe AIR.vch
file added: /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Adobe AIR_64 Helper
```
i.e. when we signed the framework, those files weren't present. I expect these are left over from a previous version of the SDK: if you updated an earlier one that was Flex + AIR, then this would explain it. (It should work okay if you just took Flex + this AIR SDK..)

To solve it, it should just be enough to delete the extra files:
```
rm -rf "/Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Flash Player.plugin"
rm "/Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Resources/Adobe AIR.vch"
rm" /Users/ciacob/_BUILD_/Flex-4-16-1-AIR-33/runtimes/air/mac/Adobe AIR.framework/Versions/Current/Adobe AIR_64 Helper"
```
Perhaps just worth checking that the first codesign command is now just saying it's valid:
```
codesign -v -vvv runtimes/air/mac/Adobe\ AIR.framework
runtimes/air/mac/Adobe AIR.framework: valid on disk
runtimes/air/mac/Adobe AIR.framework: satisfies its Designated Requirement
```

thanks

**Comment by ciacob** [comment]
OK, so deleting those files made indeed `codesign` happy:

```
ciacob@192-168-0-5 Flex-4-16-1-AIR-33 % codesign -v -vvv runtimes/air/mac/Adobe\ AIR.framework
runtimes/air/mac/Adobe AIR.framework: valid on disk
runtimes/air/mac/Adobe AIR.framework: satisfies its Designated Requirement
```

However, it did not change anything with respect to running `adl`:
```
ciacob@192-168-0-5 Flex-4-16-1-AIR-33 % bin/adl                                               
zsh: killed     bin/adl
ciacob@192-168-0-5 Flex-4-16-1-AIR-33 % 
```

**Comment by ciacob** [comment]
OK, I believe we should close this down. 

> I do not know why, but it seems like **one cannot simply drop a newer `AIRSDK_Flex` distribution on top of an already overlaid AIR + Flex package.**

Did it again, from scratch:
1. downloaded **Flex 4.16.1 MacOs** binary from http://flex.apache.org/download-binaries.html and unarchived it;
2. added `flex-fontkit.jar`, `afe.jar` and `rideau.jar` to its `lib` folder (I already had them in an older combo);
3. added `osmf.swc` to its `frameworks/libs` folder (also had these in an older SDK + Flex combo);
4. downloaded **AIR SDK for MacOS - (33.1.1.674)** from https://airsdk.harman.com/download, under "AIR SDK for Flex Developers - to be overlaid onto a Flex SDK" (there is a separate section on that page); unarchived that too;
5. launched the terminal and typed something like:

```
ditto /path/to/unarchived/AIR_SDK /path/to/unarchived/FLEX_SDK
```
Received no complains or errors. Then, still in the terminal, I did:
```
/path/to/unarchived/FLEX_SDK/bin/adl
```
and received:
```
Adobe (R) AIR (R) Debug Launcher (ADL)
Version 33.1.1.674
Copyright (c) 2008-2019 Adobe. All Rights Reserved.

application descriptor file not specified
usage:
  adl ( -runtime <runtime-dir> )? ( -pubid <pubid> )? -nodebug? ( -profile PROFILE )? ( -extdir <extensions-dir> )? ( -screensize SCREEN_SIZE )? <app-desc> <root-dir>? ( -- ... )?
  adl -help

PROFILE                : mobileDevice|extendedMobileDevice|desktop|extendedDesktop|tv|extendedTV
SCREEN_SIZE            : ( <width>x<height>:<fullscreen width>x<fullscreen height> )|PREDEFINED_SCREEN_SIZE
PREDEFINED_SCREEN_SIZE : iPhone|iPhoneRetina|iPhone5Retina|iPhone6|iPhone6Plus|iPod|iPodRetina|iPod5Retina|iPad|iPadRetina|Droid|NexusOne|SamsungGalaxyS|SamsungGalaxyTab|QVGA|WQVGA|FWQVGA|HVGA|WVGA|FWVGA|1080|720|480
```

So it **does** work. In the end, I renamed the `/path/to/unarchived/FLEX_SDK/` to something like `Flex.4.16-AIR.33.1`.

I'm sorry for having wasted everyone's time.

**Comment by ajwfrost** [comment]
Thanks for all the efforts here.. I might see if we can replicate this here, if it's to do with overlaying AIR 33 on top of AIR 28 + Flex. I've never been very happy with how the Flex and AIR SDKs have to be merged, it causes all sorts of issues like this :-(

thanks
