### ISSUE TITLE
StageWebView always shows on Main Window not using stage of other windows (Multi Window App)

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#1413]
**StageWebView**, used on a different window, will show on the initial/main window of the AIR app and not on the window where it was instatiated. It was made sure that the correct _stage_ of that window was passed to the StageWebView.
Issue is always reproducible.

* Which AIR SDK did you use? 
AIR 33.1.1.686

* Describe the affected environment:
Windows 10

**Comment by ajwfrost** [comment]
This appears to be a common problem on Windows: the creation of the native StageWebView happens in one step, and then the developer sets the 'stage' value - but by then, the Windows component has been created under a particular window structure and it can't be moved across to another one. So this is essentially a bad 'feature', the only way around this is to provide the stage at the time of construction of the StageWebView object.

Trying to decide whether we should just add another parameter to the StageWebView constructor, or instead have a new method on NativeWindow (or Stage) to create a StageWebView under that stage... 

The alternative would be to throw away all state when the stage value is changed on a WebView i.e. shut down the native implementation and re-create it on the new stage. So if you can provide your thoughts it would be good:
- would you rather that you create a StageWebView and use it as you do now, with the restriction that any history etc is lost if you change the stage (we can retain the current URL of course, but it would re-load)
- or would you prefer to have to create a new StageWebView using a new mechanism if you want it on a specific NativeWindow instance?

thanks

**Comment by itlancer** [comment]
> would you rather that you create a StageWebView and use it as you do now, with the restriction that any history etc is lost if you change the stage (we can retain the current URL of course, but it would re-load)

@ajwfrost 
I would prefer alternative way.
Creating new `StageWebView` instance passing stage or via `NativeWindow` method also good but we would like to have possibility to "move" `StageWebView` instance between windows (of course with some limitations you described).

**Comment by 2jfw** [comment]
@ajwfrost 
We would prefer the way where it is possible to assign a new stage to the webview and thus make it possible that the webview instance can be added to a new/different stage (e.g. when swapping content tabs from one window to another)

**Comment by 2jfw** [comment]
@ajwfrost Any news on this?

**Comment by ajwfrost** [comment]
@2jfw this one rings a bell, I thought we had sorted this out when we also fixed the #1496 issue linked above... at least for the Edge WebView2.

... yes I just checked the change for that and it does seem to be just for WebView2. The similar approach might work with the MSHTML-based StageWebView though, we will look into this one...

thanks

**Comment by 2jfw** [comment]
> @2jfw this one rings a bell, I thought we had sorted this out when we also fixed the #1496 issue linked above... at least for the Edge WebView2.

I can confirm that this is actually working now (using latest version .758).
StageWebView2 is now properly displayed on all windows.
Just wondering, I did not see any info on this issue being fixed - did I overlook it?
