### ISSUE TITLE
[AIR 33.1.1.698] AIR SDK build Android APK with default architecture x86 using BuildLegacyAPK

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1418]
## Problem Description
AIR SDK build Android APK with default architecture x86 instead of armv7 using AIR 33.1.1.698 and `<BuildLegacyAPK>true</BuildLegacyAPK>` in application descriptor XML.

It has been tested with latest AIR SDK 33.1.1.698 with different Windows 10 64-bit devices.
Same problem in all cases.
There is no such problem with AIR SDK 33.1.1.686 and below.
Didn't test it for macOS environment.

## Steps to Reproduce
Try to package AIR application for Android armv7 with `<BuildLegacyAPK>true</BuildLegacyAPK>` in application descriptor XML.
Packaging command:
`adt -package -target apk-captive-runtime -storetype pkcs12 -keystore android.p12 -storepass password -keypass password test_app.apk test_app-app.xml -extdir libs test_app.swf`

**Actual Result:**
Result APK will be x86 architecture and cannot be installed for ARM devices (you will get error `failed to install test_app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`).

**Expected Result:**
Result APK will be armv7 architecture as with AIR SDK 33.1.1.686 and below. Or if default architecture changed (or not applicable anymore) - it should be noticed in AIR SDK Release Notes.

## Known Workarounds
Specify armv7 architecture explicitly in packaging command:
`adt -package -target apk-captive-runtime -arch armv7 -storetype pkcs12 -keystore android.p12 -storepass password -keypass password test_app.apk test_app-app.xml -extdir libs test_app.swf`
Or don't use `<BuildLegacyAPK>true</BuildLegacyAPK>`.

**Comment by ajwfrost** [comment]
Interestingly this only happens if you use `apk-debug` or `apk-captive-runtime`; if you use `apk` it correctly defaults to armv7.

Looks like it's just a bad condition when it thinks it's generating a windows target rather than an APK..

**Comment by itlancer** [comment]
Fixed with latest AIR 33.1.1.713.
Thanks!
