### ISSUE TITLE
[AIR 33.1.1.698] AIR SDK build Android APK with all ABIs (architectures)

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1429]
## Problem Description
AIR SDK build Android APK with all ABIs (architectures) instead of default armv7 (or specified via `-arch` packaging argument) using AIR 33.1.1.698.

It has been tested with latest AIR SDK 33.1.1.698 with different Windows 10 64-bit devices.
Same problem in all cases.
There is no such problem with AIR SDK 33.1.1.686 and below.
Didn't test it for macOS environment.

Related issue (not the same): https://github.com/airsdk/Adobe-Runtime-Support/issues/1418

It could be great feature for some cases to build "universal" APK for all architectures (devices). But it should be optional and documented.
I think may be right decision:
If packaging command have "-arch" option with specific architecture - then it should be packaged with specified architecture.
If no "-arch" option (or some new "-arch all"?) specified - then it should be packaged with all supported architectures. Or may be somehow specify architectures that need to be included.

## Steps to Reproduce
Try to package AIR application for Android armv7.
Packaging command:
`adt -package -target apk-captive-runtime -storetype pkcs12 -keystore android.p12 -storepass password -keypass password test_app.apk test_app-app.xml -extdir libs test_app.swf`

**Actual Result:**
You will get APK that contains all ABIs (armv7, armv8, x86, x86_64) and APK size will be around x4 bigger.

**Expected Result:**
Result APK will be armv7 architecture as with AIR SDK 33.1.1.686 and below.
Or "universal" APK packaging should be documented in AIR SDK Release Notes.

## Known Workarounds
Use `<BuildLegacyAPK>true</BuildLegacyAPK>` in application descriptor XML.

**Comment by ajwfrost** [comment]
Thanks
We don't want to change the existing behaviour really (i.e. if you don't specify an architecture, it defaults to armv7) but can add an "all" option for those that want to have a single APK that does contain all of the different ABIs.

**Comment by itlancer** [comment]
Fixed with latest AIR 33.1.1.713.
Thanks!
