### ISSUE TITLE
[IntelliJ] How to automatically install Adobe Air runtime on Android device for debug version apk

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/Adobe-Runtime-Support#1433]
Hello, as we cannot embed the captive runtime for debug version of the apk, How am I going to download the Adobe Air apk and install it on the real device? Thanks so much!
I'm using IntelliJ. I find the Adobe air Runtime got automatically installed if I switched to FB4.7...Did I miss any settings in IntelliJ?

**Comment by ajwfrost** [comment]
This may be another occasion where the IDEs are doing something slightly different/out-dated from the actual ADT command-line tools. Even an "apk-debug" build should result in the runtime being packaged up as a captive runtime embedded within the application... I will have to check with a colleague to investigate the IntelliJ behaviour further..

**Comment by jimmymjing** [comment]
My apologies. I find that the debug version of the APK published by IntelliJ indeed packaged up with captive runtime. I'm so sorry... 
The problematic IDE is FB4.7 which forces to install Adobe Air Runtime on device for debugging.
