### ISSUE TITLE
How to increase JVM memory for debugging android app

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/Adobe-Runtime-Support#1436]
Hello, I'm trying to debug an Android app in IntelliJ and getting the error message saying JVM is out of memory. I tried to edit the adt.cfg file, but it doesn't affect the adt command line param. Is there a place to set adt command params in IntelliJ? Thanks so much!

**Comment by marchbold** [comment]
Check this out:

https://github.com/airsdk/Adobe-Runtime-Support/discussions/1426#discussioncomment-1769453

I suggest you use the discussion forum for things like this rather than creating issues.
