### ISSUE TITLE
Your App Bundle contains the following configurations where the initial install would exceed the maximum size of 150 MB

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/Adobe-Runtime-Support#1476]
Hello, I'm trying to figure out how to package aab with ”asset packs"(PAD). I followed the Release Note and added the tag as below:
(`assets` folder contains all the static assets to be packed in PAD)
```
 <assetPacks>
      <assetPack id="ap_assets" delivery="install-time" folder="assets"/>
 </assetPacks>
```
And I also tried to package with the following adt command:
`
adt -package -target aab -storetype PKCS12 -keystore /path/to/voxAndroidCerti.p12 -storepass xxx /path/to/Bf_Android.aab /path/to/Bf-app.xml -extdir /path/DigitalStrewberryAnes -extdir /path/Biofanta_dependency -extdir /path/ane -C /path/Bf/bin-Android Bf_Android.swf -C /path/Bf/assets . -C /path/Bf/src/res .
`
The aab file got successfully packaged but I have no idea if the pad file got embedded in successfully. I tried to upload it to Google Play, but got the error output saying: `Your App Bundle contains the following configurations where the initial install would exceed the maximum size of 150 MB` while I was trying to upload the abb to the play console.
Any comments would be appreciated!!!

**Comment by ajwfrost** [comment]
Just seen you've closed this so presumably don't need the response but in case it's helpful to others looking this up later ..

The asset pack "folder" value needs to be a folder that is provided as part of the list of input files, and it's then deemed to contain the files/folders that should be put into the asset pack. So if you have:
```
[root folder]/my_asset_packs/asset_pack_1/my_file.txt
```
then you should package this using something like
`<assetPack id="pack1" delivery="install-time" folder="asset_pack_1"/>`
and
`adt  -package -target aab my_app.xml my_app.swf -C my_asset_packs . -extdir ane`
So this means we'll include the contents of `my_asset_packs` i.e. a folder called `asset_pack_1` which then matches the folder name given in the XML file -> so then we know that the contents of this folder should instead be provided as an asset pack.

thanks
