### ISSUE TITLE
Android. Moving project from 33.1.1.633 to 33.1.1.713, compilation halts with "Gradle-based creation needs Android SDK path to be provided"

### ISSUE THREAD

**Issue by PippoApps** [airsdk/Adobe-Runtime-Support#1482]
## Problem Description
Compiling with Animate CC.
Moved to latest version of AIR, and Android shows the error (compiles fine for iOS and Windows).
Compilation halts with the following message using 33.1.1.713 (same project compiles fine with 33.1.1.633).
![image](https://user-images.githubusercontent.com/29799572/147086683-16d7e047-21af-494a-8d42-ae6c82e399fe.png)
 

## Known Workarounds
Use 33.1.1.633

**Comment by ajwfrost** [comment]
If you're using Animate then you'll need to put the path into the configuration file:
`[sdk_folder]\lib\adt.cfg`
and add a value such as
`AndroidPlatformSDK=c:/users/username/appdata/local/android/sdk`

**Comment by PippoApps** [comment]
cheers @ajwfrost,
the path refers to correct SDK folder, now there is another error message:
![image](https://user-images.githubusercontent.com/29799572/147496486-e21b3968-398f-4877-ba7b-0667d2f77efb.png)

**Comment by PippoApps** [comment]
It seems it can't find the path:
AndroidPlatformSDK=C:\Users\PC-1\AppData\Local\Android\Sdk

**Comment by PippoApps** [comment]
Gotcha.
Needs forward slashes also on windo
AndroidPlatformSDK=C:/Users/PC-1/AppData/Local/Android/Sdkws. Cheers
