### ISSUE TITLE
[Feature Request] Ability to control permission requests programmatically for StageWebView

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1494]
## Feature Description
AIR should have ability to control permission requests programmatically with `StageWebView` for Windows.
Essential for modern WebView2 implementation with `<UseWebView2>true</UseWebView2>` in application descriptor.

Right now it not possible programmatically to grant or deny permission request to use Camera/Microphone/... via website with `StageWebView`. It could be done only manually by user.
In many cases it not acceptable. Especially for retail kiosks where is no user.

Related links:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/308#issuecomment-864734344
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=WebView2-dotnet-1.0.664.37
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionkind?view=webview2-dotnet-1.0.1054.31

I think it could be implemented with `StageWebView` and `PermissionEvent`. If AS3 code handle such `PermissionEvent` for `StageWebView` it should have a method to grant or deny permission request by code. If it doesn't handle - default permission prompt for user should be shown.

Useful functionality for other platforms too.

Related issue (not the same):
https://github.com/airsdk/Adobe-Runtime-Support/issues/1492
https://github.com/airsdk/Adobe-Runtime-Support/issues/1493

## Known Workarounds
none

**Comment by itlancer** [comment]
Now permissions of application automatically granted to `StageWebView`.
Tested with latest AIR 51.1.1.5.
Thanks!

**Comment by marcanw** [comment]
Wonderful :-)
Thank you @ajwfrost

**Comment by raresn** [comment]
@itlancer where can we see the details on how this new mechanism works?

**Comment by ajwfrost** [comment]
@raresn best approach is to go to the "Release Notes" section on our website and search for this ID (1494) to find out what release it's in; then click on the "Full Release Notes PDF" for it and search again for the ID. That may not always work but it's the general intention!

For this one:
> When an embedded browser engine used by a WebView control is requesting permissions from the end user, this is now being redirected into the AIR application logic to check whether the application already has those permissions. If so, the appropriate response is sent to the webview control; if not, the user is prompted to grant/deny the permissions via the current PermissionManager mechanisms. 

So basically it should just hook in to the existing permissions mechanism for the application e.g. when trying to use an AS3 Camera, etc.

**Comment by raresn** [comment]
Thx a lot. You are right. Release notes! :)
