### ISSUE TITLE
[AIR 33.1.1.686] AIR SDK build IOS ipa crashed at start with my iPhone 8

### ISSUE THREAD

**Issue by llyRayYoung** [airsdk/Adobe-Runtime-Support#1501]
I updated my AIR SDK form 33.1.1.444 to 33.1.1.686, in the previous version, it worked normally, but in the latter version, it crashed at the begining. Can you help me find out what's wrong? This is my crash log

## Crash Log
Date/Time:           2021-12-20 19:13:42.2915 +0800
Launch Time:         2021-12-20 19:13:42.1453 +0800
OS Version:          iPhone OS 14.8.1 (18H107)
Release Type:        User
Baseband Version:    4.05.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000068
VM Region Info: 0x68 is not in any region.  Bytes before following region: 4330373016
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   1021c4000-1042e0000 [ 33.1M] r-x/r-x SM=COW  ...zlwc.app/zlwc

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [6964]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   zlwc                          	0x00000001024997a0 avmplus::ApplicationObject::get_applicationDescriptor() + 0
1   zlwc                          	0x00000001021db7e8 -[CTAppController application:shouldAllowExtensionPointIdentifier:] + 68
2   UIKitCore                     	0x0000000186e93000 -[UIKeyboardInputModeController+ 8052736 (Compatibility) enabledInputModeIdentifiers:] + 692
3   UIKitCore                     	0x0000000186e8811c -[UIKeyboardInputModeController activeInputModeIdentifiers] + 28
4   UIKitCore                     	0x0000000186fef988 -[UIKeyboardImpl initWithFrame:forCustomInputView:] + 684
5   UIKitCore                     	0x0000000186fed708 +[UIKeyboardImpl sharedInstanceForCustomInputView:] + 136
6   UIKitCore                     	0x0000000186fe7aa0 +[UIKeyboard isInHardwareKeyboardMode] + 28
7   WebKit                        	0x00000001906d5880 WebKit::WebPageProxy::creationParameters+ 3430528 (WebKit::WebProcessProxy&, WebKit::DrawingAreaProxy&, WTF::RefPtr<API::WebsitePolicies, WTF::RawPtrTraits<API::WebsitePolicies>, WTF::DefaultRefDerefTraits<API::WebsitePolicies> >&&) + 1368
8   WebKit                        	0x00000001906d517c WebKit::WebPageProxy::initializeWebPage+ 3428732 () + 152
9   WebKit                        	0x0000000190396334 -[WKContentView _commonInitializationWithProcessPool:configuration:] + 128
10  WebKit                        	0x0000000190396284 -[WKContentView initWithFrame:processPool:configuration:webView:] + 168
11  WebKit                        	0x0000000190394794 -[WKWebView _initializeWithConfiguration:] + 1228
12  WebKit                        	0x00000001903942b4 -[WKWebView initWithFrame:configuration:] + 76
13  WebKit                        	0x000000019039bb74 -[WKWebView initWithFrame:] + 92
14  zlwc                          	0x0000000103eae158 +[Class_CusCarr _internalGetUA:] + 60
15  libdispatch.dylib             	0x00000001845a62b0 0x184546000 + 393904
16  libdispatch.dylib             	0x00000001845a7298 0x184546000 + 397976
17  libdispatch.dylib             	0x0000000184589430 0x184546000 + 275504
18  CoreFoundation                	0x00000001848ee998 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
19  CoreFoundation                	0x00000001848e8df8 __CFRunLoopRun + 2528
20  CoreFoundation                	0x00000001848e7ed0 CFRunLoopRunSpecific + 572
21  GraphicsServices              	0x000000019b033570 GSEventRunModal + 160
22  UIKitCore                     	0x00000001872152d0 -[UIApplication _run] + 1052
23  UIKitCore                     	0x000000018721a84c UIApplicationMain + 164
24  zlwc                          	0x00000001022bf670 main + 76
25  libdyld.dylib                 	0x00000001845c6140 0x1845c5000 + 4416

**Comment by ajwfrost** [comment]
Hi
Judging by the call stack, this is related to the new ability to block off the ability to have custom, third-party keyboards (for privacy/security concerns). We will re-look at this to see what may be causing the crash there!
thanks

**Comment by llyRayYoung** [comment]
您好!来信已收到,谢谢!

**Comment by llyRayYoung** [comment]
Fixed with latest AIR 33.1.1.731.
Thanks!
