### ISSUE TITLE
error when i test after i created reward interstitial

### ISSUE THREAD

**Issue by atiani** [airsdk/Adobe-Runtime-Support#1515]
AIR SDK version: 33.1.1.731
Device OS: andriod
Device version: 30
Development IDE:adobe animate
Development OS:windows
i have this error when i test the reward interstitial on the other hand i follow your steps correctly
below : the error :

Scene 1, Layer 'Layer_2', Frame 1, Line 102, Column 88 1067: Implicit coercion of a value of type com.distriqt.extension.adverts.rewardedinterstitial:RewardedInterstitialAd to an unrelated type com.distriqt.extension.adverts.rewardedinterstitial:RewardedInterstitialAds.

please help me

**Comment by marchbold** [comment]
Any issues with the distriqt ANEs you should post in the appropriate support repository: 

https://github.com/distriqt/ANE-Adverts/issues

**Comment by marchbold** [comment]
Appears you've already posted there, our developers will follow up with you there: 

https://github.com/distriqt/ANE-Adverts/issues/356

**Comment by atiani** [comment]
OK am sorry about that 
Thank you Sir
