### ISSUE TITLE
Custom Android TV banner not showing when creating APK with Gradle

### ISSUE THREAD

**Issue by lwmirkk** [airsdk/Adobe-Runtime-Support#1564]
## Problem Description

Custom Android TV banner not showing when creating APK with Gradle.
If use the BuildLegacyAPK option, the custom banner is included correctly.

* Which AIR SDK did you use?
Flash CC to export SWF and CMD to generate the APK
Tested with 33.1.1.698 - 33.1.1.713

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
Android TV OS 

## Steps to Reproduce

`call "D:\Adobe\AIRSDK\33.1.1.713\bin\adt.bat" -package -target apk-debug -connect "MY_IP" -storetype pkcs12 -storepass "PASS" -keystore "PATH TO CERT.p12" "APK.apk" Android-App-app.xml -extdir "PATH TO ANE FOLDER" Android-App.swf assets/app`

Descriptor:
`<banner>assets/app/banner-320x180.png</banner>`

## Known Workarounds

Only if use the BuildLegacyAPK option, the custom banner is included correctly. But APK is used only for debug purpose, AAB is needed for Play Store.

**Comment by ajwfrost** [comment]
Hi @lwmirkk 
Just double-checking the behaviour here: do you see a "Powered by Adobe AIR" banner, rather than the custom one? or is there another behaviour e.g. completely missing image or error message?
thanks

**Comment by lwmirkk** [comment]
Hi @ajwfrost 

I have to test it, but it seems that the icons are displayed correctly, just the banner is with error.

The default banner is shown : Powered by AIR:
![KX](https://user-images.githubusercontent.com/36115546/150651626-20050bd8-96d3-449c-814e-45e6010441d9.png)

**Comment by ajwfrost** [comment]
Great, thanks for the quick response! So yes, it looks like this is actually just an 'ordering' thing: the custom banner is being copied but then being overwritten by the default one. We just need to update how things are prepared and then it should be solved...

thanks

**Comment by ajwfrost** [comment]
Okay yes, so we have a fix for this one. If you want to work around it for now, you can always update/remove the default banner file that's provided in the AIR SDK under "lib\android\lib\resources\app_entry\res\drawable\banner.png"

thanks

**Comment by lwmirkk** [comment]
Problem solved with the new version : 33.1.1.758

Thanks a lot. =)
