### ISSUE TITLE
[Windows 7/8/8.1] StageWebView with UseWebView2 cause IllegalOperationError #1001

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1565]
## Problem Description
Using `StageWebView` with `UseWebView2` for Windows 7/8/8.1 devices cause `IllegalOperationError #1001`.
This issue blocks for us using `UseWebView2` for all users.

It has been tested with latest AIR 33.1.1.731 with multiple Windows 7/8/8.1 devices with 32-bit and 64-bit architectures. With and without installed Edge (WebView2). Tested with installed Internet Explorer 11.0.9600. Also tested with installed Edge 96.0.10.
Same problem in all cases.
There is no such problem without `UseWebView2` usage.
Also there is no such problem with Windows 10 devices.

According WebView2 documentation it should be supported: https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms

## Steps to Reproduce
Launch code below with any Windows 7/8/8.1 device (application will try to open website using `StageWebView`).
Note: application manifest should contains
```
<windows>
    <UseWebView2>true</UseWebView2>
</windows>
```

Application example with sources attached.
[stagewebview_windows7_8_usewebview2_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7858378/stagewebview_windows7_8_usewebview2_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.media.StageWebView;
	import flash.geom.Rectangle;
	
	public class StageWebViewWindows78UseWebView2Bug extends Sprite {
		private var stageWebView:StageWebView;
		
		public function StageWebViewWindows78UseWebView2Bug() {
			addEventListener(Event.ADDED_TO_STAGE, init);
		}
		
		private function init(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, init);
			
			stageWebView = new StageWebView(true);//This line throw IllegalOperationError #1001 for Windows 7/8 
			stageWebView.loadURL("https://airsdk.harman.com");
			stageWebView.viewPort = new Rectangle(0, 0, 1280, 720);
			stageWebView.stage = stage;
		}
	}
}
```

**Actual Result:**
` new StageWebView(true)` throw error:
```
Error #1001
  Exception: flash.errors::IllegalOperationError
flash.media::StageWebView/init
flash.media::StageWebView
```

**Expected Result:**
`StageWebView` should correctly show website.
If WebView2 not available then AIR should use old implementation for `StageWebView` automatically.

## Known Workarounds
Don't use `<UseWebView2>true</UseWebView2>`.

**Comment by 2jfw** [comment]
Did you try the "Evergreen Standalone Installer" from https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section ?

**Comment by itlancer** [comment]
@2jfw, yes.
Made more tests with Windows 8.1 64-bit and **WebView2 Runtime / Evergreen Standalone Installer** from https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
The same error.

**Comment by ajwfrost** [comment]
Hi
Just to check:
> Expected Result:
StageWebView should correctly show website.
If WebView2 not available then AIR should use old implementation for StageWebView automatically.

Would you be happy with this fallback approach i.e. if you'd requested the `UseWebView2` flag, but we can't use the Edge WebView, then the fallback should be automatic? I can't really see any way of providing a choice here, without updating the API which we don't really want to do for this sort of scenario. Happy to add the fallback mechanism if that's what you think makes most sense though.

Plus of course, we'll try to work out why it's not finding the component on the earlier Windows versions....

thanks

**Comment by itlancer** [comment]
> Would you be happy with this fallback approach i.e. if you'd requested the `UseWebView2` flag, but we can't use the Edge WebView, then the fallback should be automatic?

@ajwfrost 
Yes, exactly.

**Comment by itlancer** [comment]
Fixed with latest AIR versions. Checked with latest AIR 33.1.1.856.
Thanks!

But one annoying issue found https://github.com/airsdk/Adobe-Runtime-Support/issues/1936
