### ISSUE TITLE
Getting App Rejected by violating All Files Access Permission - AIR ADK 33.1.1.686

### ISSUE THREAD

**Issue by luisbarbosakwalit** [airsdk/Adobe-Runtime-Support#1574]
Describe your problem in detail. Include the following information:

* Which AIR SDK did you use?

Harmann AIR ADK 33.1.1.686 overlayed onto Apache Flex AIR SDK 4.16

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.

Android

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?

When submitting new apks into Google Play Store, the apks are accepted but then they are rejected due to violating the policy: Policy: All Files Access Permission without the app descriptor file making any reference on the uses-permission sections that make reference to the storage permissions.

I've confirmed and checked in all of the ANE files i use in this project and they don't have any reference too.

## Steps to Reproduce

1 - Overlay Harmann AIR ADK 33.1.1.686 overlayed onto the latest Apache Flex AIR SDK 4.16 

2- Create a 101 Flex mobile app using the overlayed SDK

3- Submit the app in Google Play Store to see the rejection (This step is hard for you guys to simmulate, but could not know other way to simmulate the issue).

Give us a minimal example:

My app descriptor file:
```
<manifest android:installLocation="auto">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<application>
```

## Known Workarounds

By now, no workaround found.

**Comment by ajwfrost** [comment]
Are you able to inspect your APK/AAB file using Android Studio, to see what the generated AndroidManifest.xml looks like? It seems that for some reason, there may be a 'MANAGE_EXTERNAL_STORAGE' permission request being added... but I can't see any reference to this within our ADT packaging code or manifest templates..

thanks

**Comment by luisbarbosakwalit** [comment]
> Are you able to inspect your APK/AAB file using Android Studio, to see what the generated AndroidManifest.xml looks like? It seems that for some reason, there may be a 'MANAGE_EXTERNAL_STORAGE' permission request being added... but I can't see any reference to this within our ADT packaging code or manifest templates..
> 
> thanks

Hi @ajwfrost

I was able to inspect the generated AndroidManifest.xml and still no reference to any storage permission.
[AndroidManifest.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/7883585/AndroidManifest.zip)

**Comment by ajwfrost** [comment]
Thanks @luisbarbosakwalit  - yes I can't see anything wrong with your manifest there so am not sure why they think this is violating the policy! Do I gather from that email that you are waiting to hear back from them on an appeal to find out why they think there's a violation?

thanks

**Comment by luisbarbosakwalit** [comment]
> Thanks @luisbarbosakwalit - yes I can't see anything wrong with your manifest there so am not sure why they think this is violating the policy! Do I gather from that email that you are waiting to hear back from them on an appeal to find out why they think there's a violation?
> 
> thanks

Yes, i'm currently awaiting feedback from Google support. Let's wait to see if this is really an issue with the SDK or is something i'm doing wrong.

Thank you for your feedback

**Comment by luisbarbosakwalit** [comment]
Nothing to due with the SDK
