### ISSUE TITLE
33.1.1.743 - Android

### ISSUE THREAD

**Issue by urthling** [airsdk/Adobe-Runtime-Support#1589]
Seeing this in the popup error:
```
Error occurred while packaging the application:


Warning: packagedDependency javax.inject-1.jar used by more than one ANE. Ignoring this entry
NOTE: Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging
```

-----

Seeing this in the LOG:
`Target requested was m_targetValue, but not using legacy APK so building via Android StudioVersion in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Gradle build where ADT is using JRE version 1.8.0_171
but where Gradle will be using the JDK from /Applications/Android Studio 2.app/Contents/jre/Contents/Home/bin/java
Gradle build command:  /Applications/Android Studio 2.app/Contents/jre/Contents/Home/bin/java -Xms512m -Xmx8192m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx8192m -Duser.dir="/var/folders/88/hrtnfm195pq3vmvtvqjxbmsw0000gn/T/6d3b1d3b-f720-4a9f-a5df-82fd1170fb8e" -cp "/Applications/Adobe Flash Builder 4.7/sdks/Feathers 4.1.1 - AIR 33.1.743/lib/android/bin/gradle-wrapper.jar":"/Applications/Adobe Flash Builder 4.7/sdks/Feathers 4.1.1 - AIR 33.1.743/lib/android/bin/gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleRelease
..java.lang.Thread.getStackTrace(Thread.java:1559)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: /private/var/folders/88/hrtnfm195pq3vmvtvqjxbmsw0000gn/T/6d3b1d3b-f720-4a9f-a5df-82fd1170fb8e/app/src/main/AndroidManifest.xml Error:
	android:exported needs to be explicitly specified for <service>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s`

**Comment by ajwfrost** [comment]
Hi
The error is this one but we shouldn't have this problem with the latest AIR SDK as we have the explicit 'exported' values set ... so I'm wondering whether there is an ANE that is adding something here and that needs to be updated?
```
AndroidManifest.xml Error: android:exported needs to be explicitly specified for <service>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported` when the corresponding component has an intent filter defined
```

Are you able to set the `KeepAndroidStudioOutput=true` value in the adt.cfg file as then we'll be able to look at that AndroidManifest.xml file and fine out what element is missing the `android:exported` tag...?

thanks

**Comment by urthling** [comment]
I see the `AndroidStudioProject` folder.  So I should send that or share part with you?

**Comment by ajwfrost** [comment]
Hi
To start with we'd just need to look at the file in `app\src\main\AndroidManifest.xml`, but if you could also do a search through xml files under `app\src\main\assets\META-INF\AIR\extensions` this may find something with mention of a `service` that's not been explicitly set up to export.
thanks

**Comment by urthling** [comment]
@marchbold pretty sure I'm just identifying what you'll be fixing, can you jump in when you get a chance?

**Comment by marchbold** [comment]
@urthling Can you post your manifest and I'll have a look over it? We are aware of this new additional requirement for Android 12 and are working through it (updating docs / airpackages etc).

**Comment by urthling** [comment]
Emailed you the manifest, and a link to the `AndroidStudioProject`

**Comment by marchbold** [comment]
@urthling I've updated your manifest and emailed it back, let me know how it goes. 

Basically every activity / service / receiver in your manifest needs an `android:exported="true|false"` attribute on it. Depending on whether it should be visible outside of your application space. 

Most simple activities / receivers should be false and any with intent filters or such should be true. But there are exceptions.

This is a good overview of the changes: 

https://medium.com/androiddevelopers/lets-be-explicit-about-our-intent-filters-c5dbe2dbdce0

**Comment by urthling** [comment]
Excellent, ty Michael!

K, seeing this in the ADT.log: 

```
Error occurred while packaging the application:

/path/bin-debug/Context-app.xml: error 404: Android attribute android:exported is not allowed to be overridden

```

**Comment by marchbold** [comment]
Ah, yeah okay wasn't sure on that one, remove the one I put on your main activity:

```
<!-- URI Scheme -->
<activity android:excludeFromRecents="false" android:exported="true">
```

Change to: 

```
<!-- URI Scheme -->
<activity android:excludeFromRecents="false" >
```

**Comment by urthling** [comment]
Boom!  that did it thank you Michael!

**Comment by marchbold** [comment]
@urthling Awesome!! 

Just for anyone else coming across this `android:exported` issue, just contact us via the github repository for the extension you are using and we'll guide you through the updates. 

We are rolling out updates to our docs and packages but takes time :)

**Comment by Shaunmax** [comment]
@ajwfrost @marchbold 
I am also getting something similar : - 

```
*** ADT Logging at 2022/01/29 17:18:09 ***
Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
ADT 33.1.1.758 called with: -version
*** ADT Logging at 2022/01/29 17:18:09 ***
Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
ADT 33.1.1.758 called with: -package -target apk-debug -listen 7936 -arch armv8 -storetype PKCS12 -keystore /Users/companyNamemac/Projects/TestApp/Certificates.p12 -storepass xxxxxx /Users/companyNamemac/Projects/TestApp/out/production/TestApp/Main.apk /Users/companyNamemac/Projects/TestApp/out/production/TestApp/ChatApp-android-app.xml -extdir /Users/companyNamemac/Projects/ANE_SWC -C /Users/companyNamemac/Projects/TestApp/out/production/TestApp Main.swf
Target requested was m_targetValue, but not using legacy APK so building via Android StudioVersion in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Invalid input: JAVA_HOME is not defined: this must point to a valid JDK installation for Android App Bundle creation
```

I dint understand what should I do?

**Comment by marchbold** [comment]
@shaymolho This issue should be resolved for all cases using our extensions. Can you report this to the appropriate repository and let us know what you are seeing?
