### ISSUE TITLE
GoogleAnalytics SDK in AdobeAIRMainActivity

### ISSUE THREAD

**Issue by marchbold** [airsdk/Adobe-Runtime-Support#1594]
### Discussed in https://github.com/airsdk/Adobe-Runtime-Support/discussions/1593

<div type='discussions-op-text'>

<sup>Originally posted by **Klug76** January 24, 2022</sup>
Google Play Developer Console requires publishers to declare if they have ads or not. My app does not have ads, but flagged as having the GoogleAnalytics SDK.
Here i found that the AdobeAIRMainActivity class uses GoogleAnalytics::Tracker("UA-54849355-1"):
[https://forum.starling-framework.org/d/21074-adobe-air-adobeairmainactivity-and-google-analytics/12](https://forum.starling-framework.org/d/21074-adobe-air-adobeairmainactivity-and-google-analytics/12)
Any chance to remove google analytics from AIR (at least from the paid version)?

</div>

**Comment by ajwfrost** [comment]
Confirmed with Adobe that none of this is active or required any more... we can pull this out.
thanks

**Comment by marchbold** [comment]
Did this get done? I can't see any reference to it in the release notes?

**Comment by ajwfrost** [comment]
Looks like it did from the file history:
```
Date:   Tue Jan 25 16:02:38 2022 +0000
    [github-1594] Removing old analytics references from AdobeAIRMainActivity class
```

Jan 25th 2022 would have put it into 33.1.1.758...
And yes, it's in those release notes, at least under the online list (search in https://airsdk.harman.com/release_notes for "1594"?)

If you're able to confirm that this is appropriately fixed in the actual runtime classes, we should close this issue...

thanks

**Comment by marchbold** [comment]
Ah, nice, just didn't go back far enough :) 

I can't find any reference to it in the latest release so will close this one 👍
