### ISSUE TITLE
Looping VideoTexture Causing AIR to Crash

### ISSUE THREAD

**Issue by esidegallery** [airsdk/Adobe-Runtime-Support#16]
## Problem Description
A VideoTexture set to loop indefinitely, in this case via a seek operation on 'NetStream.Play.Complete' status, will eventually cause the running application to crash.

- **AIR SDK used:** 26.0
- **Environment:** AIR for Windows (Captive runtime and otherwise). Windows 7, 8 & 10; 32-bit & 64-bit confirmed.
- **[Adobe Bug Tracker Issue](https://tracker.adobe.com/#/view/AIR-4198451)**

The issue is discussed in [this Starling thread](https://forum.starling-framework.org/topic/videoplayer-seemless-loop) and is reproducable by at least 4 other users on the thread.

## Steps to Reproduce
1. Create an application that plays a video from a local file using `VideoTexture`
2. Cause the video to loop e.g. by listening for the `"NetStream.Play.Complete"` play status and calling `seek(0)`
3. Run the app. Usually within 15 hours, it will have crashed.

[Here is a minimal application that exhibits the problem](https://www.dropbox.com/s/3o015rxtgzhv4h6/VideoTextureCrashMinimal.zip?dl=0). This zip file can be imported directly into Flash Builder.

Here are compiled versions of the above app that can be run straight away:
- [AIR File](https://www.dropbox.com/s/ii264k229xmrqiy/VideoTextureCrashMinimal.air?dl=0)
- [Captive Runtime](https://www.dropbox.com/sh/6w731zjqj9b9phc/AAAgtQz8Mt0UDm-FB3WbU1owa?dl=0)

To minimise dependencies, and to rule out framework bugs, this app does not use Starling, but the same behaviour is exhibited when Starling is used.

## More Info
- [Error information from Starling forum thread](https://forum.starling-framework.org/topic/videoplayer-seemless-loop/page/2#post-106581)
- [Information regarding exception code c0000005](https://forum.starling-framework.org/topic/videoplayer-seemless-loop/page/2#post-106585)
- [Collection of error logs and system specs for 4 different machines](https://www.dropbox.com/sh/zp49eebijlzfvpl/AACSZoPEwLV-iqq3taWUBINqa?dl=0)

## Known Workarounds
For some, using the [appentBytes method](https://gist.github.com/tuarua/b4af96b7f30a5b71483cae3f12976e33) on an embedded FLV can prevent (or perhaps postpone) the crash, which suggests it could be a file pointer issue. However, for others this method still eventually causes a crash. This workaround is not suitable for all applications however and has been found to exhibit [a different bug](https://github.com/Gamua/Adobe-Runtime-Support/issues/17).
- [Link to appendBytes version of above application](https://www.dropbox.com/s/8jrtmq9djcrr84u/VideoTextureCrashAppendBytes.zip?dl=0)
- [Captive runtime build](https://www.dropbox.com/sh/91icxbmkf23dtic/AABKsOwAyJpnxoMtazCHJbppa?dl=0)
- [Air file](https://www.dropbox.com/s/3g0k8qat5jxvyx5/VideoTextureCrashAppendBytes.air?dl=0)

**Comment by kptac** [comment]
+1

**Comment by PrimaryFeather** [comment]
Thanks a lot for the excellent (i.e. very detailed) report!

**Comment by rquinones84** [comment]
I fixed it by changing my video player flow to:
Create a "VideoManager" class.
Add function "InstantiateVideo" where you create instance of "VideoPlayer" class and its Texture.
Add a "VideoEnd" Event Listener in "VideoManager" class attached to "VideoPlayer" class.
Assign a video file and play till the end.
On video Finished, Clear the stream and send "VideoEnd" event.
From the "VideoManager" class function tied to "VideoEnd" Tell the "VideoPlayer" class to delete its texture, null reference to video file, and then null the "VideoPlayer" class instance reference from "VideoManager".
Add 5 second timer here.
Then call "InstantiateVideo".

This is deployed in the field and has up time of over 2 weeks since we last checked, with no memory leak.

**Comment by esidegallery** [comment]
Nice one @rquinones84! Will try what you have suggested soon. If this really fixes the issue I will be very happy indeed!

**Comment by itlancer** [comment]
For me this issue finally fixed with AIR 32.0.0.83 beta. Thanks for Adobe!

**Comment by PrimaryFeather** [comment]
That's great news! Can anyone else who experienced this run a test? Then we could safely close this issue for good. 

From me, as well, a big thanks to Adobe for finally tackling this!

**Comment by esidegallery** [comment]
I'll set up a test machine and let you know! I can confirm that the related Issue #17 appears fixed. Was able to run three days straight without freezing. Fingers crossed for this one too!
