### ISSUE TITLE
Error: Install failed. Got Error "applicationVerificationFailed" with code 0xe8008015

### ISSUE THREAD

**Issue by Shaunmax** [airsdk/Adobe-Runtime-Support#1602]
I am getting this weird error : I double checked I am using the correct provisioning profile, its a test app and was working fine with older sdk. I dont understand whats the problem now? the latest air sdks are throwing this error.

![image](https://user-images.githubusercontent.com/16576562/151621810-136d5367-0b83-4a70-b314-338743f6d053.png)
![image](https://user-images.githubusercontent.com/16576562/151621881-3b55598f-974a-4cec-a9d4-fb33aca0c9ba.png)
![image](https://user-images.githubusercontent.com/16576562/151621938-bd2d0b06-cd60-4b13-afdf-28f35697665f.png)

Also, how do I copy text from intellij ideas popups ????

**Comment by ajwfrost** [comment]
Hi - seems like something is up with the signing.. can you check the log file (you may need to turn on logging via the SDK folder's "adt.cfg" file) which should be in ~/adt.log? We did have one issue where we were using the macOS 'codesign' request but were flagging the executable as not using a distribution certificate so it would be good to check the certificate details too .. if you're able to upload your IPA file, we can inspect this to see why it's showing the error...
https://transfer.harman.com/requests/8VVN19rHg4MiAeyTNfmIdm
thanks

**Comment by Shaunmax** [comment]
> if you're able to upload your IPA file

i have sent the file!

**Comment by Shaunmax** [comment]
@ajwfrost here is the adt log file 

> *** ADT Logging at 2022/01/29 12:52:33 ***
> Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
> ADT 33.1.1.743 called with: -version
> *** ADT Logging at 2022/01/29 12:52:34 ***
> Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
> ADT 33.1.1.743 called with: -package -target ipa-debug-interpreter -listen 7936 -storetype PKCS12 -keystore /Users/companyNamemac/Projects/companyName/companyName_dev_certificate.p12 -storepass xxxxxx -provisioning-profile /Users/companyNamemac/Projects/TestApp/devcomcompanyNamechatapp.mobileprovision /Users/companyNamemac/Projects/TestApp/out/production/TestApp/Main.ipa /Users/companyNamemac/Projects/TestApp/out/production/TestApp/ChatApp-ios-app.xml -extdir /Users/companyNamemac/Projects/ANE_SWC -C /Users/companyNamemac/Projects/TestApp/out/production/TestApp Main.swf -C /Users/companyNamemac/Projects/TestApp LaunchScreen.storyboardc -C /Users/companyNamemac/Projects/TestApp Assets.car
> *** ADT Logging at 2022/01/29 12:52:34 ***
> Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
> ADT 33.1.1.743 called with: -package -target ipa-debug-interpreter -listen 7936 -storetype PKCS12 -keystore /Users/companyNamemac/Projects/companyName/companyName_dev_certificate.p12 -storepass xxxxxx -provisioning-profile /Users/companyNamemac/Projects/TestApp/devcomcompanyNamechatapp.mobileprovision /Users/companyNamemac/Projects/TestApp/out/production/TestApp/Main.ipa /Users/companyNamemac/Projects/TestApp/out/production/TestApp/ChatApp-ios-app.xml -extdir /Users/companyNamemac/Projects/ANE_SWC -C /Users/companyNamemac/Projects/TestApp/out/production/TestApp Main.swf -C /Users/companyNamemac/Projects/TestApp LaunchScreen.storyboardc -C /Users/companyNamemac/Projects/TestApp Assets.car
> Using native (macos codesign) IPA signer
> compile-abc command line: /Users/companyNamemac/Projects/AIR_SDK/current/lib/aot/bin/compile-abc/compile-abc-64 -mtriple=arm64-apple-ios -emit-ane-map
> 
> ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch arm64 -L"/Users/companyNamemac/Projects/AIR_SDK/current/lib/aot/stub" -sdk_version 15.0 -F"/Users/companyNamemac/Projects/AIR_SDK/current/lib/aot/stub" -L"/Users/companyNamemac/Projects/AIR_SDK/current/lib/aot/lib" -o "../aot4355293137059557465.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/companyNamemac/Projects/AIR_SDK/current/lib/aot/lib/libRuntimeInterpreter.arm-air.a" -lc++ -lSystem.B -lz -lobjc -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -w -filelist "/Users/companyNamemac/Projects/TestApp/out/production/TestApp/AOTBuildOutput14719161911909899027.tmp/OBJFilesList.txt" -ios_version_min 9.0
> 
> Codesign request for IPA: codesign --force --sign 221eef63b629789ef9c186d434c692c8859d89a2 --entitlements /var/folders/qw/gndty00d52133td30vxn_5h80000gn/T/d5380446-063e-4dd7-9fb9-a62b2187f5d1/entitlement13733104160009124460xcent --generate-entitlement-der -o 17 /var/folders/qw/gndty00d52133td30vxn_5h80000gn/T/d5380446-063e-4dd7-9fb9-a62b2187f5d1/Payload/ChatApp.app
> *** ADT Logging at 2022/01/29 12:52:39 ***
> Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
> ADT 33.1.1.743 called with: -devices -platform ios
> *** ADT Logging at 2022/01/29 12:52:40 ***
> Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
> ADT 33.1.1.743 called with: -installApp -platform ios -device 2 -package /Users/companyNamemac/Projects/TestApp/out/production/TestApp/Main.ipa
> ..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
> ..com.adobe.air.DebugFile.printStack(DebugFile.java)
> ..com.adobe.air.ADTException.<init>(ADTException.java)
> ..com.adobe.air.ios.IOSDeviceOperations._execIDB(IOSDeviceOperations.java)
> ..com.adobe.air.ios.IOSDeviceOperations.execIDB(IOSDeviceOperations.java)
> ..com.adobe.air.ios.IOSDeviceOperations.installApplication(IOSDeviceOperations.java)
> ..com.adobe.air.ADT.parsePlatformOperationArgs(ADT.java)
> ..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
> ..com.adobe.air.ADT.run(ADT.java)
> ..com.adobe.air.ADT.main(ADT.java)
> Stack trace:
> ADT exception: WARNING: could not locate iTunesMetadata.plist in archive!
> WARNING: could not locate Payload/ChatApp.app/SC_Info/ChatApp.sinf in archive!
> ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.BZTWLP/extracted/Payload/ChatApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)

**Comment by ajwfrost** [comment]
Great, thanks! So yes, this is what I thought:
- codesign is using the native utility on the mac
- the binary is signed with `<key>get-task-allow</key><false/>`
- the provisioning profile has `<key>get-task-allow</key><true/>`

This is a bug in the ADT code which isn't identifying the right certificate type and hence puts the wrong thing into the binary file... we have a fix for this coming out shortly, or if you take the attached ADT.jar file you can put this over the top of your existing one and it should fix it..
https://transfer.harman.com/message/JO9K7J6cotNNJKgUUyB9Ry

thanks

**Comment by Shaunmax** [comment]
It worked!

**Comment by Shaunmax** [comment]
> Great, thanks! So yes, this is what I thought:
> 
> * codesign is using the native utility on the mac
> * the binary is signed with `<key>get-task-allow</key><false/>`
> * the provisioning profile has `<key>get-task-allow</key><true/>`
> 
> This is a bug in the ADT code which isn't identifying the right certificate type and hence puts the wrong thing into the binary file... we have a fix for this coming out shortly, or if you take the attached ADT.jar file you can put this over the top of your existing one and it should fix it.. https://transfer.harman.com/message/JO9K7J6cotNNJKgUUyB9Ry
> 
> thanks

But now I am unable to compile android build, getting the following error : - 

*** ADT Logging at 2022/01/29 17:18:09 ***
Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
ADT 33.1.1.758 called with: -version
*** ADT Logging at 2022/01/29 17:18:09 ***
Called by: /Users/companyNamemac/Projects/AIR_SDK/current/lib/adt.jar
ADT 33.1.1.758 called with: -package -target apk-debug -listen 7936 -arch armv8 -storetype PKCS12 -keystore /Users/companyNamemac/Projects/TestApp/Certificates.p12 -storepass xxxxxx /Users/companyNamemac/Projects/TestApp/out/production/TestApp/Main.apk /Users/companyNamemac/Projects/TestApp/out/production/TestApp/ChatApp-android-app.xml -extdir /Users/companyNamemac/Projects/ANE_SWC -C /Users/companyNamemac/Projects/TestApp/out/production/TestApp Main.swf
Target requested was m_targetValue, but not using legacy APK so building via Android StudioVersion in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
Version in APK = 33.1.1.743, version of ADT = 33.1.1.758
..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Invalid input: JAVA_HOME is not defined: this must point to a valid JDK installation for Android App Bundle creation

**Comment by ajwfrost** [comment]
Ah so for this it's trying to use the new packaging mechanism and then failing because it doesn't have an appropriate "JAVA_HOME". Either you can set this (via environment variable or via a setting in the ~/adt.cfg file) - to JDK v11 or later - or you can add `<BuildLegacyAPK>true</BuildLegacyAPK>` to the app descriptor file under the `<android>` section..

thanks

**Comment by Shaunmax** [comment]
> (via environment variable or via a setting in the ~/adt.cfg file)
ok, I set it to : 
```
# JAVA_HOME is usually picked up from an environment variable but this can override it:
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
```

but still same result!

**Comment by Shaunmax** [comment]
Also after setting <BuildLegacyAPK>true</BuildLegacyAPK> the device resolution got changed? its not giving full screen!

**Comment by ajwfrost** [comment]
Hi - thanks for the feedback. For the first of these I had the same report from the QA team so there appears to be an error in the Java detection now (looks like some versions of java report their status via stdout, some via stderr!). When using the legacy APK mechanism though, there really shouldn't be any change vs a previous build of the SDK.

Do you mean by 'not full screen' that there are black bars at the top/bottom? Do you have that aspect ratio value set in your manifest file (I always wonder whether we should just set that as a default...), and are you able to check any details like what device and what screen size it reports from Settings vs what you get from flash.system.Capabilities?

We'll double-check on this too..

thanks

**Comment by Shaunmax** [comment]
> any details like what device and what screen size it reports from Settings vs what you get from flash.system.Capabilities?

I will check again and let you know! 
But I am sure that we were testing on devices with punch hole notch!

**Comment by Shaunmax** [comment]
```

[trace] [Info] DEVICE INFO ============================
[trace] [Info]  name:
[trace] [Info]  brand:        samsung
[trace] [Info]  manufacturer: samsung
[trace] [Info]  device:       m31s
[trace] [Info]  model:        SM-M317F
[trace] [Info]  yearClass:    2014
[trace] [Info]  product:      m31snnxx
[trace] [Info] OPERATING SYSTEM =======================
[trace] [Info]  name:         Android
[trace] [Info]  type:         android
[trace] [Info]  version:      11
[trace] [Info]  API Level:    30
```

with `<BuildLegacyAPK>true</BuildLegacyAPK>`

```
[trace] [Info] DISPLAY METRICS ========================
[trace] [Info] densityDpi:   420
[trace] [Info] screenHeight: 1080
[trace] [Info] screenWidth:  2009
[trace] [Info] xdpi:         409.4320068359375
[trace] [Info] ydpi:         406.3999938964844
```

without `<BuildLegacyAPK>true</BuildLegacyAPK>`

```
[trace] [Info] DISPLAY METRICS ========================
[trace] [Info] densityDpi:   420
[trace] [Info] screenHeight: 1080
[trace] [Info] screenWidth:  2400
[trace] [Info] xdpi:         409.4320068359375
[trace] [Info] ydpi:         406.3999938964844
```

**Comment by ajwfrost** [comment]
Thanks ... what APIs are you using to get those values from? Things like the Android API level or "xdpi" aren't available from AIR..!

**Comment by Shaunmax** [comment]
> Thanks ... what APIs are you using to get those values from? Things like the Android API level or "xdpi" aren't available from AIR..!

We are using distriqt's [application ane ](https://airnativeextensions.com/extension/com.distriqt.Application)

**Comment by marchbold** [comment]
@Shaunmax Are you saying the display metrics values are changing just by changing the `BuildLegacyAPK` flag? 

This should be directly returning the native values from the default window (uses [Display getRealMetrics](https://developer.android.com/reference/android/view/Display#getRealMetrics(android.util.DisplayMetrics)) internally). So for some reason the window size for the app is changing between these two builds.  

What API level are you targeting with this build?

**Comment by Shaunmax** [comment]
> Are you saying the display metrics values are changing just by changing the `BuildLegacyAPK` flag?

Yes! 

> What API level are you targeting with this build?

`<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="30" />`
