### ISSUE TITLE
just remove  *. 758  version before anybody saw this

### ISSUE THREAD

**Issue by bobrokrol** [airsdk/Adobe-Runtime-Support#1612]
## Description
Could you make one stable build before adding new feautures?

**Comment by ajwfrost** [comment]
We've published this one just as a 'beta', so it's not the one you get if you just go to "Download SDK"... but we've had people asking for both of these changes so have pushed this online. The slightly mitigating factor is that one change is just impacting Android apps, the other is just impacting desktop apps.

But yes we are currently planning a way to be able to split things out and provide a better way to have bug fixes separated from feature updates.

Just to check though - are you seeing any specific regressions with this SDK or was it just the warning and list of changes that was concerning?

thanks
