### ISSUE TITLE
AIR SDK 758 - Error: Definition flash.html.script could not be found

### ISSUE THREAD

**Issue by makanmel** [airsdk/Adobe-Runtime-Support#1622]
I have updated to the newest AIR SDK 758 overlaying it on top of the Flex SDK:
```
<name>Apache Flex 4.15.0 FP20.0 AIR20.0 en_US</name>
<version>4.15.0</version>
<build>20160104</build>
```
And the project started to fail during ANT build with the next error for every mxml file in the project:

```
...
    [compc] ...\...\MyMainWindow.mxml(-1):  Error: Definition flash.html.script could not be found.
    [compc]
    [compc] <?xml version="1.0" encoding="utf-8"?>
    [compc] ...\...\MySecondaryWindow.mxml(-1):  Error: Definition flash.html.script could not be found.
    [compc]
    [compc] <?xml version="1.0" encoding="utf-8"?>
    [compc] ...\...\MsgBoxComponent.mxml(-1):  Error: Definition flash.html.script could not be found.
    [compc]
    [compc] <?xml version="1.0" encoding="utf-8"?>
    [compc]
...

```
Also reproducible with the sample mobile project in the Intellij IDEA:

File - New - Project - Flash
Target Platform: Mobile
Output type: Application

![Screenshot_3](https://user-images.githubusercontent.com/5139756/152770055-f7385948-cc24-4fe3-b507-992d2823a155.png)
![Screenshot_4](https://user-images.githubusercontent.com/5139756/152770783-898c9f1f-2304-4bc7-966d-2668b18ba208.png)

**Comment by 2jfw** [comment]
To me it looks like Flex's `WindowedApplication` has a reference to `HTML` in function `menuItemSelectHandler`.

`            const html:HTML = new HTML();` [Line 2664]

**Comment by ajwfrost** [comment]
Thanks for this ... so it turns out, the Flex compiler is always adding a set of implicit "import" statements to the start of every file it compiles, and because we'd removed some of the html capabilities, this part is failing.

The `new HTML` should be ok as this is `mx.controls.HTML` which imports the below three classes:
```
import flash.html.HTMLLoader;
import flash.html.HTMLHistoryItem;
import flash.html.HTMLHost;
```
and these still exist, albeit with restricted functionality...

Will just recreate an airglobal.swc with the class from the 'flash.html.script' package and check that this solves it..

**Comment by ajwfrost** [comment]
Can you try replacing the airglobal.swc, in `frameworks/libs/air/`, with the one in the below zip please?
thanks
[airglobal.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8017252/airglobal.zip)

**Comment by makanmel** [comment]
> Can you try replacing the airglobal.swc, in `frameworks/libs/air/`, with the one in the below zip please? thanks [airglobal.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8017252/airglobal.zip)

The new airglobal.swc helped and now the project compiles without errors.
Thank you.
