### ISSUE TITLE
Error while publishing to aab file using animate cc.

### ISSUE THREAD

**Issue by balaedit** [airsdk/Adobe-Runtime-Support#1666]
adt configuration :

CreateAndroidAppBundle=true
AndroidPlatformSDK=D:\\AndroidSDK
JAVA_HOME=C:\\Program Files\\Java\\jdk-17.0.2

all the above path are correctly configured and checked.

Air SDK version tried :
1) 33.1.1.620
2) 33.1.1.633
3) 33.1.1.743
4) 33.1.1.758

same issue in all AIR SDK using.

While publish the app, error screenshot below :

![error](https://user-images.githubusercontent.com/37571867/154246810-cdebf269-db2f-4f97-a1a8-fc64500660b8.png)

Please

**Comment by ajwfrost** [comment]
One minor (?) point, if you're on Windows then your config file entries have to be either
```
AndroidPlatformSDK=D:\\AndroidSDK
JAVA_HOME=C:\\Program Files\\Java\\jdk-17.0.2
```
or
```
AndroidPlatformSDK=D:/AndroidSDK
JAVA_HOME=C:/Program Files/Java/jdk-17.0.2
```
since the config file is being read by a Java app..

In terms of the error ... what version of Android SDK and Android build tools have you got there? Most likely issue is a mis-match in the gradle version or similar.. if you've got Android Studio then it may be worth updating it?

thanks

**Comment by balaedit** [comment]
I have updated the configuration but same issue.

Please find the screenshot for my configuration :

![adtConfig](https://user-images.githubusercontent.com/37571867/154261691-02e9232c-0c7f-4588-8962-5d5b9772d971.jpg)
![environmentvariable](https://user-images.githubusercontent.com/37571867/154261732-48c410b0-eb0c-4f4a-92c3-ae7392d9d7d9.jpg)
![variablePath](https://user-images.githubusercontent.com/37571867/154261748-6146133b-fffd-4ba3-bed1-3f0011b5ac32.jpg)
![java_version](https://user-images.githubusercontent.com/37571867/154262053-1abf2156-b105-463b-aaeb-d82031d2b585.jpg)

Any changes to be done ... Please guide.

**Comment by balaedit** [comment]
I had created the blank file and published for aab file and it's created perfect.

So I think it could be issue in my manifest file.. I am sharing the manifest. 

[EdulightLearningApp-app.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/8079962/EdulightLearningApp-app.txt)

Is there anything wrong in my manifest file?

**Comment by ajwfrost** [comment]
Okay thanks - the multidex thing is happening because we add this by default now via the gradle dependencies but it's also added via a jar file within the ANE's platform files. Will take a look as I had thought we were ignoring/eliminating this duplicate; maybe something else is happening here...

**Comment by marchbold** [comment]
@balaedit Make sure you aren't adding the `android.multidex` extension. It's the one that contains the multidex classes and can result in a duplicate class error. Just completely remove it from your project. 
It won't be the `androidx.core` extension causing this.

**Comment by balaedit** [comment]
No, I am not adding any other extensions. For testing I had simply created the blank file and added the '[androidx_core.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8089239/androidx_core.zip)' ANE to the project, facing the error. The project sample is in the below link.

[test.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8094479/test.zip)

Is this ANE is required to add in my project. I am using other ANE such as 'UDID-full.ane', 'pdfViewer.ane'. Is 'androidx_core.ane' is required to add in my project to run UDID and pdfviewer of myFlashlab.

**Comment by marchbold** [comment]
@balaedit That's not the standard one from here is it: https://github.com/distriqt/ANE-AndroidSupport Looks like the one from myflashlabs? 

You have multidex in that core extension so whoever built it for you should remove it. 

Or you can try adding the androidx.core and androidx.appcompat from the above url. Pretty sure that should cover everything in that one. (minus the multidex).

**Comment by balaedit** [comment]
Thanks @ajwfrost and @marchbold.

I had uncomment the line KeepAndroidStudioOutput=true and grabbed the AndroidStudioProject and remove the multidex.jar file from the dependencies (i.e. delete/comment out implementation files('libs/multidex.jar')) as you instructed and it's working fine. But Flashlab should update this ANE. 

I will also try the @marchbold instruction whether it will simplify/reduce the steps of working with android studio.

Thanks again.

**Comment by marchbold** [comment]
@balaedit I don't believe they are maintaining their extensions any more.
