### ISSUE TITLE
How to set Android Adaptive Icons 108 x 108 dp

### ISSUE THREAD

**Issue by a9848840** [airsdk/Adobe-Runtime-Support#1670]
In the past, the icon was set in xml.

<image152x152>icons/icon_152.png</image152x152>
<image512x512>icons/icon_512.png</image512x512>

When I add <image108x108>icons/icon_108.png</image108x108>
get feedback
error 103: application.icon.image108x108 is an unexpected element/attribute

Google has a 108dp icon, how can I set it in air xml?

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

https://stackoverflow.com/questions/45639952/the-correct-icon-size-for-android-adaptive-icons/45640188

**Comment by ajwfrost** [comment]
AIR doesn't natively support adaptive icons so the 108 pixel format isn't used; instead you can create your own adaptive icons and set them for your app using the below tutorial:

https://docs.airnativeextensions.com/docs/tutorials/android-adaptive-icons/

thanks

**Comment by marchbold** [comment]
@Klug76 Yeah we are working on updating all these resource based tutorials. Thanks for pointing that one out I'll see if we can get it updated soon.

**Comment by marchbold** [comment]
@Klug76 The tutorial has been updated to reference the new approach for resources with AIR.
