### ISSUE TITLE
Can´t build a 64 bit android apk using Adobe Animate 2015 and AIR 33.1.1.743

### ISSUE THREAD

**Issue by P2b10** [airsdk/Adobe-Runtime-Support#1700]
I have an android app that was signed years ago with a 1024 bit certificate. In order to not lose thousands of users I had been updating the app with the same certificate using Adobe Animate 2015 and packing it as:

32 bit = armeabi-v7a
and
64 bit = arm64-v8a

and then uploading both apks to Google Play with no issues.

In order to do that I use an iMac with mac os El Capitan 10.11.6. Did not have problems with AIR 331.1.663 for Android.

Now, with AIR 33.1.1.743, after receiiving some errors about Gradle and the Java SDK, I updated the Android SDK on Android Studio and the Java JDK to 11.0.13 and I was able to build a 32 bit apk = armeabi-v7a. But when I try to pack the 64 bit apk = arm64-v8a using the recomended way on the adt.cfg file:

DefaultArch=armv8
OverrideArch=armv8

I keep getting a 32 bit apk = armeabi-v7a. I tried with the Java JDK to 11.0.14 but I got the same result. 

I am using the Distriqt Admob ANE but even in the version of the app without any ANEs I keep getting a 32 bit apk = armeabi-v7a. There is no way to get a 64 bit apk = arm64-v8a

Any advice on how to be able to pack it as a 64 bit apk = arm64-v8a?

**Comment by ajwfrost** [comment]
That should be working ... are you able to enable the `DebugOut=true` line in the config file and try again, then check in `~/adt.log` to see what happened?

thanks

**Comment by P2b10** [comment]
Hi Anrew,

Thanks for your reply. This is what the adt.log shows:

*** ADT Logging at 2022/02/22 14:21:25 ***
Called by: /Applications/Adobe Animate CC 2015.2/AIR33.1.1.743/lib/adt.jar
ADT 33.1.1.743 called with: -package -target apk-captive-runtime -arch armv7 -storetype PKCS12 -keystore /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/andrsalvanotas.p12 -storepass xxxxxx /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/SaberLeerNotas.apk /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/1-app.xml -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ 1.swf 192.png 144.png 96.png 72.png 48.png 36.png -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ 2_menu.swf -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ 3a_clave_sol.swf -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ 3b_cifrado.swf -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ 3c_clave_fa.swf -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ swfs3a_clave_sol -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ swfs3b_cifrado -C /Users/Pablo/Documents/PABLO/BACK UP 20.01.14/back up 20.01.14/PABLO/ACTUAL/APPS/DESARROLLO/FLASH/GRATUITAS/ANDROID/SALVANOTAS/VERS 24 ADMOB/ swfs3c_clave_fa -extdir /Users/Pablo/Library/Caches/TemporaryItems/1_ANE_Cache
Target requested was m_targetValue, but not using legacy APK so building via Android StudioVersion in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Version in APK = 33.1.1.743, version of ADT = 33.1.1.743
Gradle build where ADT is using JRE version 1.8.0_40
but where Gradle will be using the JDK from /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java
Gradle build command:  /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="/var/folders/jl/kg9gxm9d36z_bwdwx5chv7tr0000gn/T/e2d6c24a-4c5d-4a00-8117-e0374857f1e4" -cp "/Applications/Adobe Animate CC 2015.2/AIR33.1.1.743/lib/android/bin/gradle-wrapper.jar":"/Applications/Adobe Animate CC 2015.2/AIR33.1.1.743/lib/android/bin/gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleRelease
Creating temporary file for v2-signed APK: /var/folders/jl/kg9gxm9d36z_bwdwx5chv7tr0000gn/T/e2d6c24a-4c5d-4a00-8117-e0374857f1e4/app/build/outputs/apk/release/signed4910926625132433953apkV2-signed file is at /var/folders/jl/kg9gxm9d36z_bwdwx5chv7tr0000gn/T/e2d6c24a-4c5d-4a00-8117-e0374857f1e4/app/build/outputs/apk/release/signed4910926625132433953apk 

Still a 32 bit = armeabi-v7a

**Comment by ajwfrost** [comment]
Ah - I can see what's happening. There's some output there (which we've since corrected!) which should read:
`Target requested was apk-captive-runtime, but not using legacy APK so building via Android Studio`

There is code in two different places that checks the architecture, and although we've overridden the earlier approach to use Gradle builds, the code that would update the arguments for Gradle is not triggered because the override setting is not used here (it re-checks the argument value which requested apk), and yet the code that earlier would have sorted out the architecture override request is not being hit because it knows about the request to use Gradle.... Anyway, basically this is a bug in our code which won't take long to sort out...

In the meantime: best thing is to switch it back to using the legacy APK mechanism for building, which you can do by adding a line into your application descriptor file (I think you need to have Animate shut down during this point): into your `<android>` section, please add `<BuildLegacyAPK>true</BuildLegacyAPK>`

thanks

**Comment by P2b10** [comment]
Hi Andrew:

Thanks for your reply. I did what you said and this is what I got.
![Screen Shot 2022-02-22 at 18 10 12](https://user-images.githubusercontent.com/49465984/155243522-9af6e693-69c9-4bf5-9d38-87c609bb06ce.png)

And the usual permissions were gone.
![Screen Shot 2022-02-22 at 18 31 02](https://user-images.githubusercontent.com/49465984/155243585-114190cc-5bd4-4217-b544-56f026c36601.png)
![Screen Shot 2022-02-22 at 18 31 38](https://user-images.githubusercontent.com/49465984/155243586-1744e9e2-b95f-4a27-acd9-42cdc8f89c9a.png)

**Comment by P2b10** [comment]
Hi Andrew:
Thanks for your reply.

My XML descriptor starts like this:

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/33.1">

So I think that´s not the point

And if I put this as you suggested:


 <android>

	<BuildLegacyAPK>true</BuildLegacyAPK>

        <manifestAdditions><![CDATA[
	
	<manifest android:installLocation="auto">
    
    
    <uses-permission android:name="android.permission.INTERNET"/>

Then I get this message on Adobe Animate 2015:

“Application descriptor cannot be parsed.”
![Screen Shot 2022-02-23 at 13 56 38](https://user-images.githubusercontent.com/49465984/155403505-46c821eb-da39-4ba5-a6ec-fa55744e2c7d.png)

I checked for spaces or unnusual characters on the name but there are not.

I don´t what´s going on.

This is my descrptor file if you want to look at it:

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<application xmlns="http://ns.adobe.com/air/application/33.1">

    
    <id>SalvaNotas</id>
    
    <filename>SaberLeerNotas</filename>
    
    <name>SaberLeerNotas</name>
    
    <versionNumber>1.0.25</versionNumber>
    
    <versionLabel>1.0.25</versionLabel>
    
    <initialWindow>
        
        <content>1.swf</content>
        
        <autoOrients>false</autoOrients>
        
        <aspectRatio>landscape</aspectRatio>
        <renderMode>direct</renderMode>
        <fullScreen>true</fullScreen>
        <systemChrome>standard</systemChrome>
    </initialWindow>
    <android>
	<BuildLegacyAPK>true<BuildLegacyAPK>

        <manifestAdditions><![CDATA[	
	<manifest android:installLocation="auto">
    
    
    <uses-permission android:name="android.permission.INTERNET"/>

    
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application 
        android:hardwareAccelerated="true"
        android:appComponentFactory="androidx.core.app.CoreComponentFactory">

	
	<meta-data
    android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT"
    android:value="true"/>

        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-XXXXXXXXXXXXXXXX~XXX”XXXXXXX/>

        <activity 
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" 
            android:exported="false"
            android:theme="@android:style/Theme.Translucent" />

        <provider
            android:name="com.google.android.gms.ads.MobileAdsInitProvider"
            android:authorities="air.SalvaNotas.mobileadsinitprovider"
            android:exported="false"
            android:initOrder="100" />

        <service
            android:name="com.google.android.gms.ads.AdService"
            android:enabled="true"
            android:exported="false" />


        
        <service
            android:name="androidx.room.MultiInstanceInvalidationService"
            android:exported="false" />

            
        
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="air.SalvaNotas.workmanager-init"
            android:directBootAware="false"
            android:exported="false"
            android:multiprocess="true" />

        <service
            android:name="androidx.work.impl.background.systemalarm.SystemAlarmService"
            android:directBootAware="false"
            android:enabled="@bool/enable_system_alarm_service_default"
            android:exported="false" />
        <service
            android:name="androidx.work.impl.background.systemjob.SystemJobService"
            android:directBootAware="false"
            android:enabled="@bool/enable_system_job_service_default"
            android:exported="true"
            android:permission="android.permission.BIND_JOB_SERVICE" />

        <receiver
            android:name="androidx.work.impl.utils.ForceStopRunnable$BroadcastReceiver"
            android:directBootAware="false"
            android:enabled="true"
            android:exported="false" />
        <receiver
            android:name="androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryChargingProxy"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.ACTION_POWER_CONNECTED" />
                <action android:name="android.intent.action.ACTION_POWER_DISCONNECTED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="androidx.work.impl.background.systemalarm.ConstraintProxy$BatteryNotLowProxy"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BATTERY_OKAY" />
                <action android:name="android.intent.action.BATTERY_LOW" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="androidx.work.impl.background.systemalarm.ConstraintProxy$StorageNotLowProxy"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.DEVICE_STORAGE_LOW" />
                <action android:name="android.intent.action.DEVICE_STORAGE_OK" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="androidx.work.impl.background.systemalarm.ConstraintProxy$NetworkStateProxy"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="androidx.work.impl.background.systemalarm.RescheduleReceiver"
            android:directBootAware="false"
            android:enabled="false"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.TIME_SET" />
                <action android:name="android.intent.action.TIMEZONE_CHANGED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="androidx.work.impl.background.systemalarm.ConstraintProxyUpdateReceiver"
            android:directBootAware="false"
            android:enabled="@bool/enable_system_alarm_service_default"
            android:exported="false" >
            <intent-filter>
                <action android:name="androidx.work.impl.background.systemalarm.UpdateProxies" />
            </intent-filter>
        </receiver>

          
    </application>

</manifest>
			
		]]></manifestAdditions>
        <containsVideo>true</containsVideo>
    </android>
    <iPhone>
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <InfoAdditions><![CDATA[ 
<key>UIDeviceFamily</key> 
<array> 
    <string>1</string> 
    <string>2</string> 
</array>

]]></InfoAdditions>
    </iPhone>
    <icon>
        <image36x36>36.png</image36x36>
        <image48x48>48.png</image48x48>
        <image72x72>72.png</image72x72>
        <image96x96>96.png</image96x96>
        <image144x144>144.png</image144x144>
        <image192x192>192.png</image192x192>
    </icon>
    <supportedLanguages>es</supportedLanguages>
    <extensions>
        <extensionID>com.distriqt.Adverts</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>androidx.appcompat</extensionID>
        <extensionID>androidx.browser</extensionID>
        <extensionID>androidx.constraintlayout</extensionID>
        <extensionID>androidx.core</extensionID>
        <extensionID>androidx.room</extensionID>
        <extensionID>androidx.vectordrawable</extensionID>
        <extensionID>androidx.work</extensionID>
        <extensionID>com.google.code.gson</extensionID>
        <extensionID>com.distriqt.playservices.Ads</extensionID>
        <extensionID>com.distriqt.playservices.AdsIdentifier</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.IDFA</extensionID>
    </extensions>
</application>

**Comment by ajwfrost** [comment]
Github formatting doesn't seem to fully cope with that! but I did see this in the copy of the xml descriptor:
`<BuildLegacyAPK>true<BuildLegacyAPK>`
but the closing tag is missing the forwardslash, it should be:
`<BuildLegacyAPK>true</BuildLegacyAPK>`

Are you able to check what's actually in the XML descriptor? but that would explain the Animate "can't parse" message...

I didn't see the very first lines of the file in that output, it should be:
```
<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/33.1">
```
in order for that BuildLegacyAPK tag to be handled (and it must be built by a recent AIR SDK of course...)

thanks

**Comment by P2b10** [comment]
Hi Andrew:

Thanks for your reply. This is a screenshot of the main part of my XML descriptor

![Screen Shot 2022-02-23 at 18 38 13](https://user-images.githubusercontent.com/49465984/155434918-61556dd0-425d-4040-926d-2a758ca30e6a.png)
.

I was able to pack both apks 32 bit abd 64 bit. Already uploaded to Google Play.

Thanks a lot for your help!

Best regards.
