### ISSUE TITLE
Error building IPA on MacOs

### ISSUE THREAD

**Issue by megajogos** [airsdk/Adobe-Runtime-Support#1701]
When we run the ADT command to build our IPAs we got the following error:

```
Error during native code-signing. Output of codesign tool is:
error: The specified item could not be found in the keychain.
```

We are passing the cert with -keystore like we do on windows.

Would be great to have some documentation about it here:
https://airsdk.dev/docs/tutorials/platform/ios/packaging-ipa

**Comment by ajwfrost** [comment]
Hi

We'll look at updating (creating) that documentation; to help with the above though, if you're using "native code-signing" then the certificate needs to be set up within the macOS keychain tool. Native code-signing happens either if you've requested it (via a config file) or if the system is running a Java version that doesn't allow us to use the internal JVM security classes to do this manually... it means we're just calling down to the `codesign` tool available on your mac.

The certificate should therefore be one that you can find via the below command on your mac:
```
security find-identity -p codesigning -v
```

Hope that helps..

thanks
