### ISSUE TITLE
[Feature Request] [Windows][macOS][iOS] FREByteArray.newByteArray support

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#175]
## Feature Description
`FREByteArray.newByteArray` method necessary to create `ByteArray` objects by native extenstions with Windows, macOS and iOS platforms.
It supported right now only with Android Java native extensions.
There is no obvious way to create (not to modify passed to native extension) `ByteArray` objects on native side for mentioned platforms.

## Known Workarounds
For Windows C++ native extension:
```
//Create AS3 ByteArray object
FREObject freByteArrayObject;
FRENewObject((const uint8_t*) "flash.utils.ByteArray", 0, NULL, &freByteArrayObject, NULL);

FREByteArray freBytes;
FREAcquireByteArray(freByteArrayObject, &freBytes);//Acquire ByteArray
freBytes.bytes = ...;//Do something with bytes, fill it etc
FREReleaseByteArray(freByteArrayObject);//Release ByteArray

//Specify bytes length
int bytesLength = ...;

//Set up length of AS3 ByteArray object
FREObject bytesLengthObject;
FRENewObjectFromUint32(bytesLength, &bytesLengthObject);
FRESetObjectProperty(freByteArrayObject, (const uint8_t*) "length", bytesLengthObject, NULL);

//return freByteArrayObject to AS3 side, with AS3 side it could be handled as ByteArray
```

**Comment by ajwfrost** [comment]
Nice idea and should be relatively straightforward! Will add this to our list...
Thanks

**Comment by ajwfrost** [comment]
Hi

It may be that you're calling it slightly wrongly...
```
typedef struct {
    uint32_t length;
    uint8_t* bytes;
} FREByteArray;

/**
* Creates a new byte array using optional input information (length and optional byte)
*/
FREResult FRENewByteArray(
    FREByteArray* byteArrayData,
    FREObject *handle
);

```

So basically you could do:
```
FREByteArray settings;
settings.length = 100;
settings.bytes = NULL;
FREObject handleToAS3ByteArray = NULL;
FRENewByteArray(&settings, &handleToAS3ByteArray);
```
Then you have the AS3 object in that handle which you can pass back to the AS3 code or similar. It will have a length of 100 but uninitialised in the above case.

Alternatively:
```
FREByteArray settings;
const char* pData = "Values that are going to end up in a byte array";
settings.length = strlen(pData);
settings.bytes = pData;
FREObject handleToAS3ByteArray = NULL;
FRENewByteArray(&settings, &handleToAS3ByteArray);
```
then you'd end up with the byte array being initialised with the data i.e. it contains the bunch of characters, so `readUTFBytes` (with the number of bytes available) would then return you that string...

Hope that helps?

**Comment by itlancer** [comment]
@ajwfrost
Thanks. Yes, I did the same. Seems it was Visual Studio cache or something.
Now it works fine. Thank for new functionality!
