### ISSUE TITLE
AAB Build failed with an exception

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#1752]
Hey guys, I am trying to compile our app with aab for the first time. 
Installed Android Studio, added the path to the sdk and gave it a go. 
D:\AdobeAIRSDK\bin\adt.bat -package -target aab -storetype pkcs12 -keystore cert+pass "Agenda.aab" "ANDROID.xml" "Agenda.swf" "google-services.json" "GoogleService-Info.plist" data icons images -extdir extensions -platformsdk c:\Users\FxStudio\AppData\Local\Android\Sdk

Then we encountered this - literaly stuck at this point. 
Anyone got this before and has an idea on how to approach this?

NOTE: Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\FxStudio\AppData\Local\Temp\a3d63302-0796-4b7f-abd0-b4e155c9016a\androidx.appcompat\build.gradle' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.library']
> Failed to apply plugin 'com.android.internal.library'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s

**Comment by raresn** [comment]
I downloaded java 11, and pointed JAVA_HOME there,
now i get:

NOTE: Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.multidex.BuildConfig found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V14 found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V14$ElementConstructor found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V14$ICSElementConstructor found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V14$JBMR11ElementConstructor found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V14$JBMR2ElementConstructor found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V19 found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDex$V4 found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDexApplication found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDexExtractor found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDexExtractor$1 found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.MultiDexExtractor$ExtractedDex found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.ZipUtil found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)
     Duplicate class androidx.multidex.ZipUtil$CentralDirectory found in modules multidex (multidex.jar) and multidex-2.0.1-runtime (androidx.multidex:multidex:2.0.1)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s

**Comment by raresn** [comment]
@ajwfrost if you have the time to give me some pointers, I would appreciate it.

**Comment by ajwfrost** [comment]
The multidex issue there is because one of your ANEs is including "multidex.jar" and we're also setting up the multidex support, so there's a duplication. We had attempted to avoid this clash but had missed some instances... there's a release coming out hopefully tomorrow that should resolve that.

In the meantime, you could get ADT to generate an Android Studio project, and then open the app/build.gradle file and remove the "multidex.jar" library dependency, then build the AAB from there?

**Comment by raresn** [comment]
Super cool! I got lucky with this next release i guess :D
I have no idea how to do the last part, but i will read about it and try to do it in the morning when i get to work, and let you know.

If you can drop a line here as well when the new release will come out, that would be great.

**Comment by marchbold** [comment]
@raresn Just remove the `androidx.multidex` extension from your app. It's no longer required as AIR includes this by default now.

**Comment by raresn** [comment]
@marchbold  i don't have a androidx.multidex ane, i only have this in the manifest that referres to multidex:
<application android:hardwareAccelerated="true" android:name="androidx.multidex.MultiDexApplication" android:allowBackup="false" android:enabled="true">
Just above the details for the distrqt contacts.
Should i change that android:name or remove it?

**Comment by marchbold** [comment]
Ah right, what other extensions are you using? One of them must contain the multidex jar.

**Comment by raresn** [comment]
@marchbold Here is the full list.
<extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidx.arch</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidx.core</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.androidx.lifecycle</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.installations</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.measurement.connector</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.measurementBase</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.stats</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
		<extensionID>com.myflashlab.air.extensions.firebase.fcm</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.messaging</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.datatransport</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.encoders.json</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.firebase.addons.fcm</extensionID>
		<extensionID>com.myflashlab.air.extensions.statusbar</extensionID>
		<extensionID>com.distriqt.Application</extensionID>
		<extensionID>com.distriqt.Contacts</extensionID>
		<extensionID>com.distriqt.Core</extensionID>
		<extensionID>com.distriqt.IDFA</extensionID>
		<extensionID>com.android.installreferrer</extensionID>

**Comment by marchbold** [comment]
Ah right, yeah pretty sure it's in one of the myflashlabs extensions. I think this one : `com.myflashlab.air.extensions.dependency.androidx.core` 

You can try extracting it and removing the jar. Are they supporting you on those anymore?

**Comment by raresn** [comment]
They are probably not - I tried a while back, but i got an email from them that they've cut support.
I will need to migrate everything to distrqt, but i ran into some problems a while back and didn't had time to chase it further.
I will try removing jar (not sure how yet, but i will :) ) 
Also the fact that @ajwfrost told us there is going to be a release today fixing this gives me hope :)

**Comment by marchbold** [comment]
Can try this version: [androidx_core.ane.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8203489/androidx_core.ane.zip)

**Comment by ajwfrost** [comment]
@raresn  fyi the updated release SDK is live now...

**Comment by raresn** [comment]
I confirm that with the new SDK it compiled without issues.
I only get a NOTE:
Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging
Anything i should do about this?

Thank you @ajwfrost and @marchbold  for the support!

**Comment by ajwfrost** [comment]
Great thanks. That warning is something you can ignore, we might as well take it out since it's not like we're giving you any choice! It just means that in your Android SDK, you've got multiple build tool versions available; we always try to use the latest version number...
