### ISSUE TITLE
Content Not Displaying When Fullscreen set to False (Android)

### ISSUE THREAD

**Issue by dean-watson** [airsdk/Adobe-Runtime-Support#1756]
When debugging Android application and the app is configured to launch in fullscreen to false, no content displays. It works fine on the emulator. just seems to be a device issue. All works as it should if fullscreen is set to true.

Using apache flex with Harman flex overlaid (downloaded from Moonshine SDK) development using Intellij Idea

**Comment by ajwfrost** [comment]
Hi

Do you have a splash screen displaying first?

Also, Is it possible to check with the latest SDK, just released? To avoid hassle - all you'd need to do for this would be to copy the "runtimeClasses.jar" file from the new SDK over the top of the existing one, from lib/android/lib.

thanks

**Comment by dean-watson** [comment]
Hi, 

I have overlaid the latest SDK over my current one and it has fixed the issue I was having. Everything is now working as it should be.

Thanks
