### ISSUE TITLE
Publishing AIR for APK after tip Could not locate adb C:\....

### ISSUE THREAD

**Issue by skysumbra** [airsdk/Adobe-Runtime-Support#1758]
I reference adobe animate help and direct try publish apk.
https://helpx.adobe.com/animate/using/publishing-air-android-applications.html
OS:Win11
AIR SDK for Flex Developers - to be overlaid onto a Flex SDK
for Windows : 33.1.1.795  from https://airsdk.harman.com/download
SDK Platform Tools for Windows: 31.0.3 from https://developer.android.com/studio/releases/platform-tools

I create blank air for android project and use default configure, not change included files.
picture from help
![image](https://user-images.githubusercontent.com/24444616/157391517-ab2ab9c7-dbaa-4efa-a3bb-80f539a08f8d.png)

Always tip could not locate adb
![image](https://user-images.githubusercontent.com/24444616/157390341-c734152f-75e9-45bc-9fda-f73b88c13000.png)

cfg file
i change other adb tool path,but still observe symptom
![image](https://user-images.githubusercontent.com/24444616/157390371-e07ca24c-0de3-4751-a3a6-a59722d1728f.png)

I use adb command  on cmd, it's normal

Anybody can help me？

**Comment by marchbold** [comment]
I'd say you've set your android sdk path incorrectly. It's the path to the root of the Android SDK not the path to the tools. The path should contain folders like `build-tools`, `platform-tools` etc

**Comment by skysumbra** [comment]
thanks, i change it folder and publish not tip this symptom, but tip aapt tool question

**Comment by skysumbra** [comment]
> I'd say you've set your android sdk path incorrectly. It's the path to the root of the Android SDK not the path to the tools. The path should contain folders like `build-tools`, `platform-tools` etc
reference following three OS platform sdk manager of v24, i install and edit air's cfg file, last adobe animate publish sucess

[SDK Installer_r24.4.1](https://dl.google.com/android/installer_r24.4.1-windows.exe) (for windows)
[SDK Installer_r24.4.1](http://dl.google.com/android/repository/tools_r24.4.1-linux.zip) (for linux) 
 [SDK Installer_r24.4.1](http://dl.google.com/android/repository/tools_r24.4.1-macosx.zip) (for macos)
