### ISSUE TITLE
AIR SDK for Linux Mouse Right click on TextField display a white menu

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#1765]
## Problem Description

When I right click in a `flash.text.TextField`, the text `copy`, `paste`,... are not visible but is selectable, only `Delete` is visible.

* AIR SDK 33.1.1.795
* Ubuntu 20.04 and Fedora 35

![menu](http://pol2095.free.fr/img/air_linux_menu.jpg)

## Steps to Reproduce

right click on a `flash.text.TextField`

## Known Workarounds

no workaround.

**Comment by ajwfrost** [comment]
Can I check when you look at other applications on these machines, when you view a menu and it has disabled items on it, what are the colours used? We don't appear to be changing any of the colours which means they should be picked up from the GTK theme... the only part we do change is the background of the main drawing window (so potentially, the menu items are picking this up from that now?)

Just looking at your example though .. it's also odd that 'Delete' is the only one visible, 'Copy' should always be a possibility! This is presumably an "input" style text field? Do the visible menu items change depending on whether you have any text in there, whether it's selected or not, etc?

thanks

**Comment by pol2095** [comment]
I created a custom ContextMenu on a Sprite, it's displayed correctly

```
var editContextMenu:ContextMenu = new ContextMenu(); 
var cutItem:ContextMenuItem = new ContextMenuItem("Cut") 
editContextMenu.customItems.push(cutItem); 

var copyItem:ContextMenuItem = new ContextMenuItem("Copy") 
copyItem.enabled = false;
editContextMenu.customItems.push(copyItem); 
 
var pasteItem:ContextMenuItem = new ContextMenuItem("Paste") 
editContextMenu.customItems.push(pasteItem); 
sprite.contextMenu = editContextMenu;
```

**Comment by ajwfrost** [comment]
Hi
Thanks for this .. so it turns out, it's just failing to load a resource bundle, we had somehow missed this from the SDK deployment! Can you please expand the below zip into the folder:
`[AIR SDK]/runtimes/air/linux/Adobe AIR/Versions/1.0/Resources/`
[menu_resources.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8319701/menu_resources.zip)

We'll include these files properly in the next SDK release..

thanks

**Comment by pol2095** [comment]
It work now, thanks.
