### ISSUE TITLE
Stagewebview on windows UseWebView2 viewport does not fit

### ISSUE THREAD

**Issue by myflashlab** [airsdk/Adobe-Runtime-Support#1784]
Finally AIR SDK **33.1.1.795** could correctly complete the Google OAuth2 authentication on windows. Thanks for that 😃  The Stagewebview on previous SDKs were working fine on Mac but not Windows. I'm super happy that it now also works on Windows with the latest SDK and using `UseWebView2`

However, the viewport size is broken and I am not able to fit the webview size to cover my whole window. Same code works fine on Mac and I have not yet tested on Linux yet.

<img width="598" alt="Untitled" src="https://user-images.githubusercontent.com/1692948/158892189-9549766a-de6b-4d46-ab30-4d61b6210b8a.png">

**Comment by 2jfw** [comment]
Are you using a the high-dpi setting `<requestedDisplayResolution>high</requestedDisplayResolution>`?
If so, try to consider the `stage.contentsScaleFactor` when applying the viewport.

**Comment by myflashlab** [comment]
Awesome tip! thank you @2jfw that solved the problem. I'm closing this ticket now but @ajwfrost , I really think there should be a proper way for documenting stuff. for example I remember that when the new StageWebView was introduced, no one could use it unless asked here (can't find the link right now) and then you mentioned that adding the following to the manifest is required.
```
    <windows>
        <UseWebView2>true</UseWebView2>
    </windows>
```
If someone tries to use it right now, they would have no idea about that as it's not mentioned anywhere else.

Or is there a place for these documentations that I'm not aware of? 😃

**Comment by ajwfrost** [comment]
Currently the documentation for these are just in the release notes which are fairly dry/brief when it comes to the detail. I had been hoping we could create tutorial information on airsdk.dev for these sorts of things which may be good - but it's also probably worth us having a longer set of release notes that focus just on new features and how to use them, again stuck under the airsdk.dev side. If these could be searchable it then may help ..

**Comment by marchbold** [comment]
I'm working on integrating search to airsdk.dev. Hoping to have that up in the next fortnight.

**Comment by norikoji1** [comment]
@myflashlab

I have the same problem as you now and I haven't solved it yet.
How did you solve it?

The SDK for Windows version 33.1.1.758 or later has a problem. 
When using StageWebView with URL specification, it is not displayed at the correct scale.

Should I have use `UseWebView2`?

**Comment by myflashlab** [comment]
@norikoji1 as `2jfw` suggested, I used `contentsScaleFactor`. In my code, I check if the software is running on a windows and if it does, I will multiply the viewPort dimensions by that.

```actionscript
var p:Point = _flex.webviewPlace.localToGlobal(new Point(0, 0));
var w:Number = _flex.webviewPlace.width;
var h:Number = _flex.webviewPlace.height;
if(BaseData.os.system == OS.WIN)
{
	w *= _flex.stage.contentsScaleFactor;
	h *= _flex.stage.contentsScaleFactor;
}
_webView.viewPort = new Rectangle(p.x, p.y, w, h);
```

**Comment by 2jfw** [comment]
> @norikoji1 as `2jfw` suggested, I used `contentsScaleFactor`. In my code, I check if the software is running on a windows and if it does, I will multiply the viewPort dimensions by that.
> 
> ```actionscript-3
> var p:Point = _flex.webviewPlace.localToGlobal(new Point(0, 0));
> var w:Number = _flex.webviewPlace.width;
> var h:Number = _flex.webviewPlace.height;
> if(BaseData.os.system == OS.WIN)
> {
> 	w *= _flex.stage.contentsScaleFactor;
> 	h *= _flex.stage.contentsScaleFactor;
> }

Note that additionally to that, even `x` and `y` need to be multiplied by the `stage.contentsScaleFactor` when they are not (0|0)
