### ISSUE TITLE
[Android] Can't install on Android 12

### ISSUE THREAD

**Issue by kubiyuan** [airsdk/Adobe-Runtime-Support#1799]
Hi...
My project was upgraded from air sdk 30.0.0 to 33.1.1.743,"FAILED_VERIFICATION_FAILURE" problem occurred when installing on Android 12.
Please help me to solve this problem.

thanks
[install_logcat.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/8346751/install_logcat.txt)

**Comment by ajwfrost** [comment]
Hi

On the phone, are you able to set up the developer menu and then within the developer settings, check for something like "Verify apps over USB" and turn this setting off. You may also need to go into the normal security settings and allow the installation of apps from unknown sources...?

thanks
