### ISSUE TITLE
bad error when creating apk file with distriqt advert ANE ver13.50 

### ISSUE THREAD

**Issue by atiani** [airsdk/Adobe-Runtime-Support#1819]
Hi Sir  ,  recently I creating android application using last ver distriqt advert ane 13.50 but the main problem is when I creating the apk file the Adobe animate show me this error , so i appreciate  if you  have the solution or suggestion please tell me .

With my respect
![gggg](https://user-images.githubusercontent.com/78841476/161553007-8bcbccb9-2f16-4cf9-9b3a-b39573c5abb8.png)

**Comment by marchbold** [comment]
Please see this discussion on using the new build method: 

https://github.com/airsdk/Adobe-Runtime-Support/discussions/1782

This error is caused by using the legacy apk method to build your application.
