### ISSUE TITLE
Object not removed from Stage on Android

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#1849]
Hello, we recently found a bug in our app that we can't figure out.
When we first start the app:
- add a "splash screen"
- load the data from the device (load files)
- launch starling
- remove the "splash screen"
Now, we encountered some scenarios where the removal of the "splash screen" doesn't work.

I am attaching the sample code to reproduce this.

SCENARIO 1 - WORKING
-by setting skipUnchangedFrames to false, it will run the app,
-it will show the splash
-it will fake load for 5 seconds (just a while loop to simulate loading of files)
-start starling 
-it will try to remove the splash after 3 seconds
-it will work

**SCENARIO 2 - NOT WORKING**
_this is the case we encounter in our app, and why we built this simple test after nearly going insane ;))_
	
-by setting skipUnchangedFrames to false, it will run the app,
-it will show the splash
-it will "fake load" for 5 seconds (just a while loop to simulate loading of files)
-- we put the app in background when this "load" starts (so, not close, just put it background)
-- we open it up again within these 5 seconds
-start starling 
-it will try to remove the splash after 3 seconds
-it will NOT WORK ANYMORE, nor show the blue background of Starling!
	
SCENARIO 3 - NOT WORKING 
-if you set skipUnchangedFrames to true,
-it will show the splash
-it will fake load for 5 seconds
-start starling, 
-it will show the blue background of starling
-it will try to remove the splash after 3 seconds, but will fail to do so.			
			
**Known fix** - rotate the screen, or put the app in background and put it in forground again.
Source files here: [splashTest.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8488982/splashTest.zip)

@ajwfrost  do you think this is something you could investigate?

**Comment by dmunsie** [comment]
I'd probably also post this in the Starling forum since it could be related to that environment.

**Comment by 2jfw** [comment]
Did (/can) you try replacing the `while loop` with something _less_ "heavy"?

**Comment by ajwfrost** [comment]
Can I just check what device(s) you've tried this on? I've tried to reproduce the 'scenario 2' but it works on a test handset here... 
1) start up the app - a red square appears
2) swipe up and press the 'home' button -> goes to the Android home screen
3) press the 'all apps' button and select the most recently viewed application -> comes back again
4) then the blue screen appears (5-6 seconds after step 1)
5) then the red square disappears (3-4 seconds after step 4)

**Comment by raresn** [comment]
I tried replicating ... A LOT of times, i can only replicate on Android 9, in debug mode. Newer android version work without a problem even in debug. AAB doesn't show this problem without debug on Android 9.
There is a bug somewhere, but since i am not able to provide a working demo of it, i won't waste everyone's time. 
Once i am able to better pin point it, i will come back. Thank you.
