### ISSUE TITLE
[android] stage.frameRate maximum value? | stage.vsyncenabled = false?

### ISSUE THREAD

**Issue by dmunsie** [airsdk/Adobe-Runtime-Support#1857]
**What is the maximum value for stage.framerate?** My apps use delta time and I'm trying to test them on phones with higher refresh rates, but I'm not able to verify anything running faster than 60fps. I'm able to verify slower frame rate settings, but nothing over 60.

Related, does **stage.vsyncenabled = false** actually work? Because again, I'm not seeing any change on desktop or mobile. Thx.

**Comment by 2jfw** [comment]
On my old 120Hz Monitor, I was able to run with exactly and true 120 FPS (not having made us of `stage.vsyncEnabled = false`) so it may somehow be tied or limited to the actual physical refresh rate (?)..

**Comment by ajwfrost** [comment]
This is an interesting minefield...

> does stage.vsyncenabled = false actually work

You should be able to check that at runtime by adding an event listener to the Stage, for `"vSyncStateChangeAvailability"`
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/Stage.html#event:VsyncStateChangeAvailability

From what I can see, this is likely to be true for macOS where we're rendering via OpenGL, or for Windows when we're rendering via Direct3D. In other words, when you have "direct" or "gpu" modes in your application descriptor, you should be able to change the `vsyncEnabled` property and have it actually make a difference.

It doesn't appear to be in use on mobile platforms i.e. these may always be vsync-driven, or limited some other way perhaps.

But if you have a phone with a high refresh rate then you should be able to get the SWF to match it.. the `Stage.frameRate` property has a maximum of 1000 when it's set from ActionScript (and I think a maximum of 255 when set in the SWF, looking at the SWF spec).

What phone platform are you actually using here? and what render mode? It would be worth checking with cpu and direct modes to see if there's a difference..

thanks

**Comment by dmunsie** [comment]
Thanks for the reply.

"What phone platform are you actually using here? and what render mode?"

Android w/ "Direct" mode. I use a custom Stage3D engine so I need Direct mode.

"But if you have a phone with a high refresh rate then you should be able to get the SWF to match it.. the Stage.frameRate property has a maximum of 1000 when it's set from ActionScript (and I think a maximum of 255 when set in the SWF, looking at the SWF spec)."

"It doesn't appear to be in use on mobile platforms i.e. these may always be vsync-driven, or limited some other way perhaps."

So can you 100% confirm then that on Android mobile devices the air captive runtime is not placing a hard cap of 60fps on the frame rate?

I'm fine with leaving vsync turned on, I'm just concerned if the internal runtime (timing mechanism) is capping the fps at 60 and how this would affect games running on devices with higher refresh rates. My apps use delta time, so the higher the refresh rate the better. But if the runtime is capped at 60, and the device is running at 90, 120, etc, I believe that could lead to the app/game having timing issues, jittery movement, animation, etc.

**Comment by ajwfrost** [comment]
Thanks

> So can you 100% confirm then that on Android mobile devices the air captive runtime is not placing a hard cap of 60fps on the frame rate?

No, sorry, what I meant is that on Android you won't be able to change things with that vsyncEnabled property...

If you're using Android and Direct mode, then it will be using OpenGL ES.. and this then goes through the Android SurfaceFlinger process and we'll be bound to the vsync rate. I would hope that we can go faster than 60fps if the device is running faster, it should just be the case that we perform the AS3 event handling (including enterFrame), do the rendering, and then call SwapBuffers which waits for the vsync before returning each time.

We can check this though, I think we have a device with 120Hz refresh rate so I'll see what this is reporting...

thanks

**Comment by ajwfrost** [comment]
... a quick test here shows we're getting around 115-116 fps, sometimes 120. So it sounds like we're dropping some frames. Oddly having just tapped on the screen a lot to see if that slowed things down (it didn't, but there aren't any event handlers) we're now more consistently hitting the 120fps mark, sometimes 119.88, sometimes 120.12, which may mean a slight inaccuracy in our calculation!

All the test is doing is adding an enterFrame handler, and in this incrementing a 'frame count' variable, then when this gets to 120 we measure the time difference since the last time we hit this (via `flash.utils.getTimer()`) and working out the FPS, then sticking this into a text field. It's running in direct mode.

The handset (Samsung Galaxy S20 FE) has developer settings with "Show refresh rate" turned on. Nothing else particularly special about it... 

thanks

**Comment by dmunsie** [comment]
Thanks for the quick testing! :) So...it's safe to say we should leave the vsyncenabled=true in the code, since it doesn't hurt and it will still be valid on desktop. But in regards to setting the stage.framerate, to insure the highest smoothest framerate (since we use delta time) would it be acceptable to just set this to a high value like 999 and let the app run as fast as it can since it will be bound by vsync anyway?

And also just for clarity..... if an app does set the framerate to 60, when running on a device that has a higher refresh rate (such as your test device at 120hz) would the app still run at 60 or would it run faster? Thanks again for your time.

**Comment by ajwfrost** [comment]
The frame rate is used primarily to work out when we should send out an 'enterFrame' event, and all the rendering/display stuff. There's actually a timer inside AIR which is going faster than that, in order to handle asynchronous things like other events or network messages etc. So setting the framerate to 999 may not help a huge amount, and may just increase CPU load.

If you set the frame rate to 60 then the runtime wouldn't render faster than this. So the value here should really be seen as a maximum target, the frame rate can drop sometimes if it's busy or if the timings don't quite work out but it won't run faster than the frameRate value.

thanks

**Comment by dmunsie** [comment]
Thanks again, just to be 100% clear so you understand (in case making games is not your main focus) delta time means the game is not bound by frames/fps. So the faster the game is running the smoother the movement, animation, etc. We use the internal timer which runs at 1000ms to get a delta of how long the last frame took (or avg of a few frames) and then use that as a delta that gets applied to everything. So setting the stageframerate is extremely important to consider.

Doing some research, it appears there's only a few devices supporting high refresh rates, but there is also a trend of lowering the refresh rate to 50,40,30, and lower to conserve battery usage so that is something to keep in mind as well. 

So if anything it seems safe to set the stage.framerate to 240 instead of 999 like you can on desktop. That should cover just about everything for quite some time. lol.. I'll close this issue now, since it wasn't really a bug. Thank you for the conversation and testing, much appreciated! 

https://www.smartprix.com/bytes/phones-with-true-variable-refresh-rate-displays/

**Comment by ajwfrost** [comment]
Thanks for the explanations. My slight concern with the approach for this "delta time" is that you're checking the time when you are in an ActionScript handler, but the actual display to the user of whatever you've calculated will happen at the next frame update i.e. vsync. So there is a delay between when you make the calculations vs when the user sees the results.

What you might see if you use Scout would be that the AS3 processing happens early in the frame time but then there's a bit of "waiting for GPU" time where the runtime is just waiting in that SwapBuffers call for the vsync when the buffer can be swapped onto the display.

We've been discussing this sort of issue a while ago with some Windows game developers, I'm still not convinced that there's a straightforward (or rather, foolproof) approach here. Ultimately (a) you need to use vsync to avoid tearing, and (b) we don't really know how long it will take to do all the AS3 processing and rendering stuff, so there may be some imperfections in how smooth things appear, particularly if we drop a frame i.e. the processing is too long and the next video frame is displayed prior to us finishing updating the buffer i.e. there is then effectively a wasted/static frame where nothing changes before we next update the screen.

Challenging! Let us know if you do see odd things happening with the frame rates and glitches or too much "waiting for GPU" going on in Scout..

thanks
