### ISSUE TITLE
[Android] renderMode=gpu works great on Android Studio but the app looks completely different on Android Devic

### ISSUE THREAD

**Issue by reibruzia** [airsdk/Adobe-Runtime-Support#1887]
Using the latest SDK (AIR 33.1.1.821)

Our app works great when we use renderMode = gpu on the Android Studio emulator, however when we try to run it on an actual Android device, fonts don't have shadows and some graphics are missing as well.  

I've read that that there are limitations to the GPU render mode, but what I'm wondering is how is it that the app works properly with no issues on the emulator, yet it fails to display things correctly on a native Android device.

**Comment by ajwfrost** [comment]
Are you able to check using Scout to see what actual mode is being used in each case? I have a suspicion that on the emulator, it's not actually using GPU mode so may end up with CPU rendering where it then supports all the shadows/graphics that perhaps then don't render properly once it's using OpenGL ES on some real hardware....

thanks

**Comment by bobrokrol** [comment]
renderMode "direct" must be used for mobile platforms

**Comment by FliplineStudios** [comment]
> renderMode "direct" must be used for mobile platforms

It depends on what you're doing -- we use gpu mode for all of our mobile games, which use vector graphics and were designed specifically with gpu mode in mind.  Direct would be used for Starling/Stage3D on mobile, but doesn't perform as well as gpu rendering with classic display list or vector graphics.
