### ISSUE TITLE
Simple alerts don't work any longer with AIR 33.1.1.856

### ISSUE THREAD

**Issue by Michoko92** [airsdk/Adobe-Runtime-Support#1929]
Hi,

I am developing mobile apps, and need a way to test them quickly on desktop first. My apps contain a few native popups displaying confirmation dialogs. Until now, I was using a simple class to display very basic alert popups on desktop platforms (on mobile devices, those dialogs are handled by native ANEs). Here is the class: https://www.purplesquirrels.com.au/2012/03/simple-way-to-get-native-alerts-with-adobe-air/

Unfortunately, with latest AIR release, it seems it doesn't work any longer. When I call:

_alertDispatcher.window.alert(pText);

_alerDispatcher.window is null. Is there a way to still use the old behavior, please? Implementing my own dialog system just for quick tests seems pretty overkill to me. Thank you! :)

**Comment by ajwfrost** [comment]
Hi

The `window` property will be null as we don't have the way to expose the JavaScript objects in quite the same way now... but below is a function that you could use for something similar. If you're calling it multiple times, I would suggest some optimisations to keep the StageWebView object around but just take it off the stage when it's not needed...

```
		private function alert(str : String) : void
		{
			var swv : StageWebView = new StageWebView(true);
			var f : Function = function(e:LocationChangeEvent):void {
				if (e.location == "about:blank")
				{
					swv.stage = null;
					swv.removeEventListener(LocationChangeEvent.LOCATION_CHANGING, f);
					swv.dispose();
					swv = null;
				}
			};
			swv.addEventListener(LocationChangeEvent.LOCATION_CHANGING, f);
			var strHTML : String = "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>" +
                    "<title></title><script>alert('" + str + "');this.location='about:blank';</script></head><body></body></html>";
			swv.loadString(strHTML);
			swv.stage = stage;
			swv.viewPort = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
		}
```

Plus you may need to do some processing of the 'str' argument to ensure it's not got any single-quote characters that would screw up the JavaScript code..

thanks

**Comment by Michoko92** [comment]
Thank you Andrew for your awesome support, as usual. With this solution, is it possible to have yes/no or ok/cancel dialogs too, and retrieve the user's choice?

**Comment by ajwfrost** [comment]
You can probably extend this a little to do those sorts of things still using JavaScript. So e.g. for a text prompt:
```
		private function prompt(str : String, listener : IEventDispatcher) : void
		{
			var swv : StageWebView = new StageWebView(true);
			var f : Function = function(e:LocationChangeEvent):void {
				if (e.location.indexOf("about:blank") == 0)
				{
					var response : String = e.location.substr("about:blank?resp=".length);
					swv.stage = null;
					swv.removeEventListener(LocationChangeEvent.LOCATION_CHANGING, f);
					swv.dispose();
					swv = null;
					listener.dispatchEvent(new TextEvent("promptResponse", false, false, response));
				}
			};
			swv.addEventListener(LocationChangeEvent.LOCATION_CHANGING, f);
			var strHTML : String = "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>" +
                    "<title></title><script>var val=prompt('" + str + "');this.location='about:blank?resp='+val;</script></head><body></body></html>";
			swv.loadString(strHTML);
			swv.stage = stage;
			swv.viewPort = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
		}
```
which is waiting for the user's response asynchronously, so you'd need to call it via something like:
```
this.addEventListener("promptResponse", function(e:TextEvent):void { trace("Response = " + e.text); });
prompt("Enter your name:", this);
```

So essentially you're able to set up an HTML string with whatever JavaScript code you want to trigger at its launch, and then use the location request to pass information back to the handler in ActionScript. A bit clunky perhaps - we will check whether it's possible to have some sort of interaction between AS and JS built back in, but there may be some security limitations that we hit nowadays..

Of course, I think it might also be quite useful if AIR had these sorts of capabilities natively... I guess Flex has similar things already which could be used; not 100% sure what the native platform support is for things like this so I'll talk with the team about it...

thanks

**Comment by Michoko92** [comment]
Thank you Andrew, much appreciated. I agree that dialogs might be one of the few features that are still lacking in the AIR API. Any improvement regarding this would be awesome!
