### ISSUE TITLE
[Android][iOS] Stage::color doesn't changes after Context3D::configureBackBuffer()

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1935]
## Problem Description
`Stage::color` doesn't changes after `Context3D::configureBackBuffer()` with Android and iOS devices.
`direct` `renderMode` should be used to reproduce this issue.
It critical for applications that use both `DisplayList` and `Stage3D` render.

Tested with latest AIR 33.1.1.856 with multiple different iOS/Android devices with different OS.
Same problem in all cases.

There is no such issues with Windows and macOS.

Related issue (not the same): https://github.com/airsdk/Adobe-Runtime-Support/issues/964

## Steps to Reproduce
1) Compile and launch code below. It just change stage color from red to green every second.
2) Click anywhere on stage. `Context3D` will be requested for `Stage3D` and `Context3D::configureBackBuffer()` will be called.

Note that `renderMode` in application manifest should be `direct`.

Application example with sources attached.
[stage_color_context3d_configure_back_buffer_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8774763/stage_color_context3d_configure_back_buffer_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.TimerEvent;
	import flash.utils.Timer;
	import flash.events.MouseEvent;
	import flash.display.Stage3D;
	import flash.events.Event;
	
	public class StageColorContext3DConfigureBackBufferBug extends Sprite {
		private var timer:Timer = new Timer(1000);
		private var changeColorTrigger:Boolean;
		
		private var stage3D:Stage3D;
		
		public function StageColorContext3DConfigureBackBufferBug() {
			timer.addEventListener(TimerEvent.TIMER, changeColor);
			timer.start();
			
			stage.addEventListener(MouseEvent.CLICK, click);
		}
	
		private function changeColor(e:TimerEvent):void {
			trace("changeColor");
			if (changeColorTrigger){
				stage.color = 0x00FF00;//Green
			} else {
				stage.color = 0xFF0000;//Red
			}
			changeColorTrigger = !changeColorTrigger;
		}
		
		private function click(e:MouseEvent):void {
			trace("click");
			
			stage3D = stage.stage3Ds[0];
			stage3D.addEventListener(Event.CONTEXT3D_CREATE, myContext3DHandler);
			stage3D.requestContext3D();
		}
	
		private function myContext3DHandler(event:Event):void {
			trace("myContext3DHandler");
			stage3D.context3D.configureBackBuffer(100, 100, 4, false);//Stage::color doesn't changes after this line
		}
	}
}
```

**Actual Result:**
Stage color stop changes. `Stage::color` do nothing anymore.

**Expected Result:**
Stage color changes from red to green every second.

## Known Workarounds
Draw `DisplayObject` at the bottom and redraw its color. But such approach has less performance.

**Comment by ajwfrost** [comment]
I think the issue here is happening because once you've configured an OpenGL ES based Stage3D context, rendering is then driven by the `Context3D.present()` call. So to make it work how you would want, you need to have an `enterFrame` handler and call the `present()` method in here.

If we were to hook into the normal rendering mechanism at this point, and to force the re-rendering of the display but without waiting for the `present()` call, your Stage3D content would disappear. This may be a limitation on the mobile platforms because of the more efficient use of OpenGL ES, rather than the different mechanisms used on macOS and Windows..

thanks

**Comment by itlancer** [comment]
@ajwfrost 
Thanks! `Context3D::present()` on `enterFrame` did the trick.
I'm trying to play VideoTexture over color background with mobile devices and stuck into another issue with iOS: https://github.com/airsdk/Adobe-Runtime-Support/issues/1939.
