### ISSUE TITLE
[Windows] StageWebView.isSupported returns false with UseWebView2 for devices without Edge WebView2

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1936]
## Problem Description
`StageWebView.isSupported` returns `false` with `<UseWebView2>true</UseWebView2>` for Windows devices without Edge WebView2.
But `StageWebView` can be used and it works as expected.
So `StageWebView.isSupported` cannot be used in some cases to check does platform support `StageWebView` to use it.

Tested with latest AIR 33.1.1.856 with multiple different Windows 7/8.1/10 devices without Edge WebView2.
Same problem in all cases.
There is no such issue with installed Edge WebView2 for Windows devices.
Also there is no such issue with `<UseWebView2>false</UseWebView2>`.
Also there is no such issue with macOS/Android/iOS.

Related issues (not the same):
https://github.com/airsdk/Adobe-Runtime-Support/issues/1882
https://github.com/airsdk/Adobe-Runtime-Support/issues/1881

## Steps to Reproduce
Launch code below with any Windows devices without Edge WebView2 installed.

Note: application manifest should contains
```
<windows>
    <UseWebView2>true</UseWebView2>
</windows>
```

Application example with sources attached.
[stagewebview_is_supported_usewebview2_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/8775164/stagewebview_is_supported_usewebview2_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.media.StageWebView;
	
	public class StageWebViewIsSupportedUseWebView2Bug extends Sprite {
		
		public function StageWebViewIsSupportedUseWebView2Bug() {
			trace("StageWebView.isSupported:", StageWebView.isSupported);
		}
	}
}
```

**Actual Result:**
`StageWebView.isSupported` returns `false`.

**Expected Result:**
`StageWebView.isSupported` returns `true`.

## Known Workarounds
none
*don't use `StageWebView.isSupported` for Windows devices if `<UseWebView2>true</UseWebView2>` set up

**Comment by itlancer** [comment]
It “as designed”. So in code we should check `StageWebView` on creation in such situation.

**Comment by itlancer** [comment]
Fixed with latest AIR 33.1.1.889.
Thanks!

**Comment by Mintonist** [comment]
@itlancer 
Is it correct, that StageWebView.isSupported == true on Windows without EdgeWebView2 component installed?
Seems it is strange behavior. I prefer not to show my users older bugged IE based StageWebView in this case. But how can I know about it if StageWebView.isSupported is true?

**Comment by itlancer** [comment]
@Mintonist, I think its correct, cause if you need to show "simple" web page - then using Edge WebView2 preferrable but even without it I can show some fallback and may be "please install new browser" message.
But I agree with your question about Edge WebView2 check.
You can check Windows registry values for that or create native extension to check installed Edge WebView2 version.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/421
https://stackoverflow.com/questions/71856902/how-can-i-check-if-microsoft-edge-webview2-runtime-or-microsoft-edge-insider
It could be done via `NativeProcess` call with cmd/Powershell/regedit or via C++/C# native extension.

**Comment by ajwfrost** [comment]
Internally, we know whether or not the Edge WebView2 component is (a) requested (via app descriptor), and (b) installed (via checking the registry and ensuring the dll it mentions is present). So we could add a new API to check what engine we would be creating here .. but with the caveat that even if we think it's available, it may not be possible to create it and then we would fall back to using the IE-based WebBrowser control.

Or maybe it would be better to change the `<UseWebView2>` options, so as well as just false/true, we could have an option like `exclusive` which would mean we don't do the fallback and we do the checks just for the WebView2? This may be a little simpler to do..

**Comment by Mintonist** [comment]
@ajwfrost, `exclusive` option is a good idea! In my scenario StageWebView.isSupported will be false?


May I ask you one more question here?
Previously I used ANE NativeWebView or old AIR StageWebView for my game payment process.  I set viewPort like this:
`stageWebView.viewPort = new Rectangle(deltaX, deltaY, Starling.nativeStage.stageWidth-2*deltaX, Starling.nativeStage.stageHeight-2*deltaY);`


But with WebView2 on 150% it looks

**Comment by Mintonist** [comment]
@ajwfrost, `exclusive` option is a good idea! In my scenario StageWebView.isSupported will be false?


May I ask you one more question here?
Previously I used ANE NativeWebView or old AIR StageWebView for my game payment process.  I set viewPort like this:
`stageWebView.viewPort = new Rectangle(deltaX, deltaY, Starling.nativeStage.stageWidth-2*deltaX, Starling.nativeStage.stageHeight-2*deltaY);`

And there were no problems with any Windows display zoom:
![2023-11-15_172119](https://github.com/airsdk/Adobe-Runtime-Support/assets/9267850/e5c93d49-2eda-489e-a4c5-15cec59a143c)

But with WebView2 on PC with 150% zoom it looks:
![2023-11-15_172314](https://github.com/airsdk/Adobe-Runtime-Support/assets/9267850/bb153249-7ce4-4c69-860d-41e5a184650d)

`Starling.supportBrowserZoom and Starling.supportHighResolutions` are true.

descriptor settings:
```
<initialWindow>
        <content>SWF file name is set automatically at compile time</content>
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <visible>true</visible>
        <renderMode>direct</renderMode>
        <softKeyboardBehavior>none</softKeyboardBehavior>
        <depthAndStencil>true</depthAndStencil>
        <resizable>true</resizable>
        <systemChrome>standard</systemChrome>
        <maximizable>true</maximizable>
        <minimizable>true</minimizable>
        <minSize>480 320</minSize>
        <maxSize>1440 960</maxSize>
 </initialWindow>
```

Is i a AIR bug or I need to count zoom myself?

**Comment by ajwfrost** [comment]
Hi

> In my scenario StageWebView.isSupported will be false?

Yes that would be the goal, it basically would mean that we ignore any presence of the IE WebBrowser control...

> Is it a AIR bug or I need to count zoom myself?

I'm not 100% sure what that `Starling.supportBrowserZoom` may be doing, but I would suspect an AIR bug, we had a complete nightmare trying to get the scaling working properly! We can check this one...

thanks

**Comment by Mintonist** [comment]
I try Starling.supportBrowserZoom true and false - same result.

Do I create a new issue about zoom?

**Comment by ajwfrost** [comment]
Thanks, yes please if you create a new issue for the zoom thing, and we'll use this one as a placeholder for this new option for adding `exclusive` as a value for the `UseWebView2` option in the app descriptor...

**Comment by itlancer** [comment]
@ajwfrost 
I think new `exclusive` mode should be documented https://airsdk.dev/docs/building/application-descriptor-files/elements/windows
And this issue should be closed after that.

**Comment by itlancer** [comment]
Now new `exclusive` mode available and documented https://airsdk.dev/docs/building/application-descriptor-files/elements/windows
