### ISSUE TITLE
[macOS][Linux][33.1.1.821+] AIR SDK contains Windows .bat files

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#1944]
## Problem Description
AIR SDK 33.1.1.821+ for macOS/Linux contains Windows specific **.bat** files in `bin` directory.
These files doesn't make sense for such platforms.
Checked with latest AIR SDK 33.1.1.821 and 33.1.1.856 for macOS and Linux.
There is no such files with AIR SDK 33.1.1.795 and below for macOS and Linux.

Related issue (no the same): https://github.com/airsdk/Adobe-Runtime-Support/issues/1882

## Steps to Reproduce
Download AIR SDK 33.1.1.821+ for macOS or Linux and take a look at `bin` directory.

**Actual Result:**
Windows specific **.bat** files inside `bin` directory.

**Expected Result:**
No **.bat** files inside `bin` directory.

## Known Workarounds
These files didn't uses for macOS/Linux, just ignore it.

**Comment by itlancer** [comment]
Fixed with AIR SDK 33.1.1.889.
But found another one issue related for **.exe** files: https://github.com/airsdk/Adobe-Runtime-Support/issues/1973

**Comment by itlancer** [comment]
Issue returns with AIR SDK 50.0.0.1 and 50.0.1.1.

**Comment by ajwfrost** [comment]
Ah, a change in the packaging script wasn't brought over from the 33.1 branch to the 50.0. Fixed this now, for future versions..
Thanks!

**Comment by itlancer** [comment]
Fixed with AIR SDK 50.0.1.2.
Thanks!
