### ISSUE TITLE
Re:Anr occurs on AIR_SDK_33.1.1.795

### ISSUE THREAD

**Issue by Gokulv617** [airsdk/Adobe-Runtime-Support#1946]
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 10. Wait queue head age: 5667.2ms.)

This anr occurs on AIR_SDK_33.1.1.795

What to do now

**Comment by marchbold** [comment]
duplicate #1947
