### ISSUE TITLE
app store issue ITMS-90338

### ISSUE THREAD

**Issue by pis0** [airsdk/Adobe-Runtime-Support#1955]
iPhoneOS SDK Version: 15.5
XCode Version: 13.4.1
Minimum iOS Target: 12.2
java 11.0.15+10-b2043.56 aarch64
air SDKs 33.1.1.821 / 33.1.1.856

> ITMS-90338: Non-public API usage - The app references non-public selectors in **_project name_** : 
>
> authorizationCode, authorizedScopes, createRequest, dataChanged, determineAppInstallationAttributionWithCompletionHandler:, 
> identityToken, initWithFrame:configuration:, isMainFrame, lookupAdConversionDetails:, 
> mediaTypesRequiringUserActionForPlayback, navigationDelegate, setAllowsAnyHTTPSCertificate:forHost:, 
> setNavigationDelegate:, setRequestedScopes:, targetFrame, transform:.
>
>  If method names in your source code match the private Apple APIs listed above, altering your 
> method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

this error is totally new in this project.. this morning the app was submitted, same code/project, with no issues.. 

ps: no errors in the Transporter app are spotted.

**Comment by pis0** [comment]
solved.. it was related to the iphone OS version

**Comment by shohei909** [comment]
It seems the same as this one.

https://developer.apple.com/forums/thread/127678?page=6

> This is due to Apple have update their policy and you need to log in from the apple developer account and click on agree to new policy updates. then this will be resolved and try with a new test flight build.

**Comment by P2b10** [comment]
So what is the solution. How did you solved it?

**Comment by pis0** [comment]
resubmitting.. just that

**Comment by P2b10** [comment]
Thanks.
