### ISSUE TITLE
Application Not Running Full Screen on Android

### ISSUE THREAD

**Issue by llyRayYoung** [airsdk/Adobe-Runtime-Support#1982]
The application was built using AIR_33.1.1.889. Our application is designed to run fullscreen for any orientation and aspect ratio, I had added the android.max_aspect meta data tag to my application, but is not work. I need your help.

<meta-data android:name="android.max_aspect" android:value="3.4"/>

The device specs and screenshots have been attached.
![L1VzZXJzL3lsbC9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMzE0MDE1NjQ3X3YyL0ltYWdlRmlsZXMvMTY1NTcyMDU2Njc4Nl8xRDEyOEE2Ny00QUVBLTQzRjItQjMzMS0yRTYwQjFFMTBGRDkucG5n](https://user-images.githubusercontent.com/16644510/174583403-ada38ff6-4f54-4a39-b50e-c382c8bf4c5f.png)

**Comment by llyRayYoung** [comment]
<meta-data android:name="android.max_aspect" android:value="3.4"/>

**Comment by ajwfrost** [comment]
Hi
It may be worth checking where the `max_aspect` meta information is being added into the app descriptor... but with build 889 we're adding a high default value anyway, so I suspect this part is actually okay. Have you checked the values for `stage.scaleMode` and maybe `stage.align`/`stage.displayState`? It may also be worth tracing out values for the `Screen.mainScreen` `bounds` and `visibleBounds` properties..
thanks

**Comment by llyRayYoung** [comment]
Thanks for answering @marchbold @dampgnat    Immersive mode is useful. I set  immersive mode in my ane,  It seemed normal
