### ISSUE TITLE
access to the 'documents provider' API

### ISSUE THREAD

**Issue by EsqualiburDEV** [airsdk/Adobe-Runtime-Support#1994]
Hello
The request concerns an improvement of Air , or if it already exists, just to know how to do it.

On android is it possible to have rights in a folder other than the specific folder of the application.
I found the method indicated by android (https://developer.android.com/training/data-storage/shared/documents-files).

But this implies having access to the 'documents provider', and allowing the user to choose a folder on his tablet.
And to ask for the rights 'Grant access to a directory's contents'.

Is it possible to do this, maybe with the help of a native extension?
Thank you all.

**Comment by marchbold** [comment]
To elaborate here, you can use the Permissions extension to request a user grants access to a directory's contents. (As discussed [here](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory)).

To do this is a matter of calling :

```as3
Permissions.service.openDirectory( "native/path/to/directory" );
```

This will present a dialog for the user to grant access.
