### ISSUE TITLE
Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

### ISSUE THREAD

**Issue by balaedit** [airsdk/Adobe-Runtime-Support#2053]
I was testing the app for push notification but getting the error given in adt.log file.

[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/9275840/adt.log)

Android Studio Version : 
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46)

Air SDK version : 33.1.1.926

Java version : java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

I am sent main to @ajwfrost which contain all files with exported 'AndroidStudioProject' folder in it.

Please check the mail as soon as possible.

**Comment by ajwfrost** [comment]
Hi

So the error log has 3x the line per the bug subject:
```
AndroidManifest.xml Error:
	android:exported needs to be explicitly specified for <receiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.
```
and your `manifestAdditions` section in the push-app.xml file has the final three receivers that don't have the `android:exported` property:
```
                <receiver android:name="com.onesignal.GcmBroadcastReceiver"
                    android:permission="com.google.android.c2dm.permission.SEND">
                    <!-- High priority so OneSignal payloads can be filtered from other GCM receivers if filterOtherGCMReceivers is enabled. -->
                    <intent-filter android:priority="999">
                        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                        <category android:name="air.push" />
                    </intent-filter>
                </receiver>
...
                <receiver android:name="com.onesignal.BootUpReceiver">
                    <intent-filter>
                        <action android:name="android.intent.action.BOOT_COMPLETED" />
                        <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                    </intent-filter>
                </receiver>
                <receiver android:name="com.onesignal.UpgradeReceiver">
                    <intent-filter>
                        <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
                    </intent-filter>
                </receiver>
```

These ones just need to have the exported property, like the `FirebaseInstanceIdReceiver` section has...

**Comment by balaedit** [comment]
Thanks for reply.

The package is now successfully created. But not getting push messages sent from OneSignal. Is there issue in my descriptor file or else. I am sending the full package over the mail with all server key and sender id.

My descriptor file :
[push-app.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/9280180/push-app.zip)

Please help.

**Comment by balaedit** [comment]
The issue is from my side. I got resolved it. Thanks.

Closing the issue.
