### ISSUE TITLE
Error #3672: Buffer creation failed

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#2054]
Using latest air (929) and emulator

[Starling] Context ready. Display Driver: DirectX11 (Standard Extended)

also running with `swf-version=38`

I get either Error
`#3672: Buffer creation failed`
or even the emulator crashes with only
` error: out of memory`
this reproduces every time I click on a popup that works for other people in my team.
@ajwfrost please advise, and i'll be happy to give more logs and info

**Comment by ajwfrost** [comment]
This may be another indication that something's not right with AIR using some recent/updated Direct3D 11 drivers. We'll come back to you to try to find out what's actually going wrong, but can you check that it would work okay if you add a line to your application descriptor file:
```
    <windows><maxD3D>9</maxD3D></windows>
```

See #1963 

thanks

**Comment by shaymolho** [comment]
sure I'll give it a try and update

**Comment by shaymolho** [comment]
also, in another emulator we see it running with direct 9 
`[trace] [Starling] Context ready. Display Driver: DirectX9 (Standard Extended)`

`swf-version=43`
and still we get out of memory error

**Comment by shaymolho** [comment]
@ajwfrost any idea?

**Comment by ajwfrost** [comment]
@shaymolho sorry for the delay, but this sounds like a different issue from that DirectX 11 one... do you see any hints as to buffer creation sizes or similar, if you run with Adobe Scout?

It sounds like it may be trying to allocate buffers that are too large so if you're able to also trace out the size of the pop-up window before it's created (if that's possible?) it could be handy. Am hoping you're not using Flex, so could you confirm how you're creating this pop-up window? is it a secondary NativeWindow object?

thanks

**Comment by eyal-katz** [comment]
@ajwfrost what do you mean by “allocate buffers that are too large” ? 

We’re only uploading ATF (etc2) textures to GPU… 

We’re running plain AIR, no Flex.

This issue suddenly became more prevalent in the last two days - ADLs that ran perfectly fine suddenly started to crash

**Comment by shaymolho** [comment]
the problem was solved by running emulator with adl.exe 64 bit rather than adl.exe 32 bit
