### ISSUE TITLE
Problem creating .aab archive for Android TV

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#206]
Hello,

I have an error message when I add in the app descriptor AndroidTV :
```
<android>
  <manifestAdditions> 
    <![CDATA[ 
      <manifest> 
        <uses-permission android:name="android.permission.PERMISSION_NAME" />
      </manifest>
    ]]> 
  </manifestAdditions>
  <supportsAndroidTV>true</supportsAndroidTV>
  <banner>/assets/mybanner.png</banner>
</android>
```

> Bundle tool failed:[BT:0.10.3] Error: Multiple entries with same key: res/drawable/banner.png=ModuleZipEntry{getZipEntry=res/drawable/banner.png, getZipFile=java.util.zip.ZipFile@b7f23d9, getPathNamesToSkip=0, shouldCompress=true} and res/drawable/banner.png=ModuleZipEntry{getZipEntry=res/drawable/banner.png, getZipFile=java.util.zip.ZipFile@b7f23d9, getPathNamesToSkip=0, shouldCompress=true}
> java.lang.IllegalArgumentException: Multiple entries with same key: res/drawable/banner.png=ModuleZipEntry{getZipEntry=res/drawable/banner.png, getZipFile=java.util.zip.ZipFile@b7f23d9, getPathNamesToSkip=0, shouldCompress=true} and res/drawable/banner.png=ModuleZipEntry{getZipEntry=res/drawable/banner.png, getZipFile=java.util.zip.ZipFile@b7f23d9, getPathNamesToSkip=0, shouldCompress=true}
>         at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190)
>         at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109)
>         at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
>         at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:373)
>         at com.android.tools.build.bundletool.model.$AutoValue_BundleModule$Builder.build($AutoValue_BundleModule.java:267)
>         at com.android.tools.build.bundletool.validation.BundleModulesValidator.toBundleModule(BundleModulesValidator.java:103)
>         at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
>         at java.util.Collections$2.tryAdvance(Unknown Source)
>         at java.util.Collections$2.forEachRemaining(Unknown Source)
>         at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
>         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
>         at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
>         at java.util.stream.ReferencePipeline.collect(Unknown Source)
>         at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:82)
>         at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:208)
>         at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:70)
>         at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)

step to reproduce on Windows :
`adt -package -target aab <signing options> output.aab <app descriptor and files>`

Also tried Beta release of SDK 33.1.0.16. Error preserved

---------------------------
Others problems compilation using aab :

- I have an error message when I have a space in the path project :
> Bundle tool failed:Error while parsing the flags: Syntax error: flags should start with -- (+)

- when I compile the abb file, I have the output.abb file and an other file aab8763711376072635514.aab not deleted.

Thanks

**Comment by pol2095** [comment]
Also tried Beta release of SDK 33.1.0.16. Error preserved

**Comment by pol2095** [comment]
Any news about Android TV banner causes this compilation error ?

**Comment by ajwfrost** [comment]
We've started looking into the AAB code again recently, so will look to check this sort of problem. The main issue with AAB is around the inclusion of resources, and merging the various resources from different sources - it's a completely different structure from the APK mechanism, new Android formats being used.. So we should get to support this, but it may take a bit of time..

**Comment by pol2095** [comment]
I find a default banner in <AIRSDK>\lib\android\lib\resources\app_entry\res\drawable, I add my custom banner in the app desciptor
```
<supportsAndroidTV>true</supportsAndroidTV>
<banner>/assets/mybanner.png</banner>
```
I don't know if it's the thing that causes the error ?

**Comment by Dima107** [comment]
Hi I have similar error. I'm trying to build aab for tests. (It's test empty project without any resources)
"D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\jbr\bin\java" -jar "d:\CodingComponents\air_sdk\lib\adt.jar" -package -target aab -storetype pkcs12 -keystore "d:\build\Clear_X3M\keystore_new.p12"  -storepass <>"d:\build\Clear_X3M\out\game_jbr.aab" "d:\build\Clear_X3M\out\x3m_android.xml" Main.swf
I can't such location in AIR SDK folders: res/mipmap-ldpi-v4/icon.png So I don't know what's wrong

Have we any news about aab?

`Bundle tool failed:WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/D:/CodingComponents/air_sdk/lib/android/lib/bundletool.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[BT:0.10.3] Error: Multiple entries with same key: res/mipmap-ldpi-v4/icon.png=ModuleZipEntry{getZipEntry=res/mipmap-ldpi-v4/icon.png, getZipFile=java.util.zip.ZipFile@1de76cc7, getPathNamesToSkip=0, shouldCompress=true} and res/mipmap-ldpi-v4/icon.png=ModuleZipEntry{getZipEntry=res/mipmap-ldpi-v4/icon.png, getZipFile=java.util.zip.ZipFile@1de76cc7, getPathNamesToSkip=0, shouldCompress=true}
java.lang.IllegalArgumentException: Multiple entries with same key: res/mipmap-ldpi-v4/icon.png=ModuleZipEntry{getZipEntry=res/mipmap-ldpi-v4/icon.png, getZipFile=java.util.zip.ZipFile@1de76cc7, getPathNamesToSkip=0, shouldCompress=true} and res/mipmap-ldpi-v4/icon.png=ModuleZipEntry{getZipEntry=res/mipmap-ldpi-v4/icon.png, getZipFile=java.util.zip.ZipFile@1de76cc7, getPathNamesToSkip=0, shouldCompress=true}
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:190)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:109)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:373)
        at com.android.tools.build.bundletool.model.$AutoValue_BundleModule$Builder.build($AutoValue_BundleModule.java:267)
        at com.android.tools.build.bundletool.validation.BundleModulesValidator.toBundleModule(BundleModulesValidator.java:103)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
        at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.android.tools.build.bundletool.validation.BundleModulesValidator.validate(BundleModulesValidator.java:82)
        at com.android.tools.build.bundletool.commands.BuildBundleCommand.execute(BuildBundleCommand.java:208)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:70)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)`
