### ISSUE TITLE
[AIR 55.0.0.1] Animate trying to use 33.1 namespace

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2147]
## Problem Description
Cannot launch and test application with AIR 55.0.0.1 using Adobe Animate CC. Animate trying to use 33.1 namespace.
After application compilation IDE throws error.

Tested with Adobe Animate CC 20.0.8 for Windows.
The same problem with any AIR project.
It works fine with AIR 33.1.1.929 and earlier.
There is no such issues with VS Code.

Manually changing application descriptor namespace to 50.0 didn't resolve this issue - IDE override it back to 33.1.
Earlier was similar issue: https://github.com/airsdk/Adobe-Runtime-Support/issues/204

## Steps to Reproduce
1) Open Adobe Animate CC, create new one AIR project (or open existing one).
2) Try to test it (or simply press Ctrl+Enter).

**Actual Result:**
Got error:
`error while loading initial content`

**Expected Result:**
Application will be compiled and launched.

## Known Workarounds
1) In AIR SDK foler open file `samples/descriptor-sample.xml` and change 
`xmlns="http://ns.adobe.com/air/application/33.1"`
to
`xmlns="http://ns.adobe.com/air/application/50.0"`
2) Use another IDE.

**Comment by ajwfrost** [comment]
Thanks - hadn't realised Animate used the sample descriptor for that! We've updated it in the code here ready for the next release..

**Comment by itlancer** [comment]
Fixed with latest AIR SDK 50.0.1.1.
Thanks!

But new one related issue came https://github.com/airsdk/Adobe-Runtime-Support/issues/2205
