### ISSUE TITLE
[Windows] A crash occurred with adl.exe (AIR 33.1.1.929)

### ISSUE THREAD

**Issue by Adolio** [airsdk/Adobe-Runtime-Support#2167]
## Problem Description

A crash occurred in `adl.exe` while using `AIR 33.1.1.929`. This software is not using any ANE.

Unfortunately, I don't have much information except this:

![AdlCrash](https://user-images.githubusercontent.com/1126990/192135831-ee78713c-d474-4a89-99da-5b5c590d2388.png)

If you need further details, please tell where can I get them. Thank you

## Steps to Reproduce

N/A

This crash occurred only once. I don't know how to reproduce.

## Known Workarounds

N/A

**Comment by ajwfrost** [comment]
I don't suppose this is reproducible? ah, I guess from your comment, it's not.. 

The crash address is very high - outside of the normal address range (although it's not showing what address the DLL was loaded at, normally we'd hope to see a "0x2400000+0x00f36755" sort of format which gives us the relative address into the library). Which either implies this is in a JIT function, or something has just gone badly wrong and execution jumped into uncontrolled code (but then it's less likely to be trying to access memory at 0x8, that seems like a dereferencing of a null pointer..)

If it does happen again, if you are able to view the disassembly and show the binary machine code a little before and after the problem area, we can then (a) see if that does match any of the actual compiled code, or (b) looks like it was JIT-generated. It may just have been a slight computer glitch changing a bit somewhere though, very tricky to tell I'm afraid!

thanks

**Comment by Adolio** [comment]
Thanks @ajwfrost

It didn't happen again so far so I'm closing the issue for now since I don't have more information to provide.

I will re-open if needed.
