### ISSUE TITLE
onPlayStatus obviously not working

### ISSUE THREAD

**Issue by ramraver** [airsdk/Adobe-Runtime-Support#2193]
For Windows Desktop
Air SDK 33.1.1.929

I just compiled our APP for windows with the latest SDK and noticed that the onPlayStatus event for a netsream does not fire when playing a local video file from the harddrive. It is working fine when loading a video from the web.

Any ideas?

Best
Kai

**Comment by itlancer** [comment]
@ramraver
May be related bug https://github.com/airsdk/Adobe-Runtime-Support/issues/1943

**Comment by ramraver** [comment]
> 

ok, thanks for the hint itlancer. works with NetStream.Play.Stop.
