### ISSUE TITLE
i taked this fault when i publish 32 or 64 bit apk.

### ISSUE THREAD

**Issue by orcuncun** [airsdk/Adobe-Runtime-Support#2194]
![Capture](https://user-images.githubusercontent.com/29103010/194846060-ad401668-243d-44d2-a231-987fe0eb37bf.GIF)

**Comment by ajwfrost** [comment]
Yes, there's a new requirement from Android as it says there, where there needs to be a value explicitly defined for "android:exported" for a receiver. I'm guessing you've customised your AIR application descriptor file to add some `manifestAddition` fields - can you check those and find a `receiver` object, then add the `exported` attribute to it?

**Comment by orcuncun** [comment]
<android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.android.vending.BILLING"/>
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
<application>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" android:enabled="true" android:exported="true" android:permission="android.permission.INSTALL_PACKAGES" >
<intent-filter>
<action android:name="com.android.vending.INSTALL_REFERRER" />
</intent-filter>
</receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:enabled="true" android:exported="false" android:permission="android.permission.BIND_JOB_SERVICE" />
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value=""/>

<provider android:name="com.distriqt.extension.share.content.ShareFileProvider" android:authorities="air.emorgames.slideyblockpuzzle.sharefileprovider" android:grantUriPermissions="true" android:exported="false">
<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/distriqt_share_paths" />
</provider>

<activity android:name="com.distriqt.extension.share.permissions.AuthorisationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<meta-data android:name="com.google.android.play.billingclient.version" android:value="3.0.0" />
<activity
android:name="com.android.billingclient.api.ProxyBillingActivity"
android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
android:theme="@android:style/Theme.Translucent.NoTitleBar" />
<activity 
android:name="com.distriqt.extension.inappbilling.activities.ProductViewActivity" 
android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<receiver android:name="com.amazon.device.iap.ResponseReceiver"
android:permission="com.amazon.inapp.purchasing.Permission.NOTIFY" >
<intent-filter>
<action android:name = "com.amazon.inapp.purchasing.NOTIFY" />
</intent-filter>
</receiver>

<meta-data android:name="android.max_aspect" android:value="ratio_float"/>

<activity
    android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity"
    android:enabled="false"
    android:exported="false"
    android:launchMode="singleInstance"
    android:process=":playcore_missing_splits_activity"
    android:stateNotNeeded="true" />
<activity
    android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
    android:enabled="false"
    android:exported="false"
    android:stateNotNeeded="true"
    android:theme="@style/Theme.PlayCore.Transparent" /> 
<service
    android:name="com.google.android.play.core.assetpacks.AssetPackExtractionService"
    android:enabled="false"
    android:exported="true" />
</application>
</manifest>]]></manifestAdditions>
  </android>

**Comment by orcuncun** [comment]
<android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="com.android.vending.BILLING"/>
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
<application>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" android:enabled="true" android:exported="true" android:permission="android.permission.INSTALL_PACKAGES" >
<intent-filter>
<action android:name="com.android.vending.INSTALL_REFERRER" />
</intent-filter>
</receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:enabled="true" android:exported="false" android:permission="android.permission.BIND_JOB_SERVICE" />
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-6338396748306124~1368851328"/>

<provider android:name="com.distriqt.extension.share.content.ShareFileProvider" android:authorities="air.emorgames.slideyblockpuzzle.sharefileprovider" android:grantUriPermissions="true" android:exported="false">
<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/distriqt_share_paths" />
</provider>

<activity android:name="com.distriqt.extension.share.permissions.AuthorisationActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<meta-data android:name="com.google.android.play.billingclient.version" android:value="3.0.0" />
<activity
android:name="com.android.billingclient.api.ProxyBillingActivity"
android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
android:theme="@android:style/Theme.Translucent.NoTitleBar" />
<activity 
android:name="com.distriqt.extension.inappbilling.activities.ProductViewActivity" 
android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<receiver android:name="com.amazon.device.iap.ResponseReceiver"
android:permission="com.amazon.inapp.purchasing.Permission.NOTIFY" >
<intent-filter>
<action android:name = "com.amazon.inapp.purchasing.NOTIFY" />
</intent-filter>
</receiver>

<meta-data android:name="android.max_aspect" android:value="ratio_float"/>

<activity
    android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity"
    android:enabled="false"
    android:exported="false"
    android:launchMode="singleInstance"
    android:process=":playcore_missing_splits_activity"
    android:stateNotNeeded="true" />
<activity
    android:name="com.google.android.play.core.common.PlayCoreDialogWrapperActivity"
    android:enabled="false"
    android:exported="false"
    android:stateNotNeeded="true"
    android:theme="@style/Theme.PlayCore.Transparent" /> 
<service
    android:name="com.google.android.play.core.assetpacks.AssetPackExtractionService"
    android:enabled="false"
    android:exported="true" />
</application>
</manifest>]]></manifestAdditions>
  </android>

**Comment by orcuncun** [comment]
> Yes, there's a new requirement from Android as it says there, where there needs to be a value explicitly defined for "android:exported" for a receiver. I'm guessing you've customised your AIR application descriptor file to add some `manifestAddition` fields - can you check those and find a `receiver` object, then add the `exported` attribute to it?

i exported .txt file. can you help me please?

**Comment by orcuncun** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/50.0">
  <id>emorgames.hiddenphoto</id>
  <versionNumber>7.32.4</versionNumber>
  <versionLabel>7.32.4</versionLabel>
  <filename>Hidden Photo</filename>
  <description/>
  <name>
  	  <text xml:lang="en">Hidden Photo</text>
	  <text xml:lang="tr">Gizli Fotoğraf</text>
  </name>
  <copyright/>
  <initialWindow>
    <content>hiddenphoto.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    <image192x192>oyunlogosu.png</image192x192>
    <image144x144>oyunlogosu144.png</image144x144>
    <image96x96>oyunlogosu96.png</image96x96>
    <image72x72>oyunlogosu72.png</image72x72>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
 				<uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
				<uses-permission android:name="android.permission.WAKE_LOCK"/>
				<uses-permission android:name="android.permission.AD_ID" />
				<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
<application>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent"/>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<receiver android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" android:enabled="true" android:permission="android.permission.INSTALL_PACKAGES">
<intent-filter>
<action android:name="com.android.vending.INSTALL_REFERRER" />
</intent-filter>
</receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:enabled="true" android:exported="false" android:permission="android.permission.BIND_JOB_SERVICE" />
<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true" android:exported="false" ></receiver>
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-......................."/>

<provider android:name="com.distriqt.extension.share.content.ShareFileProvider" android:authorities="air.emorgames.hiddenphoto.sharefileprovider" android:grantUriPermissions="true" android:exported="false">
<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/distriqt_share_paths" />
</provider>
<activity 
android:name="com.distriqt.extension.inappbilling.activities.ProductViewActivity" 
android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<meta-data android:name="com.google.android.play.billingclient.version" android:value="3.0.0" />
<activity
android:name="com.android.billingclient.api.ProxyBillingActivity"
android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<meta-data android:name="android.max_aspect" android:value="ratio_float"/>
</application>
</manifest>]]></manifestAdditions>
  </android>
  

  
  <extensions>
    <extensionID>so.cuo.platform.admob</extensionID>
    <extensionID>com.mesmotronic.ane.fullscreen</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.Share</extensionID>
    <extensionID>com.google.android.play</extensionID>
  </extensions>
</application>
