### ISSUE TITLE
[AIR SDK 50.0.1.1] adt -version returns 50.0.0.0

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2205]
## Problem Description
`adt -version` returns 50.0.0.0 with AIR SDK 50.0.1.1.
It wrong version. Also it could break some automation and CI processes.
It you try to add AIR SDK 50.0.1.1 to Animate - you will also see wrong 50.0.0.0 version. But with VSCode there is no such issue.

Tested with multiple Windows and Linux devices.
It works fine with AIR SDK 50.0.0.1 and earlier.

## Steps to Reproduce
Execute via command line/Terminal:
`adt -version`
from `AIR SDK 50.0.1.1/bin` directory.

**Actual Result:**
`adt` returns `50.0.0.0`

**Expected Result:**
`adt` returns `50.0.1.1`

## Known Workarounds
none

**Comment by ajwfrost** [comment]
Can't believe we missed this :-(    ... thanks for spotting it!
(Slight clarification = major version is "50" rather than "55", but yes the version should continue with minor = 0, milestone = 1, build = 1...

**Comment by itlancer** [comment]
@ajwfrost, my mistake about "55". Of course, "50" :)
Mistake corrected in description.

**Comment by itlancer** [comment]
Fixed with AIR SDK 50.0.1.2.
Thanks!

**Comment by itlancer** [comment]
Issue returns with AIR SDK 50.0.1.3.
It returns 50.0.1.2.

**Comment by itlancer** [comment]
Fixed with AIR SDK 50.1.1.1.
Thanks!
