### ISSUE TITLE
Package with captive runtime fails on MacOS

### ISSUE THREAD

**Issue by sebastianLIFEtool** [airsdk/Adobe-Runtime-Support#2206]
### Problem Description

After using the Flex/AIR SDK with IntelliJ successfully for many years on Windows, we require to package one of our applications for MacOS. However, I ran into the following issue when packaging the application with a captive runtime on MacOS:

```
unexpected failure: Copy failed java.io.IOException:
Copy failed at com.adobe.air.nai.MacPackager.copyWithPermissions(MacPackager.java)
at com.adobe.air.nai.AppBundlePackager.assembleInternalFiles(AppBundlePackager.java)
at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java)
at com.adobe.air.nai.AppBundlePackager.createPackage(AppBundlePackager.java)
at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
at com.adobe.air.ADT.run(ADT.java)
at com.adobe.air.ADT.main(ADT.java)
```

The application works fine, when I run it from inside the IDE and I am also able to package an IPA file for iOS.
Packaging a native installer (.dmg) also works, but I need the captive runtime.
I have used the `$ xattr -d -r com.apple.quarantine` command on both the Flex/AIR SDK and my own project files.
To verify that the issue is not connected to the application I created a new one but the issue persists.

Here is the output from the adt.log

```
*** ADT Logging at 2022/10/19 09:00:20 ***
Called by: /Users/MacUser/Documents/Actionscript/_SDKs/Flex 4.16.1 - Air 33.1/lib/adt.jar
ADT 33.1.1.929 called with: -package -storetype PKCS12 -keystore /Users/MacUser/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/flex/lib/temp_keystore.p12 -storepass xxxxxx -tsa none -target bundle /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/Main.app /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/Main-descriptor.xml -C /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest Main.swf
Creating temporary AIR package at /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/air2420439735261588354.tmp
Converting AIR file:  /Users/MacUser/Documents/Actionscript/_SDKs/Flex 4.16.1 - Air 33.1/lib/nai/bin/naip -convert /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/air2420439735261588354.tmp /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/adt10504121156639164444.tmp/temp
Unexpected failure: Copy failed
```

Here are the tools I used:
* Flex 4.16.1 with AIR 33.1.1.929
* IntelliJ 2022.2.1 (I use the temporary self-signed certificate provided by IntelliJ)
* MacOS Monterey 12.6

### Steps to Reproduce
Create a new Flex/AIR Desktop App in IntelliJ and use "Package AIR Application..."

### Known Workarounds
none

Hopefully someone is able the help me resolve this issue, since I am all out of ideas.

Thanks in advance
Sebastian

**Comment by ajwfrost** [comment]
Hi

At this point it's just doing an `rsync -a` to copy some of the template/runtime files into your "Main.app" bundle. So it's worth checking
- your user account has full write access to create the "Main.app" file in that given folder (which it must have really otherwise the `naip` process would have failed) - and maybe if this failure has left a `Main.app` folder there, can you run `find Main.app` so we can see whether it has a file under `Contents/MacOS/Main` and/or a folder under `Contents/Frameworks/Adobe AIR`?
- your user account has full read access to the file `/Users/MacUser/Documents/Actionscript/_SDKs/Flex 4.16.1 - Air 33.1/lib/nai/lib/CaptiveAppEntry`
- your user account has full/recursive read access to the folder `/Users/MacUser/Documents/Actionscript/_SDKs/Flex 4.16.1 - Air 33.1/air-captive/mac/Adobe AIR.framework`

I am wondering whether this may be a permissions thing whereby Java and/or rsync haven't been granted permissions to access the relevant files by the security system in Monterey. So if you try manually running those commands it may trigger a permissions check, which should then unblock the ADT process to do the same..

thanks

**Comment by ajwfrost** [comment]
Ah - and I just noticed that you're running this via Intellij? which may also impact the permissions.. so if you can try the packaging from the command line too it may throw up a message:
```
/Users/MacUser/Documents/Actionscript/_SDKs/Flex\ 4.16.1\ -\ Air\ 33.1/bin/adt -package -storetype PKCS12 -keystore /Users/MacUser/Library/Application\ Support/JetBrains/IntelliJIdea2022.2/plugins/flex/lib/temp_keystore.p12 -storepass xxxxxx -tsa none -target bundle /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/Main.app /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest/Main-descriptor.xml -C /Users/MacUser/Documents/Actionscript/MacOSTest/out/production/MacOSTest Main.swf
```
(you'd need to replace the `xxxxxx` bit with the real password..)

**Comment by sebastianLIFEtool** [comment]
Thanks to you, I was able to resolve the issue.

The reason is kind of embarrassing. As it turns out the `Flex 4.16.1 - Air 33.1/air-captive/mac/Adobe AIR.framework` was missing from the SDK. When I tried to set up an ANE for MacOS project in Xcode I wanted to copy the `Adobe AIR.framework` there, but as it turns out, I did not copy but move it.

Thank you very much!

Now I can try to get my MacOS ANE to work :)

Best regards
Sebastian

**Comment by ajwfrost** [comment]
Good to know, thanks for confirming!
As ever, there's probably more that we could add into ADT to do error checking and help find issues quicker by highlighting things! Weirdly, in the code, it would have alerted you specifically if that 'CativeAppEntry' binary was missing, but it calls the copy request for the framework without the similar test first...

**Comment by sebastianLIFEtool** [comment]
More detailed error messages would alway be appreciated but I understand that adding these is a Herculean task.
However I think the SDK and tools are moving in a good direction. Keep up the good work.

Thanks again
Best regards
Sebastian
