### ISSUE TITLE
Problems to compile for IOS in OSX 10.15.7 Catalina with new SDK 5.0.1.1

### ISSUE THREAD

**Issue by giucer** [airsdk/Adobe-Runtime-Support#2212]
Hi this is te content of the terminal window when i start the compilation process:

giucer@Giuseppes-Mac click % ./ios_compile_app-store.sh
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
Error during native code-signing. Output of codesign tool is:
error: The specified item could not be found in the keychain.

this is the compilation command script:
adt -package -XnoAneValidate -target ipa-app-store -useLegacyAOT no -storetype pkcs12 -keystore ios_distribution.p12 -storepass simplypassword -provisioning-profile Click_Distribution.mobileprovision Click.ipa bin-release-temp/Click-app.xml -C bin-release-temp Click.swf Assets.car Default.png Default@2x.png Default-568h@2x.png Default-Portrait.png Default-Portrait@2x.png Default-Landscape.png Default-Landscape@2x.png assets -extdir ext/

I don't undertstand why I have this code-signing error.....

**Comment by ajwfrost** [comment]
So once you hit a certain Java level, we switch to using the native "codesign" command for the iOS code-signing requirements. And the system is saying that there is no equivalent certificate in your Keychain for the "ios_distribution.p12" certificate...

Options would be either to import that from the Keychain menu (you should be able to import the p12 file directly I believe?), or if you can set up the environment to use Java 11 (or anything earlier than 16) it may revert to the internal code-signing capabilities..

thanks
