### ISSUE TITLE
Captive runtime not compatible with macOS Ventura

### ISSUE THREAD

**Issue by johnou** [airsdk/Adobe-Runtime-Support#2236]
## Problem Description

Describe your problem in detail. Include the following information:

The AIR application fails to run on macOS Ventura.

![Ff8BvZOXgAsMRJe](https://user-images.githubusercontent.com/323497/198009533-49abdaa8-6288-4f04-8296-559417671792.jpg)

(Habbo is damaged and can’t be opened)

* Which AIR SDK did you use? 

33.1.1.821

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?

We have a lot of players reporting that they cannot use our application with the latest macOS update (Ventura).

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.

Give us a minimal example:

* As little code as possible. Get to the root of the problem!
* As few dependencies as possible. Did the problem pop up with Feathers? Try to reproduce it with Starling only.
* Remove any ANEs (except if they are vital for the problem).
* Include all necessary files (e.g. textures).

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by johnou** [comment]
Has anyone else ran into this or tried their captive applications on macOS Ventura? I can provide more information once my company approves upgrades.

**Comment by johnou** [comment]
![Screenshot_2022-10-27-08-21-23-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/323497/198206662-6a7464b0-a118-4ba1-a8b3-eac7d6f0aadc.jpg)

Might have something to do with packaging and / distribution, note the small text the file was downloaded on an unknown date.

**Comment by ajwfrost** [comment]
Likely to be a code signing issue I would think. If this was packaged as a captive runtime app, did you then code sign it using ADT or in some other way? Was it notarised or is this distributed via the App Store?

**Comment by johnou** [comment]
@ajwfrost wow I almost regret looking :) we are using https://github.com/tuarua/WebViewANE/blob/master/mac_installer/sign_developerId.sh at the moment but I believe we have replaced WebViewANE with StageWebView.. what is the recommended approach for signing + notarise with ADT?

**Comment by ajwfrost** [comment]
Hmm, not sure why that script doesn’t work - normally if you submit an app (zipped) for notarization it would tell you what the problems are..

See if the below helps?
https://airsdk.dev/docs/tutorials/platform/macos/creating-macos-pkg-files

**Comment by johnou** [comment]
that's what is really throwing us off, the application is notarised and works without problems on Monterey.

**Comment by johnou** [comment]
Works with latest SDK + removal of application.xml modification + addition of allowMultipleInstances.

**Comment by ajwfrost** [comment]
Belatedly coming back to this one - not sure whether the change in behaviour was based on any one of those three changes you mention? I actually had this same error message when running an app distributed with captive runtime but that was because I'd downloaded it from the internet .. I had to remove the 'quarantine' extended attribute and then it worked fine. Gatekeeper gets a bit over-active (and doesn't necessarily give very useful information when it blocks things..)

thanks

**Comment by ajwfrost** [comment]
Ah, yes, if you modify the application.xml then the code signature for this resource would become invalid...
