### ISSUE TITLE
Linux drag file over Air app crash

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#2243]
## Description

when I drag a file (icon) over an Air app, the Air app crash.

A support of [drag-in](https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7d83.html) and [drag-out](https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7d84.html) gesture is necessary on Linux, if not possible please fix the crash.
* AIR SDK 50.0.1.1
* Ubuntu 22.04 and Fedora 36

## Steps to Reproduce

![Capture d’écran du 2022-10-27 18-17-45](https://user-images.githubusercontent.com/6962232/198346082-bc40c2e7-ede4-4b5f-8607-abdf5716974f.png)

adt return this messsage :

```
Application crashed with an unhandled SIGSEGV
Crashlog has been dumped in /tmp/airCrashLogs/1027_1124_UZT2a5
```

## Known Workarounds

no workaround.

**Comment by ajwfrost** [comment]
Hi -> still not able to reproduce this here, using Ubuntu 22. Can you please share the SWF file and app descriptor - are you running via ADL? or from an app bundle with captive runtime? And are you just dragging the file into the SWF, do you have to release the mouse button or does it crash immediately you enter the area? Is the file you're dragging a text file, or binary, and/or empty?

If you can provide a crash dump file that would also be handy?

thanks

**Comment by pol2095** [comment]
I'm just dragging the file into the SWF and it crash immediately you enter the app window, the bug occur with alls files type.
You can download it [here](http://pol2095.free.fr/Linux/app_drag_file.zip)

**Comment by ajwfrost** [comment]
Yes, sorry for the delay -> it seems that this is only an issue when running from the 'installed application' binary rather than when running from ADL, even though there's not a huge amount of difference in those wrappers - the crash itself happens in the main AIR runtime library, and it's an STL failure when allocating memory.
We've been trying to see why this is happening, it may just be a GCC error - we'll build with a newer version to see if that changes things. Plus we can always rework the code to get rid of STL..

**Comment by pol2095** [comment]
Thanks, I have the same issue using ADL.

**Comment by ajwfrost** [comment]
Hmm.. that's kind of good, though weirdly it only happened for us when using the installed app. Anyway -> turns out it's specific to the `std::deque` template. Switching the functionality over to use `std::vector` appears to have got rid of the problem!

**Comment by pol2095** [comment]
is-it possible to test it ?

**Comment by ajwfrost** [comment]
Sure -> please check https://transfer.harman.com/message/Hgnh6X2q9lgnKOdLZSSfbd
thanks

**Comment by pol2095** [comment]
The app doesn't crash now but [drag-in](https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7d83.html) and [drag-out](https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7d84.html) seems not working.
