### ISSUE TITLE
iOS, 50.0.1.1: Text to XML strange error, not happening in interpreter mode or older SDK versions.

### ISSUE THREAD

**Issue by PippoApps** [airsdk/Adobe-Runtime-Support#2252]
## Problem Description

SDK 50.0.1.1
iOS, running on an iPad.

Application loads an internal XML at startup.
Debugging in interpreter mode everything works fine.
Debugging in test mode (or AdHoc) I get this weird error when converting to XML:

`TypeError: Error #1034: Type Coercion failed: cannot convert XML@1084066d1 to Walker.`

convert to... "Walker"?!? Really weird...
XML is well formed. It all works in interpreter mode.
It works in previous versions of SDK.

Code to convert XML:
```
		public static function getXML				(s:String):XML {
			var x								:XML = new XML();
			x.ignoreWhitespace 					= true;
			x								= XML(s);
			return							x;
		}
```

Cheers

**Comment by itlancer** [comment]
@PippoApps, you need to patch latest AIR SDK: https://github.com/airsdk/Adobe-Runtime-Support/issues/2210#issuecomment-1286007233

**Comment by PippoApps** [comment]
> @PippoApps, you need to patch latest AIR SDK: [#2210 (comment)](https://github.com/airsdk/Adobe-Runtime-Support/issues/2210#issuecomment-1286007233)

Perfect!
cheers
