### ISSUE TITLE
The adobe air sdk reads the acceleration sensor. How can it be closed

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#2259]
1.Get device sensors
air.yttx.android.mi.AppEntry.onCreate(AppEntry.java:269)<---android.app.Activity.performCreate(Activity.java:7070)<---android.app.Activity.performCreate(Activity.java:7061)<---android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)<---android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3067)<---android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3191)<---android.app.ActivityThread.-wrap11(Unknown Source:0)<---android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.app.ActivityThread.main(ActivityThread.java:6843)<---java.lang.reflect.Method.invoke(Native Method)<---com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)<---com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

2.Monitoring sensor
android.app.Activity.performResume(Activity.java:7178)<---android.app.ActivityThread.performResumeActivity(ActivityThread.java:3891)<---android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3956)<---android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3197)<---android.app.ActivityThread.-wrap11(Unknown Source:0)<---android.app.ActivityThread$H.handleMessage(ActivityThread.java:1921)<---android.os.Handler.dispatchMessage(Handler.java:106)<---android.os.Looper.loop(Looper.java:164)<---android.app.ActivityThread.main(ActivityThread.java:6843)<---java.lang.reflect.Method.invoke(Native Method)<---com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)<---com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

We do not need to obtain the user's sensor status. How can we turn off the function of obtaining sensor status? Our app was rejected by the app store in Chinese Mainland because of this.In Chinese Mainland, the permission requirements for applications are very strict, which requires the user's permission before using the API.

**Comment by wmtj** [comment]
I have the same problem too. 

In the latest regulations of mainland China, the app can initialize the various sensors only after the user has clicked to agree to the privacy policy, otherwise, it will be considered illegal. The relevant government departments regularly inspect the apps in each app store to protect users' privacy. If these violations are detected, the app will be removed from app store ...

@ajwfrost Please fix the issue ASAP.

**Comment by ajwfrost** [comment]
Hi

If it's the acceleration sensor being read in order to handle the auto-orientation capability, then you can disable this already, see #2014 

But this doesn't have quite the same call stack.. do you know what actual APIs are forbidden here?

See also #2161 where there's another listener that we have, for telephony .. we can disable this perhaps. But again, for both of these bits of capabilities, you're just losing functionality. Per the above it sounds like you may want to get them back again once you've asked the user..? If so, it could be challenging.

Do you know whether any of these capabilities are covered by the normal Android permissions requirements? or is this going above any beyond that..?

thanks

**Comment by wmtj** [comment]
@ajwfrost 
To solve the issue, I think you should find out all the reference of acceleration sensor initialization code in AIR SDK. Add a new API that controls whether or not acceleration sensor initialized, so that app developers can add code to the "Agree" button on the privacy policy pops up window. If app user clicks the "Disagree" button, the AIR SDK does not invoke the sensor initialization code.

My apps has been removed from all Android stores in mainland china for months due to this issue.   :(

**Comment by ajwfrost** [comment]
Okay thanks, so it's about invoking that code, but it's okay to invoke it if the user has agreed to some privacy policy which would be an app-specific thing... so I think perhaps we need an application setting to control this, for example:

- new app descriptor option that would be used to disable any hardware/sensor APIs call by default
- new API that the application can call once they've displayed the privacy policy to the user and got their permission; if this is called, AIR adds a flag into a config file in private app storage to remember this fact
- then at start-up, the AIR behaviour is that we check for the existence of the new app descriptor option: if this is present, we then check for the flag in the config file: if the flag isn't there then we avoid calling any hardware/sensor APIs (but if the app descriptor option is missing, or if the config file flag is set, then we start up as we do now).

Hope that workflow would be appropriate! We may need to guess at the forbidden APIs a little..

**Comment by wmtj** [comment]
> Okay thanks, so it's about invoking that code, but it's okay to invoke it if the user has agreed to some privacy policy which would be an app-specific thing... so I think perhaps we need an application setting to control this, for example:
> 
> * new app descriptor option that would be used to disable any hardware/sensor APIs call by default
> * new API that the application can call once they've displayed the privacy policy to the user and got their permission; if this is called, AIR adds a flag into a config file in private app storage to remember this fact
> * then at start-up, the AIR behaviour is that we check for the existence of the new app descriptor option: if this is present, we then check for the flag in the config file: if the flag isn't there then we avoid calling any hardware/sensor APIs (but if the app descriptor option is missing, or if the config file flag is set, then we start up as we do now).
> 
> Hope that workflow would be appropriate! We may need to guess at the forbidden APIs a little..

I think it would be a good solution.

**Comment by ajwfrost** [comment]
Hi @pengyangjin, @wmtj - please try using https://airsdk.harman.com/download/50.1.1.1 with a new flag in the app descriptor file, `<disableSensorAccess>` under the `<android>` section..

thanks

**Comment by wmtj** [comment]
Thank you and your team for the hard work. @ajwfrost 
I need some time to complete the AIRSDK 33.1 to 50 upgrade and then validate the 'disableSensorAccess' feature.

**Comment by ydkgame** [comment]
![image](https://user-images.githubusercontent.com/3896827/207235288-1ee42005-6d36-4972-995c-c89074e8a98f.png)
![image](https://user-images.githubusercontent.com/3896827/207235336-c19810f2-5789-4068-ae3a-994cff542259.png)
I still have this problem after using the latest AIR 50.1.1.1 release. How can I find out if I have successfully disabled it?

**Comment by ajwfrost** [comment]
That should have done it .. unless something went wrong in the parsing to get at that 'disableSensorAccess' value, it shouldn't have triggered that OrientationEventListener.

We'll have to add a bit of diagnostics in here I think...

**Comment by yutfa** [comment]
> ![image](https://user-images.githubusercontent.com/3896827/207235288-1ee42005-6d36-4972-995c-c89074e8a98f.png) ![image](https://user-images.githubusercontent.com/3896827/207235336-c19810f2-5789-4068-ae3a-994cff542259.png) I still have this problem after using the latest AIR 50.1.1.1 release. How can I find out if I have successfully disabled it?

<android>
        <manifestAdditions><![CDATA[
---
]]></manifestAdditions>
		<disableSensorAccess>true</disableSensorAccess>
    </android>

I think this is the right configuration.

**Comment by ajwfrost** [comment]
Hi - can you extract the file from the below zip into your AIR SDK folder "lib/android/lib" and rebuild, then run it up on a device and get the logcat output? We should then be outputting some information under a tag "AdobeAIR" that will show what's happening...
thanks
[runtimeClasses.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10278209/runtimeClasses.zip)

**Comment by pengyangjin** [comment]
> 那应该已经完成​​了..除非在解析获取“disableSensorAccess”值时出现问题，否则它不应该触发该 OrientationEventListener。
> 
> 我想我们必须在这里添加一些诊断......

when i set <disableSensorAccess>true</disableSensorAccess> and the <aspectRatio>landscape</aspectRatio> can not work.
I hope Air SDK doesn't call sensors,but the app can display landscape. I current used Air SDK version is 50.2.2.2
