### ISSUE TITLE
MacOS malicious software issue

### ISSUE THREAD

**Issue by barisyild** [airsdk/Adobe-Runtime-Support#2263]
## Problem Description

"ApplicationName" can’t be opened because Apple cannot check it for malicious software.

I get this error when I run my application on other computers.
I sign it app file with the Developer ID Application certificate, add it to the dmg and share it with another computer.

* AIR SDK 50.0
* Mac OS Monterey

**Comment by ajwfrost** [comment]
Sounds like you're missing the step of notarising the DMG file?
See https://airsdk.dev/docs/tutorials/platform/macos/creating-macos-pkg-files#notarize-your-pkg-file (in your case you have a dmg rather than pkg but the same approach can be used)

thanks
