### ISSUE TITLE
Air Apps continuously triggering AIR EULA on M1 Mac

### ISSUE THREAD

**Issue by newhampshirejj** [airsdk/Adobe-Runtime-Support#2265]
I just received a new M1 Macbook Pro and none of my Air apps run anymore. I've tried other example apps online and they all do the same thing. 

Even checking 'Open using Rosetta' doesn't help.  

When running any AIR app, it kicks open the Adobe AIR Installer app and presents me with the EULA. When I click accept, it just shuts down the AIR Installer and my app.  I've been banging around at this for a couple hours and hope someone can help.  Is this also a known issue? I looked here but didn't find anything.

macOS Monterey (12.3)
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Max
Memory 32 GB

**Comment by ajwfrost** [comment]
Which version of AIR are you running? If they're HTML-based, you would need to be using 33.1.1.744 or thereabouts..
Can you see the "Adobe AIR Installer" application under /Applications in the Finder?

There's a log file that might give more clues, if you look under your user's "Library/Application Support/Adobe/AIR" folder, called "install.log"?

thanks

**Comment by newhampshirejj** [comment]
Hi Andrew, thanks.  I installed the latest from here: https://airsdk.harman.com/assets/downloads/33.1.1.744/AdobeAIR.dmg 

33.1.1.744 

Just got this new mac today from work to replace my 2018 model which of course works fine.

The "Adobe AIR Installer" is in my Applications. AIR itself seems to install fine. Just running any AIR apps triggers the installer to pop back open and prompts me w/ the EULA again. Once accepting it, it goes away, as does my app (they both close).

The interesting this is that in my personal Library/Application Support/Adobe folder i do not have an AIR folder. And no install.log that I can find.

When I try to reinstall and run the Adobe AIR Installer.app again, I accept the EULA and then it pops up an 'Adobe AIR Installer' window where it says 'Adobe AIR installer is trying to install a new helper tool.' And then prompts me to put in my password. Then I click 'Install Helper' button.  Then I get a pop up that says 'Adobe AIR - Installation completed. Adobe AIR has been successfully installed.'.  I click the Finish button.  Everything looks great.  But then I can't run the app. It keeps popping up the Adobe AIR / Harman license agreement.

Thanks for any guidance.

JJ

**Comment by newhampshirejj** [comment]
Sorry, I forgot to mention I also tried the one from the other link on the Harmon page: 33.1.1.932.  
https://airsdk.harman.com/assets/downloads/AdobeAIR.dmg

They both behave the same way for me.  I've restarted multiple times, etc. Brand new machine.  I updated a few patches up to 12.6.1 of Monterey but that didn't seem to help anything. My other laptop is running an older version but it's an Intel machine and it's fine.

**Comment by ajwfrost** [comment]
This sounds quite strange, the only thing I'm wondering is whether there's an access problem where the app is trying to write the fact that you've accepted the EULA, but failing.. which may be a new Monterey access restriction (even though it's all within Library/Application Support).

Can you try perhaps creating that folder manually..? i.e. open a terminal window and then type:
```
mkdir -p ~/Library/Application\ Support/Adobe/AIR
chmod a+w ~/Library/Application\ Support/Adobe/AIR
```
and then try it again, and see if anything appears in that folder? To check the installer.log, can you try running any .air file or similar so that it tries to install an app? - or even just launching the "Adobe AIR Installer" where it will ask you to uninstall, and then cancelling it, should result in an install.log file being written there..

**Comment by newhampshirejj** [comment]
Yep! Andrew that did it!  So interestingly enough, I could not create the folder through that Terminal command. I had to do it just by going into my own Library in Finder. When I tried to create it, it DID prompt me to authenticate w/ my password. Once I did that, the AIR folder was now there.   I DID run the second permissions update terminal command you provided before I tried to open my AIR app and that was successful. I'm not sure if that was actually needed or not (can't really tell at this point) but now when I launched my app for the first time, it again prompted me for the AIR EULA but once I accepted, it went away and the app now opens fine and opens fine on subsequent attempts.  So at least now I have it working and know what the possible workaround is.  Thanks so much for your help on this.  It is very much appreciated!!!

**Comment by ajwfrost** [comment]
Glad to hear it. It sounds from the description as if the "Library/Application Support" folder wasn't set up with the right permissions, which meant AIR kept failing to log the fact you'd accepted the EULA (hence repeatedly asking), and maybe it threw an exception when it found it couldn't..

**Comment by newhampshirejj** [comment]
Yep. Certainly sounds like that was the issue. Again, a sincere thank you for your assistance in getting me back up and running!
