### ISSUE TITLE
AIR 50.0.1.1 is reported as 50.0.0.0 in Animate

### ISSUE THREAD

**Issue by PippoApps** [airsdk/Adobe-Runtime-Support#2269]
Hello there,
installed 50.0.1.1
Animate recognizes it as 50.0.0.0, on both Win and Mac
![image](https://user-images.githubusercontent.com/29799572/200173284-08a5b143-213f-47d0-8462-7edd24023cd9.png)
Not a big deal, but you might want to know.

Thx

**Comment by ajwfrost** [comment]
Yes we had an issue in ADT which returned that value .. will be fixed in our next build
This is already reported in #2205  hence closing this one as duplicate.

thanks
