### ISSUE TITLE
Support specifiying java version in ADT

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#2281]
Currently ADT requires java 8/11 to run and the java version is being evaluated from the JAVA_HOME system property. It would be nice to have a way to specify which java to run regardless of JAVA_HOME, something like --jdk path-to-jdk flag to ADT or alike.
What do you guys think?

**Comment by marchbold** [comment]
Have you tried setting the java path in adt.cfg? Should serve this purpose already.

**Comment by shaymolho** [comment]
will try, thanks
