### ISSUE TITLE
AIR SDK 33.1.1.935 - ipa packaging issue with error code 0xe8008015 "ApplicationVerificationFailed"

### ISSUE THREAD

**Issue by isungiot** [airsdk/Adobe-Runtime-Support#2282]
## Problem Description

* Used : **AIR SDK 33.1.1.935**
* for iOS with iPhone and iPad
* I can reproduce this issue.
* Build Env : macOS Ventura 13.0, IntelliJ IDEA Ultimate 2019.2, AIR SDK 33.1.1.935, iPhone XR

## Steps to Reproduce

* Case 1
  - Build Project (succeeded), and Run with iPhone device
  - After trying to "Installing iOS Package", An error message is occurred as below
---------------------------------------------------
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/SIGNEON.app/SC_Info/SIGNEON.sinf in archive!
**ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UU7ewd/extracted/Payload/SIGNEON.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)**
---------------------------------------------------

* Case 2
  - When "Pakcage AIR Application", target ipa file is made.
  - Uploading to TestFlight, it is okay.
  - But, when I install it with test device, all devices are failure. Maybe it is a same issue with 0xe8008015 Provisioning Profile issue.
 
* Case 3
  - For checking ipa file, I tried to install with "Apple Configurator" onto iPhone.
  - Target application is transported to iPhone, but it is failure to install with a message "Unable To Install 'Appname' this app cannot be installed because itss integrity could not be verified".
 
After unpacking ipa file and compare between mobileprovision file I used (for distribution) and embedded.mobileprovision, they are perfectly same.
Also I compared Entitlement parameters between my project configuration and mobileprovision file, it also same and set for production.
I've seen some similar issue reports on other threads, so I tried almost method and applied another version of AIR SDK from 33.1.7xx to 50.0.1.1, all result are same with 0xe8008015.

Attached file is adt log file when a case 1 is occurred.
[adt_0xe8008015_20221108.log](https://github.com/airsdk/Adobe-Runtime-Support/files/9961658/adt_0xe8008015_20221108.log)
(I hope to upload my ipa file, but there are no option to upload ipa type on this thread...)

Would you please let me know how to fix this issue?

**Comment by isungiot** [comment]
Dear All.

Is anybody to follow this issue? My progress to develop this app is now pending because of this issue...
I really want to know how to fix this issue.

**Comment by ajwfrost** [comment]
The error message is saying that the provisioning profile is invalid; this usually means that the profile does not list the certificate used, or doesn't have an app id that matches the app. Are you able to check the profile?

If you do zip up the IPA file you should then be able to upload it and we can check out the code signature and embedded profile further to see if there's anything we can spot..

thanks

**Comment by isungiot** [comment]
Dear Andrew.

Thanks for your response.
I attached my IPA file. (Please use this dropbox link to download because my ipa file size is over than 25MB...)

**<DOWNLOAD : https://www.dropbox.com/s/2zkzjbv50sevhlf/IotSignageClient.ipa.zip?dl=0 >**

Also I've checked all App ID, Certifications and Provisioning Profile, it seems it don't have any problem. With same Certification and to provide same procedure of provisioning profile for another application (to be used Objective-C with XCode), it works properly with my Distribution Certification and Profile.

Would you please make sure attached IPA file what is a problem?

-BRs, Simon

**Comment by isungiot** [comment]
> <DOWNLOAD : https://www.dropbox.com/s/2zkzjbv50sevhlf/IotSignageClient.ipa.zip?dl=0 >

Dear Andrew.

Is any update for this issue? I already share a link to download zipped ipa file of mine. Because of sharing external link, the file size is over than 25MB and it cannot upload to here directly.

I'm sorry to push you, but I'm in a very critical situation right now.
Would you please let me know your anaylzing result ASAP?

-BRs.

**Comment by ajwfrost** [comment]
Hi

I've just been looking at this .. and really can't see any problems. My first thought was a mismatch between the application identifier and the provisioning profile, but that all matches. The team ids, permitted app ids, etc all matches.

The signature data on the end of the binary all looks fine from what I can see, and matches the certificate embedded within the provisioning profile.

But I'm getting the same error as you see, when trying to install this on iOS: `A valid provisioning profile for this executable was not found`

So I'm afraid I can't see anything wrong with this binary. My only suggestion might be to use Xcode and create a quick/empty application using the same name and app identifier, sign it (with same certificate and provisioning profile) and export via Xcode to get the IPA and then see if that IPA can be installed. If it can, please send us that package, and we can do a binary comparison to see what the difference may be...

thanks

**Comment by marchbold** [comment]
Looks like you have production entitlements enabled there, are you using a debug provisioning profile to install locally? If so you should have aps-environment set to development and get-task-allow set to true.

Generally you cannot install an app-store production ipa directly to a device. You need to use a development / debug version.

**Comment by isungiot** [comment]
> Generally you cannot install an app-store production ipa directly to a device. You need to use a development / debug version.

Dear Andrew.
I'm not sure about that. I can install with app-store production ipa to use TestFlight for final testing. I already tested several other apps.
Also I tried to use development certification and provisioning, but same result.

**Comment by isungiot** [comment]
> So I'm afraid I can't see anything wrong with this binary. My only suggestion might be to use Xcode and create a quick/empty application using the same name and app identifier, sign it (with same certificate and provisioning profile) and export via Xcode to get the IPA and then see if that IPA can be installed. If it can, please send us that package, and we can do a binary comparison to see what the difference may be...

Dear Andrew.

I tried to dummy XCode project, but I got an error "Provisioning profile "provisioning file" doesn't include signing certificate "Apple Distribution: ~~`". when I loaded downloaded provisioning profile. I think it is a reason, but I don't know how to get a right provisioning profile from Apple Developer.
For using Distribute / Developer Certificate via p12key and Provisioning Profile, I just proceeded as below
1. Make CSR via developer account
2. Make Certification (iOS or Apple Developer/Distribution), download and install to my Mac
3. Export p12key files from keymanager
4. Set Provisioning Profile with each key and AppID, download it
5. Set IntelliJ to those Provisioning Profile and Key pair --> Packing
Is any wrong procedure I set certification?

**Comment by ajwfrost** [comment]
So your signing certificate is "iPhone Distribution: ...", it's issued by "Apple Worldwide Developer Relations Certification Authority" and it's a little difficult to check that this is the right one (they change from time to time..). But your provisioning profile should show that it's for the App Store, and should list that "iPhone Distribution" certificate in it, when you look at it within the Apple developer portal.

If you set Xcode to manually manage the signing process, it should be possible for you to select the team, profile and certificate here..?

If the last time you did this was 3 years ago, you may be coming up against the fact that Apple's intermediate certificates changed, which I think would mean you have to re-generate a distribution certificate..

thanks

**Comment by isungiot** [comment]
Dear Andrew.

I delete all certificates and profile both my macbook and Apple Developer Cert/Ident/Profile center.
Also all sub-cert are updated, all distribute and develop cert/profile are re-generated now.
I tried to show this new Distribute Provisioning Profile on XCode (just checking), it shows an error "Provisioning profile doesn't include signing certificate "iPhone Distribution: <My Team Name (My Team ID)>".". I really don't understand why... this profile is selected a correct iOS distribution certification I re-generated... Now I'm very confuse...

**Comment by ajwfrost** [comment]
Did you edit the provisioning profile in the portal, to include the new certificates, and then re-download it to the mac/xcode?
thanks

**Comment by isungiot** [comment]
> Did you edit the provisioning profile in the portal, to include the new certificates, and then re-download it to the mac/xcode? thanks

Of course. I include the new certification to edit profile. Also I tried to generate a new profile, all cases are same...
One another test, when I archive another application via XCode, its distribution profile is not generated but uploaded to AppStoreConnect... There are no Apple Distribution Certification, but auto-generated "Apple Distribution Managed"(not downloadable). Also I just open embedded.mobileprovision file of this XCode app, it seems 2 data are there in the array of key "DeveloperCertificates"...
When I make provisioning profile from portal, it always has just one DeveloperCertificates data.
I think it is some different procedure between XCode auto gen and manual gen of portal for distribution.

**Comment by isungiot** [comment]
Dear Andrew.

I tried again to make/distribute dummy app by XCode to use exported Certification/Provisioning Profile, then it was same failure when I tried to install via TestFlight.
Also I tried to use Auto-Certification via XCode, it also same failure.

So, I need to approach what is a root cause.

-BRs, Simon

**Comment by isungiot** [comment]
Dear Andrew.

Now I tested to set a new app (new bundle ID), the certification is is no more occurred.

So, I close this issue.

Thanks for your cooperation.

-BRs, Simon
