### ISSUE TITLE
Compilation Error, Undefined symbols

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2292]
## Problem Description
Air SDK 50.0.1.2
Compilation failed while executing : ld64
Packaging output: 
Undefined symbols for architecture arm64:
  "__ZN9CSWFDecen13NeedsMoreDataEPKhS1_jPj", referenced from:
      __ZN12ScriptPlayer11PushDataBufEPKhiPbb in libRuntimeHMAOT.arm-air.a(splay.o)
ld: symbol(s) not found for architecture arm64

Please help to fix this and include the iOS 16 into the SDK to be able finally to resolve the rotation problems.
Thank you!

**Comment by ajwfrost** [comment]
Thanks -> seems we have a bit of a problem somehow in the iPhone build/update process..

For iOS 16 we're looking at getting something out hopefully the end of next week..

**Comment by pavelzmolik** [comment]
Hi.. i have same problem with new SDK version. Compiled on Windows 10

**Comment by ajwfrost** [comment]
Yes, please try with the new release https://airsdk.harman.com/download/50.0.1.3
thanks

**Comment by itlancer** [comment]
For me it fixed with AIR 50.0.1.3.
Thanks!

**Comment by pavelzmolik** [comment]
For me fixed too.. But there is bad versioning.. Animate reports me version 50.0.1.2, and if I look into "air-sdk-description.xml" there is 
`<?xml version="1.0"?>
<air-sdk-description>
<name>AIR 50.0.1</name>
<version>50.0.1</version>
<build>2</build>
</air-sdk-description>
`
but this is not bug.. for luck :D

**Comment by pavelzmolik** [comment]
no its OK.. animate shows me even build number.. its like versions 33.1 if I could advice, let the build number just as now.. I need to see which number was compiled.. for returning back version, if needed

**Comment by apofis1969** [comment]
@ajwfrost Thank you!
