### ISSUE TITLE
iOS App rejected due to Crash on iPad Air 11,3

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2300]
Before reporting this issue:

- you should consider whether this would be a question better suited to discussions above ^^ ;
- make sure you have searched for similar issues and add your experience there if one exists.

## Problem Description

Apple rejected the app because of a crash with iPAD Air 11,3 iOS 16.1.1
* Which AIR SDK did you use? 50.0.1.3

## Steps to Reproduce

Error logs of the apple review team.
I added the AspectRatio Ane and linked with a symlink of ld64 Intellij to iOS 16.1 in Xcode
@ajwfrost Please, this is really urgent!

And how to resolve all this?
1. Fully symbolicate the crash report. See [Adding Identifiable Symbol Names to a Crash Report](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/adding_identifiable_symbol_names_to_a_crash_report).

2. Match the crash report to a common pattern. Based on the pattern, take specific actions to further investigate the crash. See [Identifying the Cause of Common Crashes](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/identifying_the_cause_of_common_crashes).

[crashlog-3660E7D0-7CAD-42C1-915D-1F3A74F1978D.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/10024901/crashlog-3660E7D0-7CAD-42C1-915D-1F3A74F1978D.txt)
[crashlog-8377E29A-EC4B-4901-8975-0E9DD60F8B01.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/10024902/crashlog-8377E29A-EC4B-4901-8975-0E9DD60F8B01.txt)

**Comment by apofis1969** [comment]
Apple forgot to test with internet connection enabled. App passed the review.

**Comment by ajwfrost** [comment]
?! weird that this made a difference.. but nice to know that even Apple can make silly mistakes :-)

The update with iOS 16 and Xcode 14.1 is nearing completion though... aiming to release early next week

**Comment by apofis1969** [comment]
@ajwfrost without internet the app does not work. They wanted to install the app and entered their username and password. But without internet the app can’t connect to the server. I realized after analyzing the screenshot. Crazy all this. Great to hear that the new version is going to be released. Thanks for your reply.
