### ISSUE TITLE
Using latest SDK 50.0.1.2  for IOS getting error

### ISSUE THREAD

**Issue by Menard1965** [airsdk/Adobe-Runtime-Support#2308]
Hi!

I use the latest SDK 50.0.1.2 and tried to compile to IOS. there was never a problem in the past, but with this SDK i get the following error.

Undefined symbols for architecture arm64:
"_ZN9CSWFDecen13NeedsMoreDataEPKhS1_jPj", referenced from:
__ZN12ScriptPlayer11PushDataBufEPKhiPbb in
libRuntimeHMAOT.arm-air.a(splay.o)
ld:symbol(s) not found for architecture arm64

when switching back to air sdk 743  it works perfectly.
What i am doing wrong ?

[see screenshot](https://www.blue-2.at/blog/Files/air_25.JPG)

**Comment by ajwfrost** [comment]
This is covered under #2292, please update to 50.0.1.3 release
thanks
