### ISSUE TITLE
setAllowsAnyHTTPSCertificate

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2312]
Hi, does anyone know how to resolve this warning with Xcode 14.1 when uploading the app to iOS AppStore? Is there anything to add to the descriptor file?

![BE3C06A2-2F08-45DB-BDED-3937CB03FFF6](https://user-images.githubusercontent.com/25087613/203148997-d86d5cd7-3ae5-48a1-9f43-5ab56eebd0d2.jpeg)

**Comment by ajwfrost** [comment]
Hi

Is this a warning, or an error? It says "uploaded with warnings" and then "operation error"...!

The selector was included accidentally during a configuration update recently, it wasn't ever being called but we've removed it again.. change was made already so it should be in our next release

thanks

**Comment by apofis1969** [comment]
hi @ajwfrost, it is a warning. It appears in Xcode. The transporter does not show this after validating.

**Comment by ajwfrost** [comment]
Hi - the next release is basically ready but the iPhone SDK changes mean that it's not currently possible to build iOS apps from Windows. So we're checking to see if that's a quick fix, if so we'll put it all together and release, otherwise we'll issue the release with this as a known issue and not set it as the official/latest version... will try to get an update by the end of today.

thanks

**Comment by ajwfrost** [comment]
Yes it's going to take a bit of time to sort out the Windows build of ld64, so we'll go ahead with the next release asap to resolve this issue...

**Comment by apofis1969** [comment]
hi @ajwfrost is there any possibility you send the file which causes this warning. I am worried, that the update won't pass.
There is also a problem with the ANRs on Android with 50.0.1.3. They moved up more than 300%

**Comment by ajwfrost** [comment]
The release is available now so if you use this version to build (using a mac!) then it should get sorted out.

Not sure why there were any changes in ANR figures, what version of the AIR runtime was your previous release using?

**Comment by apofis1969** [comment]
hi @ajwfrost I tested the SDK. It seems to work well. I tried with macOS and iOS. The rotation is working the same way as with the ANE before. Great work. Thanks

**Comment by apofis1969** [comment]
Hi @ajwfrost these errors appear on Google with 50.1.1.1
Crashes and ANRs
java.lang.SecurityException: No active admin ComponentInfo{com.google.android.apps.mtaas.deviceadmin/com.google.android.apps.mtaas.deviceadmin.DeviceAdminReceiver}

java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.google.android.apps.mtaas.deviceadmin/com.google.android.apps.mtaas.deviceadmin.ToggleUserRestriction}: java.lang.SecurityException: No active admin ComponentInfo{com.google.android.apps.mtaas.deviceadmin/com.google.android.apps.mtaas.deviceadmin.DeviceAdminReceiver}

java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.google.android.apps.mtaas.deviceadmin/com.google.android.apps.mtaas.deviceadmin.SetUpdatePolicy}: java.lang.SecurityException: No active admin ComponentInfo{com.google.android.apps.mtaas.deviceadmin/com.google.android.apps.mtaas.deviceadmin.DeviceAdminReceiver}
