### ISSUE TITLE
add <disableSensorAccess>` under the `<android>` section,built apk error

### ISSUE THREAD

**Issue by avelle** [airsdk/Adobe-Runtime-Support#2325]
Hi @pengyangjin, @wmtj - please try using https://airsdk.harman.com/download/50.1.1.1 with a new flag in the app descriptor file, `<disableSensorAccess>` under the `<android>` section..

thanks

_Originally posted by @ajwfrost in https://github.com/airsdk/Adobe-Runtime-Support/issues/2259#issuecomment-1326205826_

**Comment by avelle** [comment]
https://github.com/airsdk/Adobe-Runtime-Support/issues/2259
We have the same problem to solve, but there is an error after building according to the solution

**Comment by avelle** [comment]
The error message is as follows：
error 103: application.android.disableSensorAccess is an unexpected element/attribute

**Comment by ajwfrost** [comment]
Hi

You need to update the namespace in your application descriptor so that it says:
```
<application xmlns="http://ns.adobe.com/air/application/50.1">
```

thanks
