### ISSUE TITLE
URLRequest caching not working?

### ISSUE THREAD

**Issue by johnou** [airsdk/Adobe-Runtime-Support#2331]
URLRequest has two properties, useCache and cacheResponse - even if explicitly set to true the AIR runtime doesn't seem to cache the response?

## Problem Description

URLRequest caching not working.

* Which AIR SDK did you use?

50.0.1.2

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.

Windows.

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?

100%

## Steps to Reproduce

Note the endpoint below is missing cache headers but I have also tested it locally with the webserver responding with `Cache-Control: no-transform, max-age=604800`

Minimal example:

```as3
package {

import flash.desktop.NativeApplication;
import flash.display.Sprite;
import flash.events.Event;
import flash.events.HTTPStatusEvent;
import flash.events.IOErrorEvent;
import flash.events.SecurityErrorEvent;
import flash.net.URLLoader;
import flash.net.URLLoaderDataFormat;
import flash.net.URLRequest;
import flash.text.TextField;
import flash.utils.getTimer;

public class Main extends Sprite {

    var startTime:int;

    public function Main() {
        var textField:TextField = new TextField();
        textField.width = 600;
        trace("AIR Runtime version: " + NativeApplication.nativeApplication.runtimeVersion);
        textField.text = "AIR Runtime version: " + NativeApplication.nativeApplication.runtimeVersion;
        addChild(textField);

        var _loader:URLLoader = new URLLoader();
        _loader.dataFormat = URLLoaderDataFormat.BINARY;
        _loader.addEventListener(Event.COMPLETE, loadEventHandler);
        _loader.addEventListener(Event.UNLOAD, loadEventHandler);
        _loader.addEventListener(HTTPStatusEvent.HTTP_STATUS, loadEventHandler);
        //_loader.addEventListener(ProgressEvent.PROGRESS, loadEventHandler);
        _loader.addEventListener(IOErrorEvent.IO_ERROR, loadEventHandler);
        _loader.addEventListener(SecurityErrorEvent.SECURITY_ERROR, securityErrorEventHandler);

        startTime = getTimer();
        var request:URLRequest = new URLRequest("https://sandbox.habbo.com/gamedata/furnidata_xml/28abbd276b7ffe2236f220d93da1836cdac36afb");
        request.useCache = true;
        request.cacheResponse = true;
        _loader.load(request);
    }

    protected function loadEventHandler(event:Event):void {
        trace((getTimer() - startTime) + "ms")
    }

    private function securityErrorEventHandler(event : SecurityErrorEvent) : void {

    }
}
}

```

## Known Workarounds

Custom caching which is nasty if using blocking IO read / write and the end user has a slow HDD. Hoping native caching does not block the main thread and cause the application performance to degrade.

**Comment by ajwfrost** [comment]
Thanks, we'll look into this -> sounds like a bug (or rather, functionality not matching documentation...)

**Comment by johnou** [comment]
Thanks, in the past the browser has taken care of caching resources so would be nice to reintroduce caching which doesn't block the main thread.

**Comment by ajwfrost** [comment]
Just coming back to this one, we investigated further on how this actually works. On Windows at least, when you set those values on the `URLRequest` object, we update the wininet handle in the following ways:

1.	useCache = true: set `INTERNET_FLAG_RESYNCHRONIZE` so that the online file is checked and if changed, is re-downloaded
2.	useCache = false: set `INTERNET_FLAG_RELOAD` so that we don’t load from any cached value
3.	cacheResponse = true: no flags set as the default is to cache any correct response
4.	cacheResponse = false: set `INTERNET_FLAG_DONT_CACHE` to avoid caching the response

What then actually happens with this, in the first request you won't see any difference, but a subsequent request would include a header such as
```
If-Modified-Since: Fri, 27 Jan 2023 09:32:16 GMT; length=16301627\r\n
```
which the server can then look at and decide whether to reply with the full file (http 200) or with an "unchanged" code (http 304) that would make Windows give us the file from their cache.

Sounds like this is working having discussed it further :-)

thanks

**Comment by waveofthought-code** [comment]
@ajwfrost Apologies for bumping you here but this felt like a good opportunity to ask:   Where exactly is Windows caching downloaded files?  Are they hidden away, obscured in some arcane blob deep within my file system, or somewhat accessible?

**Comment by ajwfrost** [comment]
I have absolutely no idea I'm afraid! It's all handled internally by the Windows sub-system..
Potentially it's just the same area as this:
https://www.thewindowsclub.com/temporary-internet-files-folder-location
or perhaps more likely to be:
https://stackoverflow.com/questions/11267161/how-to-clear-wininet-cache-created-by-iis

thanks

**Comment by waveofthought-code** [comment]
Ah ok, i suspected it was probably this too - thanks!
