### ISSUE TITLE
AIR SDK 50.0.0.1 BETA has expired?Android app built with it dosen't work today

### ISSUE THREAD

**Issue by AdamSun** [airsdk/Adobe-Runtime-Support#2332]
## Problem Description

* AIR SDK version: 50.0.0.1 BETA
* platform: Android, all devices
* problem detail: all our Android app not work fine built with AIR SDK 50.0.0.1 BETA today(2022/12/1).When the app start, it show a black background and not continue to work.The logcat message is below:
```
12-01 09:37:53.296 2595-2595/com.maichi.kdzl.meta I/com.maichi.kdzl.meta: BETA build of Adobe AIR 50,0,0,1
12-01 09:37:53.296 2595-2595/com.maichi.kdzl.meta I/com.maichi.kdzl.meta: This beta release has now expired, please download the release SDK and re-package your application using that
```
* expect: If the 50.0.0.1 beta version has expired and cause the problem above, we hope that the harman team can cancel the expired setting without rebuild a new app so that the exsting android app can work fine as before.For some reason, a lot of people are using our app and it would be difficult to ask our client to replace a new app. Thanks!

**Comment by ajwfrost** [comment]
Hi

It's a beta .. every time you run it, you should be seeing a pop-up message, saying it's not meant to be distributed? And per the terms of the license agreement, you can't distribute it. It's meant for you to internally test the behaviour and confirm things are working, once we are happy that the new functionality is okay then we issue the non-beta version.

So you would need to take the 50.0.1.3 release (or later) and re-deploy your app with that I'm afraid, the expiration is hard coded into the runtime.

thanks

**Comment by AdamSun** [comment]
hi @ajwfrost  the expiration is hard coded in the runtimeClasses.jar?

**Comment by ajwfrost** [comment]
It's in the C++ code actually, so libCore.so, common across all platform builds.
