### ISSUE TITLE
ANR in com.google.android.apps.maps

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2354]
Hi, since today this error message appears when sending the app to the internal testing. The Pre-Launch Report shows the following in Crashes and ANRs

ANR in com.google.android.apps.maps;PID: 6138;Broadcast of Intent { act=android.intent.action.LOCALE_CHANGED flg=0x11200010 cmp=com.google.android.apps.maps/com.google.android.apps.gmm.notification.channels.NotificationChannelBroadcastReceiver };

The internal Test device of Google Developer Console is the Pixel 2 (virtual) x86
This is already ridiculous, because no x86 device is in use.
How can I prevent this Error message or is this a bug in Adobe Air?
I am afraid, that the app update does not go online this way.

But on the Pixel 2 in Android Studio the app is working perfect. So where is this problem?
Do you have any idea?

AIR SDK version: 50.0.1.3
Device OS: Android 9 (SDK 28) ABI x86
Device version: Google Pixel 2 (virtual)
Development IDE: IntelliJ
Development OS: macOS Monterey

[logcat.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/10209792/logcat.txt)

**Comment by urmatt** [comment]
I have also something like this.
ANR in com.google.android.apps.messaging;PID: 10284;Broadcast of Intent { act=com.google.android.gms.phenotype.UPDATE flg=0x30 pkg=com.google.android.apps.messaging cmp=com.google.android.apps.messaging/com.google.android.libraries.phenotype.client.stable.PhenotypeUpdateBackgroundBroadcastReceiver (has extras) };
