### ISSUE TITLE
[Android][iOS] Screen::modes returns null

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2359]
## Problem Description
`Screen::modes` returns `null` with Android and iOS.
But reference says that it should return array https://airsdk.dev/reference/actionscript/3.0/flash/display/Screen.html#modes

Tested with multiple AIR versions even with latest AIR 50 with multiple different Android/iOS devices.

Related issue (as a feature request for Linux): https://github.com/airsdk/Adobe-Runtime-Support/issues/1879

## Steps to Reproduce
Launch code below with any Android/iOS device.
Application example with sources attached.
[mobile_screen_mode_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10231489/mobile_screen_mode_bug.zip)

```
trace(Screen.mainScreen.modes);
```

**Actual Result:**
`Screen::modes` returns `null`.

**Expected Result:**
`Screen::modes` should return array with supported screen modes: `[object ScreenMode],[object ScreenMode],[object ScreenMode],[object ScreenMode]`
Or (if screen modes not supported) `Screen::modes` should return empty array.
Or (if screen modes not supported) it should be documented in reference that `Screen::modes` returns `null` for mobile platforms.

## Known Workarounds
Just know that for mobile platforms `Screen::modes` returns `null` instead of array.

**Comment by ajwfrost** [comment]
I think for this one, because we don't have a `mode` variable for the mobile platforms, we should also keep the `modes` property as null. We can update the documentation to make this more explicitly clear...

**Comment by itlancer** [comment]
Thanks for your reply. Ok. I will close this issue after documentation update.

**Comment by itlancer** [comment]
Fixed right now.
Thanks!
