### ISSUE TITLE
[AIR SDK] Android app id cannot contains "long" word

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2408]
## Problem Description
AIR application id for Android cannot contains "long" word. It will corrupt activity name.

Tested with multiple AIR SDK versions, even with latest AIR 50.1.1.2.
Same problem in all cases.
There is no such issues with Windows platform.

Related issues (not the same):
https://github.com/airsdk/Adobe-Runtime-Support/issues/2188
https://github.com/airsdk/Adobe-Runtime-Support/issues/1188

## Steps to Reproduce
Build any AIR application (even "empty" application) for Android with application id which contains "long" word. And try to launch it via command:
`adt -launchApp -platform android -appid android.id.long.word.bug`

Launch application with code below with any Android device. Video playback should be started immediately. Metadata will be traced.

Application example with sources attached.
[android_id_long_word_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10371714/android_id_long_word_bug.zip)
This issue could be reproducible with application id `android.id.long.word.bug`

**Actual Result:**
Launch command will be failed:
```
Failed to launch android.id.long.word.bug
```
If you try to install and launch application to device via Animate you you will get the same error.
In APK manifest you will see:
```
    <application
        android:label="@ref/0x7f07000c"
        android:icon="@ref/0x7f050000"
        android:name="androidx.multidex.MultiDexApplication"
        android:hardwareAccelerated="false">

        <activity
            android:theme="@ref/0x7f080000"
            android:label="@ref/0x7f07000c"
            android:name="android.id._long.word.bug.AIRAppEntry"
            android:exported="true"
            android:launchMode="2"
            android:screenOrientation="2"
            android:configChanges="0x40000da0"
            android:windowSoftInputMode="0x12">
```
Application activity name will be `android.id._long.word.bug.AIRAppEntry` instead of `android.id.long.word.bug.AIRAppEntry`.

**Expected Result:**
Application will be launched without errors. Application activity name will be `android.id.long.word.bug.AIRAppEntry`.

## Known Workarounds
Do not use "long" word in Android application id.

**Comment by FliplineStudios** [comment]
I'm assuming it's because "long" is a Java keyword and can't be used in package names, the same happens if you use other keywords like boolean in the application ID:

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

I'm seeing this behavior in the new gradle-based builds, but not in the legacy builds (though my legacy builds aren't multidex while the gradle builds seemingly are, not sure which of those is the main factor in this).

**Comment by itlancer** [comment]
I suspected it. Thank you very much for noticing it!
I will close this issue cause seems reserved keywords shouldn't be used for application id too.
