### ISSUE TITLE
[Feature Request][Android] `FREByteArray::setLength()` support

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2467]
## Feature Description
Right now setting `ByteArray` length with native extension for Android not so obvious.
AIR should have `FREByteArray::setLength()` method to set up `ByteArray` length.

## Known Workarounds
`byteArrayObject.setProperty("length", FREObject.newObject(byteArrayLength));`

**Comment by ajwfrost** [comment]
Just to confirm, you're talking about the Java interface here? So:
https://help.adobe.com/en_US/air/extensions/WS39e706a46ad531be2664b82132a8ec9029-8000.html

I'm wondering why there wasn't a `setLength` function here already..! And `newByteArray` would surely be more useful with an optional length parameter...

Will have a check on this -> we're currently just updating the FRExxx interfaces so can probably squeeze this change in if it's a simple one...

**Comment by itlancer** [comment]
@ajwfrost 
Yes, exactly.
Optional length parameter for `newByteArray` also could be useful. But `setLength` seems also needed to work with already created ByteArray.
Also in some near future I think FRExxx documentation should be moved somewhere https://airsdk.dev/reference

**Comment by itlancer** [comment]
Implemented with latest AIR SDK. Checked with AIR SDK 50.2.3.1.
Thanks!
