### ISSUE TITLE
Other sub-window performance problems after the main window is minimized in direct mode

### ISSUE THREAD

**Issue by RayGyoe** [airsdk/Adobe-Runtime-Support#2481]
## Problem Description
other sub-window performance problems after the main window is minimized in direct mode.
please download the minimum test program to reproduce

* Which AIR SDK did you use? 
Test ：50.2.1.1,50.1.1.2

## Steps to Reproduce
1.min size main window
2.observe other sub-windows

Give us a minimal example: [https://vsdevelop.com/wp-content/uploads/2023/02/benchmark.zip](url)

## Known Workarounds
1.Close the main window and let the running window rise
2.renderMode is set to cpu

**Comment by ajwfrost** [comment]
Interesting .. so when the main (busy) window is minimised, the frame rate of the other simpler windows actually goes down. (When the main window is closed, they go straight up to 60fps on my machine..)

Seems to be the "waiting for gpu" culprit...
![image](https://user-images.githubusercontent.com/6400804/220836532-2cc7fb01-59e3-43f4-a66a-c48f59eec9b9.png)

We'll see if we can work out why this is happening! Thanks for the test case

thanks

**Comment by ajwfrost** [comment]
Hi

Are you able to try reproducing this again using the updated AIR DLL from the below message?
https://transfer.harman.com/message/qlu9B7MHlc0PlSJ7V0XABj

It would be good to know (a) if this helps, and (b) if you see any side-effects.

thanks

**Comment by RayGyoe** [comment]
Hi

Tested in detail, this issue has been fixed 

thanks

**Comment by RayGyoe** [comment]
> Interesting .. thanks for that. So the additional delay was just happening purely within Direct3D's "Present" call. Quite why the duration of that call was increasing dramatically when the window was minimised is a bit of a mystery, but it did seem a slightly unnecessary call to make given that you can't see the window contents when it's minimised, so we're just ensuring that we only make the Present call when the window is visible...
> 
> Will get this one into our next release...
> 
> thanks

Yes, waiting for the next official release.
cheers
