### ISSUE TITLE
[Desktop] Changing `Stage::displayState` after `FullScreenEvent.FULL_SCREEN` cause `SecurityError #2152`

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2492]
## Problem Description
Changing `Stage::displayState` after `FullScreenEvent.FULL_SCREEN` cause `SecurityError #2152` width desktop platforms.
It happens if I want to wait when `Stage::displayState` to be applied and then change it again.

Tested with multiple AIR versions, even with latest AIR 50.2.1.1 with multiple different Windows, macOS and Linux devices with different OS versions with different applications.
Same problem in all cases.

Related issue (not the same): https://github.com/airsdk/Adobe-Runtime-Support/issues/2486

## Steps to Reproduce
Launch application with code below with any Windows/macOS/Linux device. Application goes to fullscreen, await `FullScreenEvent.FULL_SCREEN` event and goes out of fullscreen.

Application example with sources attached.
[displaystate_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/10840534/displaystate_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.display.StageDisplayState;
	import flash.events.FullScreenEvent;
	
	public class DisplayStateBug extends Sprite {
		
		public function DisplayStateBug() {
			addEventListener(Event.ADDED_TO_STAGE, addedToStage);
		}
		
		private function addedToStage(e:Event):void {
			removeEventListener(Event.ADDED_TO_STAGE, addedToStage);
			
			stage.addEventListener(FullScreenEvent.FULL_SCREEN, fullscreenChanged);
			stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE;
		}
		
		private function fullscreenChanged(e:FullScreenEvent):void {
			trace("fullscreenChanged", e.fullScreen);
			
			if (e.fullScreen){
				stage.removeEventListener(FullScreenEvent.FULL_SCREEN, fullscreenChanged);
				
				stage.displayState = StageDisplayState.NORMAL;//This line cause SecurityError: Error #2152: Full screen mode is not allowed.
			}
		}
	}
}

```

**Actual Result:**
Run-time error:
```
SecurityError: Error #2152: Full screen mode is not allowed.
```

**Expected Result:**
Application window in non-fullscreen mode.

## Known Workarounds
Add delay in ~1 second after `FullScreenEvent.FULL_SCREEN` will be triggered before change `Stage::displayState` again.

**Comment by mesaglam** [comment]
I'm not sure if it's because of this, but after switching between full screen and normal mode a few times in Linux does the ui freeze and only half of the app appears. Tested latest 50.2.3.5 on Ubuntu 22, Debian 10 and Debian 11. Same result....

On Windows and Mac no problem...

**Comment by mesaglam** [comment]
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/7021706/daf4033c-1cf6-4a7a-ae71-82dfb9fd541f)

Second time going to fullScreen mode

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/7021706/6773326b-58fc-4974-9699-ea6dab3a8128)

**Comment by mesaglam** [comment]
I've noticed that the freezing doesn't occur when exiting full screen mode with the keyboard ESC button. 

- Go full screen mode programmatically and exit with keyboard ESC. Repeat several times, no problems...

- Go full screen mode programatically and exit programatically. Repeat several times. Problem occurs...

**Comment by ajwfrost** [comment]
Hi

Regarding the first part -> changing display state causes security error: this is by design. It looks like we'll have to update the documentation though, as I couldn't see any mention of this restriction within the AS3 docs. But the AS3 resize event is sent during the process of setting up the full screen mode, and it's not then possible to start changing back again whilst this is ongoing - essentially, the setting of "displayState" is not re-entrant:
> do not allow setting fullscreen mode while we are in the process of setting fullscreen mode


For the second thing here though, the freeze and redraw problem (@mesaglam ) .. we can't reproduce that, are you able to create a simple test case for this please?

thanks

**Comment by mesaglam** [comment]
Hello, here the screen capture. It throws errors to terminal like "GLib-CRITICAL **: 14:05:34.627: Source ID XXX was not found when attempting to remove it".

![debian](https://github.com/airsdk/Adobe-Runtime-Support/assets/7021706/45d9be41-c9d8-4185-b98d-ceeaa42f9e1a)

The switching function as simple as:

function goFullScreen()
{

  stage.displayState = stage.displayState == StageDisplayState.NORMAL ? StageDisplayState.FULL_SCREEN_INTERACTIVE : StageDisplayState.NORMAL
}

Different versions of Linux throws same error on terminal...

**Comment by mesaglam** [comment]
I read that this terminal messages might be harmless. 

https://stackoverflow.com/questions/23199699/glib-critical-source-id-xxx-was-not-found-when-attempting-to-remove-it

So is there any suggestion to solve this restriction on Linux? Should I remove fullsceen feature from app for Linux?

Thanks for all...

**Comment by ajwfrost** [comment]
Hi

Thanks - I think although the message may be harmless, it may indicate that something's not as expected within the code!

From your video/animation above, I don't see the application freezing at all? It looks like the app doesn't resize properly when it goes to the full screen mode. The earlier screenshots you had showed the UI also being drawn wrongly (half off the screen, and not resized) but I'm wondering if this is more a refresh issue...

Could we get this latest app bundle - with the simple reproduction by pressing that button - and try it out here? as we can then hopefully reproduce it and debug.. upload linke is available at https://transfer.harman.com/requests/OJ214fkoMCp2tFUTk0krab

thanks

**Comment by mesaglam** [comment]
Hi, I've sent the files. I'm awaiting your response. Thank you...

**Comment by itlancer** [comment]
Right now reason of `SecurityError` described in documentation: https://airsdk.dev/reference/actionscript/3.0/flash/display/Stage.html#displayState
Thank you!
I will close this issue cause it "as designed".
If you have any related issues please create new one.
