### ISSUE TITLE
unexpected failure: Platform conversion failed

### ISSUE THREAD

**Issue by Oldes** [airsdk/Adobe-Runtime-Support#2499]
Hi there... after a few years I am trying to rebuild one project on Winows (for Windows) and I am having this error:
```
unexpected failure: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
[ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
"
java.io.IOException: Platform conversion failed. Process exited with error 5. Output was "Conversion complete
[ErrorEvent type="error" bubbles=false cancelable=false eventPhase=2 text="Error #2038" errorID=2038]
"
        at com.adobe.air.nai.NativePackager.conversionFail(NativePackager.java)
        at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java)
        at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
```

Strange thing is, that I am able to build the same project for Steam, where the only difference is, that in the Steam version I have also an extension.

Any idea what is going on?
Thanks.

**Comment by Adrian-S** [comment]
I successfully compiled exe file 2 days ago with version 33.1.1.256 , and today I have same error on all versions. I didn't even restarted my computer in the last month, and to my knowledge java did not update itself. Only windows defender definitions were updated. Turning off defender or firewall did not fix.

My java path was suspiciously set to V1.8, and changing it to v11 (my default) or v17 did not solve the issue.

Also maybe unrelated Flash Builder (with 33.1.1.345 overlay) ran for the first time swf with mobile only ane that usually crashed at startup. Only crashed on code execution now, and OverrideAir was involved. Change to code was minimal, no ane or any configuration change.

**Comment by Adrian-S** [comment]
@Oldes Found my problem to be diskspace. Apparently 300mb is sufficient to build .AIR, .IPA and .APK, but not for .EXE

In case you don't have the same issue I run this commands inside a bat file:
```
@call java -version
@call D:\AdobeAIRSDK33_1_1_259\bin\adt.bat -package -storetype pkcs12 -tsa none -keystore certificate.p12 -storepass [password] -target native App.exe Desktop.xml App.swf [files]
```

I have java version "11.0.14" 2022-01-18 LTS and command to test it is included above. Other versions might work too, but from what I have v17 will not work for .IPA for sure.

My desktop XML even has `<architecture>64</architecture>` not sure if it's requirement or not.

**Comment by Oldes** [comment]
As I don't have this problem anymore with the latest SDK (and it is true, that with more free space) I think I can close this issue!
