### ISSUE TITLE
Multi-monitor calling startMove to move the window is not correctly set size

### ISSUE THREAD

**Issue by RayGyoe** [airsdk/Adobe-Runtime-Support#2508]
Describe your problem in detail. Include the following information:

* Win10/11 SDK50.2.x

## Steps to Reproduce

Give us a minimal example:
[https://vsdevelop.com/wp-content/uploads/2023/03/20230302160136.png](url)
[https://vsdevelop.com/wp-content/uploads/2023/03/d98ab5bc261910c80f1f5fb5cf942876.mp4](url)

## Known Workarounds
1.Disable custom drag with STANDARD style
2.Calculate/ by yourself

**Comment by itlancer** [comment]
I have the same issue for chromeless windows too https://airsdk.dev/reference/actionscript/3.0/flash/display/NativeWindowSystemChrome.html#NONE
