### ISSUE TITLE
50.2.1.1 - Bug: crash before startup on Android 4.4 and failed to request permission on Android 12

### ISSUE THREAD

**Issue by lwmirkk** [airsdk/Adobe-Runtime-Support#2517]
## Problem Description

I'm still trying to track down the problem, but logcat is showing nothing related to the problem yet.
The only log I could track when request the permission is this one:
https://pastebin.com/m3KbFY6a
(just 12 lines)

But I noticed that in this version 50.2.1.1 an error is occurring when requesting basic permission to use the basic storage.
On Chromecast 4 (Android 12) : There is an error of (you don`t have an app that can do this) when I request this permission and the popup to enable or not the permission is not open.
On some device with Android 4.4: The app opens and closes instantly.

Some other devices the problem does not occurs.... Stranger things...

The problem seems to only occur on SDK 50.2.1.1.
The problem does not occur on SDK 50.1.1.2.

## Steps to Reproduce

Request file permission:
File.applicationStorageDirectory.requestPermission();

## Known Workarounds

Use SDK 50.1.1.2

**Comment by ajwfrost** [comment]
Hi

This is presumably related to the new mechanism we have for requesting file permissions via the Android Storage Access Framework. For Chromecast it sounds like there's no handler for the intent; for Android 4.4 we should have been using the earlier APIs/code though, it sounds like something went wrong here.

As a slight aside, you should never need to call the `requestPermission` function for the application storage directory, this is meant to always be available for reading/writing regardless of the Android permissions or version... Permissions are required for other/shared locations..

thanks

**Comment by lwmirkk** [comment]
Problem persists in AIR 50.2.2.1

**Comment by lwmirkk** [comment]
Problem persists in AIR 50.2.2.2
(failed to request permission on Android 12)

**Comment by ajwfrost** [comment]
FYI for the "crash on Android 4.4" part of this issue, please see #2557 , fix will be available soon.
The permissions thing we've also got a workaround for, I believe..

**Comment by lwmirkk** [comment]
Request permission problem on Android 12 persists on AIR 50.2.2.5.

**Comment by lwmirkk** [comment]
Request permission problem on Android 12 persists on AIR 50.2.2.6.

**Comment by ajwfrost** [comment]
Just to confirm what exactly is the problem that you're still seeing here -> is this if you have a `File` object with a path in it, and you call `requestPermission()` on it, then on a Chromecast device you're seeing a pop-up "you don`t have an app that can do this"?

This does appear to be a "feature" or restriction of Chromecast, for example see https://www.reddit.com/r/AndroidTV/comments/yic698/chromecast_with_google_tv_hd_android_12_you_dont/

We can perhaps try to swallow that message, but you would need to ensure your storage requests then comply with the policy for application-specific storage on the newer Android builds (i.e. just use the application storage directory..)

thanks
