### ISSUE TITLE
The ipa compiled by the AIR 50.2.1.1 ( 21-Feb-2023 ) version of sdk cannot be displayed in full screen on the iPad air 4 , and the previous version of sdk is normal.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#2527]
The ipa compiled by the AIR 50.2.1.1 ( 21-Feb-2023 ) version of sdk cannot be displayed in full screen on the iPad air 4 , and the previous version of sdk is normal.

Black edges on both sides（error display）
![ipad4](https://user-images.githubusercontent.com/1818875/225498096-bf479ec2-6c5f-48ea-9f3a-f6df13625ff3.jpg)

Previous normal display
![ipad4ok](https://user-images.githubusercontent.com/1818875/225498216-dea9b3a5-497d-4885-a442-d171ed3e7efc.jpg)

**Comment by ajwfrost** [comment]
Hi

Can you please confirm which version of the AIR SDK you were using to get the correct view there? And also, whether you have a commercial license (so if "adt-license" returns a developer ID)? We can look at the differences between versions, something may be going wrong in packaging.

To get the proper use of fullscreen, I think a launch screen is required, which is something we should be injecting automatically for "free tier" licensees.

thanks

**Comment by pengyangjin** [comment]
We have purchased a corporate license and do not want to additionally use a custom screen. Could you tell me how we should set it up? We have tried the following configuration and failed. The application will creash as soon as it is started.

		<InfoAdditions>
			<![CDATA[
			<key>UILaunchStoryboardName</key>
			<string>LaunchScreen</string>
					]]>
		</InfoAdditions>

**Comment by pengyangjin** [comment]
> Hi
> 
> Can you please confirm which version of the AIR SDK you were using to get the correct view there? And also, whether you have a commercial license (so if "adt-license" returns a developer ID)? We can look at the differences between versions, something may be going wrong in packaging.
> 
> To get the proper use of fullscreen, I think a launch screen is required, which is something we should be injecting automatically for "free tier" licensees.
> 
> thanks

Now I'm confused. Is it the lack of storyboards that leads to the adaptation error on the iPad?I don't need to use storyboards when writing app applications unless I want to show some different content.

**Comment by pengyangjin** [comment]
https://airnativeextensions.github.io/tutorials/ios-icons-assets-car.html#method-1-command-line
