### ISSUE TITLE
iOS Dynamic Framework failing to be signed correctly on Windows

### ISSUE THREAD

**Issue by marchbold** [airsdk/Adobe-Runtime-Support#2529]
## Problem Description

Particular iOS dynamic frameworks fail to be signed correctly when packaging on Windows. We have encountered the failure with all recent versions of AIR when packaging an application on Windows using the `FBAudienceNetwork.framework` dynamic framework for the Facebook Audience advertising network. 

Packaging succeeds but the application fails to install with the following error message:

`
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008017: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.RiMt2O/extracted/Payload/MyApplication.app/Frameworks/FBAudienceNetwork.framework : 0xe8008017 (A signed resource has been added, modified, or deleted.)
`
 
* AIR SDK: tested v33.1.1.935, 50.1.1.2, 50.2.1.1  
* Affects: iOS applications packaged on Windows

## Steps to Reproduce

- Setup a simple application
- Install the `com.distriqt.ironsource.FacebookAudience` package
  - `apm install com.distriqt.ironsource.FacebookAudience`
- Package the application and attempt to install on a device 

Minimal example attached: 
[air-test-src.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11006797/air-test-src.zip)

(just run `apm install` to download the extensions and frameworks).

Also attached two packaged versions of the ipa one packaged on windows the other on macos 

[air-test-windows.ipa.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11006773/air-test-windows.ipa.zip)
[air-test-macos.ipa.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11006781/air-test-macos.ipa.zip)

## Known Workarounds

Packaging succeeds if done on a macOS machine.

**Comment by GemeXP** [comment]
Hello.
When building a build with AIRSDK 33.1.1.929, I received a message from TestFlight that the build contains errors:
ITMS-90725: SDK version issue (This app was built with the iOS 15.0 SDK)
ITMS-90683: Missing purpose string in Info.plist (should contain a NSLocationAlwaysAndWhenInUseUsageDescription key)

After that, I tried to build with AIRSDK 50.2.2.4
now TestFlight sends another message:
ITMS-90482: Invalid Executable - The executable 'game.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode.
ITMS-90482: Invalid Executable - The executable 'game.app/Frameworks/FBSDKGamingServicesKit.framework/FBSDKGamingServicesKit' contains bitcode.
ITMS-90482: Invalid Executable - The executable 'game.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode.
ITMS-90482: Invalid Executable - The executable 'game.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit' contains bitcode.

Is this a similar problem? Or is it something else? I also use Windows to build and FacebookANE from distiqt

**Comment by marchbold** [comment]
@GemeXP This is a different issue. You need to remove bitcode from any frameworks you are using in your application to satisfy Apple's new guidelines. If you are using the @distriqt Facebook extension then just make sure you have updated to the latest release. It has had bitcode removed and will resolve this issue.

**Comment by marchbold** [comment]
Resolved in 50.2.2.2

**Comment by AleDaDa** [comment]
> @GemeXP This is a different issue. You need to remove bitcode from any frameworks you are using in your application to satisfy Apple's new guidelines. If you are using the @distriqt Facebook extension then just make sure you have updated to the latest release. It has had bitcode removed and will resolve this issue.

Can you give a message on how to remove bitcode from frameworks ( the dynamic SWIFT framework in app root ) ?
Thanks a lot

**Comment by marchbold** [comment]
@AleDaDa Most of the SDKs have already been updated to exclude bitcode so you shouldn't have to do this anymore.
