### ISSUE TITLE
AIR 50.2.2 still using IOS SDK 16.0?

### ISSUE THREAD

**Issue by Michoko92** [airsdk/Adobe-Runtime-Support#2531]
Hi,

Two days ago, I started to get warnings in transporter when uploading IOS builds, telling me that I used an obsolete IOS SDK 15, and that I had to use SDK 16.1 starting April 2023. So I upgraded my AIR 33.1 SDK to the latest 50.2.2 (I build my IPAs on Windows) and submitted a new build.

However, now I get the same warning, except it tells me I'm using SDK 16.0, and should upgrade to 16.1. In the SDK release notes, the SDK is supposed to be 16.4, so I'm not sure what I'm doing wrong. I'm using District ANEs: could it be due to some ANEs being built with an older SDK? Or is it something else?

Thank you very much for your reply! 🙂

**Comment by ajwfrost** [comment]
Hi - thanks, yes we've just been looking at this, there are two things that are required for us to properly support the new requirements:
1) our runtimes need to be built with the appropriate Apple SDKs - which is what we'd done in the above release
2) the IPA packaging tool needs to be updated with the right version codes to inject into the IPA files .. and this part was missed from the recent update, apologies for that!

It's a minor change so we'll get this packaged up and released tomorrow (at least for download via the AIR SDK Manager which makes it a lot easier/smaller to update..)

thanks

**Comment by marchbold** [comment]
We're getting similar reports from our apps lately too:

```
ITMS-90725: SDK Version Issue - This app was built with the iOS 16.0 SDK. 
Starting April 2023, all iOS apps submitted to the App Store must be built 
with the iOS 16.1 SDK or later, included in Xcode 14.1 or later.
```

**Comment by Michoko92** [comment]
Fixed with today's release 50.2.2. Good job guys!!

**Comment by xxxVBxxx** [comment]
Hi,
I also started to get warnings in transporter and upgraded to the latest AIR 50.2.2.2. 
I built the IPA file and uploaded it.There are no errors or warnings but the uploaded build doesn't appear on appstore connect's builds list. 

The builds with 33.1.1.935 are OK.
Is there anything I should do after upgrading the SDK?

**Comment by Michoko92** [comment]
Hmm that's strange, I published several builds until yesterday, and didn't have any issue. Did you receive emails from Apple stating that your build was processed and it didn't contain any error?

**Comment by xxxVBxxx** [comment]
Yes I jus received it.
```

Dear Developer,

We identified one or more issues with a recent delivery for your app, "3DTuning: Car Game & Simulator" 3.7.524 (3.7.524). Please correct the following issues, then upload again.

ITMS-90482: Invalid Executable - The executable '3DTuning.app/Frameworks/FBAEMKit.framework/FBAEMKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '3DTuning.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '3DTuning.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode.

ITMS-90482: Invalid Executable - The executable '3DTuning.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode.

ITMS-90482: Invalid Executable - The executable '3DTuning.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit' contains bitcode.

Best regards,

The App Store Team
```
