### ISSUE TITLE
[AIR 50.2][Linux] Application minimization cause that it will be restored again

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2535]
## Problem Description
Application minimization cause that it will be restored again for Linux using latest AIR 50.2.x.

Tested with latest AIR 50.2.2.1 and 50.2.1.1 with multiple different Linux devices (mostly Ubuntu 22.04) with different applications.
Same problem in all cases.
There is no such issue with AIR 50.1.1.2 and below.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2497
https://github.com/airsdk/Adobe-Runtime-Support/issues/2495
https://github.com/airsdk/Adobe-Runtime-Support/issues/2492
https://github.com/airsdk/Adobe-Runtime-Support/issues/2486
https://github.com/airsdk/Adobe-Runtime-Support/issues/2241

## Steps to Reproduce
Launch any AIR application (even "empty") with Linux and try to minimize it via window minimization button.

**Actual Result:**
Application window will be restored again. 
Also application window will be "always on top" of other applications.
With some OS editions (like Ubuntu 20.04) bug happens only once. After second attempt to minimize application window all works fine. With other OS editions it happens all the time.

**Expected Result:**
Application window will be minimized without false restoring again. Application window shouldn't be "always on top" if it doesn't set up specifically.

## Known Workarounds
not found
Use AIR 50.1.1.2 or below.

**Comment by mesaglam** [comment]
I hope you'll fix soon...

stage.displayState = StageDisplayState.NORMAL not working after going
stage.displayState = StageDisplayState.FULL_SCREEN_INTERACTIVE for linux. Tested on ubuntu and debian...

**Comment by itlancer** [comment]
@mesaglam 
Your issue also could be related to:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2497
https://github.com/airsdk/Adobe-Runtime-Support/issues/2492

@ajwfrost 
For original "fake window restoring on minimization" issue. With latest 50.2.2.3 behavior come little better but issue still exists. Especially with Ubuntu 22.04 (VM and real devices).
Steps to reproduce it 100% with Ubuntu 22.04:
1) Launch any AIR application (even "empty").
2) Try to minimize application window via standard window minimization button.
**Here application window could be restored again by no reason!** If not, go to next steps.
3) Restore application window manually from Linux Dock menu by mouse left button click (as usual). Application window will be restored.
4) Maximize application window via standard window maximization button.
5) Try to minimize application window via standard window minimization button.
**Here application window will be restored again by no reason!**

Sometimes fake restoring happens with step 2, sometimes with step 5. But only once per application launch. At least for Ubuntu with our tests. With some others Linux editions in such cases application window not just restored, but maximized and go to fullscreen without any reason.
**Workaround:** Catch window minimization event and then wait for maximization/fullscreen event for a short time. If such happens - minimize window programmatically again.

**Comment by itlancer** [comment]
Issue still exists with latest AIR 50.2.2.5.

**Comment by itlancer** [comment]
Fixed with latest AIR 50.2.3.2.
Thanks!
