### ISSUE TITLE
The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#2542]
The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane.

packageAab:
     [java] unexpected failure: Unable to find source.properties 
     [java] java.io.IOException: Unable to find source.properties 
     [java] 	at com.adobe.air.apk.AABOutputStream.getAndroidSDKBuildToolPath(AABOutputStream.java)
     [java] 	at com.adobe.air.apk.AABOutputStream.getAapt2(AABOutputStream.java)
     [java] 	at com.adobe.air.apk.AABOutputStream.generateResourcesAndManifest(AABOutputStream.java)
     [java] 	at com.adobe.air.apk.AABOutputStream.addApplicationDescriptor(AABOutputStream.java)
     [java] 	at com.adobe.air.ApplicationPackager.addSpecialFiles(ApplicationPackager.java)
     [java] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [java] 	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [java] 	at com.adobe.air.ADT.run(ADT.java)
     [java] 	at com.adobe.air.ADT.main(ADT.java)

**Comment by ajwfrost** [comment]
Actually the `source.properties` file is from the Android SDK and it tells us what version of the Android build tools you have available.. e.g. on my computer:
```
C:\Users\ukinanfr\AppData\Local\Android\Sdk\build-tools\33.0.0\source.properties
```

But in our code I can see that we removed the "throw" if we encountered that...
And actually, I don't even see these functions as being members of "AABOutputStream" - we have "getAapt" but not "getAapt2", and "getAndroidSDKBuildToolPath" is a member of "AndroidDeviceSDK.java" rather than "AABOutputStream.java".

Can you enable the debug log and post the output of that? (or if you're using the new AIR SDK Manager, just go to the "troubleshooting" tab and re-run the packaging..)

thanks

**Comment by pengyangjin** [comment]
Android\Sdk\build-tools\33.0.1\source.properties


Pkg.UserSrc=false
Pkg.Revision=33.0.1
#Pkg.Revision=33.0.0 rc4







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane. (Issue #2542)





 
Actually the source.properties file is from the Android SDK and it tells us what version of the Android build tools you have available.. e.g. on my computer:
 C:\Users\ukinanfr\AppData\Local\Android\Sdk\build-tools\33.0.0\source.properties  
But in our code I can see that we removed the "throw" if we encountered that...
 And actually, I don't even see these functions as being members of "AABOutputStream" - we have "getAapt" but not "getAapt2", and "getAndroidSDKBuildToolPath" is a member of "AndroidDeviceSDK.java" rather than "AABOutputStream.java".
 
Can you enable the debug log and post the output of that? (or if you're using the new AIR SDK Manager, just go to the "troubleshooting" tab and re-run the packaging..)
 
thanks

**Comment by pengyangjin** [comment]
“Can you enable the debug log and post the output of that?”&nbsp;How can I operate it？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午5:11
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复： [airsdk/Adobe-Runtime-Support] The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane. (Issue #2542)



Android\Sdk\build-tools\33.0.1\source.properties


Pkg.UserSrc=false
Pkg.Revision=33.0.1
#Pkg.Revision=33.0.0 rc4







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane. (Issue #2542)





 
Actually the source.properties file is from the Android SDK and it tells us what version of the Android build tools you have available.. e.g. on my computer:
 C:\Users\ukinanfr\AppData\Local\Android\Sdk\build-tools\33.0.0\source.properties  
But in our code I can see that we removed the "throw" if we encountered that...
 And actually, I don't even see these functions as being members of "AABOutputStream" - we have "getAapt" but not "getAapt2", and "getAndroidSDKBuildToolPath" is a member of "AndroidDeviceSDK.java" rather than "AABOutputStream.java".
 
Can you enable the debug log and post the output of that? (or if you're using the new AIR SDK Manager, just go to the "troubleshooting" tab and re-run the packaging..)
 
thanks

**Comment by ajwfrost** [comment]
If you create/edit a file:
`c:\users\username\.airsdk\adt.cfg`
and then add a line:
`DebugOut=true`
then run it again, a log file should be generated at:
`c:\users\username\adt.log`

thanks

**Comment by pengyangjin** [comment]
This is the log we captured:
adt.log&nbsp;


*** ADT Logging at 2023/03/24 10:24:14 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -certificate -cn UnitedMindsetSelfSignedCertificate -ou Software Development -o UnitedMindset -c US 2048-RSA ${KEYSTORE} 111111
*** ADT Logging at 2023/03/24 10:24:16 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -package -target aab -storetype pkcs12 -keystore antResource/key/apk/development-android.p12 -storepass xxxxxx D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/release/yttxkr-andefun-14.3.0-14.3.0.0-efun-20230324-102254-0.aab D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup-efun-app.xml -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup.swf -extdir D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/ane -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/media/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/icons/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/res . -platformsdk D:/application/Android/Sdk
Creating device SDK handler - location passed in = D:\application\Android\Sdk
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Gradle build where ADT is using JRE version 11.0.13
but where Gradle will be using the JDK from D:/application/jdk-11.0.13\bin\java.exe
Gradle build command:&nbsp; D:/application/jdk-11.0.13\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20" -cp "C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\gradle\wrapper\gradle-wrapper.jar";"D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease
..java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init&gt;(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: ???????? (uri:"", local:"extension-level")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;
Warning: ???????? (uri:"", local:"base-extension")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;


FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
&gt; Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
&nbsp; &nbsp;&gt; Failed to transform android-support-R-1.0.0.jar to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
&nbsp; &nbsp; &nbsp; &gt; Execution failed for JetifyTransform: C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\app\libs\android-support-R-1.0.0.jar.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&gt; Failed to transform 'C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\app\libs\android-support-R-1.0.0.jar' using Jetifier. Reason: ZipException, message: duplicate entry: androidx/core/R$drawable.class. (Run with --stacktrace for more details.)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Suggestions:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&amp;s=modified_time:desc, it's possible that this issue has already been filed there.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).


* Try:
&gt; Run with --stacktrace option to get the stack trace.
&gt; Run with --info or --debug option to get more log output.
&gt; Run with --scan to get full insights.


* Get more help at https://help.gradle.org


BUILD FAILED in 34s







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane. (Issue #2542)





 
If you create/edit a file:
 c:\users\username\.airsdk\adt.cfg
 and then add a line:
 DebugOut=true
 then run it again, a log file should be generated at:
 c:\users\username\adt.log
 
thanks

**Comment by pengyangjin** [comment]
> If you create/edit a file: `c:\users\username\.airsdk\adt.cfg` and then add a line: `DebugOut=true` then run it again, a log file should be generated at: `c:\users\username\adt.log`
> 
> thanks

This is the log we captured

**Comment by ajwfrost** [comment]
Okay so it's not throwing that `source.properties` error any more..?

The log output suggests it's all set up with the Android SDK and build tools, but then encounters a problem in Gradle whilst doing the bundle generation:
```
Execution failed for JetifyTransform: ... android-support-R-1.0.0.jar.
Failed to transform android-support-R-1.0.0.jar to match attributes
Reason: ZipException, message: duplicate entry: androidx/core/R$drawable.class.
```

This sounds like there are two ANEs that are using the androidx support library but with different names so we've been unable to filter them out .. or maybe one ANE that tries to define the resource values directly?! Are you able to look through the ANEs to find the one with that `android-support-R-1.0.0.jar` file in it? and perhaps then just remove that jar file using a zip manager? It sounds like that's a bit of a workaround type library, if it's got an 'R' in the filename maybe this is just providing resource definitions but those shouldn't be compiled ahead of time, we should just include the actual resources for compilation all together into the app.....

thanks

**Comment by pengyangjin** [comment]
The attachment is the ane that was packaged and reported an error,Only the unique ane is used in the project.
It should be possible to exclude conflicts caused by different ANEs using the same jar package.
What caused the conflict? I still can't find the reason.




*** ADT Logging at 2023/03/24 10:24:14 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -certificate -cn UnitedMindsetSelfSignedCertificate -ou Software Development -o UnitedMindset -c US 2048-RSA ${KEYSTORE} 111111
*** ADT Logging at 2023/03/24 10:24:16 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -package -target aab -storetype pkcs12 -keystore antResource/key/apk/development-android.p12 -storepass xxxxxx D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/release/yttxkr-andefun-14.3.0-14.3.0.0-efun-20230324-102254-0.aab D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup-efun-app.xml -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup.swf -extdir D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/ane -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/media/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/icons/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/res . -platformsdk D:/application/Android/Sdk
Creating device SDK handler - location passed in = D:\application\Android\Sdk
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Gradle build where ADT is using JRE version 11.0.13
but where Gradle will be using the JDK from D:/application/jdk-11.0.13\bin\java.exe
Gradle build command:&nbsp; D:/application/jdk-11.0.13\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20" -cp "C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\gradle\wrapper\gradle-wrapper.jar";"D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease
..java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init&gt;(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: ???????? (uri:"", local:"extension-level")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;
Warning: ???????? (uri:"", local:"base-extension")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
&gt; Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
&nbsp;&nbsp; &gt; Failed to transform android-support-R-1.0.0.jar to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &gt; Execution failed for JetifyTransform: C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\app\libs\android-support-R-1.0.0.jar.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &gt; Failed to transform 'C:\Users\yangjin1\AppData\Local\Temp\3401791a-dcc1-4376-a23d-30c3d25a9a20\app\libs\android-support-R-1.0.0.jar' using Jetifier. Reason: ZipException, message: duplicate entry: androidx/core/R$drawable.class. (Run with --stacktrace for more details.)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Suggestions:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&amp;s=modified_time:desc, it's possible that this issue has already been filed there.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
&gt; Run with --stacktrace option to get the stack trace.
&gt; Run with --info or --debug option to get more log output.
&gt; Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s

*** ADT Logging at 2023/03/27 09:56:15 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -certificate -cn UnitedMindsetSelfSignedCertificate -ou Software Development -o UnitedMindset -c US 2048-RSA ${KEYSTORE} 111111
*** ADT Logging at 2023/03/27 09:56:18 ***
Called by: D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\adt.jar
ADT 50.2.2.2 called with: -package -target aab -storetype pkcs12 -keystore antResource/key/apk/development-android.p12 -storepass xxxxxx D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/release/yttxkr-andefun-14.3.0-14.3.0.0-efun-20230327-095313-0.aab D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup-efun-app.xml -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/Startup.swf -extdir D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/ane -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/media/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/icons/ -C D:\yttx\client\branch\14.3.0.0\main\LueDi\ant/../../LueDi/build/res . -platformsdk D:/application/Android/Sdk
Creating device SDK handler - location passed in = D:\application\Android\Sdk
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Version in APK = 50.2.2.1, version of ADT = 50.2.2.2
Gradle build where ADT is using JRE version 11.0.13
but where Gradle will be using the JDK from D:/application/jdk-11.0.13\bin\java.exe
Gradle build command:&nbsp; D:/application/jdk-11.0.13\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Users\yangjin1\AppData\Local\Temp\6873cd1d-8d43-4d72-a336-5d9066fed359" -cp "C:\Users\yangjin1\AppData\Local\Temp\6873cd1d-8d43-4d72-a336-5d9066fed359\gradle\wrapper\gradle-wrapper.jar";"D:\SDK\flex_4.13_air_33.1_x64_50.2.2.2\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease
..java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init&gt;(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
Warning: ???????? (uri:"", local:"extension-level")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;
Warning: ???????? (uri:"", local:"base-extension")??????????<{}codename&gt;,<{}layoutlib&gt;,<{}api-level&gt;

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
&gt; Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
&nbsp;&nbsp; &gt; Failed to transform android-support-R-1.0.0.jar to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &gt; Execution failed for JetifyTransform: C:\Users\yangjin1\AppData\Local\Temp\6873cd1d-8d43-4d72-a336-5d9066fed359\app\libs\android-support-R-1.0.0.jar.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &gt; Failed to transform 'C:\Users\yangjin1\AppData\Local\Temp\6873cd1d-8d43-4d72-a336-5d9066fed359\app\libs\android-support-R-1.0.0.jar' using Jetifier. Reason: ZipException, message: duplicate entry: androidx/core/R$drawable.class. (Run with --stacktrace for more details.)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Suggestions:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&amp;s=modified_time:desc, it's possible that this issue has already been filed there.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
&gt; Run with --stacktrace option to get the stack trace.
&gt; Run with --info or --debug option to get more log output.
&gt; Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following error occurred when packaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error in ane. (Issue #2542)





 
Okay so it's not throwing that source.properties error any more..?
 
The log output suggests it's all set up with the Android SDK and build tools, but then encounters a problem in Gradle whilst doing the bundle generation:
 Execution failed for JetifyTransform: ... android-support-R-1.0.0.jar. Failed to transform android-support-R-1.0.0.jar to match attributes Reason: ZipException, message: duplicate entry: androidx/core/R$drawable.class.  
This sounds like there are two ANEs that are using the androidx support library but with different names so we've been unable to filter them out .. or maybe one ANE that tries to define the resource values directly?! Are you able to look through the ANEs to find the one with that android-support-R-1.0.0.jar file in it? and perhaps then just remove that jar file using a zip manager? It sounds like that's a bit of a workaround type library, if it's got an 'R' in the filename maybe this is just providing resource definitions but those shouldn't be compiled ahead of time, we should just include the actual resources for compilation all together into the app.....
 
thanks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

efun.ane (89.58M, 2023年04月26日 10:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=08343838cea254c2066a0031156200174d400f0d5506005918060d09034f020d0756155e560303155150005d5754070d07570c00336a325d53415616520c573808&code=54883b28

**Comment by pengyangjin** [comment]
Can you consider setting a packaging parameter to set&nbsp;android.enableJetifier=false？&nbsp;These jar files are developed by other manufacturers which is a Korean app store like Google Play.It is impossible to ask the manufacturer to modify these jar files.

---Original---
From: "Andrew ***@***.***&gt;
Date: Mon, Mar 27, 2023 19:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support] The following error occurred whenpackaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error inane. (Issue #2542)




 
@pengyangjin thanks for that -&gt; is that a third party ANE, or one that you are creating? As it's got a lot of resources in it, including a lot of older support libraries, and there's a conflict here because of the use of the Jetifier setting to try to convert the old to new:
 https://stackoverflow.com/questions/51680671/what-is-jetifier
 
If we use the "android-studio" target rather than "apk" or "aab", and then update the gradle.properties file to say that android.enableJetifier=false, it then builds okay. But ideally the ANE would be updated to use AndroidX directly....
 
thanks

**Comment by ajwfrost** [comment]
Sure thing, that's relatively straightforward. Are you using Animate or another IDE here? as there's a workaround you can apply, using the above steps i.e. use the AIR SDK tools to create an Android Studio project, and then open this up in Android Studio, change the gradle properties to turn off jetifier, and then build using normal Android Studio commands... -> let me know if you need more detailed steps/instructions for that.

An update to the properties for turning off jetifier would need to be something we add when updating the AIR namespace, so either 50.3 or 51.0... 

thanks

**Comment by pengyangjin** [comment]
We use Flash Builder as a coding IDE and use Hudson with ant scripts&nbsp; to package by QA, and the cost of process operation changes is very high.



---Original---
From: "Andrew ***@***.***&gt;
Date: Mon, Mar 27, 2023 19:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support] The following error occurred whenpackaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error inane. (Issue #2542)




 
Sure thing, that's relatively straightforward. Are you using Animate or another IDE here? as there's a workaround you can apply, using the above steps i.e. use the AIR SDK tools to create an Android Studio project, and then open this up in Android Studio, change the gradle properties to turn off jetifier, and then build using normal Android Studio commands... -&gt; let me know if you need more detailed steps/instructions for that.
 
An update to the properties for turning off jetifier would need to be something we add when updating the AIR namespace, so either 50.3 or 51.0...
 
thanks

**Comment by pengyangjin** [comment]
Hi,

I did not find this the properties for turning off jetifier has benn added in AIR 50.2.2.4 or AIR 50.2.2.3 ?I look forward to adding this parameter as soon as possible.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月27日(星期一) 晚上7:31
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] The following error occurred whenpackaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error inane. (Issue #2542)



We use Flash Builder as a coding IDE and use Hudson with ant scripts&nbsp; to package by QA, and the cost of process operation changes is very high.



---Original---
From: "Andrew ***@***.***&gt;
Date: Mon, Mar 27, 2023 19:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support] The following error occurred whenpackaging aab file using AIR 50.2.2.2 SDK. It is estimated to be an error inane. (Issue #2542)




 
Sure thing, that's relatively straightforward. Are you using Animate or another IDE here? as there's a workaround you can apply, using the above steps i.e. use the AIR SDK tools to create an Android Studio project, and then open this up in Android Studio, change the gradle properties to turn off jetifier, and then build using normal Android Studio commands... -&gt; let me know if you need more detailed steps/instructions for that.
 
An update to the properties for turning off jetifier would need to be something we add when updating the AIR namespace, so either 50.3 or 51.0...
 
thanks
