### ISSUE TITLE
Multithread Worker in iOS application no longer works after AIR 50.2.2.1

### ISSUE THREAD

**Issue by dseeker** [airsdk/Adobe-Runtime-Support#2566]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? 
AIR 50.2.2.1 
* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
iPhone X 14.8.1; iPad 9 16.3.1; Windows 8 (Animate CC 19 Debug)
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
I can reproduce consistently

I have a physics engine running on a worker thread. it's been working fine in all AIR versions from 30+, and it works on 50.2.1.1 but fails start the worker on 50.2.2.1 and latest 50.2.2.2
On Scout I can see the worker comes up in 50.2.1.1 but no session for worker shows up on 50.2.2.2, and it's not only a monitoring problem, on the application the game that uses the physics engines is also not visible/started.

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.

Give us a minimal example:

* As little code as possible. Get to the root of the problem!
Main:
```
private function startMainThread(): void{
    trace('-> startMainThread')

    var _urlRequest:URLRequest = new URLRequest("physicsengine.swf");
    var _loader:Loader = new Loader();
    var _lc:LoaderContext = new LoaderContext(false, ApplicationDomain.currentDomain, null);
    
    _loader.contentLoaderInfo.addEventListener(Event.COMPLETE,completeHandler);
    _loader.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR,errorHandler);
    _loader.load(_urlRequest, _lc);
}
public function completeHandler(e:Event):void{ 

    worker = WorkerDomain.current.createWorker(e.target.bytes);  
    channelToMain = worker.createMessageChannel(Worker.current);
    channelToMain.addEventListener(Event.CHANNEL_MESSAGE, onMessageFromWorker);
    worker.setSharedProperty("channelToMain", channelToMain);
    
    channelToWorker  = Worker.current.createMessageChannel(worker);	
    worker.setSharedProperty("channelToWorker", channelToWorker);
    
    worker.addEventListener(Event.WORKER_STATE, workerStateHandler); 
    worker.start();      
}
```

Worker:
```
private function startWorker():void{
			
	if (Worker.current.isPrimordial){ 
		if (Worker.current.isPrimordial) addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
		return; 
	}
   
	condition = new Condition(new Mutex());
	Worker.current.setSharedProperty("condition", condition);

	channelToMain = Worker.current.getSharedProperty("channelToMain") as MessageChannel;
	channelToWorker = Worker.current.getSharedProperty("channelToWorker") as MessageChannel;
	channelToWorker.addEventListener(Event.CHANNEL_MESSAGE, onMessageFromMain);	
	channelToMain.send({ready: true, framerate: stage.frameRate});
		
	while(true){
		condition.mutex.lock();
		condition.wait();
		cmd = Worker.current.getSharedProperty('cmd')
		if (cmd) Decode(cmd)
		cmd.lastframe = cmd.step
		Worker.current.setSharedProperty('cmd', cmd)
	}
}

```

## Known Workarounds

Copy "lib/adt.jar" file from latest SDK version (50.2.2.6) and overwrite it in folder of SDK version 50.2.1.1
the ADT that injects the appropriate codes for Xcode/iPhoneOS SDK versioning,

**Comment by dseeker** [comment]
Tested with 50.2.2.6, behavior has not changed. 
Let me know if you need support for testing the fix, this is preventing me from uploading new releases to testflight because of the xcode build version and is very important for our app.

**Comment by ajwfrost** [comment]
Hi - I believe this is an issue that has been fixed in the underlying code but needs to be released for iOS still. We may be able to check whether this is the thing I'm thinking of, if it's straightforward for you to build a set of `-debug` SWF files and then package them using `ipa-debug`, and then run it with a connection to Adobe Scout? If you try that, you may see an error being reported from Scout when the worker is being initialised.. (but don't go to too much effort if you don't have that sort of workflow set up already..)

I will try to also get a test runtime library uploaded for iPhoneOS so that you can check against that, within the next day or two.

thanks

**Comment by dseeker** [comment]
Thanks @ajwfrost, that's good to hear. I have the scout setup, I can show how the worker looks in 50.2.1.1
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/11655138/118ff327-99c1-4195-aeed-2f6e422ce6c3)

When running with 5.2.2.6 the worker does not show up in scout. There are no errors in the main thread code.

On the release notes of 50.2.2.1 there is an issue which could have caused it as it relates to wokers
> Github-2385: Ensuring Worker isolates load ANE swf definitions at start-up

In the interim before the fix is out, I could use ver 50.2.1.1 compiled with the latest xcode to allow the Appstore to accept my app, would that be possible?

**Comment by ajwfrost** [comment]
Yes that's the likely culprit, when we load the SWF definitions we have seen sometimes there's a permission failure in getting at the library file and this was causing an AS3 exception that wasn't being handled in the right place, meaning that it was as if the Worker start-up code itself threw the exception.

> In the interim before the fix is out, I could use ver 50.2.1.1 compiled with the latest xcode to allow the Appstore to accept my app, would that be possible?

Actually yes, it should be possible to use AIR SDK 50.2.1.1 and then you could take just the file "lib/adt.jar" from 50.2.2.2 or later. It's the ADT that injects the appropriate codes for Xcode/iPhoneOS SDK versioning,

thanks

**Comment by dseeker** [comment]
@ajwfrost excellent! that worked, the app was accepted by Transporter. 
this will allow me to stay on this version until the worker fix is released, thank you!! :tada:

**Comment by ajwfrost** [comment]
Great, thanks for confirming..

**Comment by dseeker** [comment]
I just re-tested on the latest SDK and the workers are working as expected
