### ISSUE TITLE
Scoped Storage Implementation Issue

### ISSUE THREAD

**Issue by sairope** [airsdk/Adobe-Runtime-Support#2591]
I'm trying to save my bitmapdata as png to local folder on Android, and I can't get it to work. I do get the window with folder selection and ability to give permision, but as soon as I do that, I get another selection, but this time for a file. If I select any file or go back to the app I get 'save failed' message. Any ideas?

```
private function saveHandler(e: MouseEvent): void {
// get drawing as bitmapdata from the canvas instance.
var canvasBmp:BitmapData = canvas.drawing();

// create new png encoder object and convert bitmapdata to png
pngStream = PNGEncoder.encode(canvasBmp);

// dispose of the bitmapdata object when finished.
canvasBmp.dispose();`

// Use intent-based mechanism to select a directory to save the file
selectedDirectory = new File();
selectedDirectory.addEventListener(Event.SELECT, onSaveDirectorySelected);
selectedDirectory.browseForDirectory("Select Directory to Save");

}

private function onSaveDirectorySelected(event:Event):void {
	
selectedDirectory.removeEventListener(Event.SELECT, onSaveDirectorySelected);

// Get selected directory and request write permission
selectedDir = event.target as File;
selectedDir.addEventListener(PermissionEvent.PERMISSION_STATUS, onPermissionStatus);
selectedDir.requestPermission();

// Construct file name with timestamp
var currentDate:Date = new Date();
var dateString:String = currentDate.fullYear + "_" + (currentDate.month + 1) + "_" + currentDate.date;
var timeString:String = currentDate.hours + "" + currentDate.minutes + "" + currentDate.seconds;
fileName = "my image " + dateString + " " + timeString + ".png";

	
}

private function onPermissionStatus(e: PermissionEvent): void {
if (e.status == PermissionStatus.GRANTED) {
var file:File = selectedDir.resolvePath(fileName);
var stream:FileStream = new FileStream();
stream.open(file, FileMode.WRITE);
stream.writeBytes(pngStream);
stream.close();

    // Remove text from log.text after 3s.
    log.text = "Image saved";
    timer = new Timer(3000, 1);
    timer.addEventListener(TimerEvent.TIMER, removeText);
    timer.start();
} else {

    // Remove text from log.text after 3s.
    log.text = "Save failed";
    timer = new Timer(3000, 1);
    timer.addEventListener(TimerEvent.TIMER, removeText);
    timer.start();
}
}
```

**Comment by ajwfrost** [comment]
Hi

You shouldn't use the "requestPermission()" call there, the expectation with scoped storage is that in choosing a folder, you will be granted the permissions to read/write into that folder. (If you need to call "requestPermission()" so that it still works for older phone models, then do this right at the start using a new File object before setting its nativePath).

There's a bug though, in the current runtimes, so this should then work once we've pushed out 50.2.2.4 very shortly...

thanks

**Comment by sairope** [comment]
> Hi
> 
> You shouldn't use the "requestPermission()" call there, the expectation with scoped storage is that in choosing a folder, you will be granted the permissions to read/write into that folder. (If you need to call "requestPermission()" so that it still works for older phone models, then do this right at the start using a new File object before setting its nativePath).
> 
> There's a bug though, in the current runtimes, so this should then work once we've pushed out 50.2.2.4 very shortly...
> 
> thanks

I tried removing requestPermission() call, but still nothing happens except for the folder selection to obtain permission. It just doesn't save the file at all. I'm using SDK 50.2.1.1 since 50.2.2.3 results in instant startup crash. Saving works fibe on SDK 33 so I have no idea why it refuses to save the file despite obtaining the permission.

```
private function onSaveDirectorySelected(event:Event):void {
	
selectedDirectory.removeEventListener(Event.SELECT, onSaveDirectorySelected);

// Get selected directory and request write permission
selectedDir = event.target as File;

// Construct file name with timestamp
var currentDate:Date = new Date();
var dateString:String = currentDate.fullYear + "_" + (currentDate.month + 1) + "_" + currentDate.date;
var timeString:String = currentDate.hours + "" + currentDate.minutes + "" + currentDate.seconds;
fileName = "my image " + dateString + " " + timeString + ".png";

var file:File = selectedDir.resolvePath(fileName);
var stream:FileStream = new FileStream();
stream.open(file, FileMode.WRITE);
stream.writeBytes(pngStream);
stream.close();
	
}
```

**Comment by sairope** [comment]
> 

With an updated AIR 50.2.2.4 the app saves an empty png file and then crashes.

**Comment by ajwfrost** [comment]
Hi - we have some fixes to put in still, but just to point out the asynchronous write mechanism is actually where you can just throw the pngStream byte array at the stream, and it will be written out asynchronously (in a background thread). The write instructions (and 'close') just get queued up... So the above code wouldn't normally work, you can ignore that 'complete' event handler and just directly call:
```
    var stream:FileStream = new FileStream();
    stream.openAsync(file, FileMode.WRITE);
    stream.writeBytes(pngStream);
    stream.close();
```
all in a row.

See the final paragraph of https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118666ade46-7db1.html

thanks
