### ISSUE TITLE
[FEATURE REQUEST]Dispatch MouseEvent.MOUSE_WHEEL, MouseEvent.MIDDLE_MOUSE_UP, and MouseEvent.MIDDLE_MOUSE_DOWN events when bluetooth mouse is connected.

### ISSUE THREAD

**Issue by hardcoremore** [airsdk/Adobe-Runtime-Support#260]
As the title suggest can you please implement dispatching mouse scroll button events when mouse is connected to android or ios device. I have Samsung Galaxy Note 10 Plus phone and when I connect mouse everything works great except mouse middle (scroll) button. Here for my case the more important one is MOUSE_WHEEL event so that user can scroll through the Feathers UI list or zoom in on the stage in my level editor.

Is this possible to implement? How difficult it would be to dispatch these events?

It would increase usability of my app so much, especially when there are leaks already that in one month Apple will release new iPad pro with full mouse support :)

Thanks,

Caslav

**Comment by hardcoremore** [comment]
Apple just released iOS 13.4 where trackpad is supported for iPads so this feature will be required for iOS as well :)

**Comment by hardcoremore** [comment]
Hi @ajwfrost,

I have just tested this again. Bluetooth Keyboard is working great, Bluetooth mouse is working great when connected to Android device (Samsung Galaxy Note 10 plus). But it is just missing few events for mouse middle button click and mouse scroll events so that everything is complete . Can you please look into it. Thanks!

**Comment by ajwfrost** [comment]
@hardcoremore just getting hold of a bluetooth mouse, we should be able to get this sorted out...
thanks

**Comment by hardcoremore** [comment]
@ajwfrost , thanks Andrew!

**Comment by ajwfrost** [comment]
@hardcoremore  I'm curious in terms of what you're seeing currently? The right-mouse click is (mostly?) mapping to the Android 'back' button, which means you can detect it from the Keyboard event handler (and prevent the default behaviour) but as far as I can see, Android isn't sending in any other motion event for this (at least on the Samsung device being used for testing). So, are you actually seeing a MouseEvent or TouchEvent being dispatched for this?

In terms of the middle-click, this is being captured by the OS and turned into a "home" button, which doesn't even come to us in any form so there's no way we can see of preventing this..
```
05-28 18:17:25.153  5446  5613 D InputReader: Input event(16): value=1 when=941503.901111
05-28 18:17:25.153  5446  5613 D InputManager-JNI: !@interceptKeyBeforeQueueing(0), action=0, interactive=true
05-28 18:17:25.157  5446  5613 D API test: getContainerInfo: value is 10,1343225952
05-28 18:17:25.157  5446  5613 D SamsungPhoneWindowManager: sec interceptKeyTq home s_result=1
05-28 18:17:25.157  5446  5613 D WindowManager: interceptKeyTq s_result=1
05-28 18:17:25.157  5446  5613 D InputManager-JNI: !@handleInterceptActions(0), action=0, wmActions=1
05-28 18:17:25.162  5446  5612 D API test: getContainerInfo: value is 10,1343225952
05-28 18:17:25.165  5446  5612 I Telecom:SamsungTelecomServiceImpl: isRinging - callingPackage : android
05-28 18:17:25.165  5446  5612 D RestrictionPolicy: isHomeKeyEnabled :true
05-28 18:17:25.165  5446  5612 I chatty  : uid=1000(system) InputDispatcher identical 1 line
05-28 18:17:25.167  5446  5612 D API test: getContainerInfo: value is 10,1343225952
```
So I'm not entirely sure whether it would be able to work here... we can check with another device perhaps (or if you can see what events the InputManager says it's providing to AIR, we can probably work it out from there...). From what we can see though, it's going to be OEM-dependent...

FYI the scroll works though, getting MOUSE_WHEEL events coming into AS3 now...

thanks

**Comment by ajwfrost** [comment]
FYI, mouse wheel support is in 33.1.1.533; per the above, we're not able to override the OEM handling of the middle/right click events though...
