### ISSUE TITLE
HARMAN SDK 50.2.2.4 - execution failed for task ':app:lintvitalrelease'. error

### ISSUE THREAD

**Issue by kurtongicognite** [airsdk/Adobe-Runtime-Support#2657]
Good day, (Trying to build an Android release) anyone who also encounter this problem? I would like to ask for fix? Thank you.

used:

AS3
HARMAN SDK 50.2.2.4
VS CODE STUDIO

Found some solution from other post but it seems it's for jave case? or Android Studio? I don't have build.gradle on my folder either.

Thank you in advance for the correction/answer.

**Comment by kurtongicognite** [comment]
1 errors, 0 warnings
Lint found fatal errors while assembling a release target.

To proceed, either fix the issues identified by lint, or modify your build script as follows:
...
android {
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintTask$AndroidLintLauncherWorkAction
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
         > Lint found fatal errors while assembling a release target.

**Comment by ajwfrost** [comment]
Hi

The actual failure from Lint isn't shown in the above logs? It just says that Lint failed in its "lintVitalRelease" task... can you please check and see if there's addition information e.g. a line that starts "Error: ..."?

thanks

**Comment by ajwfrost** [comment]
Hi

Thanks .. but that's still not saying there are any errors! Strange output here:
```
Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered...
Warning: unexpected element (uri:"", local:"extension-level")...
Warning: unexpected element (uri:"", local:"base-extension")...
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.

1 errors, 0 warnings
Lint found fatal errors while assembling a release target.
```

So it lists 6 warnings, then says there are no warnings but one error.

I suspect we'll need to switch the "abortOnError" setting to false, per the suggestion there. I've seen all those warnings before apart from the `extension-level` and `base-extension` ones, so perhaps see whether you have anything in your manifest additions that may have these elements?

thanks

**Comment by kurtongicognite** [comment]
so weird , I just updated my sdk and roll back to jdk 18

and also detected that the xml file used has issue.

this is seems an isolated case. 

It's okay now. closing thread.

Thanks.

**Comment by ajwfrost** [comment]
Hi

Interestingly I've just tried running lintRelease on a project here and it's complained of an issue:
```
 Call requires API level 19 (current min is 8): android.content.ContentResolver#getPersistedUriPermissions [NewApi]
                List<UriPermission> arrPermissions = m_ctx.getContentResolver().getPersistedUriPermissions();
```
and this is in one of our new file-management classes. So, obviously something that we need to fix; but also, we should add the ability to ignore issues (or report them as warnings rather than errors).

Looks like we also need to adjust our templates to avoid having a default minimum SDK value of 8..! Should be 16 really, and 21 for the 64-bit platforms.

thanks

**Comment by kurtongicognite** [comment]
I see.. Thanks, we will wait for that patch/update/fix soon .. It will also help us move on with our case too.. more power and best regards.  **cheers

**Comment by ajwfrost** [comment]
Should be out tomorrow, got a bit delayed due to IT/network issues :-(

**Comment by kurtongicognite** [comment]
@ajwfrost thank you for all the response and time.

corrected they target minimum target key in xml. Working now. 

Closing thread.
