### ISSUE TITLE
Worker steady Memory increase / Memory Leak (with 50.2.x but not with 33.1.1.795)

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#2665]
Using a Worker with **AIR SDK v50.2.1.1** (also **v50.2.2.5** and likely also a few earlier versions) causes a steady increase in memory usage / memory leak. The last **AIR SDK v33.1.1.795** does not have this steady increase and falls back to "normal" memory usage after a while.

A demo with two compiled Release Builds with Captive Runtime (Windows) is linked/attached below.
The Sources with an IntelliJ Project are also inside the link/attachment.

**Test Scenario:**
- Worker sends a `String` to main app every 1ms
- Worker is running/open all the time

**Observations:**
- Data throughput is faster in v50
- After 30s to 1m you can see the memory usage still goes up in v50, v33 falls back
- Stopping v50 you can see that the memory still increases most of the time, in v33 it does not
- Sending a `ByteArray` rather than a `String` does not lead to memory increase in v50

**Screenshots:**
v50-1
![v50-1](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/7c1b970d-91a4-4ce7-b709-0c1805e1323a)

v50-2
![v50-2](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/070109b5-9fbe-4a6f-854c-5e5bc6cf59dc)

----------------------------------------------------

v33-1
![v33-1](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/bc2fe9bf-d5a7-43f0-8de8-f8c71a5e02d6)

v33-2
![v33-2](https://github.com/airsdk/Adobe-Runtime-Support/assets/73781224/03275971-a366-41f4-b073-cb8fae95a7d3)

**Demo/Attachment:** (Source code compilation requires Flex SDK; see below for Pure ActionScript Sources!)
[WorkerMemTest.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11556061/WorkerMemTest.zip)

**Comment by 2jfw** [comment]
Here is a pure ActionScript Demo (includes IntelliJ project files) without Flex dependencies:

[IntelliJ Project (Pure ActionScript).zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11562746/IntelliJ.Project.Pure.ActionScript.zip)

**Comment by ajwfrost** [comment]
Adding a comment on here -> the issue was introduced with a change in 33.1.1.929 relating to #402  - and seems to be caused by us then preventing the receiving player from triggering garbage collection relating to the serialized message.

Fix should be in our next release. Plus some optimizations to free the memory used in the serialization code early rather than waiting for GC.

**Comment by 2jfw** [comment]
Closed as it is fixed
