### ISSUE TITLE
iOS Simulator 16.4 - Undefined symbols for architecture x86_64 

### ISSUE THREAD

**Issue by dean-watson** [airsdk/Adobe-Runtime-Support#2684]
I am currently having an issue when trying to debug on an iOS simulator using Intellij Idea. I am using a MacBook M2 device, running Rosetta for use with Animate CC. I have no issues when using SDK 33.1 only with SDKs 50+.

Error Output:

Undefined symbols for architecture x86_64: "_AVAudioSessionCategoryAmbient", referenced from: __ZN13CocoaSoundMix27UpdateAudioPlaybackModeImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN20CTMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) "_AVAudioSessionCategoryPlayAndRecord", referenced from: __ZN21CTAudioSessionManager22InitializeAudioSessionEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) __ZN21CTAudioSessionManager23SetAudioSessionCategoryEP8NSString in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) __ZN13CocoaSoundMix27UpdateAudioPlaybackModeImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN20CTMicrophoneProvider23SetupAndStartAudioQueueEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AVAudioSessionCategoryPlayback", referenced from: __ZN21CTAudioSessionManager22InitializeAudioSessionEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) __ZN21CTAudioSessionManager23SetAudioSessionCategoryEP8NSString in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) __ZN13CocoaSoundMix27UpdateAudioPlaybackModeImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN20CTMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) "_AVAudioSessionInterruptionNotification", referenced from: +[InterruptionListener onAudioSessionEvent:] in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) +[InterruptionListener initializeNotification] in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) "_AVAudioSessionInterruptionTypeKey", referenced from: +[InterruptionListener onAudioSessionEvent:] in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) "_AVAudioSessionModeVoiceChat", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AVAudioSessionPortBluetoothHFP", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN18EnhSpeakerProvider24AudioRouteChangeCallbackEPvjjPKv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider24AudioRouteChangeCallbackEPvjjPKv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AVAudioSessionPortBuiltInSpeaker", referenced from: __ZN21CTAudioSessionManager16UpdateAudioRouteEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) "_AVAudioSessionPortHeadphones", referenced from: __ZN21CTAudioSessionManager22AreHeadphonesConnectedEv in libRuntimeInterpreter.x86-simulator-air.a(CTAudioSessionManager.o) "_AVLayerVideoGravityResize", referenced from: -[CTVideoViewController initializePlayer:] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) "_AVMediaCharacteristicVisual", referenced from: -[CTVideoTextureController setVideoTrackStatus:] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) "_AVMediaTypeAudio", referenced from: __ZN19CTPermissionManager15checkPermissionE10Permission in libRuntimeInterpreter.x86-simulator-air.a(CTPermissionManager.o) __ZN19CTPermissionManager17requestPermissionE10PermissionP24IPermissionEventListener in libRuntimeInterpreter.x86-simulator-air.a(CTPermissionManager.o) "_AVMediaTypeText", referenced from: -[CTVideoViewController playerStatusChange] in libRuntimeInterpreter.x86-simulator -air.a(CTVideoViewController.o) -[CTVideoTextureController playerStatusChange] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) "_AVMediaTypeVideo", referenced from: -[CTVideoViewController playerStatusChange] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) -[CTVideoTextureController playerStatusChange] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) __ZN19CTPermissionManager15checkPermissionE10Permission in libRuntimeInterpreter.x86-simulator-air.a(CTPermissionManager.o) __ZN19CTPermissionManager17requestPermissionE10PermissionP24IPermissionEventListener in libRuntimeInterpreter.x86-simulator-air.a(CTPermissionManager.o) "_AVPlayerItemDidPlayToEndTimeNotification", referenced from: -[CTVideoViewController initializePlayer:] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) -[CTVideoViewController stop] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) -[CTVideoTextureController initializePlayer:] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) -[CTVideoTextureController stop] in libRuntimeInterpreter.x86-simulator-air.a(CTVideoViewController.o) "_AudioComponentFindNext", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioComponentInstanceDispose", referenced from: __ZN18EnhSpeakerProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioComponentInstanceNew", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioConverterDispose", referenced from: __ZN18EnhSpeakerProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioConverterFillComplexBuffer", referenced from: __ZN18EnhSpeakerProvider9audioProcEPvPjPK14AudioTimeStampjjP15AudioBufferList in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider17GetNextBufferImplEPvRbS1_ in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioConverterNew", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioConverterSetProperty", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioOutputUnitStart", referenced from: __ZN18EnhSpeakerProvider8OpenImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider8OpenImplEi in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioOutputUnitStop", referenced from: __ZN18EnhSpeakerProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) __ZN21EnhMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophoneEnh.o) "_AudioQueueAllocateBuffer", referenced from: __ZN13CocoaSoundMix22PlatformOpenDeviceImplEPK16CSoundDescriptor in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN20CTMicrophoneProvider23SetupAndStartAudioQueueEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN17CTSpeakerProvider24_SetupAndStartAudioQueueEv in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) "_Aud ioQueueDispose", referenced from: __ZN13CocoaSoundMix22PlatformOpenDeviceImplEPK16CSoundDescriptor in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN13CocoaSoundMix23PlatformCloseDeviceImplEb in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) __ZN20CTMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN17CTSpeakerProvider24_SetupAndStartAudioQueueEv in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) __ZN17CTSpeakerProvider8StopImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) "_AudioQueueEnqueueBuffer", referenced from: __ZN20CTMicrophoneProvider23SetupAndStartAudioQueueEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN20CTMicrophoneProvider19RecordSoundCallbackEP16OpaqueAudioQueueP16AudioQueueBufferPK14AudioTimeStampjPK28AudioStreamPacketDescription in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN17CTSpeakerProvider17PlaySoundCallbackEP16OpaqueAudioQueueP16AudioQueueBuffer in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) "_AudioQueueEnqueueBufferWithParameters", referenced from: __ZN13CocoaSoundMix13BufferOutImplEP10WaveHeader in libRuntimeInterpreter.x86-simulator-air.a(CTAudioOutput.o) "_AudioQueueFlush", referenced from: __ZN20CTMicrophoneProvider9CloseImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTMicrophone.o) __ZN17CTSpeakerProvider8StopImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) "_AudioQueueFreeBuffer", referenced from: __ZN17CTSpeakerProvider8StopImplEv in libRuntimeInterpreter.x86-simulator-air.a(CTSpeaker.o) "_AudioQueueGetParameter", referenced from: __ZN13CocoaSoundMix22PlatformOpenDeviceImplEPK16CSoundDescriptor in...

Any help or guidance will

**Comment by ajwfrost** [comment]
Hi

Not able to reproduce this one I'm afraid, are you able to run the AIR SDK Manager and set it to the "Troubleshooting" screen, and then publish it again? Then if you can copy/paste the generated log information in here, we can see what's happening.

There should be a line like:
```
ld64 command line: /usr/bin/ld .... -arch x86_64 -syslibroot /path/to/iPhoneSimulator.sdk ... -framework AVFoundation ... -platform-version ios-simulator 11.0 16.2
```
Hopefully that's then immediately before your error output..?

thanks

**Comment by dean-watson** [comment]
Hi,

Please see the below for the output from the troubleshooting window. 

ld64 command line: /usr/bin/ld -pie -ObjC -dead_strip -Z -arch x86_64 -syslibroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk" -L/usr/lib -F"/System/Library/Frameworks" -L"/Users/deanwatson/AirSDK/AIRSDK_50.2.2/lib/aot/lib" -o "../aot12406808875456703716.tmp" -exported_symbol _main -exported_symbol __mh_execute_header -x "/Users/deanwatson/AirSDK/AIRSDK_50.2.2/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a" -lc++ -lSystem -U ___darwin_check_fd_set_overflow -lz -lobjc -lclang_rt.ios -framework CoreFoundation -framework UIKit -framework MobileCoreServices -framework CoreGraphics -framework Foundation -framework SystemConfiguration -framework AudioToolbox -framework CFNetwork -framework QuartzCore -framework OpenGLES -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework AVFoundation -framework Security -framework GameController -framework CoreMotion -framework AssetsLibrary -framework WebKit -w -filelist "/Users/deanwatson/IdeaProjects/TestApp/out/production/TestApp/AOTBuildOutput12631878589817885658.tmp/OBJFilesList.txt" -platform_version ios-simulator 13.0 16.2

Output after this is the same as I originally posted. I have tried using Animate CC and the Simulator is working fine with SDK 50.2.2, so wondering is this an Idea plugin issue with the newer SDK?

Cheers
Dean

**Comment by ajwfrost** [comment]
I think this is actually just the fact that your set-up is using the iPhoneOS SDK, and that's not got the x86_64 symbols present in it. You'd need to use the iPhoneSimulator SDK in order to get those simulators.

`"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk"` is listed in your command line there as the syslibroot...

In Animate, in the public settings for AIR for iOS, can you try changing the iOS Simulator SDK folder so that it's:
"/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk"

thanks

**Comment by dean-watson** [comment]
I have worked out what my problem is, in the AIRSDKManager in the configuration section and for the iOS Platform SDK I have had that set to the iPhoneOS SDK not the Simulator SDK. This wasn't an issue when using AIR SDK 33.1 but seem to be an issue for me when using 50.2.

Is the iOS Platform SDK path in the AIRSDKManager meant to point to the Simulator or the iPhone SDK? Either way happy for the bug to be closed, if you believe everything is working to design.

Cheers

**Comment by ajwfrost** [comment]
Ah - so yes, I guess if you have that path set in the SDK Manager / configuration file, it would override what was set in Animate. Yes that should be the simulator SDK -> we can update that label..

thanks

**Comment by dean-watson** [comment]
An update to the label could be helpful to match the labelling of other IDEs/Configs.

Cheers
