### ISSUE TITLE
TextField can't display some Unicode characters

### ISSUE THREAD

**Issue by ylazy** [airsdk/Adobe-Runtime-Support#2688]
Hi!

When I tried to use a TextField (embed font: Consolas) to display these characters:
`ⒸⒻⓁ`
They display as zero-width characters.
If I select all the TextField and copy/paste to a TextEditor (VSCode for example), I see these characters there.

Is this a bug or a limitation of TextField?

Thanks!

**Comment by manishpatel0404** [comment]
Maybe, this [ajwfrost](https://github.com/airsdk/Adobe-Runtime-Support/discussions/1143#discussioncomment-3428686) response with help answer your question.

**Comment by ylazy** [comment]
Thank you, but I think it's another case, as `Ⓒ` is a single character and doesn't require ligatures.

**Comment by ylazy** [comment]
If I use Device Font (Consolas), `Ⓒ` is displayed as `[?]`

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6010183/501bebe7-c252-4bd7-b35a-9b214d96b5ba)

But if I use Device Font (Segoe UI), it display correctly:

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6010183/b7888394-05be-413e-91c4-ac5a01b98d25)

**Comment by M4rkY4** [comment]
Hi, did you check if Consolas font contains graphics for copyright symbol at all ( just by typing it in Word or Photoshop )?
Are you talking about Flash TextField or Starling TextField? Are you sure you embedded all glyphs from the font, not only basic, in case of embedding with Adobe Animate?

**Comment by ylazy** [comment]
The [Consolas](https://learn.microsoft.com/vi-vn/typography/font-list/consolas) font is the default editor font for VSCode. It contains almost all symbols, including ⒸⒻⓁ. It displays normally with Word, PS, AI, VSCode...
I'm talking about Flash TextField. I'm also embed these characters:

```as
[Embed(
	source					=	"assets/Consolas/7.0/consola.ttf",
	fontName				=	"Consolas",
	fontWeight				=	"normal",
	fontStyle				=	"normal",
	mimeType				=	"application/x-font",
	embedAsCFF				=	"false",
	advancedAntiAliasing	=	"true",gridFitType
	unicodeRange			=	"U+0020-007E,U+00C0-00C3,U+00C8-00CA,U+00CC-00CD,U+00D2-00D5,U+00D9-00DA,U+00DD,U+00E0-00E3,U+00E8-00EA,U+00EC-00ED,U+00F2-00F5,U+00F9-00FA,U+00FD,U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+1EA0-1EF9,U+20AB,U+249C-24E9,U+25A0"
)]
```

[Ⓒ](https://www.compart.com/en/unicode/U+24B8) (U+24B8) is in the range `U+249C-24E9` and it called **Circled Latin Capital Letter C**.

**Comment by ylazy** [comment]
> it converts to the character but switches to "MS Gothic" font...

Oh I see that. It's my fault. I saw it displayed and then I thought these characters is included in the font. In my Word it switches to "MS Gothic" too.

I guess VSCode can display these character because the editor can determine whether a character is displayed or not, then it will use a fallback font if the character not found (like Arial Unicode MS).

When I change the embed font to Arial Unicode MS, everything is ok now.

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6010183/1810a9d8-a1d4-4b6a-b914-adc108503c16)
