### ISSUE TITLE
[AIR 50.2.2.6][IOS]Crash on IOS15 when ANE include third part swift frameworks

### ISSUE THREAD

**Issue by AleDaDa** [airsdk/Adobe-Runtime-Support#2692]
## Problem Description

Describe your problem in detail. Include the following information:

* Which AIR SDK did you use? 
  air sdk 50.2.2.6
* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
  IOS, compile ANE with Xcode 14.3.1
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
  yes

## Steps to Reproduce
I'm trying to intigrate [TapTap SDK](https://github.com/taptap/TapSDK-iOS/releases). 
I'm using 3 frameworks of TapTap:
1. AntiAddictionService.framework  ( coding in swift )
2. AntiAddictionUI.framework ( coding in Objective-C )
3. TapCommonSDK.framework 

In my work, I compile the .a file as usual, then pack ANE seems ok, and pack .IPA is OK too.
And the App test fine on some devices( IOS 16 + ), but crash on statr when devies( IOS 14.7, IOS 13.6, maybe IOS 15-? ).
In Crash Report, the App cannot find some swift functions when App start in IOS 14.7 ( or some version before ).

I have try some different situation:

Use  static version of AntiAddictionService.framework.
Include swift lib files( eg libswiftCore.dylib ) while complie ANE, and also inclued swift libs while packaging the  .IPA file. 
It occurs errs when compile .IPA file:

```
 unexpected failure: not a MachO binary
java.io.IOException: not a MachO binary
	at com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java)
	at com.adobe.air.ipa.MachoSigner.sign(MachoSigner.java)
	at com.adobe.air.ipa.IPASigner.signMacho(IPASigner.java)
	at com.adobe.air.ipa.IPAOutputStream.finalizeFrameworkSig(IPAOutputStream.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
```

then I try thin the "TapTap" frameworks using lipo, and places them in the root/Frameworks. It still occurs Errs:

```
unexpected failure: Negative seek offset
java.io.IOException: Negative seek offset
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:555)
	at com.adobe.air.ipa.IPASigner.prepareToSignFramework(IPASigner.java)
	at com.adobe.air.ipa.IPAOutputStream.finalizeFrameworkSig(IPAOutputStream.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
```
I try remove the TapTap frameworks, and only leave swift .dylib files in root/Frameworks ( copy from "airsdk/lib/aot/stub" ).
I still face the "unexpected failure: Negative seek offset" when compile the .IPA file.
I have tried include the dynamic version of AntiAddictionService.framework, but it seems nothing changed.

I'm confusing about : should I resign the swift framework file in root/Frameworks ? or could some guys can tell me something I should do ? I have stuck in this stuff for days. Thankssssssss.

btw, I find the .dylib files in airsdk seems diff from [ios_dependencies.zip](https://github.com/tuarua/Swift-IOS-ANE/releases/download/5.7.2/ios_dependencies.zip) ? Should I replace into airsdk folder?

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by AleDaDa** [comment]
@tuarua @ajwfrost   could you please have a look ?

**Comment by AleDaDa** [comment]
Seems I get through it ?
1. While compile ANE, I include the taptap swift lib( AntiAddictionService.framework ), and keep it in packageDepandency.
Do not include any xcode swift dylibs ( eg libswiftCore.dylib ).
2. While package .IPA file, place the taptap swift lib( AntiAddictionService.framework ) in the root/Frameworks. And include it while using ADT command. 
Most important: Do not include any libswiftxxxxxxxxxx files ( eg libswiftCore.dylib ) while compile ANE or package .ipa file.

So. I think this issues should be closed.
Hope this will help anyone stucking in this.

**Comment by marchbold** [comment]
@AleDaDa Great to hear you found the solution.

Couple of notes:
- with dylib files these are no longer required to be packaged with your application as long as you target iOS 12.4+ (this is when Apple started packaging them with iOS). If you do need to target a lower version then you need to find the correct swift lib versions that match the version used by the framework otherwise you'll get compiler errors.
- you only need to include frameworks in the `Frameworks` folder if they are "dynamic" i.e. loaded at runtime rather than compiled into your app. When doing this make sure you add the `-rpath @executable_path/Frameworks` into your platform xml linker options and you still need to include the framework in the `packagedDependencies`.
- A crash on startup is often linked to a missing dynamic framework ;)

**Comment by AleDaDa** [comment]
> 

Thanks a lot for reply. I think if your msg recorded in the airsdk.dev, it could save a lot guys like me.

**Comment by marchbold** [comment]
Yeah I think I need to spend a few weeks and write up some ANE related docs. Just need to find some time :|
