### ISSUE TITLE
Unable to compile aab from a blank animate fla

### ISSUE THREAD

**Issue by jabirraju** [airsdk/Adobe-Runtime-Support#2700]
## Problem Description
I am unable to compile aab format from Adobe Animate cc v 21.0.8 in Windows 10
adobe air SDK 50.2.2.6
no .ane used in fla. fla just has a rectangle drawn
there is just a var declaration in fla. no other as3 used.

entry in adt.cfg is as follows
#DefaultArch=armv8
#OverrideArch=armv8
CreateAndroidAppBundle=true
JAVA_HOME=C:\\Program Files\\Android\\Android Studio\\jre

![unable to exprt a blank fla](https://github.com/airsdk/Adobe-Runtime-Support/assets/68838/a0f48751-04a1-4353-a7d5-64ced69f9ccd)

**Comment by jabirraju** [comment]
error show in dialog is as below
Error creating files.
Unknown error.

unexpected failure: Unable to run java com.adobe air ADTException: grade tool failed:
FAILURE: Build completed with 2 failures.

Task failed with an exception.

What went wrong:
Execution failed for task appiprocessReleaseResources
> Afailure occurred while executing com.android.build.gradle internal res.LinkApplicationAndroidResourcesTaskSTaskAction
> AAPT2 3apt2-7.0.1-7396180-windows Daemon #1: Unexpected error during link, attempting to stop daemon.
This should not happen under normal circumstances, please file an issue if ft does.

“Ty

> Run with —stackirace option to get the stack trace.

> Run with ~info or debug option to get more log output.
> Run with —scan to get full insights.

2: Task failed with an exception.

What went wrong:
Execution failed for task “appibundieReleaseResources.
> Afailure occurred while executing com.android.build.gradle internal res. Aapt2ProcessResourcesRunnable
> AAPT2 3apt2-7.0.1-7396180-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
This should not happen under normal circumstances, please file an issue if ft does.

“Ty

> Run with —stackirace option to get the stack trace.

> Run with ~info or debug option to get more log output.
> Run with —scan to get full insights.

* Get more help at hitps:/help.gradie.org
BUILD FAILED in 255

java.io |OBxception: Unable to run java: com.adobe.air ADTException: grade tool failed:
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

What went wrong:

Execution failed for task appiprocessReleaseResources

> Afailure occurred while executing com.android.build.gradle internal res.LinkApplicationAndroidResourcesTaskSTaskAction
> AAPT2 33pt2-7.0.1-7396180-win

**Comment by ajwfrost** [comment]
Hi

This is starting to crop up a few times, I think there's been a gradle update that may have triggered this.. workaround is to add the below lines to your app descriptor `<android>` section:
```
  <gradleVersion>7.5</gradleVersion> 
  <androidGradlePluginVersion>7.4.0</androidGradlePluginVersion>
```

See https://github.com/airsdk/Adobe-Runtime-Support/issues/2608#issuecomment-1590720280

thanks

  Andrew

**Comment by jabirraju** [comment]
### after adding these tags it says.

Error creating files.
G\google_drive\PARA\ para2\para2 flow testitest-appami:
**error 402: Current Android sdk version dosn't support
gradleVersion as xm tag**
G\google_drive\PARA\ para2\para2 flow testitest-app.aml:
**error 402: Current Android sdk version dosnt support
androidGradiePluginversion as xml tag.**

**Comment by jabirraju** [comment]
![Uploading gradle.png…]()

**Comment by jabirraju** [comment]
this works. thanks
