### ISSUE TITLE
`URLLoader` dispatch `Event.COMPLETE` instead of `IOErrorEvent.IO_ERROR` if you add listener for `HTTPStatusEvent.HTTP_RESPONSE_STATUS`

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2706]
## Problem Description
`URLLoader` dispatch `Event.COMPLETE` instead of `IOErrorEvent.IO_ERROR` if you add listener for `HTTPStatusEvent.HTTP_RESPONSE_STATUS`. Tested with multiple resourcs which returns 4xx error codes.
So if you need to use `HTTPStatusEvent.HTTP_RESPONSE_STATUS` event to handle status code or something like that - your logic will be ruined.
Pretty similar to https://github.com/airsdk/Adobe-Runtime-Support/issues/177

Tested with multiple AIR versions (from 33.x) to latest AIR 50.2.2.5 with multiple different Windows devices with different OS versions, different AIR applications and architectures.
Same problem in all cases.
Didn't test yet with other platforms.
There is no such issue without adding `HTTPStatusEvent.HTTP_RESPONSE_STATUS` listener.
Also there is no such issue using `HTTPStatusEvent.HTTP_STATUS` listener.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2658
https://github.com/airsdk/Adobe-Runtime-Support/issues/177

## Steps to Reproduce
Launch application with code below with any device. It just try to load URL which returns 404 error code (for example `https://airsdk.harman.com/download/404`) and trace results.
Application example with sources attached.
[urlloader_complete_error_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/11893781/urlloader_complete_error_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.net.URLLoader;
	import flash.net.URLRequest;
	import flash.events.HTTPStatusEvent;
	import flash.events.Event;
	import flash.events.IOErrorEvent;
	
	public class URLLoaderCompleteErrorBug extends Sprite {
		var urlLoader:URLLoader = new URLLoader();
		
		public function URLLoaderCompleteErrorBug() {
			const urlRequest:URLRequest = new URLRequest("https://airsdk.harman.com/download/404");//Any URL which return 404 error for example
			urlLoader.addEventListener(HTTPStatusEvent.HTTP_RESPONSE_STATUS, httpResponseStatusEvent);//This event listener cause that URLLoader dispatched COMPLETE, not IO_ERROR
			urlLoader.addEventListener(IOErrorEvent.IO_ERROR, error);
			urlLoader.addEventListener(Event.COMPLETE, complete);
			urlLoader.load(urlRequest);
		}
		
		private function complete(e:Event):void {
			trace("complete");
		}
		
		private function error(e:IOErrorEvent):void {
			trace("error");
		}
	
		private function httpResponseStatusEvent(e:HTTPStatusEvent):void {
			trace("httpResponseStatusEvent", e.status);
		}
	}
}
```

**Actual Result:**
`URLLoader` dispatches `HTTPStatusEvent.HTTP_RESPONSE_STATUS` and then `Event.COMPLETE`. In traces you will see:
```
httpResponseStatusEvent 404
complete
```

**Expected Result:**
`URLLoader` dispatches `HTTPStatusEvent.HTTP_RESPONSE_STATUS` and then `IOErrorEvent.IO_ERROR`. In traces you will see:
```
httpResponseStatusEvent 404
error
```

## Known Workarounds
Check status codes manually after `Event.COMPLETE` event, prevent dispatch `Event.COMPLETE` and dispatch own error event. Own `URLLoader` superclass with custom tricky logic.

**Comment by ajwfrost** [comment]
This is actually be design. Looking at the code, these conditions are mentioned and the behaviour (for Flash vs AIR and for different versions) is specified. If the AIR-specific `HTTPS_RESPONSE_STATUS` event is being monitored, then this should be used to determine whether or not it's an error: the `COMPLETE` event is then sent which will allow applications to retrieve the content of any error pages sent by the server.

**Comment by itlancer** [comment]
@ajwfrost 
Thank you for clarification! I will close this issue.
But what about related one https://github.com/airsdk/Adobe-Runtime-Support/issues/177 ?
