### ISSUE TITLE
Asset validation failed (90101) error

### ISSUE THREAD

**Issue by GithubProgrammer** [airsdk/Adobe-Runtime-Support#2711]
Hello,

When I am uploading my app to App Store via Transporter app, I have received this error

"Asset validation failed (90101)
This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: cc3bc6af-299a-4233-863b-c0495857f41f)"

I am using the latest Air SDK 50.2.3.1 and also using plenty of latest Distriqt ANEs. Previously, I was using Air SDK 33.1.x and Distriqt ANEs. Everything was fine until there was a need to update for IOS SDK 16.x. 

 I have used APM to generate the Application descriptor file. When I compare this to older descriptor file, I could see a new tag added, < key >MinimumOSVersion< /key > and the value is set to 11.0. This is not present in my previous Application descriptor file. I am using < supportedProfiles >mobileDevice< /supportedProfiles > 

If somebody can shed some light, would be grateful.

Thanks

**Comment by FliplineStudios** [comment]
That's odd, do you have UIDeviceFamily set to the same values as your previous version?  I think that used to be the main reason that error would appear before, unless this is some new problem with 50.2.3.1 triggering it...

**Comment by marchbold** [comment]
Have you tried removing the `supportedProfiles` option? Could be something has changed in AIR that handles that differently now.

**Comment by GithubProgrammer** [comment]
> That's odd, do you have UIDeviceFamily set to the same values as your previous version? I think that used to be the main reason that error would appear before, unless this is some new problem with 50.2.3.1 triggering it...

Thanks, this worked for me. The UIDeviceFamily was missing in the newly generated descriptor file. Wondering, how APM is missing this crucial part.

> Have you tried removing the `supportedProfiles` option? Could be something has changed in AIR that handles that differently now.

Yes, that didn't make any difference. By adding < key> UIDeviceFamily, it worked. Thanks
