### ISSUE TITLE
AIR game on Linux: Application crashed with an unhandled SIGSEGV

### ISSUE THREAD

**Issue by GeneralVimes** [airsdk/Adobe-Runtime-Support#2712]
I'm building my game for Linux with AIR 50.2.3.1.

The building process itself which I did according to this tutorial (https://www.reddit.com/r/as3/comments/p9vqd2/building_air_game_for_linux_working_experience/) went well.

To build I'm using a Virtual Box machine with ubuntu-20.04.6

My game uses Starling, it consists of the preloader, the main menu, and the game itself.

But when it comes to running the game, I see the preloader, when it completes I see just a blink of a main menu, and then I see an error in the terminal: "Application crashed with an unhandled SIGSEGV"

Last time I used AIR 33.1.1.758 to build a Linux game, and when I run that version it works well.

Game builds can be found here: https://airapport.itch.io/farm-and-mine (scroll down to the downloads section)
The version which crashes: FarmAndMineLinuxCrash
The version which does not crash: FarmAndMineLinux

Crash log from Linux machine: https://pastebin.com/XBjUtjgX

One difference that I noticed: the executable file in the version which does not crash is considered as "executable" in properties and is run by double-clicking, and in the version which crashes it is "shared library", and doesn't run by double-clicking, I could run it only via the terminal.

Could you please check of what could go wrong? Maybe some additional build settings were needed for AIR 50 which I missed?

**Comment by ajwfrost** [comment]
Hi
We've managed to reproduce the crash with this app, which is happening within garbage collection for some reason. This isn't normally an area where things go wrong.. we can check this a little more but I'm going to also suggest we re-build the 50.2.3.1 code using our older build environment and see if that makes any difference (this 50.2.3.1 was done using a newer build server that we'd got set up, I really can't see how that may affect garbage collection but it's worth checking). We can also confirm this app build is stable using 33.1.1.758 and then start checking interim versions to find out if there's a particular version that triggers the failure..

thanks

**Comment by GeneralVimes** [comment]
Thank you!
So, here is more on this issue:
When I build a Linux game using 50.2.1.1 the game works really well. Also the resulting file type is detected as "executable" and it's possible to run it with double-click from the Ubuntu GUI. I'll make a binary search to find out where the problem first occurred.

**Comment by GeneralVimes** [comment]
So, building with 50.2.2.6 results with correct build which is detected as "executable" by Ubuntu and can be run with double-click from GUI and does not cause the crash.

Building with 50.2.3.1 results with a build which is detected as shared library (application/x-sharedlib), after double-click in the Ubuntu GUI it doesn't run by itself but asks for the associated app, and if run from the Terminal it crashes after the preloader.

Hope this will be helpful. I'll use 50.2.2.6 for now, no problem with that. 
You are doing a great work for the community, thank you!

**Comment by GeneralVimes** [comment]
Here are 2 versions for the comparison, please:
https://www.dropbox.com/s/eza04yub3d9zoxg/FarmAndMineLinux_2_2_6.zip?dl=0
https://www.dropbox.com/s/dv6urjsv8sb7rgt/FarmAndMineLinux_2_3_1.zip?dl=0

**Comment by ajwfrost** [comment]
Thanks @GeneralVimes for all the extra debugging and narrowing it down!
We're not able to access Dropbox, would you be able to upload those two zips to the below link please?
https://transfer.harman.com/requests/7uCfRdMZ6K4bMO3NybAk3t

thanks

**Comment by GeneralVimes** [comment]
Sent the files, you are welcome :)

**Comment by ajwfrost** [comment]
@GeneralVimes please try using the latest release. There seems to be an issue when we build using the later GCC versions, the same code build with an older GCC works (most likely, some optimisation that they've added is now breaking the AVM+ memory management system..)

**Comment by GeneralVimes** [comment]
@ajwfrost thank you so much! I tested and confirm that AIR 50.2.3.2 builds a Linux game well: the resulting file is "application" and the game runs well, too.

**Comment by ajwfrost** [comment]
Thanks for confirming @GeneralVimes
