### ISSUE TITLE
Migration from Flash Builder to IntelliJ IDEA Android build JAVA_HOME issue

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/Adobe-Runtime-Support#2721]
This week Flash Builder finally stopped working on my PC and I decided to migrate our projects to IntelliJ IDEA.

Based on this [doc](https://airsdk.dev/docs/basics/setup-an-editor) and [IDEA documentation](https://www.jetbrains.com/help/idea/actionscript-flex-and-air.html) I successfully migrated our project.

It builds and runs fine on PC, but I cannot package it for Android platform due to `JAVA_HOME` problem.

I get this error:
`JAVA_HOME does not point to a valid JDK installation, which is required for Android App Bundle signing`

And this is my ADT command line (without a lot of assets, which are included with the app):
`C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.3\jbr\bin\java.exe -Dapplication.home=E:\sdk\AIRSDK -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -jar E:\sdk\AIRSDK\lib\adt.jar -package -target apk-captive-runtime -arch armv8 -storetype PKCS12 -keystore E:\cert\android_upload.p12 -storepass certPassword E:\android64\bin-debug\Startup.apk E:\android64\bin-debug\Startup-app.xml -extdir E:\android64\ane -C E:\android64\bin-debug Startup.swf`

Looks like the build process is using the default IntelliJ IDEA JDK 17, but `JAVA_HOME` is set to JDK 11.
I also have Android SDK 33 and 34 and set them up in AIR Manager.

In different settings of IDEA I also tried to change JDK to 11, but it does not help.

So I guess I'm stuck.
And any help would be appreciated, especially as IDEA is the best IDE for AIR today and there is no proper manual on how to make it work with it.

I use latest AIR SDK 50.2.3.1.

**Comment by M4rkY4** [comment]
Hi,

this is a great JAVA_HOME tutorial for Windows: https://javatutorial.net/set-java-home-windows-10/

If you want IDEA to compile via certain JDK, you should run IDEA on that runtime https://www.jetbrains.com/help/idea/switching-boot-jdk.html

**Comment by sjabberwocky** [comment]
> this is a great JAVA_HOME tutorial for Windows: https://javatutorial.net/set-java-home-windows-10/

`JAVA_HOME ` is already set and it does not work for IDEA.
 
> If you want IDEA to compile via certain JDK, you should run IDEA on that runtime https://www.jetbrains.com/help/idea/switching-boot-jdk.html

If you change JDK to 11 by this manual, then IDEA will not start anymore.

**Comment by M4rkY4** [comment]
> JAVA_HOME  is already set and it does not work for IDEA.
Sadly, it will not use your JDK unless it's running on it

> If you change JDK to 11 by this manual, then IDEA will not start anymore.
Then I would advice you to install older version of IDEA, perhaps something of a 2020.03, at that times it was working well, though Choose Runtime was a plugin...

**Comment by marchbold** [comment]
Have you tried setting JAVA_HOME in the adt.cfg. Using the AIR SDK Manager is the easiest approach for this.

**Comment by sjabberwocky** [comment]
@marchbold, no it does not work.
IDEA still try to use it's own JDK 17.

Does "Package AIR Application..." work for Android builds on your IDEA?


`adt.cfg`
```
# See release notes: uncomment these lines in order to force your APK to be generated with 64-bit ARM binaries
# (needed when using an IDE such as Adobe Animate that currently only provides armv7 and x86 as the options via the UI)
#DefaultArch=armv8
#OverrideArch=armv8

# See release notes and https://github.com/Gamua/Adobe-Runtime-Support/issues/58
#UncompressedExtensions=emd,tfl,tflite,pb

# Default is to prefiix the package with 'air.' - to turn this off, uncomment the below line
#AddAirToAppID=false

# If you need to increase the heap available to Java when packaging an Android app, you can use the below setting
# when ADT is run from another tool. (If run from the command line, just add -Xmx=2048m or similar to the command
# line within the ADT launch script..)
#JavaXmx=2048m

# For debugging, set this to 'true' and a file "adt.log" should be generated in your user's home folder
#DebugOut=true

# To override the creation of an Android APK file, and to instead create an Android App Bundle, the below
# flag can be uncommented. Note that the bundle may end up with an "apk" file extension
CreateAndroidAppBundle=true

# When creating an Android App Bundle, this flag can be used to output the Android Studio project
# files in a subfolder of your build directory (rather than using a temporary location that gets
# cleaned up on exit).
#KeepAndroidStudioOutput=true

# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
AndroidPlatformSDK=C:\Users\dmitr\AppData\Local\Android\Sdk
#iOSPlatformSDK=path_to_sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
JAVA_HOME=C:\Program Files\Java\jdk-11

```

![изображение](https://github.com/airsdk/Adobe-Runtime-Support/assets/4690432/85fd44c0-864f-48c9-ae18-75b9478c0f26)

**Comment by marchbold** [comment]
Must say I haven't tried recently, I normally use ant build scripts with intellij. I'll setup a test when I have a chance.

**Comment by pitanello** [comment]
It should be JAVA_HOME=C:\\Program Files\\Java\\jdk-11

**Comment by sjabberwocky** [comment]
@ajwfrost it would be nice to have some collaboration between the AIR team and the JetBrains team to update the AIR SDK integration in IDEA to have a fully functional and friendly IDE for AIR development.

**Comment by ajwfrost** [comment]
Hi

Do you have the output from the adt log (or if you're using AIR SDK Manager, just open the Troubleshooting page)? This can give more info on what ADT is trying to use.

The ADT call to Gradle tries to ensure it's got an appropriate JDK path, since it wouldn't work if it was just a JRE or if it was < 11 (of course, that may vary as Google/Android update their tools and minimum requirements). But things are made a little more complex by things like the internal APK signing code not working on Java 17 and above - I thought we'd resolved that one (by just calling 'apksigner' directly) but if the JetBrains JDK is too high a version then it may be causing problems.

Of course, the actual error you're getting there is I think because there is the 'JAVA_HOME' definition in the config file - which would override the runtime that's called to run ADT - but that definition is malformed. It's a file that's read by Java Properties and this means path names have to either forward slashes, or as @pitanello pointed out, to escape the backslashes with another backslash..

So -> for this particular issue, can you try the format suggested above, or actually just remove that JAVA_HOME definition and see if that helps?

In terms of collaboration, we have had some discussions with the maintainer of the AS3/AIR plug-in for IDEA and can try to make some of these things easier: for this one, it may just be us that have to try to detect either the error condition (path that Java can't cope with) or to realise we're running within an IDEA context and then just continue using their JDK...

thanks

**Comment by blackjyn** [comment]
If you are using latest version of Intellij the IDE will runs only on Java 17 and yes it will uses the Jetbrains bundled runtime (jbr).
Try to set the JDK that runs IDEA to jdk 17 of your own using into `%IDEA_JDK%` env. 
Then set `%JAVA_HOME%` to JDK 11.

https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by sjabberwocky** [comment]
@ajwfrost The simplest way to reproduce this issue is create new empty Flash project in IDEA:
1. File -> New -> Project...
2. Select project type `Flash`, Target platform: `Mobile`, check `Pure ActionScript`, Target devices: `Android`.
![изображение](https://github.com/airsdk/Adobe-Runtime-Support/assets/4690432/01d0222c-7001-49aa-9c3c-57a241644533)
3. Use default descriptor `Main-app.xml`:

```
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/50.2">
    <id>Main</id>
    <filename>Main</filename>
    <name>Main</name>
    <versionNumber>1.0.0</versionNumber>
    <initialWindow>
        <content>Main.swf</content>
        <visible>true</visible>
        <autoOrients>true</autoOrients>
        <fullScreen>true</fullScreen>
    </initialWindow>
    <android>
        <manifestAdditions>
            <![CDATA[
            <manifest android:installLocation="auto">
                <uses-permission android:name="android.permission.INTERNET"/>
            </manifest>
            ]]>
            </manifestAdditions>
    </android>
</application>
```

4. Select this desriptor in File -> Project Structure -> Project Settings -> Modules -> Android -> Application -> Custom template

5. Try to package default application: Build -> Package AIR Application...

6. And than you get this error: `JAVA_HOME does not point to a valid JDK installation,`
My system JAVA_HOME points to jdk 11, but it overrides by IDEA to jdk 17.

```
ADT 50.2.3.1 called with: -package -target apk-captive-runtime -storetype PKCS12 -keystore C:\Users\user\AppData\Roaming\JetBrains\IntelliJIdea2023.2\plugins\flex\lib\temp_keystore.p12 -storepass xxxxxx E:\git\temp\out\production\temp\Main.apk E:\git\temp\out\production\temp\Main-app.xml -C E:\git\temp\out\production\temp Main.swf

Overriding request for apk-captive-runtime, instead generating Android App Bundle

Creating device SDK handler - location passed in = C:\Users\user\AppData\Local\Android\Sdk

Version in APK = 50.2.3.1, version of ADT = 50.2.3.1

Version in APK = 50.2.3.1, version of ADT = 50.2.3.1

Version in APK = 50.2.3.1, version of ADT = 50.2.3.1

Version in APK = 50.2.3.1, version of ADT = 50.2.3.1

Gradle build where ADT is using JRE version 17.0.7

but where Gradle will be using the JDK from C:/Program Files/JetBrains/IntelliJ IDEA 2023.1.3/jbr\bin\java.exe

Gradle build command:  C:/Program Files/JetBrains/IntelliJ IDEA 2023.1.3/jbr\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Users\user\AppData\Local\Temp\a6bb70f2-11d7-4dac-bd89-ddfbac8afdf3" -cp "C:\Users\user\AppData\Local\Temp\a6bb70f2-11d7-4dac-bd89-ddfbac8afdf3\gradle\wrapper\gradle-wrapper.jar";"E:\sdk\AIRSDK\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease

Stack trace:
..java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.apk.AABOutputStream.jarSign(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)

Invalid input: JAVA_HOME does not point to a valid JDK installation, which is required for Android App Bundle signing
```

**Comment by sjabberwocky** [comment]
@ajwfrost It would be nice if you could create an up-to-date manual on how to compile and package a pure ActionScript project (without Flex) for at least Android, iOS and Windows with copy-paste examples of this process for Apache Ant.

It's really frustrating when there is no complete and easy to use manual about it.
I would rather work on improving our project for thousands of our players than try to understand how to build it after decade of development when Flash Builder did this magic without my involvement.

**Comment by sjabberwocky** [comment]
At the same time, an empty project for iOS was packaged without a problem.

**Comment by sjabberwocky** [comment]
The solution to this problem is to set JAVA_HOME in adt.cfg in the correct form, which was not needed when using Flash Builder.

More details here: https://youtrack.jetbrains.com/issue/IDEA-327476
I would like to thank Serge from IDEA team for his help.
