### ISSUE TITLE
Wrong app icon list in descriptor xsd on every AIR version

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/Adobe-Runtime-Support#2755]
For icons on modern mobile devices we use Assets.car for iOS and adaptive icons for Android.

But for older devices - Android below 8.0 and iOS before 11 - png icons may still be needed.

IDEA validates descriptor by xsd schema and occasionally xsd schema is missing a lot of standard icon sizes.

You can find a list of icon sizes in the "Application Icons" section of the [AIR SDK documentation](https://help.adobe.com/en_US/air/build/WSfffb011ac560372f-5d0f4f25128cc9cd0cb-7ffe.html#WS901d38e593cd1bac1e63e3d129907d2886-8000).

This is the list of icon sizes we use in our project and which are missing in xsd scheme:

- image40x40
- image60x60
- image75x75
- image76x76
- image80x80
- image87x87
- image120x120
- image152x152
- image167x167
- image180x180
- image192x192

@ajwfrost I think it's very easy to add with new AIR update.

**Comment by marchbold** [comment]
I believe the schema IntelliJ use are embedded in the IntelliJ plugin from the last time I investigated this issue. So I believe this will need an update the plugin

**Comment by ajwfrost** [comment]
Not sure how IntelliJ uses it, but it's right that ADT can recognise more icon sizes - and the example/template app descriptor file has more icon sizes - than are present in the XSD document for this.. Will look at getting this updated shortly...
