### ISSUE TITLE
[Android] Soft keyboard don't work properly with some devices

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2773]
## Problem Description
Soft keyboard don't work properly with some Android devices.
It doesn't showed on click (focus) to `TextField` (with "input" type). It doesn't send `SoftKeyboardEvent` events. `requestSoftKeyboard()` do nothing. Also soft keyboard doesn't hide on click out of text area.

Tested with multiple AIR 50.x versions (even with latest AIR 50.2.3.3) with different AIR applications.
Isssue 100% reproducible with devices:
- Pricechecker Gausys HS101, Android 9
- Google Pixel, Android 13

Changing "renderMode" didn't help.
There is no such issues with non-AIR applications.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2615
https://github.com/airsdk/Adobe-Runtime-Support/issues/2245
https://github.com/airsdk/Adobe-Runtime-Support/issues/757
https://github.com/airsdk/Adobe-Runtime-Support/issues/443
https://github.com/airsdk/Adobe-Runtime-Support/issues/423
https://github.com/airsdk/Adobe-Runtime-Support/issues/255
https://github.com/airsdk/Adobe-Runtime-Support/issues/109

## Steps to Reproduce
1) Launch application with code below with any "problem" Android device.
2) Click on left text input (`TextField`). Soft keyboard should be shown.
3) Click on empty space (stage). Soft keyboard should be hidden.
4) Click on right text input (`StageText`). Soft keyboard should be shown.
5) Click on empty space (stage). Soft keyboard should be hidden.

*`textField.requestSoftKeyboard();` call after 500 ms on `TextField` click in sample only to demonstrate that it also doesn't work.

Application example with sources attached.
[android_softkeyboard_bug.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/12378859/android_softkeyboard_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.text.TextField;
	import flash.text.SoftKeyboardType;
	import flash.text.TextFieldType;
	import flash.events.SoftKeyboardEvent;
	import flash.text.StageText;
	import flash.geom.Rectangle;
	import flash.events.FocusEvent;
	import flash.events.MouseEvent;
	import flash.utils.setTimeout;
	
	public class AndroidSoftKeyboardBug extends Sprite {
		private var textField:TextField;
		private var stageText:StageText;
		
		public function AndroidSoftKeyboardBug() {
			textField = new TextField();
			textField.text = "TextField";
			textField.type = TextFieldType.INPUT;
			textField.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_ACTIVATE, activate);
			textField.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_ACTIVATING, activating);
			textField.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE, deactivate);
			textField.addEventListener(FocusEvent.FOCUS_IN, focusIn);
			textField.addEventListener(MouseEvent.CLICK, click);
			addChild(textField);
			
			stageText = new StageText();
			stageText.fontSize = 40;
			stageText.text = "StageText";
			stageText.color = 0x000000;
			stageText.viewPort = new Rectangle(200, 0, 600, 100);
			stageText.stage = stage;
			stageText.visible = true;
			stageText.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_ACTIVATE, activate);
			stageText.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_ACTIVATING, activating);
			stageText.addEventListener(SoftKeyboardEvent.SOFT_KEYBOARD_DEACTIVATE, deactivate);
			stageText.addEventListener(FocusEvent.FOCUS_IN, focusIn);
		}
		
		private function activate(e:SoftKeyboardEvent):void {
			trace("activate", e.target);
		}
		
		private function activating(e:SoftKeyboardEvent):void {
			trace("activating", e.target);
		}
		
		private function deactivate(e:SoftKeyboardEvent):void {
			trace("deactivate", e.target);
		}
		
		private function focusIn(e:FocusEvent):void {
			trace("focusIn", e.target);
		}
		
		private function click(e:MouseEvent):void {
			trace("click");
			//stage.focus = null;
			setTimeout(function():void{
				textField.requestSoftKeyboard();
				trace("requestSoftKeyboard");
			}, 500);
		}
	}
}
```

**Actual Result:**
1) Application launched.
2) Soft keyboard not shown.
3) Nothing happens.
4) Soft keyboard shown.
5) Soft keyboard not hidden.

In traces you will see:
```
focusIn [object TextField]
click
requestSoftKeyboard

focusIn [object StageText]
```

**Expected Result:**
1) Application launched.
2) Soft keyboard shown.
3) Soft keyboard hidden.
4) Soft keyboard shown.
5) Soft keyboard hidden.

In traces you will see:
```
focusIn [object TextField]
click
activating [object TextField]
activate [object TextField]
requestSoftKeyboard
deactivate [object TextField]


focusIn [object StageText]
activating [object StageText]
activate [object StageText]
deactivate [object StageText]
```

## Known Workarounds
none
Some issues could be avoided if you write native extension to manually show/hide soft keyboard by yourself and use something like:
```
InputMethodManager imm = (InputMethodManager) context.getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
```

**Comment by marchbold** [comment]
Resolved in [50.2.3.5](https://airsdk.dev/news/2023/09/08/air-release)

**Comment by itlancer** [comment]
Fixed with latest AIR SDK 50.2.3.5.
Thanks!

**Comment by berkayk** [comment]
Our Starling/Feathers app is broken now. Do you have any working example on how to program TextInput? Can you provide a small snippet? Thanks.

**Comment by ajwfrost** [comment]
Hi @berkayk  - can you please elaborate on "broken"? I know we have some issues with the height of the soft keyboard not being reported properly, and we have some ongoing investigations there (but it's made more complicated by the different behaviour we see between Android versions and between different renderMode and fullScreen settings in AIR app descriptors..!)

thanks

**Comment by berkayk** [comment]
Hi @ajwfrost, sorry for the confusion. I get focus errors while touching Feathers TextInputs. In the device, I cannot touch anywhere to focus. In the debugger, I can only get input to focus while touching borders of the white input with the mouse. This was working before SDK v50. Do I have to set something explicitly so that it can be touchable/focusable? What confuses me on this is that everything was working for a year. I just updated to SDK 50 and this got broken.

<img width="308" alt="image" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/603844/af1bcae9-93a6-474d-b46f-41daadc5dbdf">

**Comment by berkayk** [comment]
@ajwfrost Somehow one of the TextInputs stopped working as I mentioned above. I changed their textEditorFactory from StageTextTextEditor to TextFieldTextEditor, now it's working. Strangely, there are 6 different TextInputs with StageTextTextEditor, but only one of them stopped working. After changing to TextFieldTextEditor, it's working now. Probably, some changes in SDK affected StageTextTextEditor.
