### ISSUE TITLE
MacOS certificate using adt.jar throws error since AIR SDK 50.2.2.1

### ISSUE THREAD

**Issue by philpme** [airsdk/Adobe-Runtime-Support#2801]
## Problem Description

Reading certificate using adt.jar on MacOS throws error since AIR SDK 50.2.2.1 up to 50.2.3.4

Mac OS: Ventura 13.5.1, 13.4.1 and 13.2.1

We have a certificate installed on Mac that has been working fine with adt.jar in AIR SDK 50.2.1. In v50.2.2.1 and later, adt.jar starts throwing error “unable to retrieve key for alias”. We have tried to use “-checkstore” option to verify the key with the adt.jar in both versions of the AIR SDK: version 50.2.1x returned “valid password” while 50.2.2.1 and later throws the same error “unable to retrieve key for alias”. This seems to be a bug in the new version.

## Steps to Reproduce

1. Create a self-signed certificate using openssl:
$ openssl req -x509 -newkey rsa:2048 -keyout testkey.pem -out testcert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=TestAIRSDK"
 
2. Add the certificate to Mac Keychain and set it as Trusted:
- Open Mac "Keychain Access"
- Go to "System Keychains" -> All Items, drag the "testcert.pem" created in step 1
- After the certificate has been added, right click -> Get Info, expand the Trust section and set "Always Trust" in the first dropdown "When using this certificate"
 
3. Go to command line and try to read the certificate using adt.jar
$ java -jar adt.jar  -checkstore -storetype KeychainStore -alias "TestAIRSDK"
 
With adt.jar of AIR SDK version 50.2.1.1, the output is:
    "valid password"
 
With adt.jar of AIR SDK version 50.2.2.1 or later, the output is:
    "unable to retrieve key for alias: TestAIRS"

## Known Workarounds

No workarounds, remain using AIR SDK 50.2.1.1

**Comment by ajwfrost** [comment]
Hi - we can investigate this one.. interestingly, I can't see any changes between those releases that should have impacted this. Just to check, you're using the same version of Java for both of them, and same macOS machine?

I'll ask someone to follow those steps, I would hope it's then a straightforward fix!

thanks

**Comment by philpme** [comment]
Thanks Andrew. We've reproduced the issue on several different Macs, also with different versions of Java.  While we provided a scenario where an OpenSSL cert failed to be picked up via adt, we discovered this as our builds were failing when we were attempting to sign our app with our Apple Developer ID certificate.  We'll remain on v50.2.1 until an update is available that fixes the issue.

**Comment by marchbold** [comment]
Resolved in [50.2.3.5](https://airsdk.dev/news/2023/09/08/air-release)
