### ISSUE TITLE
-arch x86_64 builds for Android emulators not working

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#2812]
Android SDK 31 and above in Android Studio does not offer x86 images anymore to test the app on the emulators. Trying to make a x86_64 build for the emulators creates an error massage. How can I create an emulator build with -arch x86_64 to test such as on iOS Simulators the Android app with sdk 33? 
my current air sdk is: 50.2.3.4

**Comment by ajwfrost** [comment]
For Android builds, it should be possible to use `adt -package -target apk-debug -arch x64 ...` (not x86_64, sorry)
If you're getting errors with that, please let us know the output details (ideally from AIR SDK Manager 'troubleshooting' pane).

thanks

**Comment by apofis1969** [comment]
@ajwfrost thanks, this is working.
