### ISSUE TITLE
intermittent java.lang.OutOfMemoryError when packaging android

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#2821]
This happens intermittently, meaning sometime it succeeds, sometimes not
I can try use the `-Xmx` java flag (with what value?)

<details>
  <summary>adt.log</summary>
ADT 50.2.3.4 called with: -version

ADT 50.2.3.4 called with: -package -target apk-captive-runtime -arch armv8 -keystore D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/config/release.keystore -storetype JKS -providerName SUN -storepass xxxxxx -alias slotamobilekey -keypass keypass buddies-mobile-boot.apk slotagram-mobile-boot-app-android.xml slotagram-mobile.swf -C D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/target-mobile-android assets -C D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/src/main/resources/buddies/root_android . -extdir .

Ensuring we have SDK 11 and an Android SDK path

Request for a Java home folder: JDK = true, min version 11

Value of JAVA_HOME from USR folder: C:/Program Files/Java/jdk-17.0.3

java -version => javac 17.0.3

Found version 17

Android SDK path from USR config: C:\Users\Administrator\AppData\Local\Android\Sdk

Java home = C:/Program Files/Java/jdk-17.0.3
Android SDK = C:/Users/Administrator/AppData/Local/Android/Sdk
Target requested was apk-captive-runtime, but not using legacy APK so building via Android Studio

Android SDK path from USR config: C:\Users\Administrator\AppData\Local\Android\Sdk

Creating device SDK handler - location passed in = C:\Users\Administrator\AppData\Local\Android\Sdk

Warning: Using default implementation for native extension 'com.applovin.air.mediation.facebook.corekit'

Warning: Using default implementation for native extension 'com.distriqt.WindowsStore'

Adding gradle dependency: implementation 'com.google.code.gson:gson:2.8.9'

Version in APK = 50.2.3.4, version of ADT = 50.2.3.4

Version in APK = 50.2.3.4, version of ADT = 50.2.3.4

Version in APK = 50.2.3.4, version of ADT = 50.2.3.4

Version in APK = 50.2.3.4, version of ADT = 50.2.3.4

Request for a Java home folder: JDK = true, min version 11

Value of JAVA_HOME from USR folder: C:/Program Files/Java/jdk-17.0.3

java -version => javac 17.0.3

Found version 17

Gradle build where ADT is using JRE version 11.0.16.1

but where Gradle will be using the JDK from C:/Program Files/Java/jdk-17.0.3\bin\java.exe

Gradle build command:  C:/Program Files/Java/jdk-17.0.3\bin\java.exe -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="C:\Windows\Temp\e666f597-4581-4a4e-b30a-f99df2264ffb" -cp "C:\Windows\Temp\e666f597-4581-4a4e-b30a-f99df2264ffb\gradle\wrapper\gradle-wrapper.jar";"C:\flash_air_sdk_50\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleRelease

..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)

..com.adobe.air.DebugFile.printStack(DebugFile.java)

..com.adobe.air.ADTException.<init>(ADTException.java)

..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)

..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)

..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)

..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)

..com.adobe.air.ADT.parseArgsAndGo(ADT.java)

..com.adobe.air.ADT.run(ADT.java)

..com.adobe.air.ADT.main(ADT.java)

Stack trace:
..java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
..com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)

Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 38s
</details>
<details>
  <summary>console output</summary>
package.android:
     [echo] 
     [echo] 
     [echo] 
     [echo] 
     [echo] 
     [echo] 
     [echo] ########################################################################################
     [echo]   Creating APK for Android   (BRAND = buddies)  
     [echo] ########################################################################################
     [echo] Showing adt version
     [exec] 50.2.3.4
     [echo] C:/flash_air_sdk_50/bin/adt.bat (dir= D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/target-mobile-android)
     [echo] -package
     [echo] -target apk-captive-runtime
     [echo] -arch armv8
     [echo] -keystore D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/config/release.keystore
     [echo] -storetype JKS
     [echo] -providerName SUN
     [echo] -storepass storepass
     [echo] -alias slotamobilekey
     [echo] -keypass keypass
     [echo] buddies-mobile-boot.apk
     [echo] slotagram-mobile-boot-app-android.xml
     [echo] slotagram-mobile.swf
     [echo] -C D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/target-mobile-android assets
     [echo] -C D:\Jenkins\jobs\slotagram-build-designers\workspace\webapp\flex\slotagram-mobile-boot2/src/main/resources/buddies/root_android .
     [echo] -extdir .
     [exec] Warning: packagedDependency okio-1.17.5.jar used by more than one ANE. Ignoring this entry
     [exec] NOTE: Multiple Android build-tools folders exist, choosing the latest version (33.0.0 rc3) for packaging
     [exec] unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':app:packageRelease'.
     [exec] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
     [exec]    > java.lang.OutOfMemoryError (no error message)
     [exec] 
     [exec] * Try:
     [exec] > Run with --stacktrace option to get the stack trace.
     [exec] > Run with --info or --debug option to get more log output.
     [exec] > Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org/
     [exec] 
     [exec] BUILD FAILED in 3m 38s
     [exec] 
     [exec] java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':app:packageRelease'.
     [exec] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
     [exec]    > java.lang.OutOfMemoryError (no error message)
     [exec] 
     [exec] * Try:
     [exec] > Run with --stacktrace option to get the stack trace.
     [exec] > Run with --info or --debug option to get more log output.
     [exec] > Run with --scan to get full insights.
     [exec] 
     [exec] * Get more help at https://help.gradle.org/
     [exec] 
     [exec] BUILD FAILED in 3m 38s
     [exec] 
     [exec] 	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
     [exec] 	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
     [exec] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [exec] 	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
     [exec] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [exec] 	at com.adobe.air.ADT.run(ADT.java)
     [exec] 	at com.adobe.air.ADT.main(ADT.java)
[JENKINS] Archiving disabled
</details>

**Comment by ajwfrost** [comment]
If you need more than the default of 1GB, you can add this also to the adt.cfg config file:
```
JavaXmx=2048m
```

**Comment by shaymolho** [comment]
thanks, i'll give it a try
