### ISSUE TITLE
Adobe AIR Update screen 33.3 poitns to 404

### ISSUE THREAD

**Issue by radubirsan** [airsdk/Adobe-Runtime-Support#2827]
Updating shared runtime desktop application ask me to update AIR Runtime, clicking the link in the popup opens 404 page:

http://www.adobe.com/go/air_sysreqs/

Adobe should redirect this page to 

https://airsdk.harman.com/runtime

**Comment by ajwfrost** [comment]
Hi

I'll ask them if they can add this URL also to their redirection. They prefer to push people towards the announcement page, which then has the links to our website..
https://blog.adobe.com/en/publish/2019/05/30/the-future-of-adobe-air

So if you go to https://get.adobe.com/air, this is where you'd end up..


thanks
   Andrew

**Comment by radubirsan** [comment]
it looks like it's working now http://www.adobe.com/go/air_sysreqs/  redirects to https://airsdk.harman.com/runtime

thank you.

**Comment by ajwfrost** [comment]
Well spotted! I knew it was in progress but hadn't been told it was sorted out....

thanks

**Comment by delpierr** [comment]
Bonjour french please

Teddel

Le mar. 26 sept. 2023, 16:08, Andrew Frost ***@***.***> a
écrit :
