### ISSUE TITLE
[iOS] Submission failed - crash on startup

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#2836]
We have been trying for days now to update our app, but failing to do so.
They said that it crashed on startup on iPhone, and we could replicate it to a Storyboard issue - we added a Storyboard, and it worked.
Resubmitted, and now the problem is again at startup, on iPad running ios 17.
We can't replicate this, and we simply don't know what to do next
@ajwfrost could you please share some info on what we can do to find the cause?
I have attached the crashlog Apple provided, but no idea how to read this.

[crashlog-B8E33549-F14C-44EE-BB27-BD61DE43A1F4.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12659753/crashlog-B8E33549-F14C-44EE-BB27-BD61DE43A1F4.txt)
[crashlog-03A79F40-B576-4A8D-9BD3-9D5C5FC7F125.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12659751/crashlog-03A79F40-B576-4A8D-9BD3-9D5C5FC7F125.txt)
[crashlog-7E2FCCF3-FCAD-493C-A592-CB378BA1221F.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12659752/crashlog-7E2FCCF3-FCAD-493C-A592-CB378BA1221F.txt)

**Comment by ajwfrost** [comment]
Hi

Trying to pull out the exception stack from those, the final parts look like:
```
  {"imageOffset":972256,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":9},
  {"imageOffset":179200,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":6},
  {"imageOffset":3573724,"symbol":"+[UIProxyObject addMappings:forCoder:]","symbolLocation":0,"imageIndex":11},
  {"imageOffset":1034776,"imageIndex":1},
  {"imageOffset":94196,"imageIndex":1},
  {"imageOffset":97404,"imageIndex":1},
  {"imageOffset":2179544,"symbol":"-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]","symbolLocation":320,"imageIndex":11},
  {"imageOffset":2175808,"symbol":"-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]","symbolLocation":2856,"imageIndex":11},
  {"imageOffset":2171684,"symbol":"-[UIApplication _runWithMainScene:transitionContext:completion:]","symbolLocation":856,"imageIndex":11},
  {"imageOffset":2170736,"symbol":"-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]","symbolLocation":132,"imageIndex":11},
  {"imageOffset":1632732,"symbol":"_UIScenePerformActionsWithLifecycleActionMask","symbolLocation":112,"imageIndex":11},
  {"imageOffset":2187008,"symbol":"__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke","symbolLocation":216,"imageIndex":11},
  {"imageOffset":1289680,"symbol":"-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]","symbolLocation":220,"imageIndex":11},
  {"imageOffset":1284168,"symbol":"-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]","symbolLocation":608,"imageIndex":11},
  {"imageOffset":1282480,"symbol":"-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]","symbolLocation":248,"imageIndex":11},
  {"imageOffset":1282176,"symbol":"__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke","symbolLocation":148,"imageIndex":11},
  {"imageOffset":1281928,"symbol":"+[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]","symbolLocation":736,"imageIndex":11},
  {"imageOffset":1280016,"symbol":"_UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion","symbolLocation":224,"imageIndex":11},
```

I can't see any indication of our code calling "addMappings" but there's a lot that gets generated when an app it built..  have you managed to try a completely new/blank app to see if it's okay with your build environment plus hardware set-up? 

thanks

**Comment by raresn** [comment]
Only thing changed was the Storyboard. So I expect this has something to do with it.
This error happens for the Apple team while approving the app, I could not replicate locally.

**Comment by raresn** [comment]
100% sure we dont' have addMappings in our code. 
So we resubmitted the app, after remaking the storyboard and Assets.car with a script from Distriqt in the hopes that it will solve the problem. It didn't.
They submitted 3 new crashlogs. 
One thing we didn't try is to use the latest version of AIR, we are still on AIR 50.2.3, not sure it would make a difference @ajwfrost 

[crashlog-396E3D2E-D30D-4287-B545-6531A508007D.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12700933/crashlog-396E3D2E-D30D-4287-B545-6531A508007D.txt)
[crashlog-965E3AD0-9F47-4478-88D5-6B1BEE32CDC8.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12700934/crashlog-965E3AD0-9F47-4478-88D5-6B1BEE32CDC8.txt)
[crashlog-39D33D77-38B4-445F-8B1F-E43B7BD2247C.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12700935/crashlog-39D33D77-38B4-445F-8B1F-E43B7BD2247C.txt)

**Comment by raresn** [comment]
Also they said the problem happens on iPhone as well, not just ipad, and gave me 4 more logs :)
Might be an ANE file? All our ANEs are from distriqt.

[crashlog-42CA9338-016A-4002-A79E-042A2E1D9130.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12701380/crashlog-42CA9338-016A-4002-A79E-042A2E1D9130.txt)
[crashlog-B08ACE38-B5C3-40CC-AAAD-AA474F90B30F.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12701381/crashlog-B08ACE38-B5C3-40CC-AAAD-AA474F90B30F.txt)
[crashlog-6C40713F-FCB5-4522-BFAF-177E11F02B0D.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12701382/crashlog-6C40713F-FCB5-4522-BFAF-177E11F02B0D.txt)
[crashlog-C2DD6F1C-289B-4A7D-BE5B-7F1542E83488.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12701383/crashlog-C2DD6F1C-289B-4A7D-BE5B-7F1542E83488.txt)

**Comment by raresn** [comment]
So we thought this is happening because we might be using old extensions or old version of air, and we upgraded all the extensions (@marchbold ) and AIR version (@ajwfrost)
Now the compile fails with the following info from the txt
[iosCompileError.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/12702104/iosCompileError.txt)

Also here are the extensions that we use:
` <extensions>
    <extensionID>androidx.appcompat</extensionID>
    <extensionID>androidx.browser</extensionID>
    <extensionID>androidx.cardview</extensionID>
    <extensionID>androidx.constraintlayout</extensionID>
    <extensionID>androidx.core</extensionID>
    <extensionID>androidx.exifinterface</extensionID>
    <extensionID>androidx.vectordrawable</extensionID>
    <extensionID>com.android.installreferrer</extensionID>
    <extensionID>com.bumptech.glide</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.CameraRollExtended</extensionID>
    <extensionID>com.distriqt.Contacts</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
    <extensionID>com.distriqt.IDFA</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.firebase.Auth</extensionID>
    <extensionID>com.distriqt.firebase.Crashlytics</extensionID>
    <extensionID>com.distriqt.firebase.Database</extensionID>
    <extensionID>com.distriqt.playservices.AdsIdentifier</extensionID>
    <extensionID>com.distriqt.playservices.AppSet</extensionID>
    <extensionID>com.distriqt.playservices.Auth</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.playservices.CloudMessaging</extensionID>
    <extensionID>com.distriqt.square.okhttp</extensionID>
    <extensionID>com.distriqt.square.okhttp3</extensionID>
    <extensionID>com.distriqt.square.picasso</extensionID>
    <extensionID>com.google.android.datatransport</extensionID>
    <extensionID>com.google.android.recaptcha</extensionID>
    <extensionID>com.google.code.gson</extensionID>
    <extensionID>com.google.dagger</extensionID>
    <extensionID>com.google.firebase.core</extensionID>
    <extensionID>com.google.firebase.messaging</extensionID>
    <extensionID>com.google.guava</extensionID>
    <extensionID>com.google.protobuflite</extensionID>
    <extensionID>com.jetbrains.kotlin</extensionID>
    <extensionID>io.grpc</extensionID>
    <extensionID>io.reactivex</extensionID>

  </extensions> 
`

**Comment by ajwfrost** [comment]
Is that on Windows? Some of the new third-party libraries have a construct that's not supported by the build of the Apple linker that we have on Windows...

I'd looked at another of those crash logs, it looked the same. I don't think it's related to the splash screen but if you're able to try with a fresh/sample app and just see whether it happens there, it would be good to then eliminate that as a possibility.

thanks

**Comment by raresn** [comment]
@ajwfrost yes - we always compile ipa files on Windows. Did something recently changed and we need to use a MAC?
Those crash-logs are from apple, after the publish was rejected. How can i "try with a fresh/sample app and just see whether it happens there"?

**Comment by raresn** [comment]
@ajwfrost we copied files over to a Mac, tried compiling - same result as on Windows.

**Comment by ajwfrost** [comment]
@raresn interesting .. what version of Xcode do you have on that mac? I definitely expect Xcode 14 to be fine with that objc_msgsend thing, I had assumed earlier versions could also cope with it.

That linker problem is related to binaries that are created using Xcode 14 (or 15). So to isolate that issue from whether there's a problem with new apps building with your toolchain/environment, you'd need to just try a simple "hello world" application. So I would suggest creating a new .as file with just a main constructor that draws a square graphic, and then compile and package this, and see if it runs okay when you package it with the same XML descriptor file (minus the ANEs) and the same launch storyboard and assets file. If that does work okay, you can then add in the ANEs (just in the app descriptor) and see whether any of those cause a problem.

thanks

**Comment by raresn** [comment]
13.2.1 is the version of Xcode. Unfortunately i can't upgrade on this OS version i have (VMWare version).

I understand what you mean about how to continue to debug this compile problem, and i will create a simple hello world app and try to compile that one, see how it goes. 
Once this is tackled and we can compile to ipa again, we need to go back to Apple issue again :) Fun times! Thank you for sticking around and helping. It really means a lot!

**Comment by ajwfrost** [comment]
Cool -> a simple IPA file can still be created on mac or Windows, it's just when an ANE has got a dependency on a third party library that was built with Xcode 14 that we end up with a problem....

**Comment by raresn** [comment]
@ajwfrost so i removed the extensions and used a swf that doesn't use any extensions, and it compiled.
The problem is with the extensions then, for this first phase of our problems. 
@marchbold  maybe you can have a look? I will try to remove extensions 1 by 1 and see which one is the problem.

**Comment by raresn** [comment]
Also, as of now i don't think @marchbold mentioned anything about us having to use mac to compile, so we are "safe" for now :)

**Comment by ajwfrost** [comment]
> and it compiled.

Did it run up okay on the device? with the same launch storyboard file and assets.car, and the same application descriptor file? There are sometimes settings within these that we've found can affect things!

Otherwise -> if you add in all the extensions to that dummy app, it would be worth seeing if that was still okay or whether it crashed too. Adding the extensions in the XML file is half of it of course, your main application would have been making calls to them, but this is all about taking things a step at a time :-)

If you do need to test individual extensions, I usually try a half at a time. And narrow things down by adding/removing half of what's left each time. Generally (on average?) this narrows things down a bit more quickly than adjusting thing one by one.. :-)

thanks

**Comment by raresn** [comment]
I did not run it on the device, at this point just focusing on it compiling. 
I am using the divide et impera as a principle as well to eliminate the bad extensions from the list :) 
In around 15 minutes i`ll finish going through the entire list and see where the fail, but so far when i added <extensionID>com.distriqt.Application</extensionID> it failed. So i expect something is up with these ANEs.

**Comment by raresn** [comment]
So even if i leave in just the  <extensionID>com.distriqt.firebase.Crashlytics</extensionID>
I will get errors - for the other extensions the error is pretty much the same, starting with "Undefined symbols for architecture arm64:"

08:16 PM
Started compiling...
Undefined symbols for architecture arm64:
  "_FIRLogBasic", referenced from:
      _FIRCLSDebugLog in FirebaseCrashlytics(FIRCLSLogger.o)
      _FIRCLSInfoLog in FirebaseCrashlytics(FIRCLSLogger.o)
      _FIRCLSWarningLog in FirebaseCrashlytics(FIRCLSLogger.o)
      _FIRCLSErrorLog in FirebaseCrashlytics(FIRCLSLogger.o)
  "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
      objc-class-ref in FirebaseSessions(FirebaseSessions.o)
      objc-class-ref in FirebaseSessions(SettingsDownloadClient.o)
      objc-class-ref in FirebaseCrashlytics(FIRCLSApplication.o)
  "_OBJC_CLASS_$_GULNetworkInfo", referenced from:
      objc-class-ref in FirebaseSessions(FirebaseSessions.o)
  "_$s8Promises7PromiseCMa", referenced from:
      _$s8Promises7PromiseCyytGMa in FirebaseSessions(FirebaseSessions.o)
.....

**Comment by marchbold** [comment]
@raresn You can't just include the ` com.distriqt.firebase.Crashlytics` extension as it has dependencies that are included in the other extensions

```
Undefined symbols for architecture arm64:
"_FIRLogBasic
```

`FIRLogBasic`, `GULAppEnvironmentUtil` etc look like the base Firebase and Google utility classes which are included in `com.distriqt.Firebase` and `com.google.firebase.core` 

The error:

```
Undefined symbols for architecture arm64:
  "_objc_msgSend
```

Is due to Firebase / Google all using Xcode 14 to build their libs now so you need to have that installed to have the latest versions. As Andrew mentioned the windows linker currently doesn't support this, so you'll need to use macOS currently to build using any of our latest extensions requiring Xcode 14 (basically any of the Google related iOS extensions). Unfortunately if you have an older OS version you'll need to update it (Apple's forced obsolescence)

**Comment by raresn** [comment]
@ajwfrost 
"-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk"
now the compile failed with 
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
ld: library 'swiftFoundation' not found
Compilation failed while executing : ld64

**Comment by marchbold** [comment]
@raresn I'd suggest just downgrading to 14.3 for the moment. Turn off automatic updates in settings and grab the xcode 14.3 download from the apple developer portal

**Comment by raresn** [comment]
@marchbold unfortunately I can't run xcode 14.3 on Sonoma macOS :(

**Comment by raresn** [comment]
So, on OS ventura, xcode 14.3, with the compile command ending with  "-extdir extensions -platformsdk /Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk"
**I get:**
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
ld: library 'swiftFoundation' not found
Compilation failed while executing : ld64

**The same error as on xcode 15 on sonoma macos**
@ajwfrost , @marchbold - any ideas what i can do?

**Comment by marchbold** [comment]
Don't use the platformsdk option, seems to cause issues with the swift libs currently.

**Comment by raresn** [comment]
@marchbold without it i get ld: unknows options: -sdk_version

**Comment by raresn** [comment]
So i assumed that the issue might be with me compiling withing a shared folder in VMware, and moved everything to the desktop. 
Now, without the platform sdk, I get a new erorr:
Error during native code-signing. Output of codesign tool is:
error: The specified item could not be found in the keychain.
So new errors - that is very good :)

**Comment by ajwfrost** [comment]
> Don't use the platformsdk option, seems to cause issues with the swift libs currently.

I suspect we just need to include an `-L/usr/lib/swift` into the linker commands, to be able to find the swift libraries when we've got the Platform SDK added... I can check this (and it should probably be a default addition to our linker line, rather than relying on the ANEs to add it, particularly because we have the swift libs in the same location as the other libs in our 'stubs' folder when there's no platformsdk...)

For the codesign thing, it's trying to use native codesigning .. and if this is an iOS app, what sort of certificate are you using, and what sort of package target are you using? I think they need to correspond.. Alternatively try with an older Java version e.g. JDK 11 and it should use built-in codesigning instead.


thanks

**Comment by raresn** [comment]
@ajwfrost 
AdobeAIRSDK/bin/adt -package -target ipa-app-store -storetype pkcs12 -keystore CERT/OnTimeAgenda/appstore.p12 -storepass [x] -provisioning-profile CERT/OnTimeAgenda/Agenda_store.mobileprovision "Agenda-Appstore.ipa" "APPLE.xml" "Agenda.swf" "Assets.car" LaunchScreen.storyboardc data icons images GoogleService-Info.plist -extdir extensions
This is the command i run to get the ipa. 

this is the error i get:
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
Error during native code-signing. Output of codesign tool is:
error: The specified item could not be found in the keychain.

Yet an ipa file is generated.

**Comment by raresn** [comment]
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/1768694/747f0886-e2b6-4a07-8431-0522fba5f934)

WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
Error during native code-signing. Output of codesign tool is:
Warning: unable to build chain to self-signed root for signer "Apple Distribution: On Time Agenda SRL (***)"
/var/folders/qr/3nm0rgyd379g5wrgkpp_0ycm0000gn/T/fb8a118e-52c5-4c6e-bb55-df4809e01e0f/Payload/On Time Agenda.app: errSecInternalComponent

**Comment by raresn** [comment]
@ajwfrost using java 11 worked - for a guy who does not use a mac, this was simply insane!

A flag to use built-in codesigning instead would be something very very good!
I took me 2 days of my life to use mac's default keychain system and i just coulnd not make it work. 
I bet there are other windows users who are forced to use a mac for the first time now who struggle with this just like i did. 
Is there any downside on using jdk 11 instead of the latest?

**Comment by raresn** [comment]
Apple accepted our submission now
For anyone following this, here is what i've learned:
- Update ANEs before publishing.
- In order to use ANEs from distriqt you now have to use a MAC in order to compile for iOS because of dependencies.
- If you are using VMware for the MAC, don't compile in the share folder, it will not work. Copy all the files to local folder then try.
- If the keychain/signing fails after you import the cer/p12 in your mac keychain and NOTHING works, a solution would be to use JDK 11 and then the compiler will use your provided certificates instead of trying to pull them from the mac's keychain.

@ajwfrost and @marchbold thank you for the help solving this. Although it was excruciating and a super steep learning curve on mac, could not do this without your help. Thanks again.
