### ISSUE TITLE
ByteArray.clear() not working correctly in a ByteArray shareable Worker and causes a memory leak

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#2840]
## Problem Description

ByteArray.clear() not working correctly in a ByteArray shareable Worker and causes a memory leak.

* AIR SDK 50.2.3.5
* I tried on Windows 11

## Steps to Reproduce

```
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.MouseEvent;
	import flash.system.MessageChannel;
	import flash.system.Worker;
	import flash.system.WorkerDomain;
	import flash.utils.ByteArray;
	
	public class Main extends Sprite
	{	
		private var worker:Worker;
		
		protected var mainToBack:MessageChannel;
		protected var backToMain:MessageChannel;
		
		protected var bytes:ByteArray = new ByteArray();
		
		public function Main()
		{	
			if (Worker.current.isPrimordial)    
			{
				bytes.shareable = true;
				
				//Create worker from the main swf 
				worker = WorkerDomain.current.createWorker( this.loaderInfo.bytes );
				
				//Create message channel TO the worker
				mainToBack = Worker.current.createMessageChannel(worker);
				
				//Create message channel FROM the worker, add a listener.
				backToMain = worker.createMessageChannel(Worker.current);
				backToMain.addEventListener(Event.CHANNEL_MESSAGE, onBackToMain);
				
				//Now that we have our two channels, inject them into the worker as shared properties.
				//This way, the worker can see them on the other side.
				worker.setSharedProperty("backToMain", backToMain);
				worker.setSharedProperty("mainToBack", mainToBack);
				
				worker.setSharedProperty("bytesExample", bytes);
				
				//Lastly, start the worker.
				worker.start();
				
				var sprite:Sprite = new Sprite();
				sprite.graphics.beginFill(0x0000FF);
				sprite.graphics.drawRect( 0, 0, 100, 100);
				sprite.graphics.endFill();
				sprite.buttonMode = true;
				sprite.addEventListener(MouseEvent.CLICK, mouseClickHandler);
				this.addChild( sprite );
			}
			else
			{
				var worker:Worker = Worker.current;
			
				//Listen on mainToBack for SHARPEN events
				mainToBack = worker.getSharedProperty("mainToBack");
				mainToBack.addEventListener(Event.CHANNEL_MESSAGE, onMainToBack);
				//Use backToMain to dispatch SHARPEN_COMPLETE
				backToMain = worker.getSharedProperty("backToMain");
				
				bytes = worker.getSharedProperty("bytesExample");
			}
		}
		
		private function mouseClickHandler(event:MouseEvent):void
		{
			mainToBack.send("mainToBack");
		}
		
		private function onBackToMain(event:Event):void
		{
			if(backToMain.messageAvailable)
			{
				trace("main return");
				backToMain.receive();
				trace( bytes.length );
				bytes.position = 0; // very important to causes memory leak
				bytes.clear();  // causes memory leak
			}
		}
		
		private function onMainToBack(event:Event):void
		{
			if(mainToBack.messageAvailable)
			{
				trace("back");
				mainToBack.receive();
				bytes.writeInt(2);
				//bytes.position = 0; // very important for expected result but causes bytes.clear(); memory leak
				backToMain.send("backToMain");
			}
		}
	}
}
```
`trace( bytes.length );` return `4` the first time, `8` the second time, `12` the third time,...

* Expected result : always `4`

and causes a memory leak in Scout (click two time on the Sprite)

## Known Workarounds

to get the expected result add `bytes.position = 0;` after `bytes.writeInt(2);` in the back worker but causes `bytes.clear();` memory leak
(It's stange, `bytes.position = 0;` before `bytes.clear();` on main worker not working for expected result but causes memory leak)

**Comment by ajwfrost** [comment]
Okay so this is actually just a consequence of how byte arrays work when they're set as "shareable".. I'm not sure we'd want to change this (given it may then impact existing implementations) but there's a reasonable workaround..

When you set a byte array as shareable, it just means that the underlying memory buffer can be shared between workers. The actual AS3 ByteArray object is different i.e. there are two `bytes` references in your application, one in each worker, they are different objects but they both work on the same underlying memory buffer.

The problem being, this buffer is just a memory area plus a size. There's no concept of "position" in this shared part. So "position" is a property of the AS3 ByteArray objects and are not synced up between the shared values - each reference to the buffer can read or write at different locations, setting `bytes.position` in one worker does not affect the value of the other one.

So what's happening in your example:
1. The worker writes an integer which sets `length` and `position` to 4
2. The primordial calls `clear` which cleans up the underlying buffer and sets `length` to 0. The value of `bytes.position` in the primordial will also be reset to 0.
3. The worker however still has `bytes.position` at its last value, 4....
4. The worker writes an integer, from position 4, which causes a memory allocation of 8 bytes in the underlying shared memory

and thus it continues, the position in the worker is never reset to zero so the new integer values are written later and later, and the memory required for the bytearray will grow.

As long as you're aware of this behaviour, then there are workarounds - either the position can be passed back and forth between primordial and worker using a shared property, or it may be that you can just cope with this prior to the `writeInt` call by checking the length e.g. `bytes.position = Math.min(bytes.position, bytes.length);`

I do think we should update the documentation to make this a lot clearer though....!

**Comment by pol2095** [comment]
Thanks for your explanation
