### ISSUE TITLE
Huawei AppGalery reject application : "Upload a 64-bit app package and try again."

### ISSUE THREAD

**Issue by Nisaba** [airsdk/Adobe-Runtime-Support#2882]
Hello,

I tried to submit an app to the Huawei AppGalery store, (APK)
But I get this message:
"Upload a 64-bit app package and try again."

Whereas I set the <architecture>64</architecture> flag in the app.xml file.

Any idea ?

**Comment by ajwfrost** [comment]
To package an app as a 64-bit APK, you'd need to set this on the command-line ("-arch armv8")

Alternatively you can set it as default by adding the below two lines to a file "c:\users\username\.airsdk\adt.cfg" or "/Users/username/.airsdk/adt.cfg":
```
DefaultArch=armv8
OverrideArch=armv8
```

**Comment by Nisaba** [comment]
thank you
