### ISSUE TITLE
[Issue] Error using runtimeInBackgroundThread

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#2888]
I'm getting theses error when using runtimeInBackgroundThread true in my application and black screen.

` System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewRootImpl.clearChildFocus(ViewRootImpl.java:6241)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.clearChildFocus(ViewGroup.java:1184)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.clearChildFocus(ViewGroup.java:1184)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.clearChildFocus(ViewGroup.java:1184)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.clearChildFocus(ViewGroup.java:1184)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5825)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5777)
10-30 01:07:26.659 20900 21092 W System.err:    at android.view.ViewGroup.removeView(ViewGroup.java:5708)
10-30 01:07:26.659 20900 21092 W System.err:    at com.adobe.air.AndroidActivityWrapper.planeKickCascade(AndroidActivityWrapper.java:674)
10-30 01:07:26.659 20900 21092 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
10-30 01:07:26.659 20900 21092 W System.err:    at com.adobe.air.Entrypoints$1.handleMessage(Entrypoints.java:318)
10-30 01:07:26.659 20900 21092 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
10-30 01:07:26.659 20900 21092 W System.err:    at android.os.Looper.loopOnce(Looper.java:226)
10-30 01:07:26.659 20900 21092 W System.err:    at android.os.Looper.loop(Looper.java:313)
10-30 01:07:26.659 20900 21092 W System.err:    at com.adobe.air.Entrypoints.run(Entrypoints.java:339)
10-30 01:07:26.659 20900 21092 W System.err:    at java.lang.Thread.run(Thread.java:1012)`

`10-30 01:07:26.760 20900 21092 W System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-30 01:07:26.760 20900 21092 W System.err:    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
10-30 01:07:26.760 20900 21092 W System.err:    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2648)
10-30 01:07:26.760 20900 21092 W System.err:    at android.view.View.requestLayout(View.java:27623)
10-30 01:07:26.760 20900 21092 W System.err:    at android.view.View.requestLayout(View.java:27623)
10-30 01:07:26.761 20900 21092 W System.err:    at android.view.View.requestLayout(View.java:27623)
10-30 01:07:26.761 20900 21092 W System.err:    at android.view.View.requestLayout(View.java:27623)
10-30 01:07:26.761 20900 21092 W System.err:    at android.view.ViewGroup.addView(ViewGroup.java:5294)
10-30 01:07:26.761 20900 21092 W System.err:    at android.view.ViewGroup.addView(ViewGroup.java:5236)
10-30 01:07:26.761 20900 21092 W System.err:    at com.adobe.air.AndroidActivityWrapper.planeStepCascade(AndroidActivityWrapper.java:718)
10-30 01:07:26.761 20900 21092 W System.err:    at com.adobe.air.AndroidActivityWrapper.planeKickCascade(AndroidActivityWrapper.java:690)
10-30 01:07:26.761 20900 21092 W System.err:    at com.adobe.air.customHandler.callTimeoutFunction(Native Method)
10-30 01:07:26.761 20900 21092 W System.err:    at com.adobe.air.Entrypoints$1.handleMessage(Entrypoints.java:318)
10-30 01:07:26.761 20900 21092 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
10-30 01:07:26.761 20900 21092 W System.err:    at android.os.Looper.loopOnce(Looper.java:226)
10-30 01:07:26.761 20900 21092 W System.err:    at android.os.Looper.loop(Looper.java:313)
10-30 01:07:26.761 20900 21092 W System.err:    at com.adobe.air.Entrypoints.run(Entrypoints.java:339)
10-30 01:07:26.761 20900 21092 W System.err:    at java.lang.Thread.run(Thread.java:1012)`

**Comment by bobaoapae** [comment]
This occurs just at the beginning of my application, don't know for sure what was happening because it's in the loading screen of the game.. So several things happening at once.

Some examples:

Starting Starling 3d(but without use in this moment due to the loading screen are just a flash sprite).
Loading external swf to displayloader.
Loading xmls.

I can send you the compiled aab or invite you to the closed test in playstore to map these issue and futures one, as currently I'm with 3 big issues open here waiting for updates

**Comment by bobaoapae** [comment]
I made some tests my self due to the delay.

Manually editing the runtimeClasses.jar planeKickCascade and setUpAsyncMode methods.

```
 if (!Looper.getMainLooper().isCurrentThread()) {
            this.sendUIMessage(2);
             return;
}

public void setUpAsyncMode() {
        this.m_uiHandler = new Handler(Looper.getMainLooper()) {
            public void handleMessage(Message msg) {
                switch (msg.what) {
                    case 1:
                        AndroidActivityWrapper.this.continueLaunch();
                        break;
                    case 2:
                        AndroidActivityWrapper.this.planeKickCascade();
                }

            }
        };
    }
```

I can confirm that this change fix my problem, don't know nothing about the problems this can cause, just making some tests to fix my problem.

**Comment by bobaoapae** [comment]
Making this change cause problems as expected, in some devices the MovieClip initialization fail, childs are null causing runtime error of null reference.

I'm waiting for a properly fix by Harman. Thanks.

**Comment by bobaoapae** [comment]
Other problem, i'm doing some others tests and in some devices the air application don't work at all with runtimeInBackgroundThread(with or without the hardcode edit i made). Screen render without problem but screen don't respond to any click.

**Comment by ajwfrost** [comment]
Hi @bobaoapae  - it looks like the above StageText issue is a separate problem.. would you be able to extract the runtimeClasses.jar file from the below zip, and put this into your AIR SDK (lib/android/lib folder), to see if this then helps with your problem about the planeKickCascade error?

thanks

[runtimeClasses.jar.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13336898/runtimeClasses.jar.zip)

**Comment by bobaoapae** [comment]
The error in planeKickCascade it's solved. 

But the other problem that this flag cause are not solved.

> Other problem, i'm doing some others tests and in some devices the air application don't work at all with runtimeInBackgroundThread(with or without the hardcode edit i made). Screen render without problem but screen don't respond to any click.

I don't get any error from logcat or from flash events, the screen just don't work in some devices.

S23 ultra android 13 works fine.
Moto Z3 play android 9. Has this problem.
AVD emulator Pixel 7 Pro api 33 (x86_64). Has this problem.

**Comment by bobaoapae** [comment]
Even Event.ENTER_FRAME are not being fired, it's like after initial first render all stop. I only get one Event.ENTER_FRAME in theses devices with problem

**Comment by bobaoapae** [comment]
i can send you the android project generated if need, just send the private link to upload.

**Comment by ajwfrost** [comment]
Okay thanks -> so that planeKickCascade was one issue, but if you're still seeing a 'stop' on everything, this is more likely to be deadlock. Can I check (a) do you have any ANEs in this, and (b) do you use StageText and/or StageWebView?

We're still struggling with a deadlock issue when a StageText element is focused (the issue you linked against above) so that may be similar now. If you're seeing this also on AVD emulator, that's something we can hopefully then reproduce - I'll send you a link via email to request the Android project for this.

thanks

**Comment by bobaoapae** [comment]
I don't use stage text or stage webview.

Files already send on the link received via email.

Thanks.
