### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#2923]
I'm trying to package ipa on windows on air 50.2.3.8

<details>
  <summary>adt.log</summary>
  ADT 50.2.3.8 called with: -version

ADT 50.2.3.8 called with: -package -target ipa-ad-hoc -useLegacyAOT yes -provisioning-profile D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/buddies/Buddies_staging_qa.mobileprovision -storetype PKCS12 -keystore D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/Slotagram_dev.p12 -storepass xxxxxx buddies-mobile-boot.ipa slotagram-mobile-boot-app-ios.xml slotagram-mobile.swf -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target assets -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target GoogleService-Info.plist -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target Frameworks -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/src/main/resources/buddies/root_ios . -extdir .

ADT 50.2.3.8 called with: -package -target ipa-ad-hoc -useLegacyAOT yes -provisioning-profile D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/buddies/Buddies_staging_qa.mobileprovision -storetype PKCS12 -keystore D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/config/Slotagram_dev.p12 -storepass xxxxxx buddies-mobile-boot.ipa slotagram-mobile-boot-app-ios.xml slotagram-mobile.swf -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target assets -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target GoogleService-Info.plist -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/target Frameworks -C D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2/src/main/resources/buddies/root_ios . -extdir .

Warning: Using default implementation for native extension 'androidx.appcompat'

Warning: Using default implementation for native extension 'com.android.installreferrer'

Warning: Using default implementation for native extension 'com.distriqt.playservices.AppSet'

Warning: Using default implementation for native extension 'io.reactivex'

Warning: Using default implementation for native extension 'com.google.protobuflite'

Warning: Using default implementation for native extension 'com.google.android.play'

Warning: Using default implementation for native extension 'com.distriqt.playservices.CloudMessaging'

Warning: Using default implementation for native extension 'com.google.android.datatransport'

Warning: Using default implementation for native extension 'androidx.browser'
Warning: Using default implementation for native extension 'androidx.vectordrawable'

Warning: Using default implementation for native extension 'com.distriqt.WindowsStore'

Warning: Using default implementation for native extension 'com.distriqt.playservices.AdsIdentifier'

Warning: Using default implementation for native extension 'com.distriqt.square.okhttp'

Warning: Using default implementation for native extension 'androidx.constraintlayout'

Warning: Using default implementation for native extension 'com.distriqt.square.okhttp3'

Warning: Using default implementation for native extension 'com.bumptech.glide'

Warning: Using default implementation for native extension 'com.google.guava'
Warning: Using default implementation for native extension 'androidx.cardview'

Warning: Using default implementation for native extension 'com.google.code.gson'

Warning: Using default implementation for native extension 'com.jetbrains.kotlin'

Warning: Using default implementation for native extension 'com.google.dagger'

Warning: Using default implementation for native extension 'com.distriqt.playservices.Ads'

Warning: Using default implementation for native extension 'androidx.emoji2'

Warning: Using default implementation for native extension 'androidx.exifinterface'
Warning: Using default implementation for native extension 'androidx.core'

Warning: Using default implementation for native extension 'io.grpc'
Warning: Using default implementation for native extension 'com.distriqt.playservices.Base'

Finalising signature for framework: Frameworks/FBAEMKit.framework/FBAEMKit, file is D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\Frameworks\FBAEMKit.framework\FBAEMKit

Config type ipa-ad-hoc, platform is iOS

SwiftSupport files: copied as-is

Swift libraries in payload: copied as-is

Checking certificate chain for the issuer
Signing certificate subject name = C=IL,O=Everybuddy Games LTD,OU=Q7H33EX62C,CN=iPhone Developer: Aviv Everybuddy (UPS9C55HWZ),UID=5RGTL45QXD
Signing certificate issuer name  = C=US,O=Apple Inc.,OU=G3,CN=Apple Worldwide Developer Relations Certification Authority
Found certificate in chain, subject name = C=IL,O=Everybuddy Games LTD,OU=Q7H33EX62C,CN=iPhone Developer: Aviv Everybuddy (UPS9C55HWZ),UID=5RGTL45QXD
Found certificate in chain, subject name = CN=Apple Worldwide Developer Relations Certification Authority,OU=Apple Worldwide Developer Relations,O=Apple Inc.,C=US
Found certificate in chain, subject name = C=US,O=Apple Inc.,OU=G3,CN=Apple Worldwide Developer Relations Certification Authority
Match -> found issuer

Finalising signature for framework: Frameworks/FBAudienceNetwork.framework/FBAudienceNetwork, file is D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\Frameworks\FBAudienceNetwork.framework\FBAudienceNetwork

Config type ipa-ad-hoc, platform is iOS

SwiftSupport files: copied as-is

Swift libraries in payload: copied as-is

Finalising signature for framework: Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit, file is D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\Frameworks\FBSDKCoreKit.framework\FBSDKCoreKit

Config type ipa-ad-hoc, platform is iOS

SwiftSupport files: copied as-is

Swift libraries in payload: copied as-is

Finalising signature for framework: Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics, file is D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\Frameworks\FBSDKCoreKit_Basics.framework\FBSDKCoreKit_Basics

Config type ipa-ad-hoc, platform is iOS

SwiftSupport files: copied as-is

Swift libraries in payload: copied as-is

Finalising signature for framework: Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit, file is D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\Frameworks\FBSDKLoginKit.framework\FBSDKLoginKit

Config type ipa-ad-hoc, platform is iOS

SwiftSupport files: copied as-is

Swift libraries in payload: copied as-is

compile-abc command line: C:\flash_air_sdk_50\lib\aot/bin/compile-abc/compile-abc-64.exe -mtriple=arm64-apple-ios -filetype=obj -sdk C:\flash_air_sdk_50\lib\aot/lib/avmglue.abc -fields C:\flash_air_sdk_50\lib\aot/lib/air-fields.arm64-air.txt -O3 -ane-symbol=IDFAExtInitializer -ane-symbol=IDFAExtFinalizer -ane-symbol=BoltsExtInitializer -ane-symbol=BoltsExtFinalizer -ane-symbol=FirebaseCoreExtInitializer -ane-symbol=FirebaseCoreExtFinalizer -ane-symbol=FirebaseCrashlyticsExtInitializer -ane-symbol=FirebaseCrashlyticsExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinMAXFREInitializer -ane-symbol=AppLovinMAXFREFinalizer -ane-symbol=ApplicationExtInitializer -ane-symbol=ApplicationExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=VibrationExtInitializer -ane-symbol=VibrationExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=ShareExtInitializer -ane-symbol=ShareExtFinalizer -ane-symbol=FirebaseExtInitializer -ane-symbol=FirebaseExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=FacebookLoginExtInitializer -ane-symbol=FacebookLoginExtFinalizer -ane-symbol=FirebaseMessagingExtInitializer -ane-symbol=FirebaseMessagingExtFinalizer -ane-symbol=PushNotificationsExtInitializer -ane-symbol=PushNotificationsExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=CoreExtInitializer -ane-symbol=CoreExtFinalizer -ane-symbol=FacebookCoreExtInitializer -ane-symbol=FacebookCoreExtFinalizer -ane-symbol=InAppBillingExtInitializer -ane-symbol=InAppBillingExtFinalizer -ane-symbol=AFExtensionInitializer -ane-symbol=ZipUtilsExtInitializer -ane-symbol=ZipUtilsExtFinalizer -ane-symbol=AppleSignInExtInitializer -ane-symbol=AppleSignInExtFinalizer -ane-symbol=VolumeExtInitializer -ane-symbol=VolumeExtFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -ane-symbol=AppLovinAIRMediationFREInitializer -ane-symbol=AppLovinMAXMediationFREFinalizer -abc-file-list=D:\Jenkins\jobs\slotagram-build-qa\workspace\webapp\flex\slotagram-mobile-boot2\target\AOTBuildOutput4805101546938660219.tmp\ABCFilesList.txt

ld64 command line: C:\flash_air_sdk_50\lib\aot/bin/ld64/ld64.exe -pie -ObjC -dead_strip -Z -arch arm64 -L"C:\\flash_air_sdk_50\\lib\\aot/stub" -F"C:\\flash_air_sdk_50\\lib\\aot/stub" -L"C:\\flash_air_sdk_50\\lib\\aot/lib" -o "../aot8337618775722649283.tmp" -x "C:\\flash_air_sdk_50\\lib\\aot/lib/libRuntimeHMAOT.arm-air.a" "C:\\flash_air_sdk_50\\lib\\aot/lib/libNotification.arm-air.a" -lc++ -lSystem.B -lz -lobjc -lclang_rt.ios -weak_framework AppTrackingTransparency -framework AdSupport -w "-FC:\\Windows\\Temp\\968ef181-13e2-498a-97fa-a3a4e775989c" -framework "Bolts" -rpath /usr/lib/swift -lswiftFoundation -lSwiftCompat -lsqlite3 -lz -framework SystemConfiguration -framework StoreKit -framework Security -framework CoreTelephony -framework CoreData -framework "FBLPromises" -framework "FirebaseCore" -framework "FirebaseCoreExtension" -framework "FirebaseCoreInternal" -framework "FirebaseInstallations" -framework "GoogleAppMeasurement" -framework "GoogleDataTransport" -framework "GoogleUtilities" -framework "nanopb" -framework "PromisesSwift" -framework "FirebaseSharedSwift" -ObjC -lz -lsqlite3 -w -framework "FirebaseCrashlytics" -framework "FirebaseSessions" -ObjC -framework "AppLovinMediationGoogleAdManagerAdapter" -ObjC -framework "UnityAds" -ObjC -framework "AppLovinMediationIronSourceAdapter" -lclang_rt.ios -liconv -lz -framework WebKit -framework UIKit -framework SafariServices -framework MessageUI -framework CoreMotion -framework CoreMedia -framework CoreGraphics -framework AVFoundation -framework AudioToolbox -framework AppTrackingTransparency -framework "AppLovinSDK" -w -lc++ -framework Foundation -framework QuartzCore -framework Social -framework CoreLocation -framework Accounts -framework Accelerate -ObjC -framework "FBSDKCoreKit" -framework CoreHaptics -w -ObjC -framework "AppLovinMediationMintegralAdapter" -ObjC -framework "AppLovinMediationGoogleAdapter" -framework ImageIO -w -framework "FirebaseAnalytics" -ObjC -framework "AppLovinMediationFacebookAdapter" -framework "FBSDKLoginKit" -w -framework UserNotifications -framework AddressBook -lsqlite3 -lz -weak_framework WebKit -weak_framework SafariServices -weak_framework JavaScriptCore -weak_framework AdSupport -framework MobileCoreServices -framework MediaPlayer -framework CoreVideo -framework CFNetwork -ObjC -framework "GoogleMobileAds" -lclang_rt.ios -framework EventKitUI -framework EventKit -weak_framework Foundation -ObjC -framework "IronSource" -lz -lxml2 -lsqlite3 -ObjC -framework "MTGSDK" -framework "MTGSDKBanner" -framework "MTGSDKBidding" -framework "MTGSDKInterActive" -framework "MTGSDKInterstitial" -framework "MTGSDKInterstitialVideo" -framework "MTGSDKNativeAdvanced" -framework "MTGSDKReward" -framework "MTGSDKSplash" -lclang_rt.ios -ObjC -weak_framework UserNotifications -w -framework "CoreNativeExtension" -rpath @executable_path/Frameworks -weak_framework Social -framework AuthenticationServices -framework "FBAEMKit" -framework "FBSDKCoreKit_Basics" -lclang_rt.ios -liconv -framework iAd "-LC:\\Windows\\Temp\\f1d3cc38-c3f9-430c-827a-4aacf5e0f598" "-lAppsFlyerLib" -liconv -lz -w -w -framework "AppLovinMediationUnityAdsAdapter" -lxml2 -lc++ -weak_framework VideoToolbox -weak_framework SystemConfiguration -weak_framework LocalAuthentication -weak_framework CoreTelephony -weak_framework CoreMotion -weak_framework CFNetwork -framework CoreImage -ObjC -framework "FBAudienceNetwork" -filelist "D:\\Jenkins\\jobs\\slotagram-build-qa\\workspace\\webapp\\flex\\slotagram-mobile-boot2\\target\\AOTBuildOutput4805101546938660219.tmp\\OBJFilesList.txt" -framework CoreFoundation -framework OpenGLES -framework GameController -framework AssetsLibrary -platform_version ios 12.0 16.4 -exported_symbols_list "D:\\Jenkins\\jobs\\slotagram-build-qa\\workspace\\webapp\\flex\\slotagram-mobile-boot2\\target\\AOTBuildOutput4805101546938660219.tmp\\SYMFilesList.txt"

..java.lang.Thread.getStackTrace(Thread.java:1559)

..com.adobe.air.DebugFile.printStack(DebugFile.java)

..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)

..com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java)

..com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java)

..com.adobe.air.ipa.IPAOutputStream.access$100(IPAOutputStream.java)

..com.adobe.air.ipa.IPAOutputStream$CompileTask.run(IPAOutputStream.java)

..java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

..java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

..java.lang.Thread.run(Thread.java:748)

Stack trace:
..java.lang.Thread.getStackTrace(Thread.java:1559)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java)
..com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream.access$100(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream$CompileTask.run(IPAOutputStream.java)
..java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
..java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
..java.lang.Thread.run(Thread.java:748)

..java.lang.Thread.getStackTrace(Thread.java:1559)

..com.adobe.air.DebugFile.printStack(DebugFile.java)

..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)

..com.adobe.air.ipa.IPAOutputStream$CompileTask.throwAppropriateException(IPAOutputStream.java)

..com.adobe.air.ipa.IPAOutputStream.finalizeSig(IPAOutputStream.java)

..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)

..com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)

..com.adobe.air.ADT.parseArgsAndGo(ADT.java)

..com.adobe.air.ADT.run(ADT.java)

..com.adobe.air.ADT.main(ADT.java)

Stack trace:
..java.lang.Thread.getStackTrace(Thread.java:1559)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.InvalidInputException.<init>(InvalidInputException.java)
..com.adobe.air.ipa.IPAOutputStream$CompileTask.throwAppropriateException(IPAOutputStream.java)
..com.adobe.air.ipa.IPAOutputStream.finalizeSig(IPAOutputStream.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.ipa.IPAPackager.createPackage(IPAPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)

Invalid input: Compilation failed while executing : ld64
</details>

**Comment by shaymolho** [comment]
@ajwfrost any response?

**Comment by ajwfrost** [comment]
Hi - sorry, missed that originally. The failure isn't giving us much information...
```
..com.adobe.air.InvalidInputException.(InvalidInputException.java)
..com.adobe.air.ipa.AOTCompiler.generateMachineBinaries(AOTCompiler.java)
..com.adobe.air.ipa.IPAOutputStream.createIosBinary(IPAOutputStream.java)
```

It actually looks like the linker part has thrown a ProcessError.. but I would have expected actual errors in the linker to be handled more within the code that captures the stdout/stderr of the process. So I'm wondering whether there's something more fundamental here...

Are you able to just check from a command line that you can run:
```
C:\flash_air_sdk_50\lib\aot/bin/ld64/ld64.exe
```
You should get an output such as `ld64: error: must specify arch` -> but at least that shows that it's working!

Next to try would be to copy/paste that long ld64 command line from your log, and see what happens with that. It's likely that some of the temp files won't be around any more, but again you should get the process working properly, just outputting things like "cannot open xyz" or "library/framework not found.."

thanks

**Comment by shaymolho** [comment]
when running from cmd:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6802402/73dedebf-e918-4f6a-bcc0-ce1daafa0360)

**Comment by ajwfrost** [comment]
Ah okay thanks .. so it looks like we built LLVM without incorporating the Visual C++ runtime directly into the binary. Can you please try installing the Microsoft redistributable for your computer from the ones here:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

You're basically looking to get a file "vcruntime140.dll" into the Windows\System32 folder...

thanks

**Comment by shaymolho** [comment]
still same error after installing
my sys32:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6802402/fbdee072-f097-4c27-b9d1-17338c6258cc)

**Comment by ajwfrost** [comment]
Sorry, the hashes I was giving were of the ld64.exe file. I think there are different versions of the VC redistributables 

We'll also see if we can eliminate those dependencies...

**Comment by shaymolho** [comment]
SHA256 hash of C:\flash_air_sdk_50\lib\aot\bin\ld64\ld64.exe:
a5c5b19768719da1a87688139526df0aa33e6a968e497e8cb79f57aa5d757c03

**Comment by ajwfrost** [comment]
Thanks .. so that's the same binary as I have here. Will see whether we can re-build it with the Visual C++ dependencies hard-linked into it..

**Comment by shaymolho** [comment]
unfortunaely the dependency walker doesn't respond after choosing ld64.exe

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6802402/6413e522-31e5-4227-b886-2cc571685adc)

**Comment by shaymolho** [comment]
![Uploading image.png…]()

**Comment by ajwfrost** [comment]
Okay so we've managed to build it without the MSVC runtime dependencies .. are you able to unzip this somewhere and see if it will run on your machine please?
[ld64.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13435549/ld64.zip)

**Comment by shaymolho** [comment]
Now it's ok:

C:\Users\Administrator\Downloads>ld64.exe
ld64: error: must specify -arch

I'll try to build the ipa now. Thanks!

**Comment by jdtapslots** [comment]
@ajwfrost We experienced the exact same problem. 
The ipa compiles now with the replacement ld64.exe, however the built app will close immediately after launching on device.
@shaymolho does your ipa compile and run on device now?

**Comment by shaymolho** [comment]
The ipa runs ok on a non prod env
in order to troubleshoot your problem u need to upload the logs (crash,console)

**Comment by ajwfrost** [comment]
@jdtapslots are you able to create a new issue for this i.e. for the fact the app closes immediately upon launching? This one was more about the ld64.exe application not working properly..

thanks
