### ISSUE TITLE
[Android bundle] An app installed to a device from a bundle has the standard Air app icon.

### ISSUE THREAD

**Issue by ilushaaa** [airsdk/Adobe-Runtime-Support#296]
## Problem Description

AIR SDK: 33.1.1.98
When we generate usual apk and install it on a device we see app-specific icon. That is correct.
But when we build android app bundle and generate apk from it we see the standard Air app icon.

When unziping aab file inside in res folder we saw default Air application icon. For some reasons adt ignore paths to icons which passed in command line:
`-package -target aab -storetype jks -keystore <path to keystore> -storepass <password> -keypass <keypass> $ModuleFileDir$/bin-release/our_app_bundle.aab our-app-descriptor.xml ourApp.swf icons/72.png icons/96.png icons/16.png icons/36.png icons/48.png icons/144.png icons/192.png <other assets>`

All icons folder are ignored, but other assets are placed normally.

All icons from above are set in our-app-descriptor.xml:
 <icon>
        <image16x16>icons/16.png</image16x16>
        <image36x36>icons/36.png</image36x36>
        <image48x48>icons/48.png</image48x48>
        <image72x72>icons/72.png</image72x72>
        <image96x96>icons/96.png</image96x96>
        <image144x144>icons/144.png</image144x144>
        <image192x192>icons/192.png</image192x192>
        <image512x512>icons/512.png</image512x512>      
   </icon>

**Comment by zwetan** [comment]
try to include the folder containing the icons, not all single icons
see [File and path options](https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128fc240122-7ff2.html)
eg.
> **files_and_dirs** The files and directories to package in the AIR file. Any number of files and directories can be specified, delimited by whitespace. If you list a directory, all files and subdirectories within, except hidden files, are added to the package. (In addition, if the application descriptor file is specified, either directly, or through wildcard or directory expansion, it is ignored and not added to the package a second time.) Files and directories specified must be in the current directory or one of its subdirectories. Use the -C option to change the current directory.

for one directory from the root of the build try something like
`-package ... our-app-descriptor.xml ourApp.swf -C icons`

for a sub directory try something like
`-package ... our-app-descriptor.xml ourApp.swf -C ${basedir}/assets icons`

**Comment by nisa-frost** [comment]
Thanks Zwetan for your reply. The result is the same. 
Part of the is default Air icon, and other part is app icon.
Here is folders which stay with default icons:
mipmap-xhdpi-v4\icon.png - default Air icon 48x48   
drawable-xhdpi-v4\icon.png   - default Air icon 96x96
drawable-xxxhdpi-v4\icon.png    - default Air icon 192x192

It looks that is old similar [issue](https://github.com/Gamua/Adobe-Runtime-Support/issues/36).  
 Hope that Harman team will fix this in near future.

**Comment by nisa-frost** [comment]
Thanks Zwetan for your reply. Same here. I have tried your solution as well. The result is the same.
Part of the is default Air icon, and other part is app icon.
Here is folders which stay with default icons:
mipmap-xhdpi-v4\icon.png - default Air icon 48x48
drawable-xhdpi-v4\icon.png - default Air icon 96x96
drawable-xxxhdpi-v4\icon.png - default Air icon 192x192

It looks that is old similar [issue](https://github.com/Gamua/Adobe-Runtime-Support/issues/36).
Hope that Harman team will fix this in near future.

**Comment by ajwfrost** [comment]
Hi - there is an issue with packaging up icons - and resources in general - within the Android App Bundle format. The fact that we are picking up resources from different locations (and in particular if there are any ANEs with resources) is not very well supported from what we can see, so the support for App Bundle is just at an experimental stage. We are hoping to be able to move this forward at some point after discussing further with Google about how to handle the multiple/conflicting resources from the different 

thanks

**Comment by hadisn** [comment]
Problem with icons still not solved?

**Comment by ajwfrost** [comment]
We've got someone looking into the Android App Bundle approach again now, so will be addressing this as part of that activity..

**Comment by hadisn** [comment]
Please let us know when you solve this. Thank you

**Comment by Oldes** [comment]
*PING*
Still there for Android version < 8
![image](https://user-images.githubusercontent.com/454805/124110550-a125e000-da68-11eb-8ab1-bf6c7556ced9.png)

**Comment by ajwfrost** [comment]
@Oldes which AIR SDK did you try with? We have updated the bundle mechanism in 33.1.1.533 and this was one of the issues fixed during the updates to it...

thanks

**Comment by Oldes** [comment]
Ah... it was the older SDK... so my workaround using:
```
COPY %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xhdpi\icon.png R:\temp_air_icon_96.png
COPY %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xhdpi\icon.png R:\temp_air_icon_192.png
COPY /Y Data\Icons\icon_96.png  %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xhdpi\icon.png
COPY /Y Data\Icons\icon_192.png %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xxxhdpi\icon.png
..
COPY /Y R:\temp_air_icon_96.png  %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xhdpi\icon.png
COPY /Y R:\temp_air_icon_192.png %AIR_SDK%\lib\android\lib\resources\captive_runtime\res\drawable-xxxhdpi\icon.png
```
is not needed anymore? If it's fixed, this issue should be closed!

**Comment by ajwfrost** [comment]
Yes - I'd not tracked this issue hence only spotted it when you commented earlier. But yes, please switch to 33.1.1.533 where bundles are [almost] working: there is a known (and now-fixed-but-not-officially-released) issue with multi-dex support, and we are working on an update to ensure some ANEs get the resources properly compiled into the right package names....

But the icon stuff referenced here: should be fixed!

thanks
