### ISSUE TITLE
App Bundle published from Adobe Animate exceeds the maximum size of 200 MB

### ISSUE THREAD

**Issue by animangaplus** [airsdk/Adobe-Runtime-Support#2968]
AIRSDK MacOS 50.2.4.1 using Adobe Animate
The app file size is 1.03 GB

Getting an error from the Google Play Store after uploading my App Bundle:
"Your App Bundle contains the following configurations where the initial install would exceed the maximum size of 200 MB: "
<img width="1328" alt="Screenshot 2023-12-15 at 7 28 39 AM" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/3451359/95b5d88f-6dcd-475b-a2fc-31bc9dd38ea2">

Followed the instructions here: https://github.com/airsdk/ANE-PlayAssetDelivery
![Screenshot 2023-12-15 at 7 29 05 AM](https://github.com/airsdk/Adobe-Runtime-Support/assets/3451359/9951d198-9b43-45bf-b759-9927cdb074e4)

Also followed this since I'm using Adobe Animate: https://github.com/airsdk/Adobe-Runtime-Support/issues/925#issuecomment-869107708

Any insights on possible solutions/workarounds are greatly appreciated!

**Comment by ajwfrost** [comment]
Presumably your app descriptor file is listing the required asset packs that are mentioned in that "my_asset_packs" folder? Is it possible to share the ADT log of what's happening when you build it? (simplest to run the AIR SDK Manager and go to "Troubleshooting", before then doing the packaging in Animate)

thanks

**Comment by animangaplus** [comment]
Thanks for the reply. Yup, app descriptor is listing the required asset:
<img width="790" alt="Screenshot 2023-12-16 at 10 58 10 AM" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/3451359/ea15523e-d79a-4582-98be-89706889a9fb">

As for the ADT log, here's what I've got:

ADT 50.2.4.1 called with: -package -target apk-captive-runtime -arch armv8 -storetype PKCS12 -keystore /Users/melchvalimento/Documents/AnimangaPLUS/Classes/app_certificates/Animanga_2048.p12 -storepass xxxxxx /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/tr01_64.apk /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/tr_01-app.xml -C /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/ tr_01.swf appicon/android/v1/mipmap-xxxhdpi/ic_launcher.png appicon/android/v1/mipmap-xxhdpi/ic_launcher.png appicon/android/v1/mipmap-xhdpi/ic_launcher.png appicon/android/v1/mipmap-hdpi/ic_launcher.png appicon/android/v1/mipmap-mdpi/ic_launcher.png appicon/android/v1/mipmap-ldpi/ic_launcher.png -C /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/ Default-568h@2x.png -C /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/ Default@2x.png -C /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/ Landscape.png -C /Users/melchvalimento/Documents/AnimangaPLUS/Animanga_assets/Teddy Ruxpin/1/bin/ my_asset_packs -extdir /private/var/folders/_j/bm_4lzmj4rd703c5c52ndmkc0000gn/T/TemporaryItems/tr_01_ANE_Cache

Overriding request for apk-captive-runtime, instead generating Android App Bundle
Ignoring architecture request for AAB target

Creating device SDK handler - location passed in = /Users/melchvalimento/Library/Android/sdk

Gradle build where ADT is using JRE version 17.0.6
but where Gradle will be using the JDK from /Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/jre/jdk-17.0.6.uni.jdk/Contents/Home/bin/java
Gradle build command:  /Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/jre/jdk-17.0.6.uni.jdk/Contents/Home/bin/java -Xmx1024m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx1024m -Duser.dir="/var/folders/_j/bm_4lzmj4rd703c5c52ndmkc0000gn/T/6399e65b-98bb-4690-979e-70778cc69887" -cp "/var/folders/_j/bm_4lzmj4rd703c5c52ndmkc0000gn/T/6399e65b-98bb-4690-979e-70778cc69887/gradle/wrapper/gradle-wrapper.jar":"/Users/melchvalimento/Documents/AnimangaPLUS/Classes/AIRSDK_MacOS_50.2.4.1/lib/android/bin/gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:bundleRelease

AAB signer command:  /Applications/Adobe Animate 2024/Adobe Animate 2024.app/Contents/jre/jdk-17.0.6.uni.jdk/Contents/Home/bin/jarsigner -storetype PKCS12 -keystore /Users/melchvalimento/Documents/AnimangaPLUS/Classes/app_certificates/Animanga_2048.p12 -storepass xxxx /var/folders/_j/bm_4lzmj4rd703c5c52ndmkc0000gn/T/6399e65b-98bb-4690-979e-70778cc69887/app/build/outputs/bundle/release/app-release.aab 1

**Comment by animangaplus** [comment]
Was able to fix the problem. As @ajwfrost pointed out, the asset pack folder in the descriptor xml should have the same name as the asset pack folder included when the aab is packaged in Adobe Animate.
