### ISSUE TITLE
[AIR SDK 50.2.4.2] Android applications signing broken

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#2978]
## Problem Description
Android applications signing broken using AIR SDK 50.2.4.2.
APK and AAB in result has incorrect certificate/signature and cannot be installed on Android devices (or update over app built with previous AIR SDK version).

Tested with multiple Windows 10 x64 machines with multiple AIR applications for Android with multiple Java versions.
Same problem in all cases.
There is no such issues with AIR SDK 50.2.4.1 or below.

## Steps to Reproduce
Package any AIR app for Android:
`adt -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore certificate.p12 -storepass pass -keypass pass my_app.apk my_app-app.xml my_app.swf`
and try to install it on any Android device:
`adb install my_app.apk`

**Actual Result:**
In adt.log you will see packaging error:
```
Called by: C:\AIR_SDK\lib\adt.jar
ADT 50.2.4.2 called with: -package -target apk-captive-runtime -arch armv8 -storetype pkcs12 -keystore certificate.p12 -storepass xxxxxx -keypass xxxxxx my_app.apk my_app-app.xml my_app.swf
Target requested was apk-captive-runtime, but not using legacy APK so building via Android Studio
Creating device SDK handler - location passed in = C:\Users\username\AppData\Local\Android\Sdk
Version in APK = 50.2.4.2, version of ADT = 50.2.4.2
Gradle build where ADT is using JRE version 1.8.0_391
but where Gradle will be using the JDK from c:/Program Files/Android/Android Studio1/jbr\bin\java.exe
Gradle build command:  c:/Program Files/Android/Android Studio1/jbr\bin\java.exe -Xmx2048m -Dorg.gradle.appname=gradlew -Dorg.gradle.jvmargs=-Xmx2048m -Duser.dir="C:\Users\username\AppData\Local\Temp\c638fc48-cf05-46f0-b87d-3cf0d4ec928f" -DAIR_GRADLE_KEYPWD=xxxxxx -DAIR_GRADLE_STOREPWD=xxxxxx -cp "C:\Users\username\AppData\Local\Temp\c638fc48-cf05-46f0-b87d-3cf0d4ec928f\gradle\wrapper\gradle-wrapper.jar";"C:\SDK\AIR\50\lib\android\bin\gradle-cli.jar" org.gradle.wrapper.GradleWrapperMain :app:assembleRelease
Does not exist: C:\Users\username\AppData\Local\Temp\c638fc48-cf05-46f0-b87d-3cf0d4ec928f/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk
```

On installation you will get error:
```
Performing Streamed Install
adb: failed to install my_app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl184335977.tmp/base.apk: Attempt to get length of null array]
```
AIR applications for Android cannot be installed.

**Expected Result:**
Application will be properly signed and successfully installed.

## Known Workarounds
Downgrade to AIR SDK 50.2.4.1.

**Comment by ajwfrost** [comment]
Okay we appear to have two problems here:
1) a release build won't actually sign the APK... it signs with `apk-debug` but not with `apk` or `apk-captive-runtime`. Looks like we need to adjust the configuration slightly..
2) a relative path for a certificate file (.p12) is not then turned into an absolute path for the build.gradle file, which means that signing would fail anyway unless an absolute path to the .p12 is provided on the ADT command line

Will get these sorted out asap...

thanks

**Comment by marcanw** [comment]
Same issue on iOS with AIR SDK 50.2.4.2 (Windows).
Everything is fine with AIR SDK 50.2.4.1.
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/c24354aa-ee85-4f9f-803e-dc0367b84ff1)

**Comment by ajwfrost** [comment]
@itlancer  patch version for the Android signing issue:
[adt.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13733145/adt.zip)

@marcanw that's going to be a different issue but just to check, it says it's signed with invalid entitlements .. which type of build was it (debug/ad-hoc/app-store), and can you provide your certificate name? There may be a mis-match in whether we've set it up right.

**Comment by marcanw** [comment]
@ajwfrost the build type was "device testing in interpreter mode" (same with Ad-Hoc). Certificate name is "C:\work\dev2024.p12"

**Comment by itlancer** [comment]
@ajwfrost
It works fine with your patch.
Thank you very much!

**Comment by marcanw** [comment]
I wasn't able to build on android using AIR SDK 50.2.4.2.
I load the new adt.jar and it gets worse.
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/0e098457-92f0-43fc-a3cd-4f0fc0e7b5fd)
I see it uses Gradle, however I set CreateAndroidAppBundle=false. I switched it off because I had this problem in the past.

**Comment by itlancer** [comment]
@marcanw, @ajwfrost, indeed with latest patch AAB cannot be packaged. In my case:
```
NOTE: Multiple Android build-tools folders exist, choosing the latest version (34.0.0) for packaging
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\username\AppData\Local\Temp\f5b4c6c0-2916-4647-a659-8f3f99c7bf17\app\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\username\AppData\Local\Temp\f5b4c6c0-2916-4647-a659-8f3f99c7bf17\app\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

        at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
        at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
```

**Comment by FliplineStudios** [comment]
I'm seeing the same error as @itlancer for AABs with the adt patch (looks like apk works for me though)

**Comment by marcanw** [comment]
I already went to this and no luck. I get `erreur keytool : java.io.IOException: keystore password was incorrect`
I get this withn -v:
`java.io.IOException: keystore password was incorrect
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2116)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at java.base/java.security.KeyStore.getInstance(KeyStore.java:1807)
        at java.base/java.security.KeyStore.getInstance(KeyStore.java:1687)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:928)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:412)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:405)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.security.cert.CertificateException: Unable to initialize, java.io.IOException: DerInputStream.getLength(): Redundant length bytes found
        ... 8 more`

I'm 100% sure about the password. The only thing that might create a problem is that the P12 file is 10 years old.

**Comment by ajwfrost** [comment]
> The only thing that might create a problem is that the P12 file is 10 years old.

Do you have an install of JDK 1.7 or 1.8 with a build number < 161? I think those ones may work...

Although I just dug out an old store with a 1024-bit key, and didn't have much luck with keytool there:
1.7 -> "Invalid keystore format" 
1.8 ->"Unable to initialize, java.io.IOException: DerInputStream.getLength(): Redundant length bytes found"

So it may be you'll need to generate a new certificate with a 4096-bit key...?!

**Comment by ajwfrost** [comment]
@itlancer @FliplineStudios 
For a better patch:
[adt.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13745756/adt.zip)

**Comment by marcanw** [comment]
@ajwfrost I thought that generating and using a new certificate for an existing application on the Google Play Store could pose significant issues with updates.

**Comment by ajwfrost** [comment]
I think Play App Signing is the way to go...

With your certificate, it won't work if we try signing via Gradle (which is the mechanism we just put in there for APK files) because Gradle needs a higher version of Java. If you build an AAB file though, you don't need to sign it..  and then theoretically you can sign that using an older version of Java with your certificate, but I don't know that this would do any good... I'm pretty sure if you try to convert your AAB to APK, you'll need to provide a certificate and I'm not sure whether the Android bundletool works with that...

So probably you would need to follow the guidelines here:
https://airsdk.dev/docs/tutorials/platform/android/handling-1024bit-certificates

Good luck!

**Comment by itlancer** [comment]
With latest patch all works fine for me.
Thank you very much!

**Comment by marcanw** [comment]
> I think Play App Signing is the way to go...
> 
> With your certificate, it won't work if we try signing via Gradle (which is the mechanism we just put in there for APK files) because Gradle needs a higher version of Java. If you build an AAB file though, you don't need to sign it.. and then theoretically you can sign that using an older version of Java with your certificate, but I don't know that this would do any good... I'm pretty sure if you try to convert your AAB to APK, you'll need to provide a certificate and I'm not sure whether the Android bundletool works with that...
> 
> So probably you would need to follow the guidelines here: https://airsdk.dev/docs/tutorials/platform/android/handling-1024bit-certificates
> 
> Good luck!

Ok I went through the the process with Play App Signing. I have a new 2048 p12. It works fine with AIR 502.4.1 (even with CreateAndroidAppBundle=true), but I have an error this with AIR 502.4.2 
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/759322d1-2c96-4c68-9502-8d69c7601aaf)

I installed both ADT patches above but no luck...

**Comment by ajwfrost** [comment]
@marcanw just to check here, with this new 2048 p12 certificate, did you create it using ADT per those guidelines on airsdk.dev? and with which version of ADT/AIR SDK?

The error message there appears to be from Animate themselves .. (the capital 'c' on "Could not load keystore file" isn't found in our version of ADT!) - so they seem to be catching an error, reporting that in the first line, and then displaying the generic "something went wrong, maybe it's the password" error.

But curious if this works with AIR 50.2.4.1 but then fails with 50.2.4.2, do you mean having these set up within Animate it works with the former - even with the same version of Animate?

**Comment by PippoApps** [comment]
Thank you the patch worked for me as well.

**Comment by marcanw** [comment]
Hi @ajwfrost 
I haven't received any updates regarding my signing issue, so I attempted a build with the latest AIR version 50.2.4.3, but unfortunately, I had no luck.
I still can't build on Windows/Animate.
I created the p12 as follow.
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/0d66bb4c-1476-49a7-83f7-6cbe8be72424)
Then when I try to build it gives me this error:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/83d7f851-7e1d-485d-bc39-f3ed67caed44)
I'm 100% confident for the password 
What can I do?
Thank you for your help

**Comment by ajwfrost** [comment]
I just created a certificate the same way, with Java 1.8.0_302, and Animate used it successfully to sign an APK.
Can I check:
- what version of Animate is this?
- what version of AIR SDK have you got under the "manage AIR SDK" (or rather, does it have "AIR xx.xx.xx.xx for Android" in the Publish Settings menu?)
- can you check the adt.log file in your c:\users\username folder? If that doesn't exist, then add the line "DebugOut=true" to a file c:\users\username\.airsdk\adt.cfg, and re-build from Animate

thanks

**Comment by marcanw** [comment]
- what version of Animate is this?
19.2.1

- what version of AIR SDK have you got under the "manage AIR SDK" (or rather, does it have "AIR xx.xx.xx.xx for Android" in the Publish Settings menu?)
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/ef684aa5-5dbb-404e-b098-3e540c45082f)

- can you check the adt.log file in your c:\users\username folder? If that doesn't exist, then add the line "DebugOut=true" to a file c:\users\username.airsdk\adt.cfg, and re-build from Animate
[adt.log](https://github.com/airsdk/Adobe-Runtime-Support/files/14069433/adt.log)

**Comment by marcanw** [comment]
HI @ajwfrost 
Any news on this?

**Comment by ajwfrost** [comment]
Sorry, I'd missed your response there. 

I'm wondering whether there's something weird in that Animate version and the JRE that it has, which may be causing a problem here? Do you get the same error if you just run that command line (from the log file) directly? You'd have to put back in your passcode there...

If that's still failing then we may need to create a custom ADT file with more logging to find out what actually causes this, or if you're happy sending us the certificate file and password separately, we could see whether we reproduce the problem here?

thanks

**Comment by marcanw** [comment]
Hi @ajwfrost 
I tried with the command-line and it works fine. I didn't upload the result tho. I should be able to use the new upload certif in a couple days.
I guess I will have to use this route in the future?
Thx

**Comment by ajwfrost** [comment]
It might be that you can update the JRE within Adobe Animate (or update Animate itself?)..
If you can find a folder somewhere under Animate, where there's a java.exe file, move that parent folder from "jre" to "jre_old" or similar, and then create a new jre folder to copy in the 1.8 version of Java that you had earlier (or whatever you get from the command-line when doing "java -version"). Then as long as the path name for java.exe stays the same, Animate should pick that version up instead..

**Comment by marcanw** [comment]
Hi @ajwfrost 
I replaced the jre as explain. I have now this error:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/8f228fb4-c535-4196-bb4a-58e99d0d0700)
If I click ok, it makes the build. But the build doesn't work on device. I just have a black screen when I start the app.
Then trying to make a debug i get this error:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/21979056/acf0e1c3-db01-4612-9edd-bc23cad26d6d)
swf is indeed very small (102k)

**Comment by fix89** [comment]
Hi! I have the same error INSTALL_PARSE_FAILED_NO_CERTIFICATES using AIR 50.2.4.4 when try to create android bundle. The error occurs only on my new MacBook Pro m3 MAX. On my Macbook with i9 everything is ok.

I use Adobe Animate 23
