### ISSUE TITLE
AIR SDK 50.2.4.2 : ApplicationVerificationFailed using Entitlements "com.apple.security.application-groups"

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#2989]
## Problem Description

ApplicationVerificationFailed using Entitlements "com.apple.security.application-groups" on Windows and macOS.

* AIR SDK 50.2.4.2 
* iOS 17.0, ipa created on Windows 11 and macOS 14.2.1

## Steps to Reproduce

when I add in the app descriptor :
```
<Entitlements>
	<![CDATA[
		<key>com.apple.security.application-groups</key>
		<array>
			<string>group.com.test.MyApp.sharing</string>
		</array>
	]]>
</Entitlements>
```
on Windows and macOS, when I try to insatll the ipa, I have this message error :
```
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/MyApp.app/SC_Info/MyApp.sinf in archive!
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0x00000000: Application is missing the application-identifier entitlement.
```

I created an "App Groups" on the Apple Developer console, and enabled it for my App IDs "com.test.MyApp".

## Known Workarounds

using AIR SDK 50.2.3.8 the app is installed without error.

**Comment by ajwfrost** [comment]
I think you need to add the application identifier (and it should be enabled in the provisioning profile too?)


From https://stackoverflow.com/questions/28371652/ios-8-1-3-enterprise-distribution-application-is-missing-the-application-ide, which is about enterprise distribution and re-signing things, but this part I believe should apply to other deployments:
```
<key>application-identifier</key>
<string>S836XXACME.uk.co.acme.AcmeApp</string>
```

**Comment by pol2095** [comment]
If you see in `MyApp.ipa/Payload/MyApp.app/MyApp` using Air 50.2.4.2, `<key>application-identifier</key>` is defined :

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> 
<plist version="1.0"> 
    <dict> 
        <key>application-identifier</key> 
        <string>S836XXACME.com.test.MyApp</string> 
        <key>get-task-allow</key> 
        <true/> 
        <key>com.apple.security.application-groups</key> 
        <array> 
            <string>group.com.test.MyApp.sharing</string> 
        </array> 
    </dict> 
</plist> 
úÞqr   ž1“0get-task-allow03application-identifierS836XXACME.com.test.MyApp0G%com.apple.security.application-groups0group.com.test.MyApp.sharingúÞ r        R   X     ‘ ‰€             g                         z€        com.test.MyApp S836XXACME ã»
```

using Air 50.2.3.8 :

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> 
<plist version="1.0"> 
    <dict> 
        <key>application-identifier</key> 
        <string>S836XXACME.com.test.MyApp</string> 
        <key>get-task-allow</key> 
        <true/> 
        <key>com.apple.security.application-groups</key> 
        <array> 
            <string>group.com.test.MyApp.sharing</string> 
        </array> 
    </dict> 
</plist> 
úÞqr    1•0get-task-allowÿ03application-identifierS836XXACME.com.test.MyApp0I%com.apple.security.application-groups 0group.com.test.MyApp.sharingúÞ r        R   X     ‘ ‰À             g                         z€        com.test.MyApp S836XXACME >­F¶3£Ï2|’ä#†­ã_¥~ëåjåŒ.l^T•                                ýöÙi«§RqÅ`F¬òŠSŒèŠ|ýfÿ…¸‘¹ò!
```

creating a native App in Xcode, in `MyApp\DerivedData\MyApp\Build\Products\Debug-iphoneos\MyApp.app\MyApp` :

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>S836XXACME.com.test.MyApp</string>
	<key>com.apple.developer.team-identifier</key>
	<string>S836XXACME</string>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.com.test.MyApp.sharing</string>
	</array>
	<key>get-task-allow</key>
	<true/>
</dict>
</plist>
úÞqr   ×pÌ°Æ03application-identifierS836XXACME.com.test.MyApp01#com.apple.developer.team-identifier
S836XXACME0G%com.apple.security.application-groups0group.com.test.MyApp.sharing0get-task-allowÿúÞ  Á0€	*†H†÷ 
```

I just noticed a difference between Air 50.2.3.8, native App and 50.2.4.2 :

com.apple.security.application-groups0��group.com.test.MyApp.sharing // Air 50.2.3.8 and native App
com.apple.security.application-groups� 0��group.com.test.MyApp.sharing // Air 50.2.4.2

**Comment by ajwfrost** [comment]
Thanks - interesting.. the difference here is that the 'new' (50.2.4.2) code is encoding that "group.com.test.MyApp.sharing" within an "octet string" .. i.e. those two extra characters are 0x04 and then a length (0x20 I guess if it prints as a space), and then the '0??' parts are a sequence (0x30 = '0') plus the length code and the start of a utf8-string which is the group ID.

Anyway -> we can double-check how the old code was written and try to adapt the new code to handle it the same way (all this is impacted because we've dropped the old sun.security classes in favour of bouncycastle ones). Hopefully that will fix it - I'll update a test version here so that you can try it out asap!

thanks

**Comment by pol2095** [comment]
Great and fast job, the app is installed correctly and "App Groups" works.

**Comment by pol2095** [comment]
Great and fast job, the app is installed correctly and "App Groups" works.

**Comment by ajwfrost** [comment]
Thanks for confirming, will merge that in to the next release..
