### ISSUE TITLE
 Error: Apple App Store allows only universal applications. "FBSDKCoreKit" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3006]
The higher version of Facebook iOS SDK has given up support for 32-bit, so packaging ane will result in an error. What should I do?Build Ane with sdk 50.2.3.4
Error: Apple App Store allows only universal applications. "FBSDKCoreKit" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.

**Comment by ajwfrost** [comment]
Hi
We made a change in 50.2.3.5 for this, see reference "AIR-6766", and from the release notes:
> If an ANE contained iOS libraries that just had arm64 ‘thin’ binaries, rather than universal (armv7 + arm64) binaries, then ADT would throw an error unless the application descriptor had specified a minimum iOS version of 11 or higher. But, since this is now the minimum version that we support for iOS – and since we don’t support armv7 outputs either – this check was not needed and has been removed.

So I think the solution for SDK builds earlier than this is to have the minimum version specified within the app descriptor itself, so within your `<iPhone><InfoAdditions>` section, can you please add:
```
<key>MinimumOSVersion</key>
<string>11.0</string>
```

thanks

**Comment by pengyangjin** [comment]
Can you provide the download as soon as possible? FB will stop supporting version 12.3 on the 8th of next month. We are currently updating Facebook SDK to version 13.

**Comment by pengyangjin** [comment]
> Hi We made a change in 50.2.3.5 for this, see reference "AIR-6766", and from the release notes:
> 
> > If an ANE contained iOS libraries that just had arm64 ‘thin’ binaries, rather than universal (armv7 + arm64) binaries, then ADT would throw an error unless the application descriptor had specified a minimum iOS version of 11 or higher. But, since this is now the minimum version that we support for iOS – and since we don’t support armv7 outputs either – this check was not needed and has been removed.
> 
> So I think the solution for SDK builds earlier than this is to have the minimum version specified within the app descriptor itself, so within your `<iPhone><InfoAdditions>` section, can you please add:
> 
> ```
> <key>MinimumOSVersion</key>
> <string>11.0</string>
> ```
> 
> thanks



> Hi We made a change in 50.2.3.5 for this, see reference "AIR-6766", and from the release notes:
> 
> > If an ANE contained iOS libraries that just had arm64 ‘thin’ binaries, rather than universal (armv7 + arm64) binaries, then ADT would throw an error unless the application descriptor had specified a minimum iOS version of 11 or higher. But, since this is now the minimum version that we support for iOS – and since we don’t support armv7 outputs either – this check was not needed and has been removed.
> 
> So I think the solution for SDK builds earlier than this is to have the minimum version specified within the app descriptor itself, so within your `<iPhone><InfoAdditions>` section, can you please add:
> 
> ```
> <key>MinimumOSVersion</key>
> <string>11.0</string>
> ```
> 
>How to set it in the platform.xml file of ane?

<platform xmlns="http://ns.adobe.com/air/extension/33.1">
    <sdkVersion>10.0</sdkVersion>
    <linkerOptions>
        <option>-lclang_rt.ios</option>
        <option>-ObjC</option>
        <option>-framework Accelerate</option>
        <option>-rpath @executable_path/Frameworks</option>
        <option>-rpath /usr/lib/swift</option>
    </linkerOptions>
    <packagedDependencies>
        <packagedDependency>FBSDKCoreKit.framework</packagedDependency>
        <packagedDependency>FBSDKLoginKit.framework</packagedDependency>
        <packagedDependency>FBSDKShareKit.framework</packagedDependency>
        <packagedDependency>FBSDKCoreKit_Basics.framework</packagedDependency>
		<packagedDependency>FBAEMKit.framework</packagedDependency>
    </packagedDependencies>
</platform>

**Comment by pengyangjin** [comment]
> Hi We made a change in 50.2.3.5 for this, see reference "AIR-6766", and from the release notes:
> 
> > If an ANE contained iOS libraries that just had arm64 ‘thin’ binaries, rather than universal (armv7 + arm64) binaries, then ADT would throw an error unless the application descriptor had specified a minimum iOS version of 11 or higher. But, since this is now the minimum version that we support for iOS – and since we don’t support armv7 outputs either – this check was not needed and has been removed.
> 
> So I think the solution for SDK builds earlier than this is to have the minimum version specified within the app descriptor itself, so within your `<iPhone><InfoAdditions>` section, can you please add:
> 
> ```
> <key>MinimumOSVersion</key>
> <string>11.0</string>
> ```
> 
> thanks

How to set it in the platform.xml file?

**Comment by ajwfrost** [comment]
This isn't something that goes into the ANE at all.. the error message is thrown when the final IPA is being created, so the minimum OS version should be specified within the InfoAdditions of the application's app descriptor file. (There is actually a way for an ANE to also specify the minimum iOS version but that sadly wasn't tied up into the build/packaging process, hence this separate/additional place where we need to give it the 11.0 or higher MinimumOSVersion in each application..)

So there's nothing you can do in the ANE to fix this, it's just the application's descriptor file that needs updating (or switch to ADT in 50.2.3.5 or later?)

**Comment by pengyangjin** [comment]
[](url)[](url)
[buildAne3.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13916728/buildAne3.zip)

These complete projects for building ANE, errors occurred during the ANE construction phase

**Comment by ajwfrost** [comment]
> errors occurred during the ANE construction phase

Okay that's probably something different then, sorry! Wasn't aware of this, let me check and get back to you shortly..

**Comment by ajwfrost** [comment]
@pengyangjin  - you're right, there's also a check/block in the ANE creation code.. it's similar though, it can be overridden with a setting.

In your platform.xml file, can you please change/add the line (just within the top-level `<platform>` tag):
```
    <sdkVersion>11.0</sdkVersion>
```
Anything from 11 upwards should be okay to then ignore the fact it's not a universal binary.

thanks
