### ISSUE TITLE
Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3009]
Everything is ok when using the AIR SDK for Windows - (50.2.2.2) version of SDK for packaging ipa file.
An error occurred when using the new version of SDK for packaging.Signature error during IPA installation.
I tried to use the signing tool to re sign the IPA and everything returned to ok.
The attachment is CodeResources from the original IPA and the  reSigned IPA.
If need the IPA file, I can provide.

[CodeResources.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/13927451/CodeResources.zip)

**Comment by ajwfrost** [comment]
Hi
The diffs there show that:
1) something is different in the Info.plist file
2) the re-signing doesn't include the SHA-1 hash within the `<files2>` block now.. 

I don't think the second thing here should be an issue, but we can check that. But it would also help if we could see some of the other files - notably, the Info.plist files, application.xml descriptors, and the binary 'appname' files that will contain the embedded signature and entitlements..

If you're able to upload the IPAs (or just those files from them) via the below link, we can see what's happening here..

https://transfer.harman.com/requests/6Nixqx1BLh6T4uu91nJphR

thanks

**Comment by ajwfrost** [comment]
@pengyangjin any chance of those IPA files please so that we can check this? thanks

**Comment by pengyangjin** [comment]
I used the AIR SDK MacOS - (50.2.4.2) for packaging, the same error occurred.


AIR SDK MacOS - (50.2.4.2)
Mac Mini 2018 - macOS 14.2.1&nbsp;
Xcode 15.2


Now, both MacOS&nbsp;and window versions of SDK 50.2.4. 2will experience crashes.


The IPA file has 500M, I will provide the file download link later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 凌晨4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)





 
@pengyangjin any chance of those IPA files please so that we can check this? thanks

**Comment by pengyangjin** [comment]
https://drive.google.com/file/d/1lYtLS6CsaZxY-0BPR4uH9q1GoSjawNbF/view?usp=drive_link
https://drive.google.com/file/d/1dyAiyIOkN4Yn0feRxyNd6ixEX7LrwSnT/view?usp=drive_link





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 上午9:45
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复： [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)



I used the AIR SDK MacOS - (50.2.4.2) for packaging, the same error occurred.


AIR SDK MacOS - (50.2.4.2)
Mac Mini 2018 - macOS 14.2.1 
Xcode 15.2


Now, both MacOS and window versions of SDK 50.2.4. 2will experience crashes.


The IPA file has 500M, I will provide the file download link later.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 凌晨4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)





 
@pengyangjin any chance of those IPA files please so that we can check this? thanks

**Comment by ajwfrost** [comment]
Hi - thanks but I can't download from Google Drive, are you able to upload those to our Harman transfer system please?
https://transfer.harman.com/requests/6Nixqx1BLh6T4uu91nJphR

thanks

**Comment by ajwfrost** [comment]
Hi

Thanks for that. So the key difference appears to be in the entitlements section.. they have got different information in there, primarily:
1. the Apple-signed one has removed the `get-task-allow=true` setting. I'm not sure if that's actually valid or not, I would have thought this is required if you're building a developer/debug version, but maybe if you use codesign directly, they remove it...
2. the Apple-signed one has added a team identifier. Not sure this is needed, it's not in the "requirements" code blob...
3. there is a "keychain-access-groups" list. I can't see where this comes from, it's not part of your app descriptor, so it may just be picking up the fact that your account has got this set up... but I'm hoping this isn't actually needed.

So then, the other differences in the blob are how it's created:
1. the Apple codesign one precedes the entitlements with an application-specific tag (0x70) with a 'version 1' , and then wraps things into a 0xB0 tag...  whereas we are just encoding the entitlements as a sequence of elements, which is how they had been done previously!
2. BUT in the version you've got there, we have a mistake in how we encode an array. So your entitlement for the `applesignin` value is a sequence of values (well, of a single value in this case), and the Windows-generated one is wrapping up the result into an octet string (0x04)


Summary ... there are a number of differences which we will need to keep an eye on, if Apple are updating their code signature format ... but, this was built on Windows with a known error in the ADT file that generates the code signature. Are you able to re-try the Windows version using the patched version of ADT.jar that should be extracted into your AIR SDK "lib" folder, and let us know if it then works please?
https://github.com/airsdk/Adobe-Runtime-Support/files/13877375/adt.zip

thanks

**Comment by pengyangjin** [comment]
Ok, I will test and feedback as soon as possible.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)





 
Hi
 
Thanks for that. So the key difference appears to be in the entitlements section.. they have got different information in there, primarily:
  
the Apple-signed one has removed the get-task-allow=true setting. I'm not sure if that's actually valid or not, I would have thought this is required if you're building a developer/debug version, but maybe if you use codesign directly, they remove it...
 
the Apple-signed one has added a team identifier. Not sure this is needed, it's not in the "requirements" code blob...
 
there is a "keychain-access-groups" list. I can't see where this comes from, it's not part of your app descriptor, so it may just be picking up the fact that your account has got this set up... but I'm hoping this isn't actually needed.
  
So then, the other differences in the blob are how it's created:
  
the Apple codesign one precedes the entitlements with an application-specific tag (0x70) with a 'version 1' , and then wraps things into a 0xB0 tag...  whereas we are just encoding the entitlements as a sequence of elements, which is how they had been done previously!
 
BUT in the version you've got there, we have a mistake in how we encode an array. So your entitlement for the applesignin value is a sequence of values (well, of a single value in this case), and the Windows-generated one is wrapping up the result into an octet string (0x04)
  
Summary ... there are a number of differences which we will need to keep an eye on, if Apple are updating their code signature format ... but, this was built on Windows with a known error in the ADT file that generates the code signature. Are you able to re-try the Windows version using the patched version of ADT.jar that should be extracted into your AIR SDK "lib" folder, and let us know if it then works please?
 https://github.com/airsdk/Adobe-Runtime-Support/files/13877375/adt.zip
 
thanks

**Comment by pengyangjin** [comment]
After using this adt. jar, this bug which signature error during IPA installation has been resolved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 晚上7:39
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复： [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)



Ok, I will test and feedback as soon as possible.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] Signature error during IPA installation which using the AIR SDK for Windows - (50.2.4.2) version of SDK  for packaging (Issue #3009)





 
Hi
 
Thanks for that. So the key difference appears to be in the entitlements section.. they have got different information in there, primarily:
  
the Apple-signed one has removed the get-task-allow=true setting. I'm not sure if that's actually valid or not, I would have thought this is required if you're building a developer/debug version, but maybe if you use codesign directly, they remove it...
 
the Apple-signed one has added a team identifier. Not sure this is needed, it's not in the "requirements" code blob...
 
there is a "keychain-access-groups" list. I can't see where this comes from, it's not part of your app descriptor, so it may just be picking up the fact that your account has got this set up... but I'm hoping this isn't actually needed.
  
So then, the other differences in the blob are how it's created:
  
the Apple codesign one precedes the entitlements with an application-specific tag (0x70) with a 'version 1' , and then wraps things into a 0xB0 tag...  whereas we are just encoding the entitlements as a sequence of elements, which is how they had been done previously!
 
BUT in the version you've got there, we have a mistake in how we encode an array. So your entitlement for the applesignin value is a sequence of values (well, of a single value in this case), and the Windows-generated one is wrapping up the result into an octet string (0x04)
  
Summary ... there are a number of differences which we will need to keep an eye on, if Apple are updating their code signature format ... but, this was built on Windows with a known error in the ADT file that generates the code signature. Are you able to re-try the Windows version using the patched version of ADT.jar that should be extracted into your AIR SDK "lib" folder, and let us know if it then works please?
 https://github.com/airsdk/Adobe-Runtime-Support/files/13877375/adt.zip
 
thanks

**Comment by ajwfrost** [comment]
Great, thanks for the quick feedback!

**Comment by Mintonist** [comment]
I have successfully built, deployed  and got approve from Apple (Windows, AIR 50.2.4.3)
@pengyangjin you may close issue

**Comment by FliplineStudios** [comment]
@Mintonist Oh wow, will Apple actually accept an IPA built on Windows now?  They were previously rejecting IPAs packaged with the new LLVM system on Windows with "Non-public API usage" messages, and you had to package on a Mac to get around that.

**Comment by Mintonist** [comment]
> Oh wow, will Apple actually accept an IPA built on Windows now?
I have done it with two my projects. Try and tell us your results.
