### ISSUE TITLE
flash.text.engine.TextLine rawTextLength and "plus" sign

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#3050]
## Problem Description

in a flash.text.engine.TextLine, "`+`" sign causes a strange behavior in [rawTextLength](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextLine.html#rawTextLength) property

* AIR SDK 50.2.4.3 
* all platforms

## Steps to Reproduce

```
package
{
	import flash.display.Sprite;
	import flash.text.engine.TextBlock;
	import flash.text.engine.TextElement;
	import flash.text.engine.TextLine;
	import flash.text.engine.ElementFormat;
	import flash.events.Event;
	import flash.events.MouseEvent;
	
	public class Main extends Sprite
	{
		public function Main()
		{
			var sprite:Sprite = new Sprite();
			sprite.graphics.beginFill(0x0000FF);
			sprite.graphics.drawRect( 0, 0, 100, 100);
			sprite.graphics.endFill();
			sprite.buttonMode = true;
			sprite.addEventListener(MouseEvent.CLICK, clickHandler);
			this.addChild( sprite );
		}
		
		private function clickHandler(event:MouseEvent):void
		{
			var format:ElementFormat = new ElementFormat();
			format.fontSize = 26;
			format.color = 0x0000FF;
			
			var textElement:TextElement = new TextElement('jkqUP+e8Cu62ALgLjkqUPea8Cu62ALgLjkqUPea.aa8Cu62ALgLjkqUPe8Cu62ALgLjkqUPea8C', format);
			//var textElement:TextElement = new TextElement('jkqUP+e8Cu62ALgLjkqUPea8Cu62AL', format);
			
			var textBlock:TextBlock = new TextBlock();
			textBlock.content = textElement;
			
			var textLine:TextLine = textBlock.createTextLine(null, 500);
			
			trace( textLine.rawTextLength );
		}
	}
}
```

`textLine.rawTextLength` return `5` using `'jkqUP+e8Cu62ALgLjkqUPea8Cu62ALgLjkqUPea.aa8Cu62ALgLjkqUPe8Cu62ALgLjkqUPea8C'`
but using `'jkqUP+e8Cu62ALgLjkqUPea8Cu62AL` return `30`

## Known Workarounds

no workarounds

**Comment by ajwfrost** [comment]
Hi

The line is wrapping at the '+' symbol there. It's given a 500 pixel width, so wraps this onto a second line, breaking at the '+'... if you update the width (500) to 1200, for me it then comes back with 75 characters..

thanks

**Comment by pol2095** [comment]
It's strange `'jkqUP+e8Cu62ALgLjkqUPea8Cu62AL'` doesn't wraps this onto a second line, breaking ?

**Comment by ajwfrost** [comment]
If you only give a width of 200, then `jkqUP+e8Cu62ALgLjkqUPea8Cu62AL` starts to wrap.

There are certain rules that are used for putting in line breaks; carriage returns are treated as mandatory breaks, but some points where e.g. it switches from using alphanumerics to using symbols are then treated as optional breaks. So if you specify a width that doesn't allow the full text to be displayed, it will try finding an optional break before it then just starts breaking at the limit of the available width.

Try putting these texts into the old Windows Notepad app, enabling Word Wrap, and playing around with reducing the width of the window. I am getting the same behaviours there..

thanks

**Comment by pol2095** [comment]
It's not a bug, thanks.

**Comment by pol2095** [comment]
You're right on Windows 10 using the old Notepad, but on Windows 11 using the naw Notepad multi tab Microsoft changed the behavior , "plus" sign is no longer treated as optional breaks.

**Comment by ajwfrost** [comment]
Interesting finding! I just looked to see if there's any standard way of doing this ..
https://www.unicode.org/reports/tr14/#PR
> Many currency signs can appear on both sides, or even the middle, of a numeric expression. Therefore the line breaking algorithm, by default, does not break between [PR](https://www.unicode.org/reports/tr14/#PR) and numbers or letters on either side.

So maybe the plus symbols shouldn't allow a break. Although I'm slightly averse to changing the algorithm there as it's going to change behaviour for people.. 

There's actually an AS3 class to adjust this behaviour:
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/ElementFormat.html#breakOpportunity
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/BreakOpportunity.html
And they reference this:
https://unicode.org/reports/tr14/tr14-12.html
i.e. annex 14, version 3.2.0. This has different guidelines:
> Characters that usually precede a numerical expression may not be separated from following numeric characters or following opening characters, EVEN if space character intervenes.

So breaking before a plus - but not after - is allowed in version 3.2.0, but not in the latest version (15.1.0).

Wondering if we should change the behaviour by adding a new constant into `BreakOpportunity` that would allow people to choose the legacy behaviour vs the latest... or we could update based on the API version i.e. namespace of the AIR app descriptor file, but again that would mean people's apps would change behaviour just when they update to a later AIR SDK and change their namespace..

**Comment by Mintonist** [comment]
> a new constant into BreakOpportunity
+

**Comment by pol2095** [comment]
Thanks, [BreakOpportunity.NONE](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/BreakOpportunity.html#NONE) solve the problem.

**Comment by pol2095** [comment]
It's strange that is ont possible to use it in [spark.components.Label](https://flex.apache.org/asdoc/spark/components/Label.html)

**Comment by ajwfrost** [comment]
> It's strange that it doesn't have any properties to use it in spark.components.Label

Flex wraps up a lot of the Flash APIs/components to hide this sort of thing. So yes, it may not be possible to update this without changing the Flex classes themselves. It may be possible to derive a new class from one of the Flex ones, in order to expose this sort of functionality?
