### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by idanasher** [airsdk/Adobe-Runtime-Support#3073]
I have compiled an apk using:
AIR 50.2.4.4 for android 
on windows with animate 2023
target_sdk_version=33
all latest's district anes

the app ('rummyworld3') crashes immediately when opened.
attached the logcat
[crash logcat1.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/14328683/crash.logcat1.txt)

```
02-19 10:44:03.194 18348 18348 E LoadedApk: Unable to instantiate appComponentFactory
02-19 10:44:03.194 18348 18348 E LoadedApk: java.lang.ClassNotFoundException: **Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file** "/data/app/~~06TWvlqcd4XwN8yhcT3wYw==/air.com.pkama.rummyworld3-Yg7OWIwRaUf-pGcf40Cseg==/base.apk"],nativeLibraryDirectories=[/data/app/~~06TWvlqcd4XwN8yhcT3wYw==/air.com.pkama.rummyworld3-Yg7OWIwRaUf-pGcf40Cseg==/lib/arm64, /data/app/~~06TWvlqcd4XwN8yhcT3wYw==/air.com.pkama.rummyworld3-Yg7OWIwRaUf-pGcf40Cseg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
02-19 10:44:03.194 18348 18348 E LoadedApk:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
02-19 10:44:03.194 18348 18348 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-19 10:44:03.194 18348 18348 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by idanasher** [comment]
Adding more information: when compiling is completed i am getting this message:

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/8189469/7f7eb366-c105-4a3d-ae9c-4a3a871ec7a8)

**Comment by ajwfrost** [comment]
The warning there implies that there are two ANEs that have a "core-1.10.1.jar" file referenced. We are making the assumption that these are the same libraries, but maybe they're not, if one of them doesn't have androidx.core.app.CoreComponentFactory and one of them does ...

@marchbold are you able to check which ANEs have that 'core' dependency and see whether there's a possibility of some mis-match?

@idanasher the other thing to check would be in your ADT configuration (or set it via AIR SDK Manager) there's a "Keep Android Studio output" option, if you use that then you can open up the folder "AndroidStudioProject" within Android Studio and then check the dependencies there.. you should find core-1.10.1.jar within the "app\libs" folder, it would be good to just open it in a zip manager to see whether that class is in there...

**Comment by idanasher** [comment]
@ajwfrost  I have followed your guidlines and I have installed the airsdk manager (for the first time)


now when compiling I get this:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/8189469/acf481fe-6600-4bf0-bba6-19010cebb26c)

and this is adt.cfg:
`# See release notes: uncomment these lines in order to force your APK to be generated with 64-bit ARM binaries
# (needed when using an IDE such as Adobe Animate that currently only provides armv7 and x86 as the options via the UI)
DefaultArch=armv8
#OverrideArch=armv8

# See release notes and https://github.com/Gamua/Adobe-Runtime-Support/issues/58
#UncompressedExtensions=emd,tfl,tflite,pb

# Default is to prefiix the package with 'air.' - to turn this off, uncomment the below line
#AddAirToAppID=false

# If you need to increase the heap available to Java when packaging an Android app, you can use the below setting
# when ADT is run from another tool. (If run from the command line, just add -Xmx=2048m or similar to the command
# line within the ADT launch script..)
#JavaXmx=2048m
JavaXmx=3096m

# For debugging, set this to 'true' and a file "adt.log" should be generated in your user's home folder
DebugOut=true

# To override the creation of an Android APK file, and to instead create an Android App Bundle, the below
# flag can be uncommented. Note that the bundle may end up with an "apk" file extension
CreateAndroidAppBundle=true

# When creating an Android App Bundle, this flag can be used to output the Android Studio project
# files in a subfolder of your build directory (rather than using a temporary location that gets
# cleaned up on exit).
KeepAndroidStudioOutput=false

# For convenience, rather than using "-platformsdk" on the command line, these can be set up here:
#AndroidPlatformSDK=path_to_sdk
#iOSPlatformSDK=path_to_sdk

# JAVA_HOME is usually picked up from an environment variable but this can override it:
#JAVA_HOME=path_to_JDK_installation
JAVA_HOME=C:/Users/Edan/AppData/Local/Android/Sdk

# on macos platorms, use the native codesign task rather than trying to use ADT's internal code:
#UseNativeCodesign=true
`

what just happened ?

**Comment by ajwfrost** [comment]
The error is showing that it's getting an invalid value for the platform sdk. That config file isn't setting a platform sdk (although it's got an Android SDK in the "JAVA_HOME" line?)

But also, please note that the config file should be in c:\users\edan\.airsdk\adt.cfg now, so you can either edit that directly, or in the SDK Manager:

Actually .. have just checked this and we appear to have a bug in the AIR SDK Manager, if you're setting the path via that using the "Browse" option, then the config file is showing with backslashes (on Windows). Which would then explain what you're seeing in the Animate output..

Can you please manually edit 
 c:\users\edan\.airsdk\adt.cfg 
and change the backslashes to forwardslashes in those paths?

I'll raise an issue on the AIR SDK Manager project to get that corrected..
thanks

**Comment by idanasher** [comment]
@ajwfrost I have managed (after removing airsdk manager and manually settings 'KeepAndroidStudioOutput=true' on the adt.cfg) to do it.

Now I have 'AndroidStudioProject' folder on my build location. 
I have located the core-1.10.1.jat and it seems that it contains the class:

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/8189469/ad8a3d90-5c27-42c8-a877-389a46cfd627)

**Comment by ajwfrost** [comment]
You're looking for a class "CoreComponentFactory.class" under there in a folder:
androidx/core/app

But maybe that's the wrong library, I had just spotted that one because it had "core" in the name .. 

In terms of ANEs, do you have this one?
```
androidx.core.ane
```
from the "ANE-AndroidSupport" collection from Distriqt..


Also there was a suggestion here, which would involve a change to the manifest file via the App Descriptor xml:
https://stackoverflow.com/a/65980047

**Comment by idanasher** [comment]
@ajwfrost 
I  couldn't find 'CoreComponentFactory' lso folder 'androidx/core/app' neither

Yes, I'm using _androidx.core.ane_ from Distriqt ANE-AndroidSupport

I have tried the manifest App Descriptor xml change suggetsed on stackoverflow.
I have changed the <application row to this:
`<application android:appComponentFactory="androidx"	tools:replace="android:appComponentFactory"	 android:supportsRtl="true">  `

But  I got an  error parsing the xml at compilation time

**Comment by idanasher** [comment]
You're right. I am uploading it again:

[AndroidStudioProject.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/14335129/AndroidStudioProject.zip)

**Comment by marchbold** [comment]
Looks like you have an old version of the `com.google.android.play` extension which is conflicting with the latest `androidx.core` 

Try updating that one to the latest `v1.10.304` 

https://github.com/distriqt/ANE-GooglePlayServices/raw/master/lib/com.google.android.play.ane

**Comment by idanasher** [comment]
@marchbold thanks Michael, it is now working and compiling with no errors

thank you both so much
