### ISSUE TITLE
[AIR SDK 51.0.0.2] Animate trying to use 50.2 namespace

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3083]
## Problem Description
Cannot launch and test application with new AIR SDK 51.0.0.2 features using Adobe Animate CC. Animate trying to use 50.2 namespace.

Tested with Adobe Animate CC 20.0.8 for Windows.
The same issue with any AIR project.
There is no such issues with VS Code.

Manually changing application descriptor namespace to 51.0 didn't resolve this issue - IDE override it back to 50.2.
Some time ago there were the same issues with AIR SDK 50.0.0.1 and 33.1:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2147
https://github.com/airsdk/Adobe-Runtime-Support/issues/204

## Steps to Reproduce
1) Open Adobe Animate CC, create new one AIR project (or open existing one).
2) Try to test it (or simply press Ctrl+Enter) using AIR SDK 51.0.0.2.
3) Take a look at application xml namespace.

**Actual Result:**
`<application xmlns="http://ns.adobe.com/air/application/50.2">`
New AIR 51 features cannot be used.

**Expected Result:**
`<application xmlns="http://ns.adobe.com/air/application/51.0">`
New AIR 51 features cannot be used.

## Known Workarounds
1) In AIR SDK folder open file `samples/descriptor-sample.xml` and change 
`xmlns="http://ns.adobe.com/air/application/50.2"`
to
`xmlns="http://ns.adobe.com/air/application/51.0"`
2) Use another IDE.

**Comment by ajwfrost** [comment]
Thanks - really not sure why Animate are using the 'samples' folder for this, but yes that was an oversight - I had tried to ensure we'd made all the updates to the 'templates' folder which is what should be used for XML definitions/schemas etc! Might raise this with the Animate team...

**Comment by itlancer** [comment]
Fixed with latest AIR 51.0.0.3.
Thanks!
