### ISSUE TITLE
[AIR SDK 51.0.0.2] ReferenceError: Error #1069: Property declaration not found on builtin.as$0.MethodClosure and there is no default value.

### ISSUE THREAD

**Issue by ylazy** [airsdk/Adobe-Runtime-Support#3086]
Hi!
I've tested the new property `declaration` with a Function class instance, and it didn't worked.

Please view this video for more detail:

https://github.com/airsdk/Adobe-Runtime-Support/assets/6010183/fe998ab5-1f77-4852-8932-c57a1a7a96b7

Thanks!

**Comment by itlancer** [comment]
@ylazy, try this fix https://github.com/airsdk/Adobe-Runtime-Support/issues/3084 and in `asconfig.json` file be sure you set up `"swf-version": 51`

**Comment by ylazy** [comment]
> @ylazy, try this fix #3084 and in `asconfig.json` file be sure you set up `"swf-version": 51`

Yeah I did follow your instruction to fix airsdk.xml. So you can see the correct airsdk in the bottom right:
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6010183/901c4d23-f5c1-4ecb-bd0e-c386f5415acd)

Thanks!

**Comment by itlancer** [comment]
For me `declaration` (and other AIR 51 features) works fine if you set up `"swf-version": 51` in `asconfig.json` in `compilerOptions` section.

**Comment by ajwfrost** [comment]
Thanks, so yes it looks like the automatic update of the SWF version didn't work. Will get this sorted out, the idea being there's a default value set in the air-config.xml file which should be used unless you override it. (But that doesn't work by itself unless we also update the compiler...)
