### ISSUE TITLE
AIR SDK Manager doesn't propose to upgrade to AIR 51.0.0.3 from AIR 51.0.0.2

### ISSUE THREAD

**Issue by Adolio** [airsdk/Adobe-Runtime-Support#3097]
Apparently `AIR SDK 51.0.0.3` is available from the list of SDKs but is not proposed as an upgrade of `AIR SDK 51.0.0.2`.

![SDKs](https://github.com/airsdk/Adobe-Runtime-Support/assets/1126990/d41b202f-9b62-45ac-aca0-94858a70a598)
![Installs](https://github.com/airsdk/Adobe-Runtime-Support/assets/1126990/131a9f9d-1e21-4fb9-85dd-3470ff9f072a)

FYI @marchbold 

Best,
Aurélien

**Comment by ajwfrost** [comment]
Interesting -> I hadn't tried with that version but the latest AIR SDK Manager had picked this up for me.
FYI we added a new "prerelease" section to handle these ones...
https://github.com/airsdk/airsdkmanager/releases/tag/v0.7.0

![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/6400804/b5499447-89e4-422f-a3c9-5b233aa3ea27)

**Comment by Adolio** [comment]
Oh nice! Thanks Andrew, I completely missed this new option available from the cog aside the top title! Maybe from a UX stand point people could catch that more easily through a "Preferences" tab...

However from my initial concern, there is still maybe a tiny issue about the fact that `AIR SDK 51.0.0.3` was actually listed from the "Install SDK" without having the "Show Pre-release" option checked.

I'm closing this issue since I managed to upgrade using the AIR SDK Manager 👍 Thank you!
