### ISSUE TITLE
maxD3D cannot be undone

### ISSUE THREAD

**Issue by Fancy2209** [airsdk/Adobe-Runtime-Support#3125]
Before reporting this issue:

- you should consider whether this would be a question better suited to discussions above ^^ ;
- make sure you have searched for similar issues and add your experience there if one exists.

## Problem Description

Describe your problem in detail. Include the following information:
50.2.4
Windows
Myself

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.

Give us a minimal example:

1. On any Starling app, set maxD3D to 9 on the descriptor.
2. Open the app, it'll report DX9
3. Close the app, set maxD3D to 11
4. Open the app, it will still report DX9

**Comment by ajwfrost** [comment]
Hi

Not able to reproduce that here .. with an app being launched via ADL, we can switch the `<maxD3D>` setting between 9 and 11 in the app descriptor file, and each time it launches it shows up as the appropriate value as reported by Starling and from Scout..

Are you able to double-check this please, and ensure you're definitely saving and using the app descriptor correctly (and if using Animate, bear in mind that changes made whilst Animate is open are unlikely to take effect...)

thanks

**Comment by Fancy2209** [comment]
> Hi
> 
> Not able to reproduce that here .. with an app being launched via ADL, we can switch the `<maxD3D>` setting between 9 and 11 in the app descriptor file, and each time it launches it shows up as the appropriate value as reported by Starling and from Scout..
> 
> Are you able to double-check this please, and ensure you're definitely saving and using the app descriptor correctly (and if using Animate, bear in mind that changes made whilst Animate is open are unlikely to take effect...)
> 
> thanks

I can reproduce even after reboots, seeing it on Scout.
I do not have the source of the game, I was just testing it as a end user to see if it'd fix a issue related to black artifacts on ATF textures.
I can reproduce this every try, modifying or removing it has no difference, I swear I am saving application.xml.
I can verify it through ADL, the game did report DX11 before changes.

**Comment by FliplineStudios** [comment]
@Fancy2209 You don't have the source files for the game?  If you're trying to package someone else's game files, it could be the original SWF was compiled with swf-version 37 or earlier, which always defaults to DirectX 9 and will not run as DirectX 11 no matter what you set for maxD3D...

**Comment by Fancy2209** [comment]
> @Fancy2209 You don't have the source files for the game? If you're trying to package someone else's game files, it could be the original SWF was compiled with swf-version 37 or earlier, which always defaults to DirectX 9 and will not run as DirectX 11 no matter what you set for maxD3D...

Last time I checked the header it was set to 41

**Comment by Fancy2209** [comment]
Also I am not packaging someone else's game, I am just a end user, the PC Game is using AIR 50 on a beta branch so I just made the modification to try to fix something, when it didn't have any noteworthy difference I tried rolling back and it seemed stuck

**Comment by ajwfrost** [comment]
It's possible that the game may have noticed the setting and cached something somewhere perhaps - it can always request the Direct9 option when setting up Context3D (although .. hmm... actually .. not sure that's publicly documented!!)

Worth checking anyway, if you clear out the application completely (check in app data for shared objects or other settings..?) to see whether it reverts back to the original D3D11.

Curious as to whether it did fix the ATF issue you were seeing!?

**Comment by Fancy2209** [comment]
It worked now, I was probably editing the wrong file. my bad
![imagem](https://github.com/airsdk/Adobe-Runtime-Support/assets/64917206/f56bf4c3-dac2-4721-be1d-0c3e97f69e34)
the atf issue is that sometimes those black things happen
