### ISSUE TITLE
[Feature] Support dependency via maven on ane android 

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#3130]
In android several times we need to manually dig to download all the dependencies and sub dependencies of any library we want to use on or ane.

I think it's very easy to make some variation of tag in the application plattaform xml to allow add the maven string with version and this just be copied to the grade setting of the android project and then the process of download will all be handled by gradle, this will make the whole process of create ane much more easy.

**Comment by ajwfrost** [comment]
For ANEs, this is already supported?
See `<gradleDependencies>` from #956 

Definition is in templates/extensions/android/Descriptor.50.2.xsd

So you can add gradle repositories and dependencies using your platform xml for an ANE, specifying whatever dependencies are required for frameworks/libraries that are in use.

Not sure this is 100% what you're after but if you can suggest it with an example, we can see what tweaks to the formats/packaging would be required.

thanks

**Comment by ajwfrost** [comment]
Actually just checking the format, it's not `gradleDependencies`, more that we have a section `<gradle>` in which you can have a `<dependencies>` entry, which contains a bunch of `<dependency>` items...

We could probably do with an example for all that...

**Comment by bobaoapae** [comment]
Oh nice, that was what i'm looking, i can't found the docs on the website sorry.
