### ISSUE TITLE
Worker.current.isPrimordial always true AIR 50.2.4

### ISSUE THREAD

**Issue by SigmaAppdevelopment** [airsdk/Adobe-Runtime-Support#3132]
Hi,

I updated AIR SDK from 33.1.1.743 to 50.2.4.

Now my workers aren't working any more.

There is a swf containing Background Worker for Database

DatabaseWorker.as

  	  public function DatabaseWorker()
  	  {
	  	  super();
  
	  	  if(!Worker.current.isPrimordial)
	  	  {
		  	  _toBGChannel = Worker.current.getSharedProperty(TO_BG_CHANNEL) as MessageChannel;
		  	  _toMainChannel = Worker.current.getSharedProperty(TO_MAIN_CHANNEL) as MessageChannel;
		  	  _toBGChannel.addEventListener(Event.CHANNEL_MESSAGE, onMainMessage);
	  	  }
  	  }

Another swf contains the main application

	  public class DBUtil extends EventDispatcher
	  {
	  	  private static var workerInstance:Worker;
	  	  private var _toBGChannel:MessageChannel;
	  	  private var _toMainChannel:MessageChannel;

	  	  [Embed(source="../workerswfs/worker/DatabaseWorker.swf", mimeType="application/octet-stream")]
	  	  private static var DB_BgWorker_ByteClass:Class;

	  	  private function initWorker():void
	  	  {
		  	  if(workerInstance)
			  	  return;

		  	  var _workerTarget:ByteArray = new DB_BgWorker_ByteClass();
	  	  	  workerInstance = WorkerDomain.current.createWorker(_workerTarget, true); 

	  		  _toBGChannel = Worker.current.createMessageChannel(workerInstance);
		  	  _toMainChannel = workerInstance.createMessageChannel(Worker.current);

		  	  workerInstance.setSharedProperty(DatabaseWorker.TO_BG_CHANNEL, _toBGChannel);
	  		  workerInstance.setSharedProperty(DatabaseWorker.TO_MAIN_CHANNEL, _toMainChannel);
	  		  workerInstance.addEventListener(Event.WORKER_STATE, onWorkerStateChanged);

		  	  try
		  	  {
			  	  workerInstance.start();
		  	  }
		  	  catch(error:Error)
		  	  {
			  	  Debug.error("initWorker error: " + error.message);
			  	  return;
		  	  }

		  	  _toMainChannel.addEventListener(Event.CHANNEL_MESSAGE, onWorkerChannelMessage);
	  	  }
	  }
		
The problem is, in Constructor of DatabaseWorker.as is Worker.current.isPrimordial always true, so the background worker is not started.
What am I missing?

**Comment by ajwfrost** [comment]
Did anything change other than the SDK version? and which version are you using now, is it the latest one? Plus - are you using any ANEs?

We did have some issues I think when we were trying to make the ANE SWF definitions to be available from Workers, but I believe those were all fixed in the 50.2.4.x branch.

Have you confirmed that the "isPrimordial" value is true there, or just assuming it is because the code in the "if" block doesn't get executed? (i.e., could it be that the constructor itself is not being called?)

If you are able to create a small self-contained demo showing the problem, we can try to run it here..  which OS are you running on btw?

thanks

**Comment by SigmaAppdevelopment** [comment]
Hi,

no we didn't change anything else. Yes, we are using latest version 50.2.4.4. 

Yes, we are using ANEs. But not inside the worker swfs.

Yes, I have confirmed, that isPrimordial is true, the constructor itself is called. I verified by debugging breakpoints.

I'm developing on macOS Sonoma 14.3, the app with the worker problem is for Android, tested on Android 12 and Android 14.

**Comment by ajwfrost** [comment]
Interesting .. are you able to provide a test app for this? We've just created a quick app based on your code, but this is working (i.e. reports `Is primordial = false`).

Worker:
```
package {
  import flash.system.Worker;
  import flash.display.Sprite;

  public class BkgndWorker extends Sprite
  {
    public function BkgndWorker()
    {
      trace("Is primordial = " + Worker.current.isPrimordial);
    }
  }
}
```

Main app:
```
package {
  import flash.display.Sprite;
  import flash.system.Worker;
  import flash.system.WorkerDomain;
  import flash.utils.ByteArray;

  public class TestWorkers extends Sprite
  {
    [Embed(source="bkgnd/BkgndWorker.swf", mimeType="application/octet-stream")]
    private static var BkgndWorker : Class;

    public function TestWorkers()
    {
      trace("Test workers");
      var workerBytes : ByteArray = new BkgndWorker() as ByteArray;
      var worker : Worker = WorkerDomain.current.createWorker(workerBytes, true);
      trace("Starting worker");
      worker.start();
    }
  }
}
```

Result (from Android 13, armv8 build of 50.2.4.3, but that really shouldn't make a difference - we can check later on Android 14 and 50.2.4.4 though..)

```
03-25 11:17:17.943  5178  5178 I air.com.harman.air.TestWorkers: Test workers
03-25 11:17:17.943  5178  5178 I air.com.harman.air.TestWorkers: Starting worker
03-25 11:17:17.985  5178  5297 I air.com.harman.air.TestWorkers: Is primordial = false
```

**Comment by SigmaAppdevelopment** [comment]
Thanks for your support and the example, it helped a lot. I figured out the problem, it was one single ANE, which was outdated.
I close the issue.
