### ISSUE TITLE
[ANR] My application get not responding dialong even running smoth

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#3137]
How to reproduce: force application to stop respoding due to some AS 3 slow code, or just add a breakpoint, in the time application it's not respoding touch screen some times wait for the first dialog of ANR and then resume application. Even after the application start working normally android keep showing that application it's not responding, maybe due to the old touch events being in some queue or somethink like that.

https://github.com/airsdk/Adobe-Runtime-Support/assets/33332428/2d70c8e2-dfa0-426b-9fe6-5737206cd6b2

**Comment by bobaoapae** [comment]
Anr log from bugreport

[anr_2024-03-24-16-30-33-832.log](https://github.com/airsdk/Adobe-Runtime-Support/files/14736744/anr_2024-03-24-16-30-33-832.log)

**Comment by ajwfrost** [comment]
What version of the AIR SDK was used for this one? we can look at the call stack traces but only if we know the exact version number..

thanks

**Comment by bobaoapae** [comment]
50.2.4

**Comment by ajwfrost** [comment]
@bobaoapae there are four different versions that start 50.2.4..... if you're using the AIR SDK Manager and you're up to date, then it should show a build number of "4" just to the right of the SDK version. Otherwise you can also check in the root of the SDK for the air-sdk-description.xml file and confirm the "build" number - or just run "adt -version".

But we can check this assuming it's 50.2.4.4...
thanks

**Comment by bobaoapae** [comment]
Yeah sorry, 50.2.4.4 latest one available on release channel

**Comment by bobaoapae** [comment]
Hello, was possible to identify anything?

**Comment by bobaoapae** [comment]
@ajwfrost was possible to find the root cause of that? Getting ant even without frame loss it's really bad

**Comment by bobaoapae** [comment]
@ajwfrost hello any news on that?

**Comment by ajwfrost** [comment]
Sorry for the delay. According to your ANR call stacks:

```
"main" prio=5 tid=1 Native
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x738b3f68 self=0xb4000072d1e72400
  | sysTid=9317 nice=-10 cgrp=top-app sched=0/0 handle=0x737d9d5500
  | state=S schedstat=( 96486803892 217860724 50203 ) utm=8395 stm=1253 core=0 HZ=100
  | stack=0x7fc9c38000-0x7fc9c3a000 stackSize=8188KB
  | held mutexes=
  native: #00 pc 000e8dec  /apex/com.android.runtime/lib64/bionic/libc.so (nanosleep+12) (BuildId: 02a91a85343debb2911714273ff2b670)
  native: #01 pc 0028c348  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
  native: #02 pc 00411618  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= waiting for socket data
  native: #03 pc 0057aa88  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= waiting for "continue"
  native: #04 pc 0057ac04  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= halt at breakpoint
  native: #05 pc 00438d5c  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= halt at breakpoint
  native: #06 pc 006acee0  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= enter debugger
  native: #07 pc 007b6f8c  /data/app/~~KFg2AmlKz-2tpq2Fb4lQsA==/br.com.redesurftank.lite.android-i35YvfMeHfEtb1-eAQT4gg==/split_config.arm64_v8a.apk (offset 1000) (???) (BuildId: 5b82e433c72b49787261d88bc6638e041cdf693d)
= "debugLine" handlier
  native: #08 pc 0000e858  <anonymous:71570fb000> (???)
  at com.adobe.air.customHandler.nativeOnTouchCallback(Native method)
  at com.adobe.air.customHandler.handleMessage(customHandler.java:39)
```

So basically, it's executing some ActionScript with a touch handler, and there's a breakpoint set up for the line that it's gone to, so the runtime broke into the debugger and is waiting for the debugger to give it the signal to continue...

Are you able to check whether this happens if you run up the application without the debugger? And then I guess can you also check whether you did actually have any debug breakpoints set up?

thanks
