### ISSUE TITLE
/lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3143]
When I use  AIR SDK for MacOS - (50.2.4.4) to package on Mac mini  M1, 2020  14.4.1 (23E224) , on June 2023, Apple has discontinued the production of computers with Intel chips.
get a error:

packageIpa:
     [echo] p12->antResource/key/ios/iosyttxen_dis.p12
     [echo] mobileprovision->antResource/key/ios/yttxeniphone_dis.mobileprovision
     [java] CodeCache: size=131072Kb used=5839Kb max_used=5839Kb free=125232Kb
     [java]  bounds [0x0000000102b7c000, 0x000000010313c000, 0x000000010ab7c000]
     [java]  total_blobs=1890 nmethods=1523 adapters=282
     [java]  compilation: disabled (not enough contiguous free space left)
     [java] Java HotSpot(TM) 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
     [java] Java HotSpot(TM) 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
     [java] Warning: MinimumOSVersion passed in app-xml is less than supported version, ignoring MinimumOSVersion value
     [java] Warning: ipa-ad-hoc build but provisioning profile contains the beta-reports-active entitlement.
     [java] Compilation failed while executing : compile-abc
     [java] /var/folders/m4/msh701697dj3nzhbchxf07br0000gp/T/cmd6033490877952198985.tmp: line 2: /Users/yangjin1/Downloads/SDK/flex_4.13_air_33.1_x64_50.2.4.4/lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable
     [java] 
BUILD FAILED
/Users/yangjin1/Documents/yttx_ios/client/branch/15.5.0.0/main/LueDi-iOS/ant/build.xml:162: The following error occurred while executing this line:
/Users/yangjin1/Documents/yttx_ios/client/branch/15.5.0.0/main/LueDi-iOS/ant/build.xml:646: Java returned: 12

**Comment by ajwfrost** [comment]
Hi

We build the `compile-abc` application as an x86_64 binary still, because this is something that's also meant to work on the Intel-based mac computers. And on the newer Apple Silicon ones, they have the "Rosetta 2" framework which will allow an x86_64 binary to run seamlessly.

I'm guessing that your machine hasn't got this Rosetta 2 thing on it yet .. it's meant to automatically detect the need for it, and prompt you to install it, and configure itself etc etc ... but that does seem to fail when the application in question is a command-line tool.

So, can you please try manually installing Rosetta 2: if you open a terminal window, enter:
```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```
(from https://machow2.com/rosetta-mac/)

**Comment by pengyangjin** [comment]
I have already tried to package but ipa file will&nbsp;crash.Can provide a air SDK that can be directly used on OSX?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 下午5:57
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复： [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)



Is it okay to use this version of iPhoneOS17.4.sdk with AIR SDK for MacOS - (50.2.4.4)？
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)





 
Hi
 
We build the compile-abc application as an x86_64 binary still, because this is something that's also meant to work on the Intel-based mac computers. And on the newer Apple Silicon ones, they have the "Rosetta 2" framework which will allow an x86_64 binary to run seamlessly.
 
I'm guessing that your machine hasn't got this Rosetta 2 thing on it yet .. it's meant to automatically detect the need for it, and prompt you to install it, and configure itself etc etc ... but that does seem to fail when the application in question is a command-line tool.
 
So, can you please try manually installing Rosetta 2: if you open a terminal window, enter:
 /usr/sbin/softwareupdate --install-rosetta --agree-to-license  
(from https://machow2.com/rosetta-mac/)

**Comment by ajwfrost** [comment]
What SDK version are you using? and can you provide the crash log from the phone's analytics? Most people are using the AIR SDK on mac OSX 14.x - I don't think it would make a difference being 14.4.1 (but am checking).

Have you tried a basic/simple AIR app, as a first step to seeing where an issue may lie?

thanks

**Comment by pengyangjin** [comment]
i use the&nbsp;AIR 50.2.4.4 ( 11-Feb-2024 )&nbsp;AIR SDK for MacOS - (50.2.4.4)，which sdk should i can use?
The packaged ipa file experiencing a crash use&nbsp;AIR SDK for MacOS - (50.2.4.4)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)





 
What SDK version are you using? and can you provide the crash log from the phone's analytics? Most people are using the AIR SDK on mac OSX 14.x - I don't think it would make a difference being 14.4.1 (but am checking).
 
Have you tried a basic/simple AIR app, as a first step to seeing where an issue may lie?
 
thanks

**Comment by pengyangjin** [comment]
the key word is&nbsp;cn.kx.wg.yttxen
the attachment file is crash log
iPhone 13 and iOS ver is 17.3.1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangjin1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上8:12
***@***.******@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;回复： [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)



i use the AIR 50.2.4.4 ( 11-Feb-2024 ) AIR SDK for MacOS - (50.2.4.4)，which sdk should i can use?
The packaged ipa file experiencing a crash use AIR SDK for MacOS - (50.2.4.4)


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)





 
What SDK version are you using? and can you provide the crash log from the phone's analytics? Most people are using the AIR SDK on mac OSX 14.x - I don't think it would make a difference being 14.4.1 (but am checking).
 
Have you tried a basic/simple AIR app, as a first step to seeing where an issue may lie?
 
thanks

**Comment by FliplineStudios** [comment]
@pengyangjin Hmm we've been able to package fine with 50.2.4.4 on macOS 14.4 when using -platformsdk in our adt package command.  I believe the usual path to use is:

`-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`

In our case we specified iPhoneOS17.2.sdk (that was the one included with our Xcode version), but I think the one above will automatically choose whichever is installed in your version of Xcode.

(Also it looks like your crash log didn't get attached in your last message)

**Comment by pengyangjin** [comment]
I used this one you provided to pack, and unfortunately, it crashed.Can you provide an integrated air adk? You know that switching xcode versions is not easy.



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 28, 2024 20:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support]/lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue#3143)




 
@pengyangjin Hmm we've been able to package fine with 50.2.4.4 on macOS 14.4 when using -platformsdk in our adt package command.  I believe the usual path to use is:
 
-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
 
In our case we specified iPhoneOS17.2.sdk (that was the one included with our Xcode version), but I think the one above will automatically choose whichever is installed in your version of Xcode.
 
(Also it looks like your crash log didn't get attached in your last message)

**Comment by ajwfrost** [comment]
> Can you provide an integrated air adk? You know that switching xcode versions is not easy.

Not sure what you mean here? You need to download the AIR SDK, and you need to have Xcode installed with an iPhoneOS SDK. No need to switch between particular Xcode versions? If, by "integrated AIR SDK", you mean an AIR SDK that also includes the iPhoneOS SDK, then no, sorry, that's not permitted by Apple.

How are you packaging up your IPA file at the moment? Do you use a terminal window, command-line tools or ant or similar? or an IDE such as Animate or IDEA? I suspect the key thing is to add that `-platformsdk` per the suggestion from @FliplineStudios because that will make the AIR SDK pick up the official Apple SDK with its "tbd" files, rather than using the generated stub files that don't support this same mechanism..

thanks

**Comment by pengyangjin** [comment]
i use the AIR 50.2.4.4 ( 11-Feb-2024 ) AIR SDK for MacOS - (50.2.4.4)，which sdk should i can use?
The packaged ipa file experiencing a crash use AIR SDK for MacOS - (50.2.4.4)



---Original---
From: "Andrew ***@***.***&gt;
Date: Thu, Mar 28, 2024 20:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support]/lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue#3143)




  
Can you provide an integrated air adk? You know that switching xcode versions is not easy.
  
Not sure what you mean here? You need to download the AIR SDK, and you need to have Xcode installed with an iPhoneOS SDK. No need to switch between particular Xcode versions? If, by "integrated AIR SDK", you mean an AIR SDK that also includes the iPhoneOS SDK, then no, sorry, that's not permitted by Apple.
 
How are you packaging up your IPA file at the moment? Do you use a terminal window, command-line tools or ant or similar? or an IDE such as Animate or IDEA? I suspect the key thing is to add that -platformsdk per the suggestion from @FliplineStudios because that will make the AIR SDK pick up the official Apple SDK with its "tbd" files, rather than using the generated stub files that don't support this same mechanism..
 
thanks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							20240328_201418_880_Huan_Huan的iPhone.log 							 (572.7KB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=9ec64c370a68016dacb519373b363964d7cb3f373936396444164f430e520f07525d1a0f080f0049570f000514040b000314020701030f51570a5302010413645309050309050b5c3e0b07060d07013b590107687143580a3e71425657d1a3e008695f58575317080e5e230ae20d6722db54fab0ae8f1131e040110ae816eb&key=9ec64c370a68016dacb519373b363964d7cb3f373936396444164f430e520f07525d1a0f080f0049570f000514040b000314020701030f51570a5302010413645309050309050b5c3e0b07060d07013b590107687143580a3e71425657d1a3e008695f58575317080e5e230ae20d6722db54fab0ae8f1131e040110ae816eb&code=a977969d&from=

**Comment by FliplineStudios** [comment]
I just checked your iPhone log (the link was in the email thread, but it never copied to GitHub), but I don't see any crashes listed there...

Do you have a crash log on the device itself?  If it was a crash, you should find a log on the iPhone in Settings > Privacy & Security > Analytics & Improvements > Analytics Data, and there should be a file there with your app's name.

Also have you updated any ANEs you're using?

**Comment by pengyangjin** [comment]
What upgrades does ane file need？Does have more details?




---Original---
From: ***@***.***&gt;
Date: Thu, Mar 28, 2024 21:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [airsdk/Adobe-Runtime-Support]/lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue#3143)




 
I just checked your iPhone log (the link was in the email thread, but it never copied to GitHub), but I don't see any crashes listed there...
 
Do you have a crash log on the device itself?  If it was a crash, you should find a log on the iPhone in Settings &gt; Privacy &amp; Security &gt; Analytics &amp; Improvements &gt; Analytics Data, and there should be a file there with your app's name.
 
Also have you updated any ANEs you're using?

**Comment by FliplineStudios** [comment]
Not sure, I guess it depends on what ANEs you're using.  It's one of the first things I would check if something is crashing though -- or making a test app that doesn't use any ANEs to see if things are still crashing with the AIR SDK I'm trying to use.

**Comment by pengyangjin** [comment]
this is the crash log from iphone.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "airsdk/Adobe-Runtime-Support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [airsdk/Adobe-Runtime-Support] /lib/aot/bin/compile-abc/compile-abc-64: Bad CPU type in executable (Issue #3143)





 
Not sure, I guess it depends on what ANEs you're using.  It's one of the first things I would check if something is crashing though -- or making a test app that doesn't use any ANEs to see if things are still crashing with the AIR SDK I'm trying to use.

**Comment by FliplineStudios** [comment]
> this is the crash log from iphone.

It doesn't look like your attachments are making it through via email, you may want to go to Github directly and add the crash logs there.

**Comment by pengyangjin** [comment]
[ENYTTX-2024-03-28-182053.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/14796079/ENYTTX-2024-03-28-182053.zip)
this is the crash log from iphone.

**Comment by pengyangjin** [comment]
> Not sure, I guess it depends on what ANEs you're using. It's one of the first things I would check if something is crashing though -- or making a test app that doesn't use any ANEs to see if things are still crashing with the AIR SDK I'm trying to use.

[ENYTTX-2024-03-28-182053.zip](https://github.com/airsdk/Adobe-Runtime-Support/files/14796087/ENYTTX-2024-03-28-182053.zip)
this is the crash log from iphone.

**Comment by FliplineStudios** [comment]
From your crash log:
>"vmRegionInfo" : "0xdac11530 is not in any region.  Bytes before following region: 641444560\n      REGION TYPE                 START - END      [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                   100fcc000-102fcc000 [ 32.0M] r-x\/r-x SM=COW  ...TX.app\/ENYTTX",
>
>"exception" : {"codes":"0x0000000000000105, 0x00000000dac11530","rawCodes":[261,3670086960],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"UNKNOWN_0x105 at 0x00000000dac11530"},
> 
>"termination" : {"flags":0,"code":10,"namespace":"SIGNAL","indicator":"Bus error: 10","byProc":"exc handler","byPid":35228},
>  
>"vmregioninfo" : "0xdac11530 is not in any region.  Bytes before following region: 641444560\n      REGION TYPE                 START - END      [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                   100fcc000-102fcc000 [ 32.0M] r-x\/r-x SM=COW  ...TX.app\/ENYTTX",
>
>  "faultingThread" : 0,

Hmmm maybe @ajwfrost would have a better idea of what the SIGBUS error would be, I've never seen one of those happen before...

**Comment by pengyangjin** [comment]
> From your crash log:
> 
> > "vmRegionInfo" : "0xdac11530 is not in any region.  Bytes before following region: 641444560\n      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                   100fcc000-102fcc000 [ 32.0M] r-x/r-x SM=COW  ...TX.app/ENYTTX",
> > "exception" : {"codes":"0x0000000000000105, 0x00000000dac11530","rawCodes":[261,3670086960],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"UNKNOWN_0x105 at 0x00000000dac11530"},
> > "termination" : {"flags":0,"code":10,"namespace":"SIGNAL","indicator":"Bus error: 10","byProc":"exc handler","byPid":35228},
> > "vmregioninfo" : "0xdac11530 is not in any region.  Bytes before following region: 641444560\n      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                   100fcc000-102fcc000 [ 32.0M] r-x/r-x SM=COW  ...TX.app/ENYTTX",
> > "faultingThread" : 0,
> 
> Hmmm maybe @ajwfrost would have a better idea of what the SIGBUS error would be, I've never seen one of those happen before...

I have found out that the problem which was caused by Facebook SDK ANE.

**Comment by ajwfrost** [comment]
> I have found out the problem which was caused by Facebook SDK ANE

I'm glad you found that .. I wouldn't have been able to tell that from the crash log. Sigbus I think shows that something is seriously wrong, it's not something we see often!

thanks
