### ISSUE TITLE
All commands can be preceeded by '-licenseFile (path)adt.lic' or '-licenseDevID DevID' to override the use of the lib/adt.lic file

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3147]
When use osx 50.2.4.4 sdk package ipa file. get an error: 
      [echo] p12->antResource/key/ios/iosyttxen_dev.p12
     [echo] mobileprovision->antResource/key/ios/yttxeniphone_dev.mobileprovision

     [java] Directory  does not exist.
     [java] usage:
     [java]   adt -checkstore SIGNING_OPTIONS
     [java]   adt -certificate -cn <name> ( -ou <org-unit> )? ( -o <org-name> )? ( -c <country> )? ( -validityPeriod <years> )? (2048-RSA | 4096-RSA) <pfx-file> <password>
     [java]   adt -license
     [java]   adt -help
     [java]   adt -migrate SIGNING_OPTIONS ( <air-file-in> | <airn-file-in> ) <output-file>
     [java]   adt -package SIGNING_OPTIONS ( -target air )? <output-package> ( <app-desc> FILE_OPTIONS | <input-package> )
     [java]   adt -package SIGNING_OPTIONS -target airn <output-package> ( <app-desc> FILE-AND-PATH-OPTIONS | <input-package> )
     [java]   adt -package -target ( apk | apk-debug | apk-emulator | apk-captive-runtime ) ( CONNECT_OPTIONS? | LISTEN_OPTIONS? ) ( -airDownloadURL <url> )? ( ARCH_OPTIONS )? SIGNING_OPTIONS <output-package> ( <app-desc> PLATFORM-SDK-OPTION? FILE-AND-PATH-OPTIONS | <input-package> PLATFORM-SDK-OPTION? )
     [java]   adt -package -target ( aab | aab-debug ) ( CONNECT_OPTIONS? | LISTEN_OPTIONS? ) (SIGNING_OPTIONS?) <output-package> ( <app-desc> FILE-AND-PATH-OPTIONS | <input-package> ) PLATFORM-SDK-OPTION
     [java]   adt -package -target ( android-studio | android-studio-debug ) ( CONNECT_OPTIONS? | LISTEN_OPTIONS? ) <output-folder> ( <app-desc> FILE-AND-PATH-OPTIONS | <input-package> ) PLATFORM-SDK-OPTION
     [java]   adt -package -target ( ipa-test | ipa-debug | ipa-app-store | ipa-ad-hoc | ipa-test-interpreter | ipa-debug-interpreter | ipa-test-interpreter-simulator | ipa-debug-interpreter-simulator ) ( CONNECT_OPTIONS? | LISTEN_OPTIONS? ) ( -sampler )? ANE_LINK_OPTIONS? AOT_MODE_OPTIONS? EMBED_BITCODE_OPTIONS? SIGNING_OPTIONS <output-package> ( <app-desc> PLATFORM-SDK-OPTION? FILE-AND-PATH-OPTIONS | <input-package> PLATFORM-SDK-OPTION? )
     [java]   adt -package SIGNING_OPTIONS? -target native SIGNING_OPTIONS? <output-package> ( <app-desc> FILE-AND-PATH-OPTIONS | <input-package> )
     [java]   adt -package SIGNING_OPTIONS? -migrate SIGNING_OPTIONS -target native SIGNING_OPTIONS? <output-package> <app-desc> FILE_OPTIONS PATH-OPTION
     [java]   adt -package SIGNING_OPTIONS? -target bundle SIGNING_OPTIONS? ARCH_OPTIONS? <output-package> ( <app-desc> FILE-AND-PATH-OPTIONS | <input-package> )
     [java]   adt -package SIGNING_OPTIONS? -target ane <output-package> <ext-desc> ANE_OPTIONS
     [java]   adt -prepare <airi-file> <app-desc> FILE_AND_PATH_OPTIONS
     [java]   adt -sign SIGNING_OPTIONS ( -target ( air | airn | ane | bundle ) )? ( <airi-file> | <unsigned-ane-file> | <bundle-folder> ) <output-file>
     [java]   adt -devices          PLATFORM-OPTION PLATFORM-SDK-OPTION? 
     [java]   adt -deviceLog        PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION?
     [java]   adt -installRuntime   PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION? ( -package <apk-file> )?
     [java]   adt -installApp       PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION? -package <apk-file | aab-file | ipa-file>
     [java]   adt -uninstallRuntime PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION?
     [java]   adt -uninstallApp     PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION? -appid <app-id>
     [java]   adt -launchApp        { PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION? ( -debuggerPort port )? -appid <app-id> }
     [java]   adt -runtimeVersion   PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION?
     [java]   adt -appVersion       PLATFORM-OPTION PLATFORM-SDK-OPTION? DEVICE-OPTION? -appid <app-id>
     [java]   adt -version
     [java] 
     [java] SIGNING_OPTIONS      : -storetype <type> ( -keystore <store> )? ( -storepass <pass> )? ( -alias <aliasName> )? ( -keypass <pass> )? ( -providerName <name> )? ( -tsa <url> )? ( -provisioning-profile <profile> )?
     [java] FILE_OPTIONS         : <fileOrDir>* ( ( -C <dir> <fileOrDir>+ ) | ( -e <file> <path> ) )*
     [java] ARCH_OPTIONS         : -arch (armv7 | x86 | x64 | armv8 )
     [java] CONNECT_OPTIONS      : -connect <host>
     [java] LISTEN_OPTIONS       : -listen <port>
     [java] ANE_LINK_OPTIONS     : -hideAneLibSymbols ( yes | no )
     [java] ANE_OPTIONS          : -swc <swc> ( -platform <name> (-platformoptions <file>)? <fileOrDir>* ( -C <dir> <fileOrDir>+ )* )*
     [java] FILE-AND-PATH-OPTIONS: ( PATH-OPTION | FILE-OPTIONS ) FILE-AND-PATH-OPTIONS?
     [java] PATH-OPTION          : ( -extdir <dir> | -resdir <dir> )
     [java] PLATFORM-OPTION      : -platform (android | ios)
     [java] PLATFORM-SDK-OPTION  : -platformsdk <platform-sdk-home-dir>
     [java] DEVICE-OPTION        : -device ( deviceID | ios-simulator )
     [java] AOT_MODE_OPTIONS     : -useLegacyAOT ( yes | no )
     [java] EMBED_BITCODE_OPTIONS: -embedBitcode ( yes | no )
     [java] All commands can be preceeded by '-licenseFile (path)adt.lic' or '-licenseDevID DevID' to override the use of the lib/adt.lic file
     [java]

**Comment by ajwfrost** [comment]
It's complaining that "Directory does not exist".. so there may be something on the command-line which is making it look for a folder but not find it. 

I'm wondering whether this may be another restriction of folders with non-latin characters in them? although I thought osx was a bit more robust in that than Windows... 

Could you double-check your command line to make sure all the files/folders that are passed in do actually exist and are spelled correctly? And also please check in the adt.log file to see if there is more information available there, such as the directory that it's trying to find.

thanks
