### ISSUE TITLE
[Feature Request][macOS] Allow to use `CFBundleDisplayName` with `InfoAdditions`

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3172]
## Feature Description
AIR SDK for macOS should allow to add `CFBundleDisplayName` with `InfoAdditions`.
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledisplayname?language=objc

Right now trying to add to manifest `InfoAdditions` section for macOS:
```
<key>CFBundleDisplayName</key>
    <string>Test App</string>
```
cause packaging error:
`error 105: application.macOS.InfoAdditions contains an invalid value`

Alternatively, AIR SDK could automatically fill `CFBundleDisplayName` the same value as `CFBundleName`.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2857
https://github.com/airsdk/Adobe-Runtime-Support/issues/2083

## Known Workarounds
Manually add `CFBundleDisplayName` to packaged AIR app and re-sign it.

**Comment by ajwfrost** [comment]
Hi

Going with the "automatically fill `CFBundleDisplayName` the same as `CFBundleName`" option for now...
https://airsdk.harman.com/download/50.2.5.1

Do you think there's a situation where it would need to be different?

thanks
