### ISSUE TITLE
`Error: Cannot invoke "macromedia.asc.util.Names.hasNext(int)" because "names" is null`

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#3179]
After a bigger commit to the CI/Jenkins, one of the pipeline modules does no longer build and the following error is thrown in the `Console Output`:

> Error: Cannot invoke "macromedia.asc.util.Names.hasNext(int)" because "names" is null
> Error: 
> [Pipeline] echo
> Error: hudson.AbortException: script returned exit code 1

Locally, everything (all modules/SWCs/SWFs) are build fine with the same source code.

There aren't any other errors or details on this in the log.
The console output before the compiling ends with this error is working fine in other branches so it's not quite clear where the actual error occurs and it does not seem related to the previous output.

I wasn't able to find anything related to that "exotic" error.
@ajwfrost: Could you please share some information and details on this error? 

**EDIT:** The error occurs in a SWC library compilation with `compc`

**Comment by 2jfw** [comment]
Any details on this error?

**Comment by ajwfrost** [comment]
That looks like a Flex compiler issue...
https://github.com/apache/flex-sdk/blob/develop/modules/asc/src/java/macromedia/asc/util/Names.java

Presumably you're using Flex/MXML files, if not it would be worth switching to build using the latest ActionScript compiler. The only other thing I can suggest here is either to reach out to the Apache Flex maintainers, or to build that ASC compiler yourselves and see if you can debug it?

thanks

**Comment by 2jfw** [comment]
Many thanks for the information on this!
Yes, it's a Flex project and MXML is involved.
I may get in Touch with Alex Harui on this issue.

[Changing the name of the branch did actually fix the issue (whereas the revision remained the exactly same!).
We had encountered something similar before and Alex stated that the compc compiler is not 100% thread-safe and it may cause various issues so I would think it's the same issue]
