### ISSUE TITLE
ABB and armv7?

### ISSUE THREAD

**Issue by marcanw** [airsdk/Adobe-Runtime-Support#3210]
I have some users complaining that they can't use my app anymore because the latest release lacks the required armv7 code.
I thought that the App Bundle included multiple architectures. 
Is this not the case? Is there something I can do to include armv7?
Thank you for your help

**Comment by FliplineStudios** [comment]
It _should_ have armv7 included, have you tried unzipping your AAB to check if you see armv7 included (in base/lib/armeabi-v7a)?  I think AIR 50.2.4.3 fixed an issue where Animate wasn't always including them all, in case you're using Animate and/or an earlier SDK.

That said, I've also heard the same thing from some people, saying our newest app isn't available on their armv7 device (packaged as AAB with 50.2.4.4 from command line).  I'm not sure if there are just other requirements that their phones aren't meeting like Android version, or if there's actually a problem there... we sometimes get complaints of armv7 compatibility when someone is trying to run a pirated copy of our games (where they grabbed an APK that was generated for armv8), so I'm never sure whether there's actually a problem or not.  

It's tough to find a pure armv7 device these days to test, I've got a couple Samsung A tablets that run a 32-bit OS and require armv7 (despite having a 64-bit chip), and it seems they're able to install our newest app fine from the Play Store at least...

**Comment by marcanw** [comment]
Thank you,
Indeed, I only had the arm64 in the lib.
I finally found the solution: I had to comment out these two lines in the adt.cfg, and then all the architectures were present:
#DefaultArch=armv8
#OverrideArch=armv8
I thought it wasn't important when using the command line build, but I was wrong...
Thanks again for the help.
