### ISSUE TITLE
[ISSUE] Digest and Encryption not working on IOS

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#3211]
Running on IOS device these codes i'm getting errors:

Encryption.getRandomBytes(128) -> Error #2014: Feature is not available at this time.
Digest.hash(Digest.SHA256, bytesRandomId) -> Error #1508: The value specified for argument algorithm is invalid.,ArgumentError: Error #1508: The value specified for argument algorithm is invalid.

Same code works normally on Android and Windows.

**Comment by ajwfrost** [comment]
Yes, iOS support was not initially included; it's been done now (using Apple libraries) and will be published in 51.0.1 coming shortly..

**Comment by bobaoapae** [comment]
Oh thanks, I previously had searched on docs for anything related for ios limitation but I can't find, maybe I just don't have seen it
