### ISSUE TITLE
Error while building AAB file with Sonoma 14.5

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#3265]
After the macOS has been updated to Sonoma 14.5 I get an error while building an AAB file. 
Is this a known issue and how could this be resolved?

**The error message:**
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarReleaseFileDependencies'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.
BUILD FAILED in 33s

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed: ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:desugarReleaseFileDependencies'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
      > Error while dexing.

BUILD FAILED in 33s

	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)

**Comment by marchbold** [comment]
See the discussion here: https://github.com/airsdk/Adobe-Runtime-Support/issues/3236


Short answer, either: 
- set your minimum version to 24. 
- use the Android Studio Project output to build.
- wait for an update from Harman.

**Comment by apofis1969** [comment]
Thanks, I missed to change to 25 as minimum version. Now the app is running.

**Comment by marchbold** [comment]
Not really a change but a building issue it seems, hopefully we'll be able to support back to 19 again shortly, with an AIR update.
