### ISSUE TITLE
Asset validation failed (90035)  when using transporter

### ISSUE THREAD

**Issue by Menard1965** [airsdk/Adobe-Runtime-Support#3267]
We are using Adobe Animate to deploy APPS in IOS.

SDK: 50.2.5.1
InAPPBilling from District (latest version)

On a new APP we get the error on Transporter:
Asset validation failed (90035)
Certzificate Error maybe you are using wrong certificate:

Certificates are valid and distribution certificates
Also the Prov Files are valid.

Please help: 
Michael

**Comment by marchbold** [comment]
Can you get any more information about what failed validation? 

Which variant of the InAppBilling extension are you using?

**Comment by Menard1965** [comment]
I solved the Problem!
It took me over one Week of testing:

**Comment by marchbold** [comment]
Glad to hear you found the issue!
