### ISSUE TITLE
Error: Apple App Store allows only universal applications. "EfunSDK" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#3289]
The newest version of xcode only supports arm64.But the ane tools  still require the static library. a file needed support arm32 and arm64.The following error occurred during the production of ane.

[java] Error: Apple App Store allows only universal applications. "EfunSDK" is not a universal binary. Please change build settings in Xcode project to "Standard Architecture" to create universal library/framework.
Use the  AIR 51.0.1.2 ( 31-May-2024 ) version of AIR SDK for Windows

**Comment by marchbold** [comment]
Normally if you just set your minimum version to 12 this error is resolved. 

You can still build a static library that supports arm64.
