### ISSUE TITLE
Build ipa-test-interpreter success, but if ipa-test error unexpected failure: Cannot invoke "java.io.File.getAbsolutePath()" because "<parameter1>" is null

### ISSUE THREAD

**Issue by CNHappy21s** [airsdk/Adobe-Runtime-Support#3301]

**Comment by ajwfrost** [comment]
The 'getAbsolutePath()' is a Java method, which is happening within the ADT tool itself. Somehow during the code signing it's failing to get a file that it expects, I assume. The error message isn't the most helpful .. the command lines look okay but of course I have no idea what those variables expand to.. 

Are you able run the AIR SDK Manager with its Troubleshooting tab open, and check what happens there when you run the second command? It should at least display the full command line (please share that here if you can) and also it may provide more details on the error location. All I can tell from that is that it's within the 'CompileTask' which is doing all the compiling/linking of the ActionScript into machine code.

thanks

**Comment by CNHappy21s** [comment]
> The 'getAbsolutePath()' is a Java method, which is happening within the ADT tool itself. Somehow during the code signing it's failing to get a file that it expects, I assume. The error message isn't the most helpful .. the command lines look okay but of course I have no idea what those variables expand to..
> 
> Are you able run the AIR SDK Manager with its Troubleshooting tab open, and check what happens there when you run the second command? It should at least display the full command line (please share that here if you can) and also it may provide more details on the error location. All I can tell from that is that it's within the 'CompileTask' which is doing all the compiling/linking of the ActionScript into machine code.
> 
> thanks

Hello, This is what I see
If I build ipa-test-interpreter, it will succeed in picture 2

<img width="1194" alt="Ảnh màn hình 2024-06-14 lúc 12 21 34" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96587667/42ea9f02-37c2-4aae-89eb-6a825b99cd9a">

<img width="924" alt="Ảnh màn hình 2024-06-14 lúc 12 23 00" src="https://github.com/airsdk/Adobe-Runtime-Support/assets/96587667/d6578a8d-cb6d-4898-b9c3-186f95d127b3">
