### ISSUE TITLE
Build Error, Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by cevansOTBS** [airsdk/Adobe-Runtime-Support#3303]
I'm trying to update an existing Air iOS app I have. It hasn't been updated in over 3 years, so I've had to do a bit of house keeping to get it back up and running.

I'm running on Macbook Pro Apple Silicon M1. I downloaded the latest Air SDK (51.0.1.3). When I try to build with adt on the command line to run it on a simulator, I get the following error:

Undefined symbols for architecture x86_64:
  "_UITextContentTypeBirthdate", referenced from:
      __ZN11CTStageText18SetContentTypeImplEN4MMgc5GCAPI5GCRefIN7avmplus6StringEEE in libRuntimeInterpreter.x86-simulator-air.a(CTStageText.o)
ld: symbol(s) not found for architecture x86_64

The app does have several ANEs from distriqt but I believe those have already been updated to 64 bit. I also removed those extensions from the app.xml and still got the above error. I'm also using this for the application descripter:
<application xmlns="http://ns.adobe.com/air/application/51.0">

And the simulator I'm trying to run is this:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk

I've searched online, but I've run out of things to try that doesn't involve completely disassembling the project. I'm hoping this is just a simple XML or build setting issue. Any help would be appreciated!

**Comment by ajwfrost** [comment]
Hi

That symbol was introduced in the 17.0 SDK .. are you able to update your Xcode / iPhoneSimulator SDK to this version? As long as the build is done on the latest SDK, it should still run on previous versions of iOS (but the 'birth date' category just wouldn't work for StageText content type..)

thanks

**Comment by cevansOTBS** [comment]
Yes I ended up needing to upgrade MacOs Sonoma, so I could get access to the 17.0 SDK. This allowed me to build successfully. Thank you!
