### ISSUE TITLE
[ISSUE] Create ANE using AIR 51

### ISSUE THREAD

**Issue by bobaoapae** [airsdk/Adobe-Runtime-Support#3320]
I have a ANE created and working using AIR 50.2, updating to AIR 51 (`<extension xmlns="http://ns.adobe.com/air/extension/51.0">
`) cause this error:

`platformAndroid.xml(2): error 103: platform.gradle is an unexpected element/attribute`

plataformAndroid content:
```
<platform xmlns="http://ns.adobe.com/air/extension/51.0">
	<gradle>
		<repositories>
			<repository>google()</repository>
			<repository>mavenCentral()</repository>
		</repositories>
		<dependencies>
			<dependency>implementation "io.sentry:sentry-android:6.34.0"</dependency>
			<dependency>implementation "com.google.android.play:asset-delivery:2.2.2"</dependency>
			<dependency>implementation "com.google.android.play:app-update:2.1.0"</dependency>
			<dependency>implementation "com.android.billingclient:billing:6.2.1"</dependency>
			<dependency>implementation "androidx.appcompat:appcompat:1.6.1"</dependency>
			<dependency>implementation "com.google.android.material:material:1.12.0"</dependency>
		</dependencies>
	</gradle>
</platform>
```

**Comment by ajwfrost** [comment]
Internally referenced as "AIR-7136" - this was an incorrect derivation in the validator for Android platform extension files.. we have a fix which will be in our next release.

thanks

**Comment by bobaoapae** [comment]
Can you send private via email build with that fix? Or create a pre release version? I'm building a ane for websocket to use on Android until ssl websocket for Android have been fixed

**Comment by ajwfrost** [comment]
Fix version of ADL: https://transfer.harman.com/message/jmoqzjq1uqm0noSDao5QZJ

The ANE with Android Websocket is kind of what we were doing..! Just need to get that binary data thing working I guess.

**Comment by bobaoapae** [comment]
> Fix version of ADL: https://transfer.harman.com/message/jmoqzjq1uqm0noSDao5QZJ
> 
> The ANE with Android Websocket is kind of what we were doing..! Just need to get that binary data thing working I guess.

thanks, yeah i have a urgent case, so i'm building my own using other android library to try if that will work
