### ISSUE TITLE
[AIR 51.0.1.4] Unexpected failure parsing app descriptor settings.

### ISSUE THREAD

**Issue by wmtj** [airsdk/Adobe-Runtime-Support#3339]
Hi,@ajwfrost  It works fine with previous AIRSDK versions, but [AIR 51.0.1.4] does not work. How to fix it ?

Unexpected failure parsing app descriptor settings (ignoring): xxx-app.xml(316): error 105: application.android.manifestAdditions contains an invalid value
Target requested was apk-captive-runtime, but not using legacy APK so building via Android Studio
Creating device SDK handler - location passed in = F:\Android\AndroidSDK
..java.lang.Thread.getStackTrace(Unknown Source)
..com.adobe.air.DebugFile.printStack(DebugFile.java)
..com.adobe.air.ADTException.<init>(ADTException.java)
..com.adobe.air.validator.DescriptorValidationException.<init>(DescriptorValidationException.java)
..com.adobe.air.Descriptor$2.message(Descriptor.java)
..com.adobe.air.validator.DescriptorValidator.dispatchError(DescriptorValidator.java)
..com.adobe.air.validator.DescriptorValidator.endElement(DescriptorValidator.java)
..com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
..com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
..com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
..com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
..com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
..com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
..com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
..com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
..com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
..com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
..com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
..com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
..javax.xml.parsers.SAXParser.parse(Unknown Source)
..com.adobe.air.Descriptor.validateXML(Descriptor.java)
..com.adobe.air.Descriptor.<init>(Descriptor.java)
..com.adobe.air.ApplicationDescriptor.<init>(ApplicationDescriptor.java)
..com.adobe.air.ApplicationPackager.validateApplicationDescriptor(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.validateApplicationDescriptor(AABPackager.java)
..com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
..com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
..com.adobe.air.ADT.parseArgsAndGo(ADT.java)
..com.adobe.air.ADT.run(ADT.java)
..com.adobe.air.ADT.main(ADT.java)
Stack trace:
Description validation error: D:\xxx\xxx-app.xml(316): error 105: application.android.manifestAdditions contains an invalid value

**Comment by ajwfrost** [comment]
Hmm.. this isn't an area we should have changed! Are you able to share your manifestAdditions section and we can try reproducing it here? (feel free to email it to our Adobe Support inbox if you don't want to post publicly)

thanks

**Comment by wmtj** [comment]
> Hmm.. this isn't an area we shouldn't have changed! Are you able to share your manifestAdditions section and we can try reproducing it here? (feel free to email it to our Adobe Support inbox if you don't want to post publicly)
> 
> (Editing - "should" -> "shouldn't"..!)
> 
> thanks

I have found the cause of the problem and it is my fault, not an AIRSDK bug. Very sorry!

**Comment by wmtj** [comment]
I have found the cause of the problem and it is my fault, not an AIRSDK bug. Very sorry!

**Comment by ajwfrost** [comment]
> not an AIRSDK bug

Phew! Thanks for confirming :-)
