### ISSUE TITLE
What do I need to do to set the targetSdkVersion to 34?

### ISSUE THREAD

**Issue by ulsan1635** [airsdk/Adobe-Runtime-Support#3342]
I'm using a translator to ask this question because my English is not very good.

I received the following message from the Google Console indicating a violation of Google policies: "Your app must target Android 14 (API level 34) or higher."

Typically, to comply with Google policies when we need to raise the targetSdkVersion, we check the Android Target SDK Version in the "2.2.3 Build Environment" section of the AIR SDK Release Notes and upgrade the AIR SDK accordingly.

However, the release notes for version 51.0.1.4, distributed on July 8, list the Android Target SDK Version as 33. Therefore, it seems that additional actions might be necessary besides upgrading the AIR SDK to raise the targetSdkVersion to 34.

Below is the current Android build environment:

AIR SDK: 50.2.3.6
Platform: Android
Android Studio / build-tools: 31.0.0
JDK: 1.8.0_251
Additionally, we are using several distriqt ANEs in the app, which were upgraded to the latest version in mid-March.

Is there anything else required besides changing the targetSdkVersion to 34 in the manifest?

**Comment by ajwfrost** [comment]
See discussion thread:
https://github.com/airsdk/Adobe-Runtime-Support/discussions/3337

thanks

**Comment by ulsan1635** [comment]
Thank you very much.

I will read it carefully.
