### ISSUE TITLE
Error on debug on device since 51.0.1.4

### ISSUE THREAD

**Issue by Policy56** [airsdk/Adobe-Runtime-Support#3343]
**Description:**
I encountered an issue after upgrading to Adobe AIR 50.1.0.4. My application throws a _**NoClassDefFoundError**_ for _**org.bouncycastle.jce.provider.BouncyCastleProvider**_. This error did not occur in the previous version I was using, AIR 50.2.3.8.

**Steps to Reproduce:**

Upgrade to Adobe AIR 51.0.1.4.
Compile the application to a device attached.
Attempt to run the application on a Google Pixel tablet.

**Expected Behavior:**
The application should compile and run without throwing any **_NoClassDefFoundError_**.

**Actual Behavior:**
The following error is thrown during compilation:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at com.adobe.air.apk.AABPackager.setArch(AABPackager.java)
	at com.adobe.air.ADT.parseArchOptions(ADT.java)
	at com.adobe.air.ADT.parsePackage(ADT.java)
	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
	at com.adobe.air.ADT.run(ADT.java)
	at com.adobe.air.ADT.main(ADT.java)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more
```

**Environment:**

- Adobe AIR Version: 51.0.1.4.
- Previous Working Version: 50.2.3.8
- Device: Google Pixel tablet
- OS: Android

**Additional Context:**
The issue appears to be related to the inclusion or exclusion of the BouncyCastle library in the new version. No changes were made to the codebase other than the upgrade of Adobe AIR. Any assistance in resolving this issue would be greatly appreciated.

**Comment by ajwfrost** [comment]
Hi

Can you please check your AIR SDK location and confirm you have files in a folder under `lib\bouncycastle`?
Plus, what version of Java do you have by default?

(I'm not sure what operating system you're running this on, but hopefully just calling "java -version" in a command line or terminal window would give the details..)

The bouncy castle libraries should be valid for Java 1.8 or later....

thanks

**Comment by Policy56** [comment]
Hi, 

You're right ! The lib\bouncycastle was not in my AIR SDK ...

I use this script to setup apache flex with the latest version of AIR SDK, but i think it doesn't work yet
https://github.com/actions-marketplace-validations/joshtynjala_setup-apache-flex-action/blob/master/harman-installer.xml

**Comment by ajwfrost** [comment]
Just copying in @joshtynjala - I had a quick look at that ant file but could see how to add it copying in this dependency (as well as `lib/adt.jar`, we need `lib/bouncycastle/*.jar` to come from the AIR SDK).

thanks

**Comment by joshtynjala** [comment]
So, my harman-installer.xml script is a wrapper around the the Flex SDK's official installer.xml script. harman-installer.xml takes the downloaded AIR SDK bundles from HARMAN and converts them to the zip/dmg/tbz2 file formats expected by installer.xml, if needed. And that's basically it.

The file copying happens inside installer.xml, and it seems to copy specific files and directories only. It doesn't know about lib/bouncycastle/*.jar, so it doesn't copy those files.

https://github.com/apache/flex-sdk/blob/apache-flex-sdk-4.16.1/installer.xml#L384-L408
https://github.com/apache/flex-sdk/blob/apache-flex-sdk-4.16.1/installer.xml#L474-L562

Ideally, the Flex SDK installer.xml would be updated to support copying everything in lib/, but I'd guess that it's unlikely that we'll have another release of the Flex SDK in the future. Regardless, that wouldn't help anyone who wants to continue using existing releases of the Flex SDK with AIR from HARMAN.

So the best approach is probably by modifying my harman-installer.xml. In the -prepare target, it unzips the SDK and creates a copy of playerglobal.swc. This seems like it would be the ideal place to copy the lib/bouncycastle directory into ${flexsdk}/lib/bouncycastle too.

https://github.com/joshtynjala/setup-apache-flex-action/blob/v2.1.0/harman-installer.xml#L144

I can make this change, but it'll need to wait until I have some time available.

**Comment by joshtynjala** [comment]
@Policy56 @ajwfrost I have updated the harman-installer.xml script to copy the full contents of lib/ (including lib/bouncycastle/) into the Flex SDK.

https://github.com/joshtynjala/setup-apache-flex-action/blob/master/harman-installer.xml

**Comment by ajwfrost** [comment]
That's awesome, thanks @joshtynjala!

**Comment by Policy56** [comment]
Nice work @ajwfrost , thank's ! :)
