### ISSUE TITLE
[Docs] `?? nullish coalescing` not in the list

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3347]
## Problem Description
`?? nullish coalescing` operator not in the list at the top of the page.
But it has description in page below.

## Steps to Reproduce
https://airsdk.dev/reference/actionscript/3.0/operators.html

**Actual Result:**
?? nullish coalescing` not in the list.

**Expected Result:**
?? nullish coalescing` in the list.

**Comment by marchbold** [comment]
Isn't it listed under the logical section?

**Comment by itlancer** [comment]
![image](https://github.com/airsdk/Adobe-Runtime-Support/assets/10899066/f9d9b7aa-71b1-425a-835c-166466488cb7)
In table of contents.

**Comment by marchbold** [comment]
Yeah it's listed under the logical section which I think is correct 

![Screenshot_20240710-212557.png](https://github.com/airsdk/Adobe-Runtime-Support/assets/442356/96e7f716-08dd-41bd-b66e-7902e4c17739)

**Comment by marchbold** [comment]
Not at all!
