### ISSUE TITLE
Slow Network Requests?

### ISSUE THREAD

**Issue by barisyild** [airsdk/Adobe-Runtime-Support#335]
I'm trying load game on Adobe Air and Puffin. (500 External SWF)

Puffin loading faster than Adobe Air on Android, Puffin probably it can throw more requests at the same time.

Update: probably max http connection limit is very small on Adobe Air Android.

**Comment by zwetan** [comment]
what is Puffin?

**Comment by barisyild** [comment]
> what is Puffin?

Puffin is Flash Player supported Web Browser for Android && iOS.

[Video](https://www.youtube.com/watch?v=WALxKHTN_xs)

**Comment by zwetan** [comment]
> Puffin is Flash Player supported Web Browser for Android && iOS

No, not for iOS

anyway, loading 500 external SWF, in Adobe AIR or a browser
would require you to queue those requests etc.

now about being "slow", did you have some code that test and prove that the slowness is happening in AIR ?

it could be anything, your network, your ISP, the server you're trying to reach, etc.

**Comment by ajwfrost** [comment]
FYI I think there’s a limit to how many http requests can be opened at any one time, but I thought that was the same for FP and AIR.

If you’re finding AIR particularly slow then please let us know and also it’s worth tracking the status of the various request objects so that you can see how long the network side is taking, how many are opened in parallel, etc

**Comment by barisyild** [comment]
> FYI I think there’s a limit to how many http requests can be opened at any one time, but I thought that was the same for FP and AIR.
> 
> If you’re finding AIR particularly slow then please let us know and also it’s worth tracking the status of the various request objects so that you can see how long the network side is taking, how many are opened in parallel, etc

The requests are not queued on the PC version of Adobe AIR, but on the Android version they are queued, which leads to late loading of external SWFs one by one.

Example:

There are 50 SWFs in order and there is a SWF we need to load first (prioritize).
When adding a new SWF to queue it waits for other requests on the mobile device to load, while the new SWF loads on the computer without waiting.

**Comment by zwetan** [comment]
are you programming the queue or are you expecting AIR to do it for you ?

sample code to illustrate the problem always help

**Comment by barisyild** [comment]
> are you programming the queue or are you expecting AIR to do it for you ?
> 
> sample code to illustrate the problem always help

Yes we had to program the queue because there are high pritority items to load first.
but this cause one by one loading which is in AIR 7 SWFs max at a time.
Normally, there is no need for a queue because the desktop version loads all of them at the same time.
If you try to load them all on android at the same time, they only load a few at a time.

**Comment by zwetan** [comment]
> Normally, there is no need for a queue because the desktop version loads all of them at the same time.

You can not expect the same on mobile, everything is more limited in term of resources etc.
