### ISSUE TITLE
[AIR 51.0.1.4][iOS 17] Application crash on start with Scout

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3357]
## Problem Description
Application built with AIR 51.0.1.4 crash on start with Scout using iOS 17 devices.

Tested with AIR 51.0.1.4 with different AIR applications with different iPhones and iPads.
Same issue in all cases with iOS 17.
There is no such issues with other iOS versions. With iOS 16 and iOS 12 all fine.
There is no such issues with AIR 50.2.4.4 and below.
There is no such issues with other platforms.
There is no such issues if application launches without Scout.

Related issue: https://github.com/airsdk/Adobe-Scout/issues/5

## Steps to Reproduce
1) Start Scout with iOS device.
2) Launch any application built with AIR 51.0.1.4 for iOS .

**Actual Result:**
Application crash.

**Expected Result:**
Application start without crash and Scout session started.

## Known Workarounds
none

**Comment by ajwfrost** [comment]
Curious that this only happens on iOS 17 .. but it looks like this issue was introduced when adding support for the NativeWindow activations, should be fixed in the forthcoming 51.1 release..
thanks

**Comment by itlancer** [comment]
Fixed. Tested with latest AIR 51.1.1.2.
Thanks!
But still have related issue: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1913
And new one: https://github.com/airsdk/Adobe-Runtime-Support/issues/3394
