### ISSUE TITLE
[AIR 51][Android] `EncryptedLocalStore.reset()` cause internal error after restart

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3370]
## Problem Description
`EncryptedLocalStore.reset()` cause `Error: EncryptedLocalStore internal error` after Android application restart using AIR 51.

Tested with latest AIR 51.0.1.4 and 51.0.1.5 with multiple different Android devices, different OS versions, architectures and with different applications.
Same issue in all cases.
There is no such issue with other platforms.
There is no such issue using AIR 50.2.5.1, AIR 50.2.4.4 or below.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/2253
https://github.com/airsdk/Adobe-Runtime-Support/issues/229

## Steps to Reproduce
1) Launch application with code below with any Android device. It will write some data to `EncryptedLocalStore`, reset it and write again.
2) Close application and launch it again.

Application example with sources attached.
[air51_android_encrypted_local_store_reset_bug.zip](https://github.com/user-attachments/files/16332085/air51_android_encrypted_local_store_reset_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.data.EncryptedLocalStore;
	import flash.utils.ByteArray;
	
	public class AIR51AndroidEncryptedLocalStoreResetBug extends Sprite {
		
		public function AIR51AndroidEncryptedLocalStoreResetBug() {
			EncryptedLocalStore.setItem('test', new ByteArray());//This line on second launch cause Error: EncryptedLocalStore internal error
			EncryptedLocalStore.reset();
			EncryptedLocalStore.setItem('test', new ByteArray());
		}
	}
}
```

**Actual Result:**
`Error: EncryptedLocalStore internal error`
And there is no way to restore `EncryptedLocalStore` work anymore. Just delete application data in OS settings.

**Expected Result:**
`EncryptedLocalStore` works without errors.

## Known Workarounds
none
*Use AIR 50.2.5.1 or below

**Comment by itlancer** [comment]
@ajwfrost 
Issue still exists with AIR 51.1.1.2 with:
```
<encryptedLocalStorage> 
	<fallbackMode>once</fallbackMode> 
	<storageMode>file</storageMode> 
</encryptedLocalStorage>
```
in manifest.
Any `fallbackMode` with `<storageMode>file</storageMode>` cause `Error: EncryptedLocalStore internal error` in case above.

May be related to ELS issue: https://github.com/airsdk/Adobe-Runtime-Support/issues/3391#issuecomment-2265492219

**Comment by Devin-Licastro** [comment]
Sorry to hijack this a bit. Where can I read about these new <encryptedLocalStorage> tags? In the release notes, I can see that this feature was added but I haven't been able to find any documentation showing what options exist and what they do.

**Comment by itlancer** [comment]
@Devin-Licastro, take a look at https://airsdk.dev/docs/building/application-descriptor-files/elements/encryptedLocalStorage

**Comment by Devin-Licastro** [comment]
> @Devin-Licastro, take a look at https://airsdk.dev/docs/building/application-descriptor-files/elements/encryptedLocalStorage

Thanks a lot!

**Comment by lwmirkk** [comment]
Same problem here, but for me the problem happen most of time on Amazon Fire devices...
I was using 50.2.4.1 without any problems, I updated to 51.1.1.1 and had this problem.

**Comment by itlancer** [comment]
Fixed. Tested with latest AIR 51.1.1.5.
Thanks!
