### ISSUE TITLE
object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by orcuncun** [airsdk/Adobe-Runtime-Support#3392]
I get this error right below the swf files. "Object reference not assigned to an instance of an object."
SDK version I'm using: AIRSDK_51.1.1
I'm using Flash develop.

**Comment by orcuncun** [comment]
![Capture](https://github.com/user-attachments/assets/fb5d37dd-3ddd-4fdc-98ab-1ee3d82ca9ad)

**Comment by ajwfrost** [comment]
That looks like an issue from 51.0 when we added float support. FlashDevelop is trying to parse the ActionScript Byte Code within the SWF file to show you some of the details e.g. class names that are included.

In order for FlashDevelop to do that with the latest ABC format, they would need to make a change on their end.

Or if you don't use/want the float support, with 51.1 you can add a new compiler option:
Project -> Properties -> Compiler Options -> Additional Compiler Options
Edit the string array and add a line: `-compiler.float=false`

thanks
