### ISSUE TITLE
Debugging connection does not work when using SDK 51.1.1.2

### ISSUE THREAD

**Issue by koreaflash** [airsdk/Adobe-Runtime-Support#3402]
OS: Windows 10
IDE: Flashbuilder 4.7
DEVICE: SM-X200(Android 14)

When using 51.1.1.1, debugging connection works normally,
but when using 51.1.1.2, debugging connection does not work.

The Air app and the app for debugging are installed normally, but the debugging connection does not work.

**Comment by crooksy88** [comment]
I'm getting the same issue with Animate on MacOS. 

OS: MacOS 14.4.1
IDE: Animate 24.0.4
DEVICE Samsung S8+

**Comment by gosgame** [comment]
Same on MacOS

**Comment by nygas** [comment]
Same here.
OS: Windows 10
IDE: FlashDevelop
OnePlus 9pro Android 14

51.1.1.1 - works fine.

**Comment by ajwfrost** [comment]
Reproduced here -> thanks for the details. Will get a fix into a release asap..

**Comment by idanasher** [comment]
Same here

**Comment by koreaflash** [comment]
Fixed in version 51.1.1.3.

**Comment by koreaflash** [comment]
Fixed in version 51.1.1.3.
