### ISSUE TITLE
[AIR 51.1] `EncryptedLocalStore.getItem()` with `never` mode with no ELS files cause internal error

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3403]
## Problem Description
`EncryptedLocalStore.getItem()` with `never` mode with no ELS files cause internal error using AIR 51.1.

Tested with latest AIR 51.1.1.2 with multiple different Windows and macOS devices, different OS versions, architectures and with different applications.
Same issue in all cases.
There is no such issue using AIR 51.0 or below.
There is no such issue if some ELS files exists for application.
Didn't test it with Android/iOS.

Related issues:
https://github.com/airsdk/Adobe-Runtime-Support/issues/3391#issuecomment-2265492219
https://github.com/airsdk/Adobe-Runtime-Support/issues/3370
https://github.com/airsdk/Adobe-Runtime-Support/issues/2253
https://github.com/airsdk/Adobe-Runtime-Support/issues/229

## Steps to Reproduce
Launch application with code below with any Windows or macOS device where is no ELS files for this application.
Or you can delete all related ELS files before launch.
In application manifest you should use:
```
<encryptedLocalStorage>
	<fallbackMode>never</fallbackMode>
	<storageMode>file</storageMode>
</encryptedLocalStorage>
```

Application example with sources attached.
[air51_encrypted_local_store_getitem_never_bug.zip](https://github.com/user-attachments/files/16573686/air51_encrypted_local_store_getitem_never_bug.zip)

```
package {
	import flash.display.Sprite;
	import flash.data.EncryptedLocalStore;
	
	public class AIR51EncryptedLocalStoreGetItemNeverBug extends Sprite {
		
		public function AIR51EncryptedLocalStoreGetItemNeverBug() {
			trace(EncryptedLocalStore.getItem('test'));//This line with no ELS files cause Error: EncryptedLocalStore internal error
		}
	}
}
```

**Actual Result:**
Exception:
```
Error: EncryptedLocalStore internal error
 at flash.data::EncryptedLocalStore$/processErrorCode()
 at flash.data::EncryptedLocalStore$/getItem()
```

**Expected Result:**
`EncryptedLocalStore` works without errors.

## Known Workarounds
none
*Use AIR 51.0.1.4 or below or don't use `never` mode for ELS.

**Comment by itlancer** [comment]
The same issue with Linux.

**Comment by ajwfrost** [comment]
This may be the root of a number of these problems ... when we can't open the new store, we delegate it to the old mechanism... but the error handling for that (given we don't have the old mechanism, with 'never') wasn't updated to cope with the fact you may not have wanted the old mechanism.

Will get a fix out asap...

**Comment by itlancer** [comment]
@ajwfrost 
With AIR 51.1.1.3 there is no more errors  with `never` mode.
But `EncryptedLocalStore.setItem()` doesn't work anymore.
If you update from AIR 50.2.0.4 to AIR 51.1.1.3 and call `EncryptedLocalStore.setItem()` - no new `.dat` file will be created. Moreover, your ELS data will be lost after application restart.
The same result if you run application with AIR 51.1.1.3 (without migration from AIR 50 or below).
`encryptedLocalStorage` settings in manifest doesn't make sense.
Tested without
and with
```
<encryptedLocalStorage>
	<fallbackMode>once</fallbackMode>
	<storageMode>file</storageMode>
</encryptedLocalStorage>
```
and with
```
<encryptedLocalStorage>
	<fallbackMode>never</fallbackMode>
	<storageMode>file</storageMode>
</encryptedLocalStorage>
```
The same issue in all cases.
Tested with Windows and macOS platforms.

Only case which works - when you try to update from AIR 51 to AIR 51.1.1.3. In this case `.dat` file will be properly moved to `app-storage` directory.

Here sample to reproduce issue.
```
package {
	import flash.display.Sprite;
	import flash.data.EncryptedLocalStore;
	import flash.utils.ByteArray;
	
	public class AIR51EncryptedLocalStoreGetItemNeverBug extends Sprite {
		
		public function AIR51EncryptedLocalStoreGetItemNeverBug() {
			trace(EncryptedLocalStore.getItem('test'));
			var bytes:ByteArray = new ByteArray();
			bytes.writeUTFBytes("test");
			EncryptedLocalStore.setItem('test', bytes);
		}
	}
}
```
Launch it firstly with AIR 50 or with AIR 51.1.1.3 and restart application again with AIR 51.1.1.3.

Actual result: trace `null`
Expected result: trace `test`

May be workaround:
Call `EncryptedLocalStore.reset()`. After that seems `EncryptedLocalStore.setItem()` could work sometimes.

**Comment by itlancer** [comment]
Fixed. Tested with latest AIR 51.1.1.5.
Thanks!
