### ISSUE TITLE
Cannot load compile-abc-64

### ISSUE THREAD

**Issue by yoquese1425** [airsdk/Adobe-Runtime-Support#3418]
I'm working on MacBookPro, High Sierra 10.13.6, on Animate. I have the last Air updated, 51.1.1.3. Also working with 2 distriqt ANE.
Packaging for Android works perfect and already working fine. When exporting for ios, I have this message:

cannot load 'compile-abc-64' (load command 0x80000034 is unknown)
/var/folders/7d/_nwv_52x65x9mgd393fnkd280000gn/T/cmd6105509880147868802.tmp: line 2: 78230 Abort trap: 6           "/Applications/Adobe Animate CC 2017/AIR51.1.1.3/lib/aot/bin/compile-abc/compile-abc-64" "-mtriple=arm64-apple-ios" "-filetype=obj" "-sdk" "/Applications/Adobe Animate CC 2017/AIR51.1.1.3/lib/aot/lib/avmglue.abc" "-fields" "/Applications/Adobe Animate CC 2017/AIR51.1.1.3/lib/aot/lib/air-fields.arm64-air.txt" "-O3" "-ane-symbol=CoreExtInitializer" "-ane-symbol=CoreExtFinalizer" "-ane-symbol=InAppBillingExtInitializer" "-ane-symbol=InAppBillingExtFinalizer" "-abc-file-list=/var/folders/7d/_nwv_52x65x9mgd393fnkd280000gn/T/213a11e5-547c-425e-aa74-1c282f2c44bd/ABCFilesList.txt"

Any idea???

**Comment by ajwfrost** [comment]
It looks like the compile-abc tools are built with a minimum SDK version of 10.15 ... although I thought we should be targeting 10.13. Will check that ...

**Comment by ajwfrost** [comment]
Hi

Are you able to try downloading the attached version (for any 51.x release of AIR SDK) and put this into lib/aot/bin/compile-abc/ and see if it then works?
Or actually, just save this to the downloads folder and try running it from a terminal window, "~/Downloads/compile-abc-64" to see if it runs (and complains about a missing triple...)?
https://transfer.harman.com/message/bqzvaMaLH8FTkUxbiQehov

thanks

**Comment by yoquese1425** [comment]
Thanks for your answer!

Terminal Answer:
-bash: /Users/Josisa/Downloads/compile-abc-64: Permission denied

Error on Animate:
/var/folders/7d/_nwv_52x65x9mgd393fnkd280000gn/T/cmd264018240440420559.tmp: line 2: /Applications/Adobe Animate CC 2017/AIR51.1.1.3/lib/aot/bin/compile-abc/compile-abc-64: Permission denied

Also when I copy the file in the folder, does not look like a exec file, just look like an editable text file, don't know why.

<img width="1280" alt="Captura de pantalla 2024-08-23 a las 16 56 48" src="https://github.com/user-attachments/assets/0194ea21-3e97-4651-bd4e-d23d78b5f81d">

**Comment by ajwfrost** [comment]
Ah .. so if you go into a terminal window and `cd ~/Downloads`, can you then check:
```
file compile-abc-64
ls -la compile-abc-64
```

The first one will tell if it is the right file:
```
compile-abc-64: Mach-O 64-bit executable x86_64
```
And if that works, the second one will help us understand what's wrong:
```
-rwxr-xr-x  1 username  groupname  26331120 date time compile-abc-64
```

If that line doesn't have the 'x' bits at the start, then:
```
chmod a+x compile-abc-64
```
and then try it.

Or else if there is an `@` sign in that line, try
```
xattr-d com.apple.quarantine compile-abc-64
```
although I didn't think this kind of thing was present on macOS 10.13.... so I'm hoping it's just that 'x' executable attribute that's missing...

thanks

**Comment by yoquese1425** [comment]
Yes, that made it work !!!! You are a genius !!
So that problem was because I have an old macOs system?

But now I have a new error on Animate... looks like it made ll the packaging, but right at the end says 
"ld: unknown option: -platform_version""

I will try to figure out what that minds

Thanks !!

**Comment by ajwfrost** [comment]
Great! Glad that worked .. yes it is an older OS version, but it's within the versions that we are able to support (mostly just dependent upon the latest Xcode, so each year it seems the 'lowest supported OS' goes up by a version..).

I'll get that put into the next SDK release.

The unknown `-platform_version` thing though .. this is because Apple changed the arguments they would accept in the Linker: older linkers aren't able to accept this newer argument, but sadly they also removed the previous argument (`-macOS_min_version`) so that the newer linker versions are not backwards compatible.

I think the only option for this is to copy in an older version of ADT to the newer SDK. But it actually should be possible for us to detect the versions and adapt - or at a minimum, to take a configuration setting so that we know which set of arguments are accepted. We'll have to have a play with the different linkers that are available... are you able to let us know what you get if you just run `ld -v` in a terminal window? I see:
```
% ld -v 
@(#)PROGRAM:ld PROJECT:ld-1053.12
BUILD 10:14:46 Mar 29 2024
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.3.2.2)
```

I think if we could test this and parse the first line, we may be able to check the arguments that we should then use...

**Comment by yoquese1425** [comment]
Great, thanks !!

This is what I get for that comand:

@(#)PROGRAM:ld  PROJECT:ld64-409.12
BUILD 17:47:51 Sep 25 2018
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em arm64e arm64_32
LTO support using: LLVM version 10.0.0, (clang-1000.11.45.5) (static support for 21, runtime is 21)
TAPI support using: Apple TAPI version 10.0.0 (tapi-1000.11.8.2)

**Comment by yoquese1425** [comment]
Hi! Any news about this? Thanks!

**Comment by yoquese1425** [comment]
Sorry, but that ADT will be released with a new AIR SDK version?? Or I should find it samewhere else?

**Comment by ajwfrost** [comment]
Sorry - had a few problems with this one, but we've just issued it in 51.1.1.4...

**Comment by yoquese1425** [comment]
Great, this problem was solved !!
