### ISSUE TITLE
Clear instructions on how to clear build cache

### ISSUE THREAD

**Issue by perholmes** [airsdk/Adobe-Runtime-Support#3427]
I've just spent literally an entire day changing JDK versions, and nothing had anything to do with anything. It was something that ADT is leaving behind in <username>/AppData/Local/Temp.

It would really be nice if this was clearly explained, because looking through the many issues, they're repeatedly about getting the right combination of JDK, Gradle, AIR SDK and Android SDK. People are banging heads against walls, and nothing works.

What clued me in was that a simple `DebugOut=true` in adt.cfg suddenly worked.

Deleting everything in /Temp is a huge hammer. It would be great to know what ADT is actually persisting there, and this should be described everywhere that JDK/SDK configuration is discussed, because nothing you do matters until the cache is cleared.

**Comment by ajwfrost** [comment]
We shouldn't be leaving anything behind in the temp folder! But I will double-check on this again. Sometimes there can be error conditions that mean code paths get skipped and some clean-up may not happen.

The gradle process we kick off is run with "no daemon" arguments which should mean that each time you run it, it's independent of everything else.

If you've got anything showing up in the adt.log output that you think shows that there is data still being left behind in temp, it would be helpful if you're able to share those details, anonymised somehow perhaps?

thanks

**Comment by perholmes** [comment]
It was only because another user in this issue tracker had a sense that there was some cache somewhere tripping things up. I deleted everything in Temp, and this was the first success I'd had all day. All my packaging errors went away, whether running with 17 or 21.

This was triggered by doing a packaging with DebugOut=true in adt.cfg, and getting my first working packaging of the day. I surmised that this caused a mode that didn't have access to the previous cache. I know nothing about how this works under the hood. I can only say that after a full day of trying many versions of the AIR SDK and JDK (all with identical errors), I could suddenly package without errors.

This is a 12 year old project that moved from Flash Builder to IntelliJ, where I've been doing steady releases. But it's been a small year since the last update, and I'm on new gear. My detailed instructions for setting up the environment aren't working, so I'm doing the environment from scratch, and struggling quite a lot.

**Comment by ajwfrost** [comment]
Definitely something curious happening then. We can check with and without that debug line in case this does make a difference somehow. Under the hood, that literally just determines whether we output log information to a file (or to the AIR SDK Manager if it's open), vs just not printing out the strings. But there should never be any functional differences whether you have DebugOut on or off...

We tend to always have it turned on, so will turn it off and try to reproduce things!

The other setting that could be helpful here is the `KeepAndroidStudioOutput` line, that you can set to "true" in order for it to not use the "temp" folder, but instead to generate everything within a subfolder of your build area called "AndroidStudioProject". When you rebuild, it wipes and recreates the folder, but when you've finished, it stays there - it's a folder you could then open in Android Studio to do any troubleshooting from.

thanks

**Comment by perholmes** [comment]
I didn't mean the DebugOut thing as something important, only that it's what triggered it. Often, a debug build uses a different cache in different folders, and that's when I connected it with the other user's comments about some hidden cache.

Clearing Temp got me unstuck earlier today, but since then, I've been unable to get back to the broken state, so I can't reproduce it. My speculation was that one of the underlying tools, e.g. IntelliJ or Android Studio's JDK might be caching something without telling you. But at this point, it's anecdotal, and perhaps should only be revisited if it comes up again for someone else.

Thank you guys for being on top of the whole AIR SDK. We subscribe because we have still very popular app. We were biting nails when Adobe handed it off to Harman, but we've been continuously delighted to see how you're maintaining and adding to the platform. Kudos.
