### ISSUE TITLE
cacheAsBitmap and black background problem

### ISSUE THREAD

**Issue by JuanCaiza** [airsdk/Adobe-Runtime-Support#3434]
## Problem Description
In our game, there were complaints about the background being black in some places on Android devices. Today, after detailed investigations and experiments, I realized that the problem is to enable cacheAsBitmap. There is no problem when cacheAsBitmap is disabled (except extreme slowness.). But from a performance point of view it makes much more sense to enable cacheAsBitmap.

* Which AIR SDK did you use? **51.1.1.3**
* Describe the affected environment: **Android** 
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
**Yes, I prepared 2 separate swf files and tried to turn them into apk files.**

## Steps to Reproduce
**You can use the files I provided.**
https://www.mediafire.com/file/6hh3k65dcd488m7/dene.apk/file
https://www.mediafire.com/file/5mo9msumn70w4a2/deneFalse.apk/file

Or you can keep a large image file in the background and try the following code.
```
bg.cacheAsBitmap = true;

var keyPressed:Object = {};

stage.addEventListener(KeyboardEvent.KEY_DOWN, onKeyDown);
stage.addEventListener(KeyboardEvent.KEY_UP, onKeyUp);
stage.addEventListener(Event.ENTER_FRAME, onEnterFrame);

function onKeyDown(event:KeyboardEvent):void {
    keyPressed[event.keyCode] = true;
}

function onKeyUp(event:KeyboardEvent):void {
    keyPressed[event.keyCode] = false;
}

function onEnterFrame(event:Event):void {
    var moveAmount:int = 5;
    
    if (keyPressed[Keyboard.W]) bg.y += moveAmount;
    if (keyPressed[Keyboard.A]) bg.x += moveAmount;
    if (keyPressed[Keyboard.S]) bg.y -= moveAmount;
    if (keyPressed[Keyboard.D]) bg.x -= moveAmount;
}

```

**Comment by FliplineStudios** [comment]
This is unfortunately a long-standing problem with AIR and Android (I reported the same issue years ago here: #103).

It seems to more frequently affect Huawei devices, Honor devices, and some Samsung devices.

There never was a solution to this, and we eventually had to abandon cacheAsBitmap and anything that would internally function the same (like using rotationX, rotationZ, etc. which would automatically cache the clip as a bitmap).  Instead we manually have to create BitmapData objects and draw the vector content into them.  Definitely disappointing that a good chunk of the API just isn't usable anymore on one of the platforms.

**Comment by JuanCaiza** [comment]
the problem is not on some android devices but on all

**Comment by ajwfrost** [comment]
Hi @JuanCaiza  - I'm not sure whether this is the same as the old issue mentioned by @FliplineStudios, we did make a change recently to the EGL surface handling on Android to prevent some context losses, which may have affected things (although I'm not 100% sure what the steps are here for reproducing it?)

We're not able to access those APK files, are you able to zip up a test SWF file and attach it directly here please? And is this something that gets reproduced without any kind of changes to the application i.e. it's just the cached bitmap moving around the screen that is leaving behind some black areas where it used to be? No switching of application into background/foreground etc?

What device are you trying this on? it seems to be something with a USB keyboard I assume? If you're able to provide details on what Android device(s) you've seen the failure on, and what OS versions they're running, we can try to ensure we're using the same thing.

thanks

**Comment by JuanCaiza** [comment]
[dene.zip](https://github.com/user-attachments/files/16796156/dene.zip)
I have attached the swf file in zip here.

It was a bug from a long time ago. I was postponing it because it was only happening on 1 map. yesterday when I was investigating the cause of the error I saw that activating cacheAsBitmap triggered the problem.

there is no problem with the swf file on the computer, it just shows up as black in the APK files. I prepared this simple swf file as an example. in our normal game, in this way, the character moves with the keys, not the map. but the same problem exists. We add gamepad that mimics keys for Android phones.

**Comment by JuanCaiza** [comment]
@ajwfrost Were you able to get the error, any progress?

**Comment by ajwfrost** [comment]
Hi - we've got that SWF onto a phone but not quite sure what we're expecting to see? Looks like a map/scene background and you can move it around with wasd, left/right seems to loop but there's a top and bottom where it's black beyond the border of the image? Or is it meant to wrap top/bottom as well?

Trying this on a Samsung S20 currently, with Android 13 - you mention it's a problem on all phones, have you checked the OS versions etc? What are you reproducing it on, we can look at other devices perhaps..?


thanks

**Comment by JuanCaiza** [comment]
I have a Redmi Note 13 Pro and I only get a black screen. Almost all of my users say the same problem.

**Comment by JuanCaiza** [comment]
Now I tried with Emulator and the problem is the same.

https://github.com/user-attachments/assets/cba37276-8d41-4250-bcf6-093f20fb83b9

**Comment by ajwfrost** [comment]
I tried on the Android Studio emulator and also got a black screen. Worked on the Samsung handset .. let me see if it works with the emulator if we disable cacheAsBitmap..

**Comment by JuanCaiza** [comment]
In the video, when I make cacheAsBitmap false, I try it and it works fine. out of the 2 applications I tried, the one called dene is the one with cacheAsBitmap active. deneFalse is the one with cacheAsBitmap off.

**Comment by ajwfrost** [comment]
Have you tried the same functionality but with a smaller image? Just wondering:
```
CreateCanvas (2883) 8572 x 3090
```
this is fairly large, needs over 101MB of memory for the texture, so I'm wondering if there's just a failure depending on the available graphics memory. We'll see if we can confirm this though - better if we're able to find this out and throw an error somehow I think! Some devices seem to have a limit of 8k for a single dimension, we'll see what this emulator reports..

**Comment by ajwfrost** [comment]
Ah - so on a bit more debugging, there is an 8k limit on any dimension. But, actually this limit (I think) should instead match what the device reports, and on this emulator:
GL_MAX_TEXTURE_SIZE = 16384

And when we change that limit to 16384, with the cache as bitmap set to 'true', the image does actually appear.

So -> looks like this is a bug where there's a hardcoded value used in the AIR source code where it should be the device-specific limit which is provided. I'll also see whether we can ensure that when it fails, the `cacheAsBitmap` property remains `false` so that you can read it back after setting it, to see if it worked..

thanks

**Comment by JuanCaiza** [comment]
It would be great if it can be fixed with the new update. Thanks for everything @ajwfrost :)

**Comment by JuanCaiza** [comment]
@ajwfrost any progress?

**Comment by ajwfrost** [comment]
Hi

We've put some updates in here so that:
1) when you set the `cacheAsBitmap` property to true, if we can work out that the size of the image is too large for the platform, then we would ignore the call (so the property remains false).
2) when the internal rendering engine tries to create the texture, we check this against the context-specific maximum size, rather than relying on any hard-coded/arbitrary values.

There is a limitation though: in your scenario, we are not able to tell that the size is too large when you set the `cacheAsBitmap` property. I've not seen your source code but I think this is just because the call is happening in the constructor of the object - i.e. before we've actually set up any of the internal rendering contexts, which is asynchronous. So although it's working now on the emulator (with a 16k texture limit), if you ran this on a device that only supported 8k textures then it may still fail silently.

The changes we've made will be in our next release, later this week hopefully if we can get our build machine errors sorted out..

thanks

**Comment by JuanCaiza** [comment]
And we automatically set the default limit according to the phone? or will it stay 8k?

**Comment by ajwfrost** [comment]
The 8k limit has been removed, if it can get the information from the GPU then it uses that, otherwise it will just try whatever it's given..

**Comment by JuanCaiza** [comment]
perfect thank you very much :) Now we have no choice but to wait for the new update :)

**Comment by JuanCaiza** [comment]
@ajwfrost sorry to bother you. my users are currently waiting. will there be a new update soon? if not, can you share the changed file with us?

**Comment by ajwfrost** [comment]
Sorry - had a few problems with this one, but we've just issued it...

**Comment by JuanCaiza** [comment]
Everything seems to be fine with the new update. Thank you very much
