### ISSUE TITLE
[Feature Request][AIR SDK] Use `banner320x180` instead of `banner` for Android manifest

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3487]
## Feature Description
With AIR 51.1 we can use different banner resolutions for AndroidTV.
But if you miss `banner` in manifest you will get package error:
`descriptor.xml: error 407: To support application on Android TV, <banner>  tag  with attribute 'Path to the image used for banner' must be added in application.xml`

I think it excessively to include `banner` anymore if `banner320x180` is set up.

## Known Workarounds
Include `banner` with the same value as `banner320x180`.

**Comment by itlancer** [comment]
Implemented. Tested with latest AIR 51.1.2.2.
Thanks!

**Comment by dmunsie** [comment]
> Implemented. Tested with latest AIR 51.1.2.2.
> Thanks!

I'm having some major problems updating an app for Android TV. Have you had any success updating or releasing an Android TV app via the Google Play Store in late 2025 or 2026? If so, could you PLEASE take the time to detail how you setup your application.xml to handle the banner, icon images for use on Android TV? I keep getting a rejection from Google regarding my banner not being full width. Thank you for your time.
