### ISSUE TITLE
EncryptedLocalStore not longer working after Runtime update (PC)

### ISSUE THREAD

**Issue by meducati** [airsdk/Adobe-Runtime-Support#3501]
## Problem Description

Updating Runtime 50.2.4.1 to 51.1.1.3 breaks App (Encrypted Local Storage no longer working)
Tested on Win 7, Win 11
Fresh install on new computers.

## Steps to Reproduce

The following lines of code stores data in the Encrypted Local Storage inbetween App start/stop.
Updating Runtime 50.2.4.1 to 51.1.1.3 causes this to no longer work

private function setSettings(strKey:String, strValue:String)
{
	var bytes:ByteArray = new ByteArray();
	bytes.writeUTFBytes(strValue); 
	EncryptedLocalStore.setItem(strKey, bytes);
}
		
private function getSettings(strItem:String) : String
{
	var storedValue:ByteArray = EncryptedLocalStore.getItem(strItem);
	if(EncryptedLocalStore.getItem(strItem)) return String(storedValue.readUTFBytes(storedValue.length));
	else return "";
}

## Known Workarounds

Downgrade to 50.2.4.1

**Comment by ajwfrost** [comment]
Yes, please use 51.1.1.5 rather than 51.1.1.3. A number of the earlier 51.1.1.x versions had some issues with ELS particularly when trying to use earlier versions, 51.1.1.5 I believe resolves all these..

thanks

**Comment by meducati** [comment]
> Yes, please use 51.1.1.5 rather than 51.1.1.3. A number of the earlier 51.1.1.x versions had some issues with ELS particularly when trying to use earlier versions, 51.1.1.5 I believe resolves all these..
> 
> thanks

Thanks for the update. 
When I go to https://airsdk.harman.com/runtime only the 5.1.1.3 version is present...

**Comment by ajwfrost** [comment]
Ah ... good point! So if you're using shared runtime... we need to update that.
Let me get on it now, I think I can pick up the installers from our build server...

**Comment by ajwfrost** [comment]
@meducati  - updated now!
thanks

**Comment by meducati** [comment]
Much appreciated.
Works now with 51.1.1.5
:)

**Comment by meducati** [comment]
51.1.1.3

**Comment by meducati** [comment]
51.1.1.3
