### ISSUE TITLE
Not update android billing client 7.0.0 (error ) (update app in Google play )

### ISSUE THREAD

**Issue by kaizer1** [airsdk/Adobe-Runtime-Support#3507]
Hi 
  My version sdk : 51 ( last )
  android version 33/34 ( library 34, apk 33 )
   
  in Gradle app     
  implementation 'com.android.billingclient:billing:7.0.0'   

when uploading an updated application to Google Play, this is the error. I think this is due to the limitation of your framework on the payment library, tell me how to solve this problem. Thank you
  
![image_2024-10-06_21-24-09](https://github.com/user-attachments/assets/3f5f9508-be1e-4618-b150-0841235d0272)

**Comment by marchbold** [comment]
Are you using an ANE for billing? The play billing library isn't included in AIR so the issue is likely with the extension you are using. If you are using ours (@distriqt) then you just need to ensure you have updated to the latest.

**Comment by kaizer1** [comment]
No, I don't use it @distriqt what is it anyway? I just connected Android billing in Ane (and that's it) as it was connected before (but an old app, last updated 8 years ago and it worked fine there), and now I need to update it. I included it in the ane build like this:

**Comment by marchbold** [comment]
Sounds like an implementation / integration issue. Not really sure what to suggest without looking at the extension.

**Comment by kaizer1** [comment]
I've decided everything, forgot to update the version in the android manifest. Sorry =))
