### ISSUE TITLE
[Feature Request / ANE] Restart (mobile) App?

### ISSUE THREAD

**Issue by 2jfw** [airsdk/Adobe-Runtime-Support#3529]
I have a scenario where I would want to restart my mobile application (primary on Android).
There is no native functionality in AIR as such available, which is fine,
so I was wondering:

1) if there is any ANE available for this already (I haven't found one)
2) if others are also interested in such functionality
3) @marchbold : if it would be possible to create such an ANE, in the case there is no ANE already capable of doing so
?

**Comment by bobaoapae** [comment]
For android and windows  I think that it's relatively easy to build a ane to do this, don't know about mac and ios. I also need some ane to do that but for ios, next month I will have free time and I will build a ane to try that, on Android I know I can do this very easily. If you don't find any ane until next month, just check this issue again I will add a link to my ane when I build.

**Comment by marchbold** [comment]
Haven't tested it in a while but:

https://github.com/distriqt/ANE-RestartApp

**Comment by 2jfw** [comment]
> For android and windows I think that it's relatively easy to build a ane to do this, don't know about mac and ios. I also need some ane to do that but for ios, next month I will have free time and I will build a ane to try that, on Android I know I can do this very easily. If you don't find any ane until next month, just check this issue again I will add a link to my ane when I build.

Thanks a lot for your kind offer on this!
I will try out the distriqt ANE (which is Android exclusive as it seems) and get back to your offer for the case it is no longer working.

> Haven't tested it in a while but:
> 
> https://github.com/distriqt/ANE-RestartApp

Thanks a lot, Michael!
I will check it out and report back, if it is still working 👍

**Comment by 2jfw** [comment]
Just reporting back that the ANE is working well and was exactly what I was looking for!
Thanks again, @marchbold !

Is it actually intentional that the Restart ANE is not listed on _airnativeextensions.com_?
I saw some free ANE's are listed there but not this one.. [-> Gotta check on github for other useful ANE's]

**Comment by marchbold** [comment]
Great to hear! 

Regarding why it isn't on the ane site, there are just some extensions that we don't maintain or aren't completely feature developed so we don't advertise them. 

There's a few here:

- [airnativeextensions](https://github.com/orgs/airnativeextensions/repositories?q=visibility%3Apublic+archived%3Afalse)
- [distriqt](https://github.com/orgs/distriqt/repositories?q=visibility%3Apublic+archived%3Afalse)
