### ISSUE TITLE
AIR 51.1 Fails on SteamDeck OLED

### ISSUE THREAD

**Issue by RossD20Studios** [airsdk/Adobe-Runtime-Support#3534]
## Problem Description

After upgrading from AIR 50.2 to AIR 51.1 on Linux SDK in our latest Steam release, I received numerous reports from players using the Steam Deck OLED version that they couldn't play the game due to an unresolvable AIR SDK warning prompt.

Here's a photo one of our player's sent:
![airOnSteamdeckIssue](https://github.com/user-attachments/assets/9ffda919-8f24-4c95-8b0d-f75f777622cb)

The error message reads: _"Running 32-bit AIR 51.1 on 64-bit systems has not been fully tested. However, 32-bit AIR is expected to run on 64-bit systems if they have the required 32-bit libraries and packages installed.

The following links describe how to install or update AIR 51.1 on the 64-bit versions of Ubuntu 9.10, Fedora Core 12 and openSUSE 11.2."_

This was a pretty devastating user experience and could've really hurt our update launch if not for the patience, understanding, and reports of our players. None-the-less, I'm sure we incurred at least a few refunds as a result.

## Steps to Reproduce

We updated from AIR 50.2 to the latest 51.1 in the recent update to our Steam game and immediately received reports from players downloading the update that the game no longer worked.

SteamDeck is the primary platform for our Linux audience, so it's a high priority for us that this gets issued resolved in future updates of AIR, otherwise we'll be unable to continue supporting the game with the latest AIR features.

## Known Workarounds

We incrementally rolled back versions of the SDK until we found the latest version that worked, which was AIR 50.2.4.5 (March 2024 update). Version 50.2.5.1 (April update) DID NOT work - our game would immediately crash, which I suspect was the result of the back worker bug that was introduced and later resolved in a later version of AIR 51.1. (See issue: https://github.com/airsdk/Adobe-Runtime-Support/issues/3394#issuecomment-2329706211)

**Comment by ajwfrost** [comment]
Current assumption is that the introduction of "libsecret-1" as a dependency for the AIR runtime is causing a failure in loading this .. we will switch that to a dynamic loading (i.e. only loaded when present on the machine) which should then work around this.

**Comment by ajwfrost** [comment]
Fixed in [AIR 51.1.2.2](https://airsdk.harman.com/download/51.1.2.2)
