### ISSUE TITLE
[Docs] `Object::toJSON()` not documented

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#3553]
## Problem Description
`Object::toJSON()` should be documented similar to `Object::toString()` https://airsdk.dev/reference/actionscript/3.0/Object.html#toString()

## Steps to Reproduce
https://airsdk.dev/reference/actionscript/3.0/Object.html

**Actual Result:**
`Object::toJSON()` not documented.

**Expected Result:**
`Object::toJSON()` documented.

**Comment by ajwfrost** [comment]
Hi

There's no `Object.toJSON()` method, at least not that I can see in the source code, and when I try an example with this, it compiles but then throws a runtime exception.
```
[Fault] exception, information=TypeError: Error #1006: toJSON is not a function.
```
See https://github.com/adobe/avmplus/blob/master/core/Object.as

It does appear that some classes do implement a `toJSON()` method, but those are limited (and basic implementations), and are described in the description of the JSON class here:
https://airsdk.dev/reference/actionscript/3.0/JSON.html

Can you confirm how you're seeing a generic Object `toJSON()` method?

thanks

**Comment by itlancer** [comment]
@ajwfrost 
Sorry. I misunderstood it with JSON related `toJSON()` methods for objects stringifying.
Closed.
