### ISSUE TITLE
How to change app display name?

### ISSUE THREAD

**Issue by githubccz** [airsdk/Adobe-Runtime-Support#3576]
I can change my app display name with th 50.0 sdk or higher version, when change the name in the xml file, it  comes the error like this :

invalid application descriptor: Illegal values for application/name.

How can I  fix this problem?

**Comment by ajwfrost** [comment]
Hi
Are you able to share the relevant snippet of the application descriptor file that causes this problem? The `name` field can be localised, it's the `filename` field that is best to stick to ascii.

See https://airsdk.dev/docs/building/application-descriptor-files/elements/application#name

thanks

**Comment by githubccz** [comment]
> Hi Are you able to share the relevant snippet of the application descriptor file that causes this problem? The `name` field can be localised, it's the `filename` field that is best to stick to ascii.
> 
> See https://airsdk.dev/docs/building/application-descriptor-files/elements/application#name
> 
> thanks

Problem  solved!  The app name config have been put to the end of xml file!

Thanks!

**Comment by ajwfrost** [comment]
Okay thanks for confirming!
