### ISSUE TITLE
Android : lot of overheads and high CPU usage starting with version 51.1.1.1

### ISSUE THREAD

**Issue by lwmirkk** [airsdk/Adobe-Runtime-Support#3583]
## Problem Description

Starting with version 51.1.1.1, there are a lot of overheads seen in Scout and a constant high CPU usage on Android, the device gets very hot over time.
We tested different versions of the SDK and the problem started with this version.

Problem happens in Debug and Device release.

* Which AIR SDK did you use? 
Tested with 50.2.4.1 - 51.0.1.4 - 51.1.1.1 - 51.1.2.2 - 51.1.2.3
I could not download the 51.0.1.5 to test.

* Describe the affected environment: Android vs. iOS, all devices vs. just specific models.
Android

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Tested by myself in many different devices.

App:
Render mode : Auto / CPU

ANEs:
androidx.appcompat
androidx.core
androidx.vectordrawable
com.distriqt.Application
com.distriqt.Core
com.distriqt.Exceptions
com.distriqt.MediaPlayer
com.distriqt.PackageManager
com.distriqt.Permissions
com.distriqt.playservices.AppSet
com.distriqt.playservices.Base
com.distriqt.RestartApp
com.google.code.gson.gson
com.google.guava
com.mesmotronic.ane.fullscreen
com.tuarua.frekotlin
com.tuarua.WebViewANE

## Steps to Reproduce
Just compile and run the app with these version, on SCOUT will show the overhead entire time and high CPU usage, the device will get hot with time...

## Known Workarounds

Use AIR SDK 51.0.1.4 or older.

Images and FLM (scout)
51.0.1.4:
![until-51 0 1 4](https://github.com/user-attachments/assets/5fca3ddf-9bb7-4877-bb52-c534b94ef5db)

51.1.1.1:
![after-51 1 1 1](https://github.com/user-attachments/assets/bb612358-0237-4c61-80f4-80cf7270543c)

51.0.1.4:
https://drive.google.com/file/d/1Mw6JxS5r_F1IlxSXyyA5tlGs75c3ZoKh/view?usp=sharing

51.1.1.1:
https://drive.google.com/file/d/1Svi8fO3ChU0PfcvATGcCyZcy00edAiuY/view?usp=sharing

EDIT:
Tested the version 51.0.1.5 and this version doesn`t have the problem, so the problem started in 51.1.1.1.

**Comment by ajwfrost** [comment]
Hi - thanks, we'll check what's happening here.. but we can't access those Google Drive links, are you able to upload the APKs using the below link please?
https://transfer.harman.com/requests/sdo21MAQ9CCl4UrbhjVL3L

thanks

**Comment by lwmirkk** [comment]
> Hi - thanks, we'll check what's happening here.. but we can't access those Google Drive links, are you able to upload the APKs using the below link please? https://transfer.harman.com/requests/sdo21MAQ9CCl4UrbhjVL3L
> 
> thanks

Files uploaded.
Thanks! =)

**Comment by ajwfrost** [comment]
Thanks for the files.

So with the 51.0.1.5 version, we're seeing a CPU level of around 3-5% for your app on a device here. And when we take that APK and replace the AIR libraries with the latest version, it hits around 280-290%...! If we take your APK and repackage it with 51.0.1.5 (but with our Android set-up) then it stays the same. So - definitely related to the AIR SDK update.

But for other complex AIR apps that are built with this version of AIR, we don't see any such change... so I'm wondering if there's some interaction here with one of the ANEs, or some specific use case within your SWF file that is causing this.

Scout isn't showing any increased ActionScript usage, instead it's all within the 'Other Overhead' category. We'll have to drill down into this one...

thanks

**Comment by ajwfrost** [comment]
We've triggered the next release, 51.1.3.1 which has this in, should be available next Wednesday...
