### ISSUE TITLE
Issue when manually sending Cookies on iOS and MacOS

### ISSUE THREAD

**Issue by Devin-Licastro** [airsdk/Adobe-Runtime-Support#3613]
In my app, we are attempting to securely download files from an AWS content-delivery network that relies on cookies to ensure the user should have access to the file. On Windows and Android and Postman, this is working fine, rather than rely on built-in tools we manually store the cookies and then manually send them during the file requests. Basically, we just send a url request header with the key "Cookie" and the value of the needed cookie. 

Inside Air on iOS and Mac however, this does not work. We get back a 403 status error, and since the response is not visible from inside Air we are unable to learn anything else... leaving us at a bit of a loss. 

Note: This works on a Mac in postman, but just not in our air app. I'm not sure what would be different between how Postman is sending the request and how URLRequest is sending it from inside Air?

Does anyone have experience/knowledge about how to handle cookies differently on Mac and iOS? I'm guessing there is some kind of stricter network security layer in place here. Any suggestions on how to approach understanding or getting past that?

**Comment by ajwfrost** [comment]
Do you have multiple cookies? I'm wondering if this is an issue with formatting... the Apple documentation for `addValue` for updating a header field would normally append text with a comma delimiter, but cookies are meant to have `; ` as the delimiter..

Although having said that, there appears to be some custom handling of the cookie headers for some of the Mac/iOS code. It may depend exactly on what mechanism you're using to send things, plus some other setting within the code.

Are you able to direct your request at a page such as
https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending/
(and in the html response, look for the text "headers your browser sent when requesting this page")

If you can create a code snippet that demonstrates how you construct and send the request, and describe what you actually expect it to send, we can look to see how this is actually being sent out..

thanks
