### ISSUE TITLE
[Feature Request] - DateTime Timezone/getLocalTimezone

### ISSUE THREAD

**Issue by raresn** [airsdk/Adobe-Runtime-Support#401]
Hey Andrew, we discussed this a while back but i think it is wise to have it here:

We have an app that handles appointments and we do A LOT of operations with the Date class.
We would like to have the option to set the time zone of the Date class, that way when our users travel from one country to another we can use the original time zone inside the app.
I know we can build a class that extend the Date and write a few IF conditions, but we would like something like this done from the core level so it's fast.

I believe adding a setTimezoneOffset function would be wrong because it would not help much with daylight saving time.

We were thinking more of setting named timezone like 'Europe/London'. This should be in line with the timezone in PHP and MySQL and take care of DST changes.

setLocalTimezone(timeZoneName:String):Boolean
getLocalTimezone():String
Date.getAvailableTimezones():Vector.<String>

 
We should be able to get and set the timezone in this format, either:

- static, that will affect all new and existing Date() objects

or

- local on a single Date object and would override system and static time zones.

Setting null would cancel the override.

PHP handles it like this
A list of timezone name should also be provided trough a method.
We need to keep our clients in the same timezone. So we will need the static functions more.

This doesn't have to be on Date class, it could be more globally, like maybe on NativeApplication class.
This way all date related functions will be aligned and consistent. Including Date and DateTimeFormat and any other.

 
Proposed functions:
setLocalTimezone(timeZoneName:String):Boolean
getLocalTimezone():String
Date.getAvailableTimezones():Vector.<String>

 
PHP reference to all this:
https://www.php.net/manual/en/function.date-default-timezone-set.php
https://www.php.net/manual/en/timezones.europe.php
https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_convert-tz
 
If you think we can do more to help with this, let me know

**Comment by JohnBlackburne** [comment]
This is available in iOS

https://developer.apple.com/documentation/foundation/timezone

`knownTimeZoneIdentifiers ` in particular is an Array (so AS Vector) of timezone strings. `current` is the current TimeZone for that user/device.  I don't see a way to set the system TimeZone but that does not make sense as it is under user/device control.

It could be done with an ANE but I agree, like language/locale it is the sort of thing that makes sense to be available in AIR.

**Comment by ajwfrost** [comment]
Closing this one now as (a) it's covered under #1396 and (b) it's in AIR 50.0...
thanks
