### ISSUE TITLE
AIR SDK not compatible with Firebase/Crashlytics

### ISSUE THREAD

**Issue by mateo-kozomara** [airsdk/Adobe-Runtime-Support#515]
## Problem Description
 
It doesn't seem possible to implement new Firebase/Crashlytics through an ANE with AIR 33.1.1.300.

It looks like Adobe AIR doesn't add the "__mh_execute_header" to the executable, which seems to be the requirement for using Firebase/Crashlytics.

These logs can we found when trying to start Crashlytics:

`6.31.0 - [Firebase/Crashlytics][I-CLS000000] Crashlytics could not find the symbol for the app's main function and cannot start up. This can happen when Exported Symbols File is set in Build Settings. To resolve this, add "__mh_execute_header" as a newline to your Exported Symbols File.`

`6.31.0 - [Firebase/Crashlytics][I-CLS000000] Crash reporting could not be initialized`

Everyone using Firebase/Crashlytics through an Adobe AIR ANE should be affected by this issue, and since the deadline to switch from Fabric implementation is November 15th 2020, we will not be able to get crash reports from there on without an AIR SDK update.

**Comment by marchbold** [comment]
Yeah we have run into this issue as well and did raise it with @ajwfrost a while ago. We don't have a solution for this currently.

**Comment by pnico** [comment]
We're filing a support request with Google to ask for an extension on the deadline to stop using Fabric SDK for Adobe AIR apps. Any response from @ajwfrost on when/if a fix for this could be available?

**Comment by ajwfrost** [comment]
Hi
I'll sync up with the developer tomorrow on this one and will provide an ETA.. 
thanks

**Comment by ajwfrost** [comment]
Hi
Can I ask if people are able to check using a test version of ADT that we've uploaded to the below link? 
https://transfer.harman.com/messages/HHe8EQFGEgjmM6zT6XT9oZ/attachments/52XkEffAjonFHxBsf0yrxh/download/adt.jar.zip
(2.8 MB) Checksum (SHA256): 205bb62ebbfa7761f351b19863b5f44506047764e2ed37114c5263843c1ca747

thanks

**Comment by pnico** [comment]
It looks like this is working so far. There are apparently some issues with AdMob grabbing the exception handler but that's not related

**Comment by marchbold** [comment]
Confirming from our side as well. This is working with the latest Crashlytics SDK.

**Comment by marchbold** [comment]
@ajwfrost We can probably close this issue with 345 correct?
