### ISSUE TITLE
FileFilter not updated on Mac

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#526]
## Problem Description

FileFilter not updated on Mac.

* AIR SDK 33.1
* Air for MacOS
* link to the [Starling forum](https://forum.starling-framework.org/d/22803-filefilter-doesnt-updated-on-mac)

## Steps to Reproduce

```
package
{
	import flash.display.Sprite;
	import flash.events.MouseEvent;
	import flash.filesystem.File;
	import flash.net.FileFilter;

	public class Main extends Sprite
	{
		public function Main()
		{
			var sprite:Sprite = new Sprite();
			sprite.graphics.beginFill(0x0000FF);
			sprite.graphics.drawRect( 0, 0, 100, 100);
			sprite.graphics.endFill();
			sprite.buttonMode = true;
			sprite.addEventListener(MouseEvent.CLICK, mouseClickOutsideHandler);
			this.addChild( sprite );

			var sprite2:Sprite = new Sprite();
			sprite2.graphics.beginFill(0x00FF00);
			sprite2.graphics.drawRect( 0, 0, 100, 100);
			sprite2.y = 120;
			sprite2.graphics.endFill();
			sprite2.buttonMode = true;
			sprite2.addEventListener(MouseEvent.CLICK, mouseClickOutsideHandler2);
			this.addChild( sprite2 );
		}
			
		private function mouseClickOutsideHandler(event : MouseEvent) : void
		{
			var txtFilter:FileFilter = new FileFilter("Text", "*.xml");
			var file:File = File.desktopDirectory;
			file.browseForOpen("Please select a file...", [txtFilter]);
		}
		
		private function mouseClickOutsideHandler2(event : MouseEvent) : void
		{
			var txtFilter:FileFilter = new FileFilter("Images", "*.jpg;*.jpeg;*.gif;*.png");
			var file:File = File.desktopDirectory;
			file.browseForOpen("Please select a file...", [txtFilter]);
		}
	}
}
```
step 1 : click on sprite, choose an xml file
step 2 : click on sprite2, It's only possible to choose xml file in the select box, not image

the FileFilter is never updated

it work correctly on Windows

## Known Workarounds

no workaround

**Comment by pol2095** [comment]
I created an [ANE](http://pol2095.free.fr/macOS/file) for this problem
but it's better that Harman fix it

**Comment by pol2095** [comment]
Any news about this problem ?

**Comment by ajwfrost** [comment]
@pol2095 this is in the list of things to look at next..

**Comment by pol2095** [comment]
Its' fixed, thanks.

**Comment by pol2095** [comment]
In MacOS Monterey 12.1, file browse work only one time, after it's impossible to select a file in the native browse window or cancel it...

**Comment by ajwfrost** [comment]
Hi - fyi there's an updated AIR SDK to fix this now, currently available via the below link (or see the [Release Notes](https://airsdk.harman.com/release_notes) for details.
https://airsdk.harman.com/download/33.1.1.731
thanks

**Comment by pol2095** [comment]
Thanks, FileFilter seems not working now.
