### ISSUE TITLE
Can't Access iOS Simulator with Animate and AIR 33.1.1.345

### ISSUE THREAD

**Issue by craigory623** [airsdk/Adobe-Runtime-Support#569]
Hello, In the latest Animate 2021, I get the following error when trying to build for the simulator. Xcode Verison 12.2, Mac OS Catalina.

```
Warning: The path to platform sdk should end with any one of the (iPhoneOSx.x | iPhoneSimulatorx.x | AppleTVSimulatorx.x | AppleTVOSx.x) format to avoid any unintended behavior.
ld: in /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/../../../../../usr/lib/llvm-gcc/4.2.1/libgcc.a(libgcc.o), building for iOS Simulator, but linking in object file built for macOS, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/../../../../../usr/lib/llvm-gcc/4.2.1/libgcc.a' for architecture x86_64
```

**Comment by buyANE** [comment]
@craigory623 here is a workaround,copy the file libgcc.a in  "pathToYourAIRSDK\lib\aot\lib" folder,then navigate to xcode's folder "/Applications/Xcode.app/Contents/Developer/usr/lib/llvm-gcc/4.2.1" folder,first backup the libgcc.a in it,then paste the libgcc.a file you just copyed from AIRSDK in that folder,then everything goes fine ,just test your air app in iOS simulator as usual.

**Comment by craigory623** [comment]
Thanks you so much! The error is gone, but I now get "Can't Install on iOS Simulator". It always feels like I have to jump though a bunch of hoops for this stuff..... I really just need to take screenshots for the App Store. Very frustrating.

**Comment by derRaab** [comment]
@buyANE just a quick note upfront: The path is `pathToYourAIRSDK/lib/aot/lib/gcc/libgcc.a`. (inside the `gcc` directory)

I tried your approach and it did help with the file libgcc.a, but now I have a similar error with another file:

```
Warning: removing user-included storyboard "LaunchScreen"
ld: in /...flex_sdk_4.16.1_air_33.1_fp_32/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a(CTGameInput.o), building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file '/...flex_sdk_4.16.1_air_33.1_fp_32/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a' for architecture x86_64
Compilation failed while executing : ld64
```

I'm on macOS Big Sur 11.1 with Xcode 12.3 and I hope you do have enough insight that you see a way to force building for a specific arch? I did open a related bug report on [https://youtrack.jetbrains.com/issue/IDEA-259414](https://youtrack.jetbrains.com/issue/IDEA-259414) and we try to figure out a way to forward something like `ARCHS=i386 ONLY_ACTIVE_ARCH=NO` through adt to xcodebuild but that might be not the way to go. I do not have the knowledge to understand how that might be related anyway. :D

Any ideas? To me it looks like there is no straight forward way to use adt with the iOS simulator right now?

**Comment by buyANE** [comment]
@craigory623 I'm using latest Xcode 12.3 and with the latest iOS Simulator and there's no error when install on iOS simulator.

**Comment by craigory623** [comment]
Hmmm... Are you one Catalina or Big Sur?

**Comment by buyANE** [comment]
@derRaab ARCHS=i386 maybe the problem, XCode 12.3 is 64 bit only, change it to ARCHS=x86_64 may work?
@craigory623 Big Sur 11.1

**Comment by craigory623** [comment]
I'm still on Catalina....... I just need to upload screenshots! So frustrating......

**Comment by buyANE** [comment]
@craigory623 Catalina may not the problem,you can make a HelloWorld project,Then try install it on iOS simulator using adl command, maybe Animate 2021 is the problem.

**Comment by craigory623** [comment]
Could you post the specific ADL command line you use?

**Comment by buyANE** [comment]
@craigory623 
compile ipa command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -package -target ipa-test-interpreter-simulator -storetype pkcs12 -keystore "path to your dev p12 file" Test.ipa Test-app.xml Assets.car "folder or file you need to package" Test.swf -extdir "path to your ane folder" -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk

install command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -installApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -package Test.ipa

uninstall command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -uninstallApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -appid "your app id"

launch command 
java -jar "pathtoyourAIRSDK/lib/adt.jar" -launchApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -appid "your app id"

**Comment by buyANE** [comment]
@craigory623 

first set the device you want to install,use command "xcrun simctl list devices" to list all available devices
export AIR_IOS_SIMULATOR_DEVICE='iPhone 12'
export AIR_IOS_SIMULATOR_DEVICE='iPhone xxx'

compile ipa command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -package -target ipa-test-interpreter-simulator -storetype pkcs12 -keystore "path to your dev p12 file" Test.ipa Test-app.xml Assets.car "folder or file you need to package" Test.swf -extdir "path to your ane folder" -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk

install command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -installApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -package Test.ipa

uninstall command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -uninstallApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -appid "your app id"

launch command
java -jar "pathtoyourAIRSDK/lib/adt.jar" -launchApp -platform ios -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -device ios-simulator -appid "your app id"

**Comment by derRaab** [comment]
@buyANE I tried `ARCHS=x86_64` as well - without success.

So maybe someone can explain to me what the actual problem is: As I understand, it might have something to do with the fact, that macOS Big Sur also supports Apple Silicon and therefore the default platform everything used to work on (`x86_64`) is not the default anymore. So we have to tell adt to use that platform if we want to test a AIR application in the iOS simulator? Is that the real problem?

And if so, how would I do that from the command line? I tried to set these environment variables:
```
export ONLY_ACTIVE_ARCH=NO
export ARCHS=x86_64
```

I also tried to provide these as additional arguments for adt between -package and -target:
```
...adt.jar -package ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -target ipa-debug-interpreter-simulator -storetype PKCS12 -keystore ...
```

But that always ends with the error: `Signing options required to package IPA`

**Comment by craigory623** [comment]
@buyANE - Thanks so much, you are the man! 
Command line works. Animate does not. I owe you.

**Comment by derRaab** [comment]
Hi again,

I tried everything I could to build that ipa version for the iOS simulator. That's my command:

```
export EXCLUDED_ARCHS=[arm64]

/Applications/IntelliJ\ IDEA\ 2020.2.3.app/Contents/jbr/Contents/Home/bin/java
 -Dapplication.home=/...flex_sdk_4.16.1_air_33.1_fp_32
 -Dfile.encoding=UTF-8
 -Djava.awt.headless=true
 -Duser.language=en
 -Duser.region=en
 -Xmx512m
 -jar /Users/markusraab/Documents/BYPR-Staff/Software/FlexSDKs/flex_sdk_4.16.1_air_33.1_fp_32/lib/adt.jar
 -package
 -target ipa-test-interpreter-simulator
 -storetype PKCS12
 -keystore /...project/src-ios/signing/2nd_ios_development.p12
 -storepass SECRET
 /...project/bin-ios/iOS-Debug-Simulator.ipa
 /...project/bin-ios/ApplicationIOS-app.xml
 -platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk
 -C /...project/bin-ios ApplicationIOS.swf
 -C /...project/bin data
 -C /...project/src-ios/assets-car-build/build Assets.car
 -C /...project/src-ios LaunchScreen.storyboardc
 -C /...project/src-ios AppIcons
 -C /...project/bin templates
 -extdir /...project/src/ane/com.distriqt.Core/lib
 -extdir /...project/src/ane/com.distriqt.Dialog/lib
 -extdir /...project/src/ane/com.distriqt.Notifications/lib
 -extdir /...project/src/ane/com.distriqt.Application/lib
```

But now I'm stuck with this error:

```
ld: building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file 'extensionglue.o' for architecture x86_64
Compilation failed while executing : ld64
```

I hope anyone could point me in the right direction. Please!

**Comment by buyANE** [comment]
@derRaab 
from what i see you are using flex sdk,I almost never used flex
the error msg you post maybe ane issue,one of your ane only supoort 64bit (and you may want to generate universal an ipa file with both 32 and 64 bit)

to get this error away, you can try add next 2 line in your -app.xml file in <InfoAdditions> tag
<key>MinimumOSVersion</key>
<string>11.0</string>
use 11.0 or some more high value (such as 14.0) to force adt generate an 64 bit ipa file only.

**Comment by derRaab** [comment]
@buyANE : I tried that as well - makes no real difference. I always get linking errors that state I'm building for iOS simulator. I think everything is 64 bit.

I tried again with a JDK 1.8 variant and still get this error:

```
ld: in
/...flex_sdk_4.16.1_air_33.1_fp_32/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a(CTGameInput.o),
building for iOS/iOS Simulator, but linking in object file built for iOS Simulator, file '
/...flex_sdk_4.16.1_air_33.1_fp_32/lib/aot/lib/libRuntimeInterpreter.x86-simulator-air.a' for architecture x86_64
Compilation failed while executing : ld64
```

ADT command line call:

```
/Users/markusraab/Library/Application Support/JetBrains/IntelliJIdea2020.2/jdks/jbsdk8u112b809.1_osx_x64/jdk/Contents/Home/jre/bin/java
-Dapplication.home=/...flex_sdk_4.16.1_air_33.1_fp_32
-Dfile.encoding=UTF-8
-Djava.awt.headless=true
-Duser.language=en
-Duser.region=en
-Xmx512m
-jar /...flex_sdk_4.16.1_air_33.1_fp_32/lib/adt.jar
-package
-target ipa-debug-interpreter-simulator
-storetype PKCS12
-keystore /Users/markusraab/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/flex/lib/temp_keystore.p12
-storepass keystore_password
/...project/bin-ios/iOS-Debug-Simulator.ipa
/...project/bin-ios/ApplicationIOS-app.xml
-platformsdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk
-extdir /...project/src/ane/com.distriqt.Core/lib
-extdir /...project/src/ane/com.distriqt.Dialog/lib
-extdir /...project/src/ane/com.distriqt.Notifications/lib
-extdir /...project/src/ane/com.distriqt.Application/lib
-C /...project/bin-ios ApplicationIOS.swf
-C /...project/bin data
-C /...project/src-ios/xcode Assets.car
-C /...project/src-ios/xcode LaunchScreen.storyboardc
-C /...project/src-ios AppIcons
-C /...project/bin templates
```

So again my question: Did anyone successfully test his AIR application within the iOS simulator on macOS Big Sur with XCode 12.4?

And if so: How did you force the build only for simulator?

**Comment by buyANE** [comment]
@derRaab recent days i met your problem as well,and finally i found the problem and get it done, I found you use distriqt's ANE,It's the ANE's problem,with the latest macos,you can only build 64bit ipa,but distriqt's ANE have "-ios_version_min 9.0" in there ane's platform.xml file,this made the MinimumOSVersion drop to 9.0 even you set it to 11.0 in your app-app.xml file,when compile the error you post will show.
to get this prolblem done,you can ask them to repackage the ane for you or just repackage by your self. When repackage ane,remove -ios_version_min 9.0 or set it to -ios_version_min 11.0. After repackage just compile and build for simulator and everything is fine.

**Comment by derRaab** [comment]
@buyANE Wow - thank you so much! I already finished the project by using only on device testing but thank god I didn't need to create screenshots for all devices. :) I will ask for repackaged versions at let you know if you fixed it for everybody! :)

**Comment by derRaab** [comment]
@buyANE ❤️ You were right! Thanks for figuring that out. It's to late for me, but will help others!!!

**Comment by ajwfrost** [comment]
@craigory623 just checking, I believe all the issues mentioned in this ticket have been resolved hence closing it for now, but if you believe there's still an issue here, please re-open..
thanks
