### ISSUE TITLE
Null Pointer Exception at AndroidInputManager

### ISSUE THREAD

**Issue by berkayk** [airsdk/Adobe-Runtime-Support#573]
## Problem Description

I am receiving many crashes related to AndroidInputManager. Here is the crash log:

````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.InputDevice.isVirtual()' on a null object reference
       at com.adobe.air.AndroidInputManager.onInputDeviceAdded(AndroidInputManager.java:172)
       at android.hardware.input.InputManager$InputDeviceListenerDelegate.handleMessage(InputManager.java:1108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
````

* Which AIR SDK did you use? 

AIR 33.1.1.345

* Describe the affected environment: 

Android. Devices having the crash are distributed as follows. 

88% General Mobile (64% GM 8, %24 GM 8 d), 
6% Oppo (4% A9 2020, 2% A5 2020), 
3% HUAWEI (P20 Lite) 
and others.

Operating systems:

88% Android 9
9% Android 10

* Can you reproduce it yourself, or did you get reports from other users? 

Reports are gathered from Firebase Crashlytics. 

* If applicable, link to the Starling/Feathers issues that brought you here.

No

## Steps to Reproduce

I cannot reproduce myself, this data is gathered from Crashlytics.

**Comment by ajwfrost** [comment]
Thanks for the report, another one where a coding assumption has turned out to be false causing a null pointer exception.. Simple to protect against, so a fix will be in the next release.
thanks

**Comment by lwmirkk** [comment]
> Thanks for the report, another one where a coding assumption has turned out to be false causing a null pointer exception.. Simple to protect against, so a fix will be in the next release. thanks

Hi @ajwfrost and @berkayk !

Has this already been fixed?

Thanks a lot. =)

**Comment by ajwfrost** [comment]
I can't see this issue mentioned in the release notes ... but I can see a change in this file in Feb 2021 -> it should be in 33.1.1.406 or 33.1.1.444. Apologies, not sure why we've not got this change listed in the release notes..!

Will close this now .. if you do reproduce this, please re-open (although it won't be the exact same issue, it's not a tricky code change...)

thanks
