### ISSUE TITLE
 Update StageWebView to a modern implementation

### ISSUE THREAD

**Issue by Mintonist** [airsdk/Adobe-Runtime-Support#668]
StageWebView implementation is pretty outdated.
We can open very simple html content (without dynamic content). 
Is it possible to update it for rendering html5/css/js?

As for me native StageWebView is needed for common things inside AIR apps such as OAuth process, payment process (e-wallets), etc.
Now we can only use one ANE from Distriqt for it. Few month ago it was impossible at all. Thanks Distriqt team for it. 
But I think some basic functuionality for web content in 2021 year must be inside AIR platform.

Thx!

**Comment by Mintonist** [comment]
![image](https://user-images.githubusercontent.com/9267850/107847446-b58c7780-6dfc-11eb-9f60-a2143b44d0ba.png)

Russian popular social network vk.com (aka Facebook) starts to show this instead of login dialog. The text about old-fashion browser type.

**Comment by Mintonist** [comment]
On Windows, StageWebView is probably still using Internet Explorer's engine, so it would be stuck on IE11 at best. Microsoft doesn't like breaking backwards compatibility. Assuming that Edge has an embedded equivalent that can be easily swapped in, that's probably something that HARMAN will need to opt into.

**Comment by johnou** [comment]
StageWebView cannot be used to embed captcha into applications, we have tried true and false for useNative, one fails silently, the other fails with "SyntaxError: Parse error". I have created a small application to reproduce the problem available here https://gist.github.com/johnou/da7bd6d1f1efd7c049191e7f928c4364

**Comment by itlancer** [comment]
@Mintonist, you can try to use Edge WebView2 with latest AIR versions https://github.com/airsdk/Adobe-Runtime-Support/discussions/1170#discussioncomment-1346559

**Comment by Mintonist** [comment]
Thanks for Edge WebView2  with latest AIR versions!
