### ISSUE TITLE
Bug at Android Devices with DropShadowFilter and IconItemRenderer

### ISSUE THREAD

**Issue by apofis1969** [airsdk/Adobe-Runtime-Support#753]
## Problem Description
DropShadowFilters does not appear on Samsung devices, but the elements where the filter has been used still appeared. 
But testing with LG Device K52 we found out that DropShadowFilter does not let appear the elements. This is a huge bug, because some principal buttons did not appear. Stayed invisible.
e.g.: 
` <s:filters>
	<s:DropShadowFilter distance="4" quality="2" angle="90" color="#000000" blurX="4" blurY="4"/>
</s:filters>`
no matter if s:filters or mx:filters
This bug effected buttons and also video.

IconItemRenderer is working on our Samsung Devices.
But testing with our LG Device the whole List does not appear, stayed invisible, same problem as with the filters.

## Known Workarounds
For IconItemRenderer we created the List with ItemRenderer as a huge workaround, because all list items are saved in an external database and a principal feature of the app.
DropShadowFilters we deleted. 
As it is impossible to test the app with all existing Android devices, we have no idea how many other devices are affected by these two errors.  They make/made the app unusable.

All Devices have Android 10, AIR SDK 33.1.1.345 or 33.1.1.406
Tested with Samsung S9+, Samsung Galaxy S6 Lite and LG K52

**Comment by ajwfrost** [comment]
Hi @apofis1969  - would you be able to create a quick test app for this and build with "apk-debug"? If you can send us the APK we can add a profiled version of the AIR runtime and see what's happening: from the description, there may be a GPU error that's then causing this side-effect.

FYI filters aren't supported in GPU rendering mode so please check whether your app descriptor is using renderMode of "gpu"; also it may be worth changing the `android:hardwareAccelerated` setting in your `manifestAdditions`..


thanks

  Andrew

**Comment by apofis1969** [comment]
@ajwfrost Hi, the rendering mode is GPU because of a better result at the video live streaming. The Android Tablet works better as basic Station. HardwareAccelerated is set true.
The most easiest thing is to make a debug version of my app and send it to you. Are only a few clicks to move back to the IconItemRenderer. If this is ok for you?

**Comment by ajwfrost** [comment]
@apofis1969 that would be fine, yes, I would hope we can ensure that the lack of support for the filter doesn't mean that the element itself disappears..

There are a few issues it seems with some of these LG devices..

**Comment by FliplineStudios** [comment]
Since you mention GPU mode, I wonder if this is related to the cacheAsBitmap issue we're seeing in #103 on certain Android devices, since applying a drop shadow filter does automatically set cacheAsBitmap to true.  I just looked through our app reviews where users have commented about clips with cacheAsBitmap either getting scrambled or being invisible, and I do see a review for a user with an LG K7 where it sounds like some graphics are disappearing for them (I don't see any reviews for anyone using an LG K52 though).  We're also using GPU rendering mode in our apps where this is happening.

**Comment by apofis1969** [comment]
@ajwfrost please send me a link where I can send the debug version. This happens since SDK 33.1.1.259 that the dropshadow is not working anymore. So no idea since when the iconitemrenderer is not working on some android devices.

**Comment by ajwfrost** [comment]
@apofis1969 please use the below link to upload this.
https://transfer.harman.com/requests/mmcOH5qeCIxSq3dntmy3GH
Is it fully reproducible on these devices?

@FliplineStudios  I also wondered if it was linked; the filter shouldn't ever work but taking out the parent element just on these devices implies there is some difference in the OpenGL implementation, so maybe some error handling here would also change things for your issue with cacheAsBitmap..

thanks
