### ISSUE TITLE
load an URI scheme on Android

### ISSUE THREAD

**Issue by pol2095** [airsdk/Adobe-Runtime-Support#759]
## Problem Description

load an URI scheme on Android.

* AIR SDK 33.1
* Air for Android

## Steps to Reproduce

```
package
{
	import flash.display.Sprite;
	import flash.events.Event;
	import flash.events.IOErrorEvent;
	import flash.media.Sound;
	import flash.net.URLRequest;
	
	public class Main extends Sprite
	{
		public function Main()
		{		
			var uri:String = "content://com.android.externalstorage.documents/document/primary%3AMusic%2Fmysound.mp3";
			var sound:Sound = new Sound();
			sound.addEventListener(Event.COMPLETE, onSoundLoaded);
			sound.addEventListener(IOErrorEvent.IO_ERROR, onSoundLoadError);
			sound.load( new URLRequest( uri ) );
		}
		
		private function onSoundLoaded(event:Event):void
		{
			var sound:Sound = event.target as Sound;
			sound.play();
		}
		
		private function onSoundLoadError(event:IOErrorEvent):void
		{
			trace(event.text);
		}
	}
}
```

it's impossible to load a mp3 file using an URI scheme "content://..." on Android
I have this error : `Error #2032: Stream Error. URL: content://com.android.externalstorage.documents/document/primary%3AMusic%2Fmysound.mp3`

I can get the file path using an ANE but Uri can lacks file scheme

## Known Workarounds

no workaround

**Comment by balaedit** [comment]
Which ANE you are using to get file path, especially external sd card location.

**Comment by pol2095** [comment]
I use a custom [ANE](http://pol2095.free.fr/Android-Storage-Access-Framework/) that I created to use the Storage Access Framework
