### ISSUE TITLE
Windows Cef - Critical error detected c0000374

### ISSUE THREAD

**Issue by RayGyoe** [airsdk/Adobe-Runtime-Support#782]
AIR 33.1/29 Create multiple windows, memory 0xc0000374 appears。

Please investigate the problem：

<img width="546" alt="微信图片_20210411222029" src="https://user-images.githubusercontent.com/336440/114308033-01198400-9b15-11eb-99df-7ec70629f6ee.png">
<img width="672" alt="微信图片_20210411222043" src="https://user-images.githubusercontent.com/336440/114308036-05de3800-9b15-11eb-8176-1171e25948fe.png">

Test Demo：
1. Single process click go to create multiple browsers without problems
2. Click add window to create it again

download:https://vsdevelop.com/wp-content/uploads/2021/04/examplebundle1.0.zip

**Comment by ajwfrost** [comment]
Has this bundle zip got all the necessary files? We're getting some output:
```
[0413/073715:ERROR:main_delegate.cc(734)] Could not load cef_100_percent.pak
[0413/073715:ERROR:main_delegate.cc(743)] Could not load cef_200_percent.pak
[0413/073715:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
```
and can't see those files in there..

Given how this appears to be working though, are you able to check whether the calls to the extension context are returning properly? If it's hanging/crashing then it may be happening within an extension DLL..

**Comment by RayGyoe** [comment]
another extension has the same error, but works on air29

[https://github.com/RayGyoe/ANEWinWebView](url)

air30-33 the same mistake

**Comment by RayGyoe** [comment]
AIR29：[https://vsdevelop.com/wp-content/uploads/2021/04/air29.zip](url)

AIR33：[https://vsdevelop.com/wp-content/uploads/2021/04/air33.zip](url)

**Comment by RayGyoe** [comment]
> 此捆绑包zip是否已获取所有必需的文件？我们得到一些输出：
> 
> ```
> [0413/073715:ERROR:main_delegate.cc(734)] Could not load cef_100_percent.pak
> [0413/073715:ERROR:main_delegate.cc(743)] Could not load cef_200_percent.pak
> [0413/073715:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
> ```
> 
> 并且在那里看不到那些文件。
> 
> 鉴于这看起来是如何工作的，您是否能够检查对扩展上下文的调用是否正确返回？如果它挂起/崩溃，则可能是在扩展DLL中发生的。



> Has this bundle zip got all the necessary files? We're getting some output:
> 
> ```
> [0413/073715:ERROR:main_delegate.cc(734)] Could not load cef_100_percent.pak
> [0413/073715:ERROR:main_delegate.cc(743)] Could not load cef_200_percent.pak
> [0413/073715:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
> ```
> 
> and can't see those files in there..
> 
> Given how this appears to be working though, are you able to check whether the calls to the extension context are returning properly? If it's hanging/crashing then it may be happening within an extension DLL..

please test the attachment provided

**Comment by RayGyoe** [comment]
`window = ::FindWindow(NULL, result);`
change to fix crash
`window = FindWindow(NULL, result);`
