### ISSUE TITLE
AIR SDK 33.1.1.476: Building a 'bundle' on Windows - Packager internal error.

### ISSUE THREAD

**Issue by ajwfrost** [airsdk/Adobe-Runtime-Support#817]
AIR SDK 33.1.1.476
Building on Windows desktop, using -target bundle
```
*** ADT Logging at 2021/04/28 12:38:28 ***
Called by: I:\SDKs\33.1.1.476\lib\adt.jar
ADT called with: -package -storetype pkcs12 -keystore xx.p12 -target bundle TestApp application.xml AIRInfo.swf -C ..\..\utils\assets .
Invalid input: Packaging failed. Packager internal error
```

As found on #779  - creating a new issue to track this one

**Comment by TheUsual251** [comment]
I can confirm. 33.1.1.444 works though.

**Comment by ajwfrost** [comment]
Okay we've found the problem - not code-signing, but certificate-related. We're creating a patch for this...

**Comment by MobiliteDev** [comment]
I have the same problem, any news of the patch ?

**Comment by ajwfrost** [comment]
We updated it at the end of last week, overwriting the earlier/invalid 33.1.1.476 build .. so if you re-download the same zip file, you should get the patched SDK.
thanks

**Comment by MobiliteDev** [comment]
ok, it's good with overwriting 33.1.1.476.
Thank you

**Comment by micha01** [comment]
Hi, now publishing out of ANIMATE works fine. Thank you very much.

**Comment by itlancer** [comment]
@ajwfrost, latest 33.1.1.476 after "redownloading" fixed version works fine.
This issue should be closed.

**Comment by ajwfrost** [comment]
Great, thanks for confirming
