### ISSUE TITLE
URLLoader does not work AIR 33.1.1.476

### ISSUE THREAD

**Issue by GemeXP** [airsdk/Adobe-Runtime-Support#850]
- AIR 33.1.1.476 (444 too)
- intellij idea Windows 7 x64
- target iOS

after build with these SDK URLLoader stops working and gives an error
Error # 2032: Stream Error.

we also cannot roll back the SDK, since we use ANE from the district for Facebook and in version 33.1.1.406 it does not sign correctly

**Comment by ajwfrost** [comment]
Is this something you're seeing on-device, after packaging with this SDK on Windows?  could you please confirm the handset type/iOS version, and also is the URL http or https etc?

thanks

**Comment by GemeXP** [comment]
Apple iPad 10.2 (2020) 14.5.1

URL example
http://static.pf.gamexpconnect.com/freedom/data/version.txt

**Comment by dgurney75** [comment]
I am seeing this as well for iPhone 14.5.1 using AIR 33.1.1.476.

**Comment by marchbold** [comment]
http traffic is blocked by default on iOS. Have you set the appropriate exceptions in your info additions?

**Comment by GemeXP** [comment]
> http traffic is blocked by default on iOS. Have you set the appropriate exceptions in your info additions?
Thank you! Apparently, when switching to new libraries from the distriqt and the new AIR SDK, these lines were missed.
<key>NSAllowsArbitraryLoads</key>
<true />

**Comment by marchbold** [comment]
Glad that resolved it for you!
