### ISSUE TITLE
AirSDK not working properly with Adobe XMP Core 6.0

### ISSUE THREAD

**Issue by maxpropp** [airsdk/Adobe-Runtime-Support#857]
## Problem Description

Describe your problem in detail. Include the following information:

I've been testing with many videos, and this is what I am suspecting the issue is. This is the only difference I've found. I've also exported a working video (that was exported originally with adobe XMP Core 5.7) , and this time exported it with Adobe XMP Core 6.0 and it stopped working.

* Which AIR SDK did you use? 33.1.1.444, also tried with other 33.1 versions.
* Describe the affected environment: Windows mainly, though IOS also has crashes but at least it start reproducing the video.
* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
* If applicable, link to the Starling/Feathers issues that brought you here.

Furthermore, **always** add a link to one or more analog [Adobe Tracker](https://tracker.adobe.com) issues. This repository is not a replacement for Adobe's bug tracker!

## Steps to Reproduce

Tell us how this issue can be reproduced. Seriously: if you want this issue to be fixed, this is the part you **really** need to get nailed.

Export any video using Adobe XMP Core 6.0. This video will not work with Air SDK

## Known Workarounds

Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

Encoding video with another encoder such as Handbrake will solve this issue. But would make adobe useless. Unless you want to use adobe to edit the video, export it, and import it in handbrake and export it from there.

These are some samples of one non-working video encoded with adobe, and a working video encoded with handbrake. 

adobe premiere 2021
https://drive.google.com/file/d/1dGGwoESVeQXkcfzmmDdl0D40ckI3m4de/view?usp=sharing

handbrake: 
https://drive.google.com/file/d/1-GI6kLAeCguN4LxG2NexPfUOoKHnAjlD/view?usp=sharing

**Comment by ajwfrost** [comment]
Thanks for this - we can reproduce that here so will check why this isn't playing.. it looked like the first frame was displayed which implies the decoder is working okay, potentially it's an audio issue then (although the codec information looks identical..)

**Comment by ajwfrost** [comment]
... actually nothing to do with audio, the issue was that the first frame that Windows can decode is set up with a timestamp of 40ms. The stream was expecting an initial timestamp of 0 in order to kick the pipeline into action... so this we can cope with and it will be fixed in the next release. Thanks for the sample video!

**Comment by ajwfrost** [comment]
Should be fixed in 33.1.1.533, please check and re-open if necessary.
Thanks
