### ISSUE TITLE
[macOS] Capabilities.cpuArchitecture returns x86 instead of ARM for Apple Silicon M1 CPUs devices

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#859]
## Problem Description
`Capabilities.cpuArchitecture` returns x86 instead of ARM for Apple Silicon M1 CPUs devices with macOS.
It has been tested with different macOS Big Sur Apple Silicon M1 CPUs devices with latest AIR 33.1.1.476.
The same problem in all cases.

Related issue (not the same): https://github.com/airsdk/Adobe-Runtime-Support/issues/843

## Steps to Reproduce
Compile and try to launch code below for any macOS device with Apple Silicon M1 CPU.
`trace(Capabilities.cpuArchitecture);`

**Actual Result:**
`Capabilities.cpuArchitecture` returns x86.

**Expected Result:**
`Capabilities.cpuArchitecture` returns ARM.

## Known Workarounds
Write native extension to detect real CPU architecture using guide https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by ajwfrost** [comment]
Curiously, on an x86_64 based CPU, it's still returning x86 and saying that it supports 32-bit processes..
These need updating, pretty trivial changes...
Thanks for drawing them to our attention!

**Comment by ajwfrost** [comment]
Should be fixed in 33.1.1.533, please check and re-open if necessary.
Thanks
