### ISSUE TITLE
Not compiling for windows

### ISSUE THREAD

**Issue by maxpropp** [airsdk/Adobe-Runtime-Support#864]
## Problem Description

Describe your problem in detail. Include the following information:

I am using Air SDK 33.1.1.476.
The problems happens when I am trying to compile for windows, but not for ios.
this is the screenshot of the message I get 
https://drive.google.com/file/d/1D6ar6tFGZxQoxjiODktdp-Uzknk_Haec/view?usp=sharing

If i click for more details, this is what I get
C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.4\jbr\bin\java.exe -Dapplication.home=C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK_33_1_1_476
 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -jar C:\Program Files\Adobe\Adobe Flash Builder 4.7 
 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK_33_1_1_476\lib\adt.jar -package -storetype PKCS12 -keystore 

Not sure what else to offer.
Though I can say that I am using captive runtime bundle. And all the settings have not changed. If I change it back to version 444, it will work.

## Known Workarounds

None. I just use Air SDK 33.1.1.444

**Comment by ajwfrost** [comment]
@maxpropp thanks: this sounds very much like the issue in Flash Builder where it doesn't cope with sorting the sections from the airglobal.swc library. 

You may be able to use the latest SDK if you pull the airglobal.swc file from the older one, see the SDK's `frameworks\libs\air` folder. We're trying to work out how we can do some checks and post-processing on this library to ensure that it doesn't cause the problem (which seems simpler than trying to patch Flash Builder...)

thanks

**Comment by maxpropp** [comment]
> @maxpropp thanks: this sounds very much like the issue in Flash Builder where it doesn't cope with sorting the sections from the airglobal.swc library.
> 
> You may be able to use the latest SDK if you pull the airglobal.swc file from the older one, see the SDK's `frameworks\libs\air` folder. We're trying to work out how we can do some checks and post-processing on this library to ensure that it doesn't cause the problem (which seems simpler than trying to patch Flash Builder...)
> 
> thanks

Hi! Already tried that, it's not working though.

**Comment by ajwfrost** [comment]
Ah - @maxpropp  sorry I've just realised what it may be .. did you download the SDK fairly early after it was released? as we found and fixed a problem that had the same "Packager internal error" output, and just re-uploaded a patched SDK with the same release number: see #817 

So it might be that you need to re-download the SDK and it will fix this one..

**Comment by maxpropp** [comment]
> Ah - @maxpropp sorry I've just realised what it may be .. did you download the SDK fairly early after it was released? as we found and fixed a problem that had the same "Packager internal error" output, and just re-uploaded a patched SDK with the same release number: see #817
> 
> So it might be that you need to re-download the SDK and it will fix this one..

yes, this fixed it. Thanks.
