### ISSUE TITLE
Multiple language support NSUserTrackingUsageDescription 

### ISSUE THREAD

**Issue by qq5000521** [airsdk/Adobe-Runtime-Support#865]
On access to IOS 14.5 later IDFA apple new NSUserTrackingUsageDescription multilingual configuration, AIRSDK will support?

```
<key>NSUserTrackingUsageDescription</key>
<string>APP Related support</string>
```

**Comment by itlancer** [comment]
May be using purposeStings.xml support it
https://forum.starling-framework.org/d/20839-localization-of-purpose-strings-with-purposestringsxml/2
Didn't tried this yet.
