### ISSUE TITLE
Incorrect value returned from stage.fullScreenWidth / Capabilities.screenResolutionX and stage.fullScreenHeight / Capabilities.screenResolutionX for iPhone XR

### ISSUE THREAD

**Issue by gnicox** [airsdk/Adobe-Runtime-Support#878]
AIR SDK 33.1.1.476

For iPhone XR (iOS Version 14.5.1)  return 750x1624 instead of 828x1792

**Comment by marchbold** [comment]
Have you provided a launch screen etc to ensure the stage is correctly setup?

**Comment by gnicox** [comment]
Hi @marchbold, thank you for your reply.

Yes, I provided a launch screen. Launch screen works by a LaunchScreen.storyboardc and Assets.car both generated by Xcode.

The license is valid until 12/31/2021.

With AIR 33.1.1.345 the launch screen worked good, as well as its values. Now I can't use it anymore for certificate problems.

With iPhone 6 no problem.

I also tried as you suggest in https://github.com/airsdk/Adobe-Runtime-Support/issues/869 and now the screen values are always wrong and also the launch image is smaller than the display. 

(see Attachement)

When I use iOS sdk included in AIR the launch image cover all display, I can see it correct only the values are wrong.


Considering that you tell me about the launch screen, I am updating Xcode and will try to regenerate the LaunchScreen.storyboardc and Assets.car with this latest version.

I'll let you know.

**Comment by ajwfrost** [comment]
We're looking into an issue that may be related to this, where the display of the launch screen is changing some of the values that had been set up and are then read back to provide the screen resolution values. So if you can provide some details of what you're seeing - resolution and stage size values etc - it could with the diagnostics here.. 

A bit of a puzzle if you're saying there's a difference between 33.1.1.345 and the latest build though, nothing was changed around here...

thanks

**Comment by gnicox** [comment]
Hi @marchbold, I just tried to regenerate  LaunchScreen.storyboardc,  as well as mentioned in my previous reply, with the latest Xcode but nothing....

**Comment by gnicox** [comment]
Hi @ajwfrost, thank you. 

Thinking about it with 33.1.1.345  I'm sure the launch screen covered all XR display but I don't sure the value returned from stage.fullScreenWidth was correct. It is possible was a previous version. I worked to the function that use those value several months ago. 

In these days we were doing the last tests first of publish the game  and I noted it because in the game some labels in the help section was positioned wrong. That labels positioning depends from that values (XR has notch and in the application is considered a high display).

Tomorrow I'll try to give you some more details. Thanks

**Comment by gnicox** [comment]
Hi @ajwfrost, as agreed I'll try to give you more details,  I'll also try to summarise to avoid misunderstandings

Several months ago I decided to use a new class property to distinguish between different sized displays. At that time the values returned by 'stage.fullScreenWidth / Hight' were correct. I had done a unit test and tried the iPhone XR I'm having the problem with but with another version of iOS.

For my part I report the method where I put the breakpoint to read the values (see first comment).

`private function useStage (e:flash.events.Event):void
        {
            if (stage)
            {
                removeEventListener(flash.events.Event.ENTER_FRAME, useStage);

                stage.scaleMode = StageScaleMode.NO_SCALE;
                stage.align = StageAlign.TOP_LEFT;

	      // HERE BREAKPOINT 
                screenWidth = stage.fullScreenWidth;
                screenHeight = stage.fullScreenHeight;

                _viewPort = new Rectangle(0, 0, screenWidth, screenHeight);

                calcualateScaleFactor();

                if (isIOS)
                {
                    setIosPngPrefix();
                }
                else
                {
                    pngPrefix = 'screen@android-';
                }

                loadImage();

                if (isIOS)
                {
                    loadImagesForClip(counter);
                }
            }
        }`

--------------------------------------------------------------------------------------------------------

iPhone 6 (iOS 12.x.x)  these the values I can read into debugger

--------------------------------------------------------------------------------------------------------

align = "TL"
allowsFullScreen = true
allowsFullScreenInteractive = false
autoOrients = false
browserZoomFactor = 1 (0x1)
color = 4281357962 (0xff30568a)
colorCorrection = null
colorCorrectionSupport = "notSupported"
constructor = null
contentsScaleFactor = 1 (0x1)
deviceOrientation = "unknown"
displayContextInfo = null
displayState = "fullScreenInteractive"
focus = null
frameRate = 30 (0x1e)
fullScreenHeight = 1334 (0x536)
fullScreenSourceRect = null
fullScreenWidth = 750 (0x2ee)
height = 240 (0xf0)
mouseChildren = true
mouseLock = false
nativeWindow = null
numChildren = 1 (0x1)
orientation = "default"
quality = "MEDIUM"
scaleMode = "noScale"
showDefaultContextMenu = true
softKeyboardRect = {flash.geom::Rectangle} [4383876417]
stage3Ds = {Vector.<flash.display::Stage3D>} fixed = false, size = 1
stageFocusRect = true
stageHeight = 1334 (0x536)
stageVideos = {Vector.<flash.media::StageVideo>} fixed = false, size = 1
stageWidth = 750 (0x2ee)
supportedOrientations = {Vector.<String>} fixed = false, size = 4
tabChildren = true
textSnapshot = <Error: Error #2071: The Stage class does not implement this property or method.>
vsyncEnabled = true
width = 320 (0x140)
wmodeGPU = false


--------------------------------------------------------------------------------------------------------

iPhone  XR (iOS Version 14.5.1)     ***return 750x1624 instead of 828x1792 

these the values I can read into debugger

--------------------------------------------------------------------------------------------------------

align = "TL"
allowsFullScreen = true
allowsFullScreenInteractive = false
autoOrients = false
browserZoomFactor = 1 (0x1)
color = 4281357962 (0xff30568a)
colorCorrection = null
colorCorrectionSupport = "notSupported"
constructor = null
contentsScaleFactor = 1 (0x1)
deviceOrientation = "unknown"
displayContextInfo = null
displayState = "fullScreenInteractive"
focus = null
frameRate = 30 (0x1e)
fullScreenHeight = 1624 (0x658)
fullScreenSourceRect = null
fullScreenWidth = 750 (0x2ee)
height = 0 (0x0)
mouseChildren = true
mouseLock = false
nativeWindow = null
numChildren = 1 (0x1)
orientation = "default"
quality = "MEDIUM"
scaleMode = "noScale"
showDefaultContextMenu = true
softKeyboardRect = {flash.geom::Rectangle} [4453338369]
stage3Ds = {Vector.<flash.display::Stage3D>} fixed = false, size = 1
stageFocusRect = true
stageHeight = 1624 (0x658)
stageVideos = {Vector.<flash.media::StageVideo>} fixed = false, size = 1
stageWidth = 750 (0x2ee)
supportedOrientations = {Vector.<String>} fixed = false, size = 4
tabChildren = true
textSnapshot = <Error: Error #2071: The Stage class does not implement this property or method.>
vsyncEnabled = true
width = 320 (0x140)
wmodeGPU = false


--------------------------------------------------------------------------------------------------------

iPad 10.5 - 14.5.1

these the values I can read into debugger

--------------------------------------------------------------------------------------------------------


align = "TL"
allowsFullScreen = true
allowsFullScreenInteractive = false
autoOrients = false
browserZoomFactor = 1 (0x1)
color = 4281357962 (0xff30568a)
colorCorrection = null
colorCorrectionSupport = "notSupported"
constructor = null
contentsScaleFactor = 1 (0x1)
deviceOrientation = "unknown"
displayContextInfo = null
displayState = "fullScreenInteractive"
focus = null
frameRate = 30 (0x1e)
fullScreenHeight = 2224 (0x8b0)
fullScreenSourceRect = null
fullScreenWidth = 1668 (0x684)
height = 0 (0x0)
mouseChildren = true
mouseLock = false
nativeWindow = null
numChildren = 1 (0x1)
orientation = "default"
quality = "MEDIUM"
scaleMode = "noScale"
showDefaultContextMenu = true
softKeyboardRect = {flash.geom::Rectangle} [4356465985]
stage3Ds = {Vector.<flash.display::Stage3D>} fixed = false, size = 1
stageFocusRect = true
stageHeight = 2224 (0x8b0)
stageVideos = {Vector.<flash.media::StageVideo>} fixed = false, size = 1
stageWidth = 1668 (0x684)
supportedOrientations = {Vector.<String>} fixed = false, size = 4
tabChildren = true
textSnapshot = <Error: Error #2071: The Stage class does not implement this property or method.>
vsyncEnabled = true
width = 320 (0x140)
wmodeGPU = false


------------------------------------------------------


The above method does its job before the Starling instance is created and when the flash stage is available. It is the first method executed on my side after the class constructor that I report you here below


`public function GinBob ():void
        {

            isIOS = Capabilities.manufacturer.indexOf("iOS") >= 0;
            isAndroid = Capabilities.manufacturer.indexOf("Android") >= 0;
            isMacOs = Capabilities.manufacturer.indexOf("Macintosh") >= 0;

            loadingImage = new Loader();
            loadingImage.contentLoaderInfo.addEventListener(flash.events.Event.COMPLETE, setLoadingImage);

            addEventListener(flash.events.Event.ENTER_FRAME, useStage);

            Core.coreDispatcher.addEventListener("addPauseResumeCheck", addPauseResumeListeners)

            if (isIOS)
            {
                bytesForClip = new ByteArray();
                streamForClip = new FileStream();

                counter = 0;

                sun = new Vector.<Loader>()

                sun[counter] = new Loader()
                sun[counter].contentLoaderInfo.addEventListener(flash.events.Event.COMPLETE, addImages);
            }
        }`

Note that

If I make the ipa with the iOS SDK packaged with AIR SDK 33.1.1.476 I get for XR wrong values and a launch screen image in full screen correct

If I make the ipa with the iOS SDK 14  external to  AIR SDK 33.1.1.476 I get for XR wrong values and a launch screen smaller than the display, like you can see in the attachment of a previous post.

Let me know If I can do other.

**Comment by ajwfrost** [comment]
Hi @gnicox  - we've been looking into this, but aren't seeing any problems with the resolution/fullscreenWidth and Height values, when using an XR - as long as we have a launch storyboard. Are you using the "noScale" mode, and listening out for "resize" events, before using the final values for these?

**Comment by gnicox** [comment]
Hi ajwfrost, , after you told me you hadn't encountered any resolution problems with size for XR I did some research and I found the origin of the problem.

In the XR we use as test device the  'Display Zoom' was enabled in the settings from someone. After I set it to 'Standard' the resolution/fullscreenWidth and Height values are read correctly.

Thanks
