### ISSUE TITLE
AIR 33.1.1.476. android armv8. IOErrorEvent errorID=2032 when request https

### ISSUE THREAD

**Issue by balaedit** [airsdk/Adobe-Runtime-Support#880]
Dear Sir,
I am still facing this issue in my new release.

I am using Animate CC 2021 and **Adobe Air SDK 33.1.1.476**

**While publishing my app using ARMv7 (32 bit), it's working fine in debugging (testing) and release version.**

![WhatsApp Image 2021-05-31 at 12 39 47 AM](https://user-images.githubusercontent.com/37571867/120117718-2d17c400-c1ac-11eb-9772-9b8d538991d0.jpeg)

**But when publishing my app using ARMv8 (64 bit), it's working fine in debugging (testing) but getting 2032 error in release version.**

![WhatsApp Image 2021-05-31 at 12 40 31 AM](https://user-images.githubusercontent.com/37571867/120117733-3e60d080-c1ac-11eb-8617-b0e1dda6953c.jpeg)

**Since, playstore didn't publish app without 64bit. Reason : This release is not compliant with the Google Play 64-bit requirement.

I am stuck.** Should I use the older version i.e. AIR SDK 33.1.1.345 which was working fine in all release.

OLD LINK ISSUE : https://github.com/airsdk/Adobe-Runtime-Support/issues/758#issue-846314030

**Comment by marchbold** [comment]
Can you show any code to reproduce this issue?

**Comment by ajwfrost** [comment]
I'm wondering whether it's not properly updated via Animate, sometimes we've seen this where an SDK has been updated but Animate was either still pointing to an older SDK, or had locked a file that wasn't then updated. Could you add the debug output to your pop-up to include `flash.system.Capabilities.version`?
