### ISSUE TITLE
Air 33.1.1.406/476 produces IPAs built with iOS SDK 13.2, but should be 14.1?

### ISSUE THREAD

**Issue by ChacHauLam** [airsdk/Adobe-Runtime-Support#888]
When I build an IPA in Windows using Flash Develop using Air 33.1.1.406, I can't submit to Apple as I get the error:

_ITMS-90725: SDK Version Issue - This app was built with the iOS 13.2 SDK. All iOS apps submitted to the App Store must be built with the iOS 14 SDK or later, included in Xcode 12 or later._

I can see in the Air Release notes that Air 33.1.1.406 is built with iOS SDK 14.1. But when I inspect the IPA on a Mac, I can confirm that its seems the IPA is built with iOS SDK 13.2.

I have tried:
- building with Air 33.1.1.476
- replaced all my ANEs (Distriqt) with the latest versions
- using the latest version of Starling.swc (2.6)
- regenerated a new Assets.car
- checked the manifest.xml

I must be missing something?

**Comment by ChacHauLam** [comment]
On a Mac I unzip the IPA and then:
otool -l Payload/APPNAME.app/APPNAME | fgrep --after-context=3 LC_VERSION_MIN_IPHONEOS

I've just opened the info.plist and it looks like the same details:
**<string>com.apple.compilers.llvm.clang.1_0</string>
        <key>DTPlatformBuild</key>
        <string>17B102</string>
        <key>DTSDKBuild</key>
        <string>17B102</string>
        <key>DTPlatformName</key>
        <string>iphoneos</string>
        <key>DTSDKName</key>
        <string>iphoneos13.2</string>
        <key>DTPlatformVersion</key>
        <string>13.2</string>
        <key>DTXcode</key>
        <string>1121</string>
        <key>DTXcodeBuild</key>
        <string>11B500</string>
        <key>LSRequiresIPhoneOS</key>
        <true/>
        <key>MinimumOSVersion</key>
        <string>9.0</string>**

**Comment by ChacHauLam** [comment]
Ah ha! I think you're onto something! I can see its returning "33.1.1.217" which was an older version of Air I had used previously, but not sure where I need to change this:

**echo %PATH%**
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;%JAVA_HOME%\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\chaca\AppData\Local\Microsoft\WindowsApps;C:\Users\chaca\AppData\Roaming\npm;C:\Users\chaca\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\chaca\AppData\Local\Yarn\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\chaca\.dotnet\tools;C:\Program Files (x86)\FlashDevelop\Tools\AppMan;C:\Program Files (x86)\FlashDevelop;C:\Users\chaca\AppData\Local\FlashDevelop\Apps\flexairsdk\4.6.0+33.1.1.217\bin;C:\Program Files (x86)\FlashDevelop\Tools\android\platform-tools;C:\Python27\

**call adt -version**
33.1.1.217

**Comment by ajwfrost** [comment]
When I look at the batch files that FlashDevelop uses, there's a "SetupSDK.bat" one that either has a hard-coded value in it, or it uses a setting `%FD_CUR_SDK%`. But either way, it would set up the path with:
```
set PATH=%FLEX_SDK%\bin;%PATH%
```
But from your path it doesn't seem like this is working!
So I would suggest just adding some `echo` outputs into the PackageApp.bat file (and double-checking: you're running this, rather than Packager.bat?) and checking that this does call SetupSDK.bat, then more echo output in there to see what it's doing...

thanks

**Comment by ChacHauLam** [comment]
Thank you so much! 

Embarrassingly, I had not updated the SetupSDK.bat to point to 33.1.1.406 folder, it was still pointing to 33.1.1.217. I do usually do this but just missed it this time!

I had only changed in: project > properties > sdk

Thanks again, the support is fantastic as always!!!

**Comment by ajwfrost** [comment]
Great .. it still makes me think we need more/better diagnostics for these sorts of things...
I trust with the settings updated properly, it will report the IPA correctly now!!

**Comment by ChacHauLam** [comment]
Yes, I can confirm that both otool and the info.plist now displays 14.1
