### ISSUE TITLE
Air 33.1.1.476: "Сould not create a temporary .itmsp package for the app" when adding to Apple's Transporter

### ISSUE THREAD

**Issue by sjabberwocky** [airsdk/Adobe-Runtime-Support#891]
Hi!

We have the game which we update frequently on Android and it works fine on Air 33.1.1.476.
This week we are trying to update our game on iOS and something goes terribly wrong.

Flash Builder generate ipa file on Windows fine, but we can not add it to Transporter due "Сould not create a temporary .itmsp package for the app. Look-up application information from the web service failed" error.

Firstly I cut all ANEs from the project (they are all up-to-date, but who knows what is broken?).
It does not help.

Then I created new iOS project with assets.car and LaunchScreen storyboard set the same ids and signed it with the same certificates. And it worked. It went to TestFlight without an issue and work fine on my devices.

Then I added game code without ANEs and this error come back!
![error](http://dl3.joxi.net/drive/2021/06/04/0004/1311/288031/31/e5c3c02bf3.jpg)

Our latest update on iOS was about year ago with AIR 33.1.1.98, but it is too outdated nowadays.

It would be nice to find and fix this critical issue.

**Comment by ajwfrost** [comment]
Hi
Just wondering whether this could be similar to #850  -> are you trying to look something up from an http service?
thanks

**Comment by sjabberwocky** [comment]
#850 is not related, we open some web pages only by user action, like pressing on Privacy Policy button.
Our projects use only Starling and Feathers + distriqt anes + gameanalytics ane.
And this issue here even without ANEs.

Maybe there is some problem with code signing?

**Comment by ajwfrost** [comment]
So in terms of the bit that worked:
> Then I created new iOS project with assets.car and LaunchScreen storyboard set the same ids and signed it with the same certificates. And it worked. It went to TestFlight without an issue and work fine on my devices.

Was this an AIR application as well? or do you mean the new iOS project was just created by Xcode?

If you have an IPA that works vs an IPA that doesn't work, then yes it may be to do with code-signing.. we could take a look at the differences between them perhaps; also, have you tried re-signing the IPA prior to uploading?

thanks

**Comment by sjabberwocky** [comment]
I found what is happening.
Previously we used `res` folder for our assets, last year you reserved it for Android custom resources and we renamed it to `resources`.
Testing and googling I explore that in iOS build your can not have your own `resources` folder cause it reserved in xCode or something.
I renamed this folder and Transporter start to accept our build.

**Comment by ajwfrost** [comment]
Thanks - well found! Maybe we need to send out a warning if there's a `resources` folder then...

**Comment by sjabberwocky** [comment]
> Maybe we need to send out a warning if there's a resources folder then...
@ajwfrost 
It would be nice, it was really hard to find source of this issue.

**Comment by ajwfrost** [comment]
Just fyi, we've added a warning output if you have a folder called "resources" added to the root of an IPA now...

**Comment by sjabberwocky** [comment]
Great, thank you!
