### ISSUE TITLE
[Feature Request] 256x256 icon support for associated file types

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#907]
## Description

Large (256 * 256 pixels) icons support for associated file types essential for modern OS versions.
Right now AIR support only 128*128 pixels as maximum: https://help.adobe.com/en_US/air/build/WSfffb011ac560372f2fea1812938a6e463-8000.html#WSfffb011ac560372f2fea1812938a6e463-7fdd

Earlier similar already done with latest AIR versions for application icon:
https://github.com/airsdk/Adobe-Runtime-Support/issues/462
https://github.com/airsdk/Adobe-Runtime-Support/issues/475

**Comment by itlancer** [comment]
Trying to add 
`<image256x256>icons/256.png</image256x256>`
to `fileType` section cause packaging error:
`error 103: application.fileTypes.fileType.icon.image256x256 is an unexpected element/attribute`
Tested with latest AIR SDK 50.2.4.5

**Comment by ajwfrost** [comment]
It looks like the "create icon file" code already supports 256 (the same code is used for the application icon) so this is just about the validator in ADT... will check this, it should be simple..!

**Comment by itlancer** [comment]
Now it supported. Tested with latest AIR 51.0.1.5.
Thanks!
