### ISSUE TITLE
Can't debug on air simulator with 33.1.1.533_BETA

### ISSUE THREAD

**Issue by jimmymjing** [airsdk/Adobe-Runtime-Support#917]
I couldn't debug the app in AIR simulator on Windows after upgrading to 33.1.1.533_BETA. My IDE is Flash Builder 4.7.
I keep getting invalid profile specified 'Profile not supported' message, but I have set this value in the descriptor as recommended. 

I also tried to remove this value from Customize Launch panel. But then I'm getting the message 'Not supported native extensions profile'.

Here's the command with params:
"C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\bin\adl.exe" -runtime "C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\runtimes\air\win" -screensize 640x1116:640x1136 -XscreenDPI 326 -XversionPlatform IOS -extdir "C:\Users\Jimmy\Adobe Flash Builder 4.7\.metadata\.plugins\com.adobe.flexbuilder.project.ui\ANEFiles\Bf\win32\" "G:\Bf 15\Bf\bin-debug\Bf-app.xml" "G:\Bf 15\Bf\bin-debug" 

p.s. I don't have this issue with all previous released AIR SDKs.

**Comment by ajwfrost** [comment]
That's curious - there shouldn't really have been anything that changed in that area of the code!
What's in the descriptor file? I think ADL on Windows just looks at the first entry, so that should be `extendedDesktop`.

I also recollect that we've had to use ADL with `-profile extendedDesktop` on the command line to get things to work, but that was with an older SDK. We can look to see whether there's any change here. I would have thought the inclusion of `-extdir` - or just the fact that the XML file has got extensions mentioned - would push ADL into the extended desktop mode...

**Comment by leossmith** [comment]
I am getting the same behavior with intellij. I tried adding extendedDesktop in profile but didnt make any difference

`<supportedProfiles>mobileDevice extendedDesktop extendedMobileDevice</supportedProfiles>`

**Comment by ajwfrost** [comment]
Could you try:
```
<supportedProfiles>extendedDesktop mobileDevice extendedMobileDevice</supportedProfiles>
```
If that doesn't work, then if you're able to update your ADL command line to include the `-profile extendedDesktop` it may help..

thanks

**Comment by leossmith** [comment]
Doesn't seem to work. with the supportedProfiles. I get the following:

```
`"C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3\jbr\bin\java.exe" -Dapplication.home=I:\Development\flex-sdks\4161_331 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx4048m -classpath I:/Development/flex-sdks/4161_331/lib/fdb.jar flex.tools.debugger.cli.DebugCLI -ide
Apache fdb (Flash Player Debugger) [build 20171115]
Copyright 2017 The Apache Software Foundation. All rights reserved.
Waiting for Player to connect
I:\Development\flex-sdks\4161_331\bin\adl.exe -profile extendedMobileDevice -screensize 375x815:375x815 -XscreenDPI 160 -XversionPlatform AND -extdir C:\Users\leo_s\AppData\Local\Temp\IntelliJ_ANE_unzipped E:\Development\Bitbucket\trekrecord-flex\bin-debug\Main-app.xml E:\Development\Bitbucket\trekrecord-flex\bin-debug
[AIR Debug Launcher]: invalid profile specified 'Profile not supported'
[AIR Debug Launcher]: Process finished with exit code 10`
```

Can i somehow update the adl command in intellij?

**Comment by ajwfrost** [comment]
Ah, okay, I think I see what you're doing - so if I have ADT with "-profile extendedMobileDevice" then I'm also seeing the same thing. And it doesn't look like there's any support built into the runtime for those other profiles... just "desktop" and "extendedDesktop". That was a change from last July ... it looks like we have an issue with the build configurations for the two AIR binaries ('captive' vs 'sdk') where the SDK should support those profiles as it's called by ADT, but the captive runtimes wouldn't as they're just built into Windows apps...

Not quite sure how this was working before (assuming 'before' meant an AIR SDK that we'd provided) but we can get this sorted out; in the meantime you'll likely need to use the extendedDesktop profile if you need to load in ANEs...

**Comment by ajwfrost** [comment]
... okay now I'm wondering why it's working in 33.1.1.476 but not in 33.1.1.533! Will check this further...

**Comment by jimmymjing** [comment]
Hello, I'm getting the error `Argument 'screensize' not supported in current profile` after changing from extendedMobile to extendedDesktop. Without `screensize` argument the app startsup but the viewport is way too small and I don't know how to test my app in different mobile resolutions...

**Comment by ajwfrost** [comment]
@jimmymjing which version of the SDK are you using there?

From what I can see, in our 33.1.1.533 beta release, we had a configuration change which meant that this 'extendedMobileDevice' option is not working. It should be working with the runtime in the "air" folder, so we'll ensure we package the right binary in the right folder for the official release of this!

**Comment by jimmymjing** [comment]
Hello, I'm using the latest AIR SDK 33.1.1.533 beta (NOT the flex one)

**Comment by 42retfa** [comment]
Hello, 

I just overlayed the Flex SDK 4.16.1  with the latest Harman AIR SDK 33.1.1.533 and I'm experiencing the same problem (I'm using the latest version of Intellij).

Is there a workaround for this issue ?

Thank you.

After24.
