### ISSUE TITLE
command line: unknown configuration variable 'platformsdk'

### ISSUE THREAD

**Issue by leossmith** [airsdk/Adobe-Runtime-Support#919]
I am trying to compile with the new beta sdk, added -platformsdk in aditional compiler options in intellij but i get this error:

command line: unknown configuration variable 'platformsdk'.

Any ideas?

**Comment by leossmith** [comment]
Is there a way to add the platformsdk (android sdk) in the adt configuration file @ajwfrost ?

**Comment by ajwfrost** [comment]
@leossmith not yet but that should be straightforward...

**Comment by leossmith** [comment]
I am using Intellij so there is not "easy" way to add it that i know of, except using adt directly. I am trying to streamline the process.

**Comment by ajwfrost** [comment]
Can you set an environment variable that will be picked up by Intellij (maybe it needs to be set prior to Intellij being launched?)
`AIR_ANDROID_SDK_HOME` is in ADT already, and looks like it overrides anything you could provide on the command line...

**Comment by leossmith** [comment]
That did the trick. Thank you.

**Comment by leossmith** [comment]
Here is a small guide, including all the info @ajwfrost helped me gather on how to compile the new aabs

https://medium.com/@kanellopoulos.leo/air-apache-flex-2021-how-to-compile-android-app-bundle-aacc72caa3db

**Comment by ajwfrost** [comment]
That's great, thanks @leossmith!

**Comment by pol2095** [comment]
I have this message : `NOTE: Multiple SDKs exist, choosing version 30.0.0 for packaging` but it work.

**Comment by ajwfrost** [comment]
Actually I think that line comes out because it's looking for the build-tools path multiple times .. I thought that had been sorted out but maybe not.
Although perhaps you do have multiple build-tool values? ... it will choose the latest of them, I don't think there's any way to select this though.

**Comment by ajwfrost** [comment]
FYI, this issue should be fixed in terms of the AIR SDK providing workarounds e.g. via that environment variable, or alternatively in 33.1.1.533 there's a new config file setting for this.
