### ISSUE TITLE
33.1.1.533 doesn't recognise iOS device in Flash Builder

### ISSUE THREAD

**Issue by davecates** [airsdk/Adobe-Runtime-Support#936]
I've upgraded the SDK and now Flash Builder doesn't recognise an iOS device attached. Previous SDK versions work fine.

**Comment by ajwfrost** [comment]
Which operating system are you using? we just found an issue with MacOS pre Big Sur .. there's a replacement for the lib/aot/bin/iOSBin folder available from the below link:
https://transfer.harman.com/message/T4oPobA23QEvkClkY4TA3J

thanks

**Comment by davecates** [comment]
Hey Andrew,

Sorry, I should have said - Mojave - 10.14.6

Thanks.

**Comment by ajwfrost** [comment]
Okay so yes, that's most likely the code-signing issue that should be resolved via the zip file from the above link; are you able to try that out and confirm please?

**Comment by davecates** [comment]
Yes, that works well - replacing the iOSBin folder with your zipped version.

Fab, thanks!

**Comment by ajwfrost** [comment]
The updated files were included in 33.1.1.554, please let us know of any further issues
