### ISSUE TITLE
File.documentsDirectory gives Error #3001: File or directory access denied. Android only for SDK 30

### ISSUE THREAD

**Issue by balaedit** [airsdk/Adobe-Runtime-Support#939]
I am getting error using File.documentDirectory as File or directory access denied only when I added SDK ver 30 in manifest.

Files are kept in below path :
https://drive.google.com/file/d/1E8KCYAcC2I_ADDMt0xEnZzVxvFgZ8XYm/view?usp=sharing

Updated the manifest to SDK ver 30 as below : 
`<uses-sdk 
	android:minSdkVersion="19"
	android:targetSdkVersion="30" />`

**Comment by ajwfrost** [comment]
Hi

This is expected, given the SDK/API level and the folder you're trying to access there. See https://developer.android.com/about/versions/11/privacy/storage

The `documentsDirectory` is returning `/storage/emulated/0` and this is no longer writable. When we run your test app we see an output immediately before this:
```E MediaProvider: Creating a non-default top level directory or deleting an existing one is not allowed!```

You would probably want to either use `File.applicationStorageDirectory` or `File.applicationRemovableStorageDirectory`, these two should be used for anything custom to your application.

thanks

**Comment by balaedit** [comment]
Thanks for guidance.

I had two issue / help needed from you.

1) If client do not have an external storage, and I check using File.applicationRemovableStorageDirectory method then my application close/crash.
My apk and files are shared on drive link is : https://drive.google.com/file/d/14qLcmsVOP0i3pmhzP7LNr4RL0ub7X3Xw/view?usp=sharing

2) We work on education content, runtime download swf and viewing it. So, one standard/class contain more than 1 gb data runtime download. (each file approx. 5mb) If client do not have removable storage, then app save data in applicationStorage directory. If user/client uninstall the app, then content will be wiped. And they will not get the content event if the user again install my application. Please guide me on this topic.

**Comment by ajwfrost** [comment]
@balaedit thanks for this: for the first of these we've reproduced this and are debugging so we should be able to get a fix out for this in our next release.

In terms of the overall approach for storage though, you'd need to follow the Android guidelines, I'm not sure you can have storage that will continue beyond your application's uninstallation unless you mark it and make it available as "shared" media:
https://developer.android.com/training/data-storage

thanks

**Comment by ajwfrost** [comment]
Hi - are you able to check this (crash when accessing File.applicationRemovableStorageDirectory) using 33.1.1.554 or later please, it should have been fixed in that release. Please re-open the ticket if you still see the problem..
thanks

**Comment by balaedit** [comment]
Can we have feature in Air SDK itself to store data as sharable media or document which can not be deleted when app uninstalled.
