### ISSUE TITLE
[Feature Request] AIR Linux support

### ISSUE THREAD

**Issue by itlancer** [airsdk/Adobe-Runtime-Support#94]
Please return back (and continue develop) Linux support for AIR.
Linux market share growth and many clients need to Linux support too. Its many kiosks, retail devices etc.
This feature important for many enterprise clients and also for IoT devices.

**Comment by pol2095** [comment]
In the release notes of [https://airsdk.harman.com/download/33.1.1.533_BETA](AIR 33.1.1.533_BETA), I see Linux support, for commercial licensees but how to download "Adobe AIR SDK – for Linux" ? thanks

**Comment by ajwfrost** [comment]
The web app changes for Linux have just been done but it's not yet been pushed live - should be ready on Monday I hope!
thanks

**Comment by pol2095** [comment]
Great job.

**Comment by pol2095** [comment]
Any news to download "Adobe AIR SDK – for Linux" ?

**Comment by ajwfrost** [comment]
It was meant to get updated at the weekend - have just chased up again, although I know the guy doing this has had some family issues hence the delays :-(

**Comment by pol2095** [comment]
Thanks, Air for Linux support Stage3D, File, SQLite, Socket, SecureSocket, PrintJob, ANE,... ?

**Comment by ajwfrost** [comment]
I'll have to check on the PrintJob actually... but the rest should be okay! Stage3D implemented via OpenGL ES with MESA drivers I believe..

**Comment by ajwfrost** [comment]
@pol2095 we got the website updated now .. let us know of any issues!
thanks

**Comment by itlancer** [comment]
@ajwfrost
Trying to download AIR SDK for Linux with new ActionScript Compiler cause redirect without file downloading. And it seems to trying to download Flex SDK edition.

**Comment by ajwfrost** [comment]
Sorry! I should have checked that ...!
Updated now

thanks

**Comment by pol2095** [comment]
I tried on Ubuntu 20.04.2 LTS :

I have this message error with adl :
```
/home/user/Bureau/SDKs/AIR_SDK/AIR_SDK_33.1.1.533/bin/../runtimes/air/linux/Adobe
AIR/Versions/1.0/libCore.so
Error loading the runtime (/usr/lib/x86_64-linux-gnu/libcurl.so.4: 
version `CURL_OPENSSL_3' not found (required by /home/user/Bureau/SDKs/AIR_SDK/AIR_SDK_33.1.1.533/bin/../runtimes/air/linux/Adobe
AIR/Versions/1.0/libCore.so))
```

and with adt (captive runtime) :
`Failed to load the AIR Runtime`

**Comment by rathann** [comment]
On Fedora 34 it's crashing with a SIGSEGV after loading an old AIR game (Botanicula):
```
$ ./adl /usr/share/botanicula/BotaniculaLinux-app.xml /usr/share/botanicula
loadRuntime: /home/rathann/adobe-air-33.1.1.533/bin/../runtimes/air/linux/Adobe AIR/Versions/1.0/libCore.so
Application crashed with an unhandled SIGSEGV
```
Stack trace is not very useful because all the debug symbols were stripped. @ajwfrost would you like me to open a separate issue for the crash?

**Comment by ajwfrost** [comment]
Thanks, we'll look into these issues -> yes please feel free to raise new bugs against them. Stack trace is useful for us because we have the map/gdb files here :-)

thanks

**Comment by pol2095** [comment]
On Ubuntu 16.04 LTS it work correctly, I think Ubuntu 20.04.2 LTS need libcurl4-openssl

**Comment by pol2095** [comment]
contentsScaleFactor seems not working on Ubuntu ? the window is very small

**Comment by pol2095** [comment]
adt has a new target ane -platform "Linux-x86-64" since Air 33.1.1.533, but how to create an Air Native Extensions for Linux ?

**Comment by Twilight774** [comment]
Any progress? Should we wait for version for commoners? I mean Air runtime not SDK

**Comment by ajwfrost** [comment]
@Twilight774 getting a shared AIR runtime together for Linux is something we'll be looking at but isn't a particular priority right now, as you should be able to package up applications as bundles and distribute those. There's still a potential issue with the 'native' targets (i.e. creating RPM/DEB files) but the focus for a while has been on the `contentsScaleFactor` issue, which has meant we've been looking at a major update to use GTK3...

@pol2095 creating ANEs should be similar to creating them for Android native (C++) targets. There's an include file and a library to link against within the AIR SDK, and the platform tag as you say is `Linux-x86-64`. Are you having any specific issues with the packaging process, or getting them to run?

thanks

**Comment by pol2095** [comment]
> ANE

ANE work now.

**Comment by al-sabr** [comment]
Could someone create a vcpkg for the c++ header files required to build ANE on the different platforms?

**Comment by itlancer** [comment]
With latest AIR versions Linux support level already pretty well!
Thank you to return Linux platform support!

It still have some issue but I will create new tickets about that.
Right now especially critical `EncryptedLocalStore` support https://github.com/airsdk/Adobe-Runtime-Support/issues/1829
