### ISSUE TITLE
SDK is missing file air/android/device/x86/Runtime.apk

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#948]
When I use the AIRSDK_Windows version 33.1.1.533 to package Android App Bundle File.
There was a mistake like this. I have set AndroidPlatformSDK on the adt.cfg .
AndroidPlatformSDK=C:/Users/yangjin1/AppData/Local/Android/Sdk
But package APK File can be successfully packaged.
Error:
   SDK is missing file air/android/device/x86/Runtime.apk

**Comment by ajwfrost** [comment]
See #938 - this is happening if AIR is looking at your Android SDK's "build-tools" folder, and finding a subfolder that doesn't have a `source.properties` file in it. We have an updated ADT that fixes this:
https://transfer.harman.com/message/rGFdqpUg3kHplopv095H4o

**Comment by ajwfrost** [comment]
@pengyangjin can you please check that you don't have a file AndroidManifest.xml anywhere in your code tree? This file is generated by AIR into the appropriate location, but Gradle appears to be saying that it's found another one in a 'root' subfolder:
```
File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.
```
thanks

**Comment by pengyangjin** [comment]
> 
> 
> @pengyangjin can you please check that you don't have a file AndroidManifest.xml anywhere in your code tree? This file is generated by AIR into the appropriate location, but Gradle appears to be saying that it's found another one in a 'root' subfolder:
> 
> ```
> File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.
> ```
> 
> thanks

**Comment by pengyangjin** [comment]
> @pengyangjin can you please check that you don't have a file AndroidManifest.xml anywhere in your code tree? This file is generated by AIR into the appropriate location, but Gradle appears to be saying that it's found another one in a 'root' subfolder:
> 
> ```
> File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.
> ```
> 
> thanks

After careful search, I finally found a  file  named androidmanifest.xml in a jar file used in ane.Everything went well after delete this filen amed androidmanifest.xml. thanks.

**Comment by pengyangjin** [comment]
> @pengyangjin can you please check that you don't have a file AndroidManifest.xml anywhere in your code tree? This file is generated by AIR into the appropriate location, but Gradle appears to be saying that it's found another one in a 'root' subfolder:
> 
> ```
> File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.
> ```
> 
> thanks

After careful search, I finally found a  file  named androidmanifest.xml in a jar file used in ane.Everything went well after delete this filen amed androidmanifest.xml. thanks.
