### ISSUE TITLE
 The project name '???PK' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details)

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#951]
When I named the app in Korean, an error occurred.
This is what I set in the app descriptor.
My application is for many non English speaking areas, such as Korea, Japan, Myanmar and Vietnam.
It is not a good idea to equate project name with <name>

<filename>삼국지PK</filename>
<name>삼국지PK</name>

     [java] NOTE: Multiple SDKs exist, choosing version 30.0.3 for packaging
     [java] NOTE: Multiple SDKs exist, choosing version 30.0.3 for packaging
     [java] NOTE: Multiple SDKs exist, choosing version 30.0.3 for packaging
     [java] NOTE: Multiple SDKs exist, choosing version 30.0.3 for packaging
     [java] NOTE: Multiple SDKs exist, choosing version 30.0.3 for packaging
     [java] unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
     [java] FAILURE: Build failed with an exception.
     [java] 
     [java] * Where:
     [java] Settings file 'C:\Users\yangjin1\AppData\Local\Temp\9de10cd5-3a7c-46fe-a3e9-8aca72630976\settings.gradle' line: 2
     [java] 
     [java] * What went wrong:
     [java] A problem occurred evaluating settings '9de10cd5-3a7c-46fe-a3e9-8aca72630976'.
     [java] > The project name '???PK' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
     [java] 
     [java] * Try:
     [java] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [java] 
     [java] * Get more help at https://help.gradle.org
     [java] 
     [java] BUILD FAILED in 653ms
     [java] 
     [java] java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
     [java] FAILURE: Build failed with an exception.
     [java] 
     [java] * Where:
     [java] Settings file 'C:\Users\yangjin1\AppData\Local\Temp\9de10cd5-3a7c-46fe-a3e9-8aca72630976\settings.gradle' line: 2
     [java] 
     [java] * What went wrong:
     [java] A problem occurred evaluating settings '9de10cd5-3a7c-46fe-a3e9-8aca72630976'.
     [java] > The project name '???PK' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/6.5/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
     [java] 
     [java] * Try:
     [java] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [java] 
     [java] * Get more help at https://help.gradle.org
     [java] 
     [java] BUILD FAILED in 653ms
     [java] 
     [java] 	at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
     [java] 	at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
     [java] 	at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
     [java] 	at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
     [java] 	at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
     [java] 	at com.adobe.air.ADT.run(ADT.java)
     [java] 	at com.adobe.air.ADT.main(ADT.java)

**Comment by ajwfrost** [comment]
Please see the below link for a build of ADT.jar that should fix this.
thanks
https://transfer.harman.com/message/ghqv7zUIEZAGOPxjMh90k4

**Comment by pengyangjin** [comment]
> 
> 
> Please see the below link for a build of ADT.jar that should fix this.
> thanks
> https://transfer.harman.com/message/ghqv7zUIEZAGOPxjMh90k4

Use the new adt.jar to package and the app descriptor is,

-------------------------------------------------------------------------------------------------------------
	
	<filename>삼국지PK</filename>
	
	<name>삼국지PK</name>
-------------------------------------------------------------------------------------------------------------

Another error has occurred.
     [java] NOTE: Multiple Android build-tools folders exist, choosing the latest version (30.0.3) for packaging
     [java] unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
     [java] FAILURE: Build failed with an exception.
     [java] 
     [java] * What went wrong:
     [java] Execution failed for task ':app:buildReleasePreBundle'.
     [java] > java.lang.OutOfMemoryError (no error message)

**Comment by ajwfrost** [comment]
I think our default Java heap is 1GB, you may need to increase this... see the "adt.cfg" file in the lib folder of the SDK, you can uncomment a line and adjust it:
```
#JavaXmx=2048m
```

**Comment by Dima107** [comment]
I have issue to build aab too
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

 Where:
Settings file 'C:\Users\Dima\AppData\Local\Temp\37965cdf-cf43-4d09-9bc9-d5d3f9e2db1e\settings.gradle'

 What went wrong:
Could not compile settings file 'C:\Users\Dima\AppData\Local\Temp\37965cdf-cf43-4d09-9bc9-d5d3f9e2db1e\settings.gradle'.
 startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  
[error.txt](https://github.com/airsdk/Adobe-Runtime-Support/files/6771266/error.txt)
Can you help me with this?

**Comment by ajwfrost** [comment]
That sounds like a Java version issue... have you built any ANE files for this? Class file version 60 means it was built with Java 16! all our stuff should class version 50, 51 or 52 (1.6, 1.7, 1.8 aka 6, 7, 8...) so it sounds like the Java that's running Gradle can't cope with the newer class file from a dependent library....

thanks

**Comment by pengyangjin** [comment]
> 
> 
> I think our default Java heap is 1GB, you may need to increase this... see the "adt.cfg" file in the lib folder of the SDK, you can uncomment a line and adjust it:
> 
> ```
> #JavaXmx=2048m
> ```

It works.

**Comment by ajwfrost** [comment]
FYI, the original error here is fixed in 33.1.1.554.

The subsequent issue with gradle builds can be solved by adjusting the JavaXmx configuration value - sometimes you might find you need to shut down "java" processes that are hanging around on the OS task list, we're changing it in the next release so that we don't use the gradle daemon which seems to be causing problems due to caching...

thanks
