### ISSUE TITLE
The number of method references in a .dex file cannot exceed 64K.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#952]
My App use a ane for facebook and complied error:

Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by ajwfrost** [comment]
We've added support for multi-dex into AAB generation now, please use the below version:
https://transfer.harman.com/message/ghqv7zUIEZAGOPxjMh90k4

**Comment by rimtemp** [comment]
> We've added support for multi-dex into AAB generation now, please use the below version:
> https://transfer.harman.com/message/ghqv7zUIEZAGOPxjMh90k4

I'm getting this error after using the version.

![image](https://user-images.githubusercontent.com/22320065/124835360-d23d6d80-df9e-11eb-8b10-80fabf5b632b.png)

**Comment by ajwfrost** [comment]
Yes that was the side-effect of building in support: if you separately add it, we get a duplication..
We've fixed this though, it should be okay in our forthcoming release..

thanks
