### ISSUE TITLE
Temporary files generated by packaging are not cleaned up.

### ISSUE THREAD

**Issue by pengyangjin** [airsdk/Adobe-Runtime-Support#958]
When I use the SDK to package AAB files,A problem was found that a lot of temp files generated by packaging AAB are not cleaned up.
The directory at  C:\Users\yangjin1\AppData\Local\Temp have a lot of temporary files which is generated by packaging aab file.
Can you optimize this problem?

**Comment by ajwfrost** [comment]
We'll check that to see what's still left around, I thought everything had been set up to delete the temp files on exit.. There may be an issue if the JVM exits unexpectedly rather than doing a graceful shut down..

**Comment by pengyangjin** [comment]
> We'll check that to see what's still left around, I thought everything had been set up to delete the temp files on exit.. There may be an issue if the JVM exits unexpectedly rather than doing a graceful shut down..

I use jenkins and ant to package aab file. And it will not happen when  package apk file.All the settings are the same.

**Comment by ajwfrost** [comment]
Interestingly while reviewing this, it looks like some APK build assets may have also been left around, if it had some ANEs that needed certain processing... basically all this is due to the use of the Java `File.deleteOnExit` method, which doesn't work on folders...

**Comment by ajwfrost** [comment]
Hi - are you able to check this using 33.1.1.554 or later please, it should have been fixed in that release. Please re-open the ticket if you still see the problem..
thanks
