### ISSUE TITLE
ADT not signing v2

### ISSUE THREAD

**Issue by shaymolho** [airsdk/Adobe-Runtime-Support#985]
## Problem Description
My ADT command:
` C:/flash_air_sdk_33.1.1.554/bin/adt.bat (dir=target)
      -package
      -target apk-captive-runtime
      -arch armv8
      -keystore release.keystore
      -storetype JKS
      -providerName SUN
      -storepass storepass
      -alias alias
      -keypass keypass
      my-apk.apk
      android.xml
      my-swf.swf
      audience_network.dex
      -C target assets
      -C root_android .
      -extdir .
      Warning: packagedDependency installreferrer-1.0.jar used by more than one ANE. Ignoring this entry
      NOTE: The application has been packaged with a captive runtime.
     `

then apksigner shows:
`apksigner.bat verify --verbose "my-apk.apk"
DOES NOT VERIFY
ERROR: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme`

**Comment by ajwfrost** [comment]
Hmmm... when I try it here:
```
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```
Have just checked this with both pkcs12 and jks certificate types.
Looking at the code, there should be some output if there was any error happening there..
Could you try deleting the .apk file and re-running that, plus check that there's the "apksigner.jar" file within the SDK's "lib\android\lib" folder?
We can add a bit of debug output to this process to see what may be happening within ADT...

thanks

**Comment by shaymolho** [comment]
I checked again, it's a problem on our side. Thanks for the response
